import Mathlib

namespace MathlibPlus.Open.GroupTheory.R0989R1558

noncomputable section

abbrev C2Cube := Fin 3 → ZMod 2

noncomputable def normalizedCubeDerivative
    (σ : Equiv.Perm C2Cube) (u : C2Cube) : Equiv.Perm C2Cube :=
  ((Equiv.addRight u).trans σ).trans
    ((Equiv.addRight (σ u)).trans σ.symm)

/-- Claim 27966: `Δ_σ` is the subgroup generated by all displayed
normalized derivatives of a zero-fixing permutation of `C₂³`. -/
def derivativeGroup_claim27966
    (σ : Equiv.Perm C2Cube) : Subgroup (Equiv.Perm C2Cube) :=
  Subgroup.closure (Set.range (normalizedCubeDerivative σ))

abbrev EightWord (p : ℕ) := Fin 8 → ZMod p

noncomputable def cyclicShift {p : ℕ} (x : EightWord p) : EightWord p :=
  fun i => x (Fin.ofNat 8 (i.1 + 1))

noncomputable def alternatingSign {p : ℕ} (x : EightWord p) : EightWord p :=
  fun i => if i.1 % 2 = 0 then x i else -x i

noncomputable def firstDifference {p : ℕ} (x : EightWord p) : EightWord p :=
  cyclicShift x - x

noncomputable def periodicDerivativeSpace {p : ℕ} (d : ℕ) : Set (EightWord p) :=
  {v | ∃ c : EightWord p,
    (cyclicShift^[d]) c = c ∧ v = firstDifference c}

noncomputable def signedCoboundaryDerivativeSpace {p : ℕ} (d : ℕ) : Set (EightWord p) :=
  {v | ∃ t : EightWord p,
    v = firstDifference (alternatingSign ((cyclicShift^[d]) t - t))}

/-- Claim 31117: in odd characteristic the periodic derivative space and the
signed shifted-translation coboundary space meet only at zero for every
separation from one through seven. -/
def allOrderEightBlockPeriodIntersection_claim31117 : Prop :=
  ∀ p : ℕ, Nat.Prime p → 2 < p →
    ∀ d : ℕ, 1 ≤ d → d ≤ 7 →
      ∀ v : EightWord p,
        v ∈ periodicDerivativeSpace d →
          v ∈ signedCoboundaryDerivativeSpace d →
            v = 0

end

end MathlibPlus.Open.GroupTheory.R0989R1558
