import Mathlib
import MathlibPlus.Open.ResearchFormalization.R1203.Claim41970

namespace MathlibPlus.ResearchFormalization.R1203Counterexample

open MathlibPlus.ResearchFormalization.R1203Claim41970

abbrev a49 := Multiplicative (ZMod 49)
abbrev w7 := Fin 3 → ZMod 7

/-- The subgroup generated by `7` in the cyclic `49`-group. -/
def sevenA : Subgroup a49 :=
  Subgroup.closure {Multiplicative.ofAdd (7 : ZMod 49)}

abbrev sevenInE {rho : c3 →* MulAut a49} :=
  Subgroup.map (SemidirectProduct.inl : a49 →* eGroup a49 rho) sevenA

/-- Division by `7` on the subgroup `7 C₄₉`, expressed through the canonical
representative of its underlying `ZMod 49` element. -/
def sevenQuotient {rho : c3 →* MulAut a49}
    (x : sevenInE (rho := rho)) : ZMod 7 :=
  ((ZMod.val (Multiplicative.toAdd x.1.left) / 7 : ℕ) : ZMod 7)

def vectorLift (q : ZMod 7) : w7 :=
  fun i => if i = 0 then q else 0

/-- The action on the matching target `C₇³`; its scalar is the reduction of
`30` modulo `7`, namely `2`. -/
def matchingTargetAction {rho : c3 →* MulAut a49}
    (h : eGroup a49 rho) (w : w7) : w7 :=
  matchingCharacter 7 (2 : ZMod 7) h • w

/-- Explicit module laws and the matching action constraints for `C₇³`. -/
def matchingTargetModule {rho : c3 →* MulAut a49} : Prop :=
  (∀ (a : a49) (w : w7),
      matchingTargetAction (SemidirectProduct.inl a : eGroup a49 rho) w = w) ∧
    (∀ w : w7,
      matchingTargetAction
          (SemidirectProduct.mk (1 : a49) cGenerator : eGroup a49 rho) w =
        (2 : ZMod 7) • w) ∧
    (∀ (h k : eGroup a49 rho) (w : w7),
      matchingTargetAction (h * k) w =
        matchingTargetAction h (matchingTargetAction k w)) ∧
    (∀ (h : eGroup a49 rho) (w w' : w7),
      matchingTargetAction h (w + w') =
        matchingTargetAction h w + matchingTargetAction h w') ∧
    (∀ (h : eGroup a49 rho), matchingTargetAction h 0 = 0)

def matchingTargetCocycle {rho : c3 →* MulAut a49}
    (f : eGroup a49 rho → w7) : Prop :=
  ∀ h k, f (h * k) = f h + matchingTargetAction h (f k)

def subgroupMatchingTargetCocycle {rho : c3 →* MulAut a49}
    (L : Subgroup (eGroup a49 rho)) (f : L → w7) : Prop :=
  ∀ h k, f (h * k) = f h + matchingTargetAction h.1 (f k)

/-- A homomorphism from a multiplicative group to the additive presentation of
`C₇³` or `C₇`. -/
def additiveHom {G W : Type*} [Group G] [AddGroup W]
    (f : G → W) : Prop :=
  f 1 = 0 ∧ ∀ x y, f (x * y) = f x + f y

def subgroupAdditiveHom {G W : Type*} [Group G] [AddGroup W]
    (L : Subgroup G) (f : L → W) : Prop :=
  f 1 = 0 ∧ ∀ x y, f (x * y) = f x + f y

def generatorAtSeven {rho : c3 →* MulAut a49}
    (x : sevenInE (rho := rho)) : Prop :=
  x.1 = SemidirectProduct.inl
    (Multiplicative.ofAdd (7 : ZMod 49))

end MathlibPlus.ResearchFormalization.R1203Counterexample

namespace MathlibPlus.Open.ResearchFormalization.R1203

open MathlibPlus.ResearchFormalization.R1203Claim41970
open MathlibPlus.ResearchFormalization.R1203Counterexample

/-- Claim 41974: the non-elementary Sylow counterexample is carried by the
explicit `E(C₄₉,3)` action with scalar `30`, its matching `C₇³` module, and
both the vector and scalar nonextension witnesses. -/
def claim41974 : Prop :=
  ∃ (rho : c3 →* MulAut a49),
    (∀ x : a49,
      rho cGenerator x =
        Multiplicative.ofAdd
          ((30 : ZMod 49) * Multiplicative.toAdd x)) ∧
    matchingTargetModule (rho := rho) ∧
    (∃ z : sevenInE (rho := rho) → w7,
      subgroupMatchingTargetCocycle (rho := rho) (sevenInE (rho := rho)) z ∧
      subgroupAdditiveHom (sevenInE (rho := rho)) z ∧
      (∀ x : sevenInE (rho := rho),
        z x = vectorLift (sevenQuotient x)) ∧
      (∃ x : sevenInE (rho := rho),
        generatorAtSeven x ∧ z x = vectorLift (1 : ZMod 7)) ∧
      (¬ ∃ F : a49 → w7,
        additiveHom F ∧
        ∀ x : sevenInE (rho := rho), F x.1.left = z x) ∧
      (∀ F : a49 → w7,
        additiveHom F →
          F (Multiplicative.ofAdd (7 : ZMod 49)) = 0)) ∧
    (∃ s : sevenInE (rho := rho) → ZMod 7,
      subgroupAdditiveHom (sevenInE (rho := rho)) s ∧
      (∀ x : sevenInE (rho := rho), s x = sevenQuotient x) ∧
      (∃ x : sevenInE (rho := rho),
        generatorAtSeven x ∧ s x = (1 : ZMod 7)) ∧
      (¬ ∃ F : a49 → ZMod 7,
        additiveHom F ∧
        ∀ x : sevenInE (rho := rho), F x.1.left = s x) ∧
      (∀ F : a49 → ZMod 7,
        additiveHom F →
          F (Multiplicative.ofAdd (7 : ZMod 49)) = 0))

end MathlibPlus.Open.ResearchFormalization.R1203
