import Mathlib

namespace MathlibPlus.Open.Combinatorics.Claim5539

/-!
For a finite matrix, `rowSupport` is the set of columns incident with a row.
-/
noncomputable def rowSupport {𝕜 : Type*} [Field 𝕜] {m n : ℕ}
    (A : Matrix (Fin m) (Fin n) 𝕜) (r : Fin m) : Finset (Fin n) := by
  classical
  exact Finset.univ.filter (fun c => A r c ≠ 0)

/-!
The finite-stage attractor generated by singleton peeling.  At the next
stage a column is removed when some incident row has no other incident column
outside the preceding stage.
-/
noncomputable def singletonPeelingAttractor {𝕜 : Type*} [Field 𝕜] {m n : ℕ}
    (A : Matrix (Fin m) (Fin n) 𝕜) : ℕ → Finset (Fin n)
  | 0 => ∅
  | k + 1 => by
      classical
      let previous := singletonPeelingAttractor A k
      exact previous ∪ Finset.univ.filter (fun c =>
        ∃ r : Fin m,
          A r c ≠ 0 ∧ (rowSupport A r).erase c ⊆ previous)

/-! Every column is eventually removed by singleton peeling. -/
def completeSingletonPeeling {𝕜 : Type*} [Field 𝕜] {m n : ℕ}
    (A : Matrix (Fin m) (Fin n) 𝕜) : Prop :=
  ∀ c : Fin n, ∃ k : ℕ, c ∈ singletonPeelingAttractor A k

/-! An incident-row selector chooses one nonzero row entry at every column. -/
def incidentRowSelector {𝕜 : Type*} [Field 𝕜] {m n : ℕ}
    (A : Matrix (Fin m) (Fin n) 𝕜) (s : Fin n → Fin m) : Prop :=
  ∀ c : Fin n, A (s c) c ≠ 0

/-! The dependency arrows of an incident-row selector. -/
def selectorDependency {𝕜 : Type*} [Field 𝕜] {m n : ℕ}
    (A : Matrix (Fin m) (Fin n) 𝕜) (s : Fin n → Fin m) (c d : Fin n) : Prop :=
  d ≠ c ∧ A (s c) d ≠ 0

/-! A relation is acyclic when it has no nonempty directed cycle. -/
def relationAcyclic {α : Type*} (R : α → α → Prop) : Prop :=
  ∀ a : α, ¬Relation.TransGen R a a

/-!
Singleton peeling removes every column if and only if there is an
incident-row selector whose dependency digraph is acyclic.
-/
def completePeeling_iff_acyclicSelector {𝕜 : Type*} [Field 𝕜] {m n : ℕ}
    (A : Matrix (Fin m) (Fin n) 𝕜) : Prop :=
  completeSingletonPeeling A ↔
    ∃ s : Fin n → Fin m,
      incidentRowSelector A s ∧ relationAcyclic (selectorDependency A s)

end MathlibPlus.Open.Combinatorics.Claim5539
