import Mathlib

namespace MathlibPlus.Open.Combinatorics

/-- The two-element subsets of a type with decidable equality. -/
def TwoSubset (V : Type*) [DecidableEq V] :=
  {e : Finset V // e.card = 2}

/-- The action of a permutation on two-element subsets. -/
def mapTwoSubset {V : Type*} [DecidableEq V]
    (p : Equiv.Perm V) (e : TwoSubset V) : TwoSubset V :=
  ⟨e.1.image p, by
    calc
      (e.1.image p).card = e.1.card := Finset.card_image_of_injective _ p.injective
      _ = 2 := e.2⟩

/-- The Boolean graph-bit equation expressing a pointed card isomorphism. -/
def pointedCardIsomorphism {V : Type*} [Fintype V] [DecidableEq V]
    (i : V) (π : V → Equiv.Perm V) (A B : TwoSubset V → Bool) : Prop :=
  ∀ e : TwoSubset V, i ∉ e.1 → A e = B (mapTwoSubset (π i) e)

/-- Constraint multiedges retain the deleted vertex and the source two-subset,
so parallel endpoint constraints remain distinct. -/
def ConstraintEdge {V : Type*} [Fintype V] [DecidableEq V]
    (π : V → Equiv.Perm V) :=
  Σ i : V, {e : TwoSubset V // i ∉ e.1}

/-- The left endpoint of a constraint multiedge. -/
def constraintLeft {V : Type*} [Fintype V] [DecidableEq V]
    {π : V → Equiv.Perm V} (c : ConstraintEdge π) :
    Sum (TwoSubset V) (TwoSubset V) :=
  Sum.inl c.2.1

/-- The right endpoint of a constraint multiedge. -/
def constraintRight {V : Type*} [Fintype V] [DecidableEq V]
    (π : V → Equiv.Perm V) (c : ConstraintEdge π) :
    Sum (TwoSubset V) (TwoSubset V) :=
  Sum.inr (mapTwoSubset (π c.1) c.2.1)

/-- The coloring whose left and right values are respectively `A` and `B`. -/
def constraintColor {V : Type*} [DecidableEq V]
    (A B : TwoSubset V → Bool) : Sum (TwoSubset V) (TwoSubset V) → Bool
  | Sum.inl e => A e
  | Sum.inr e => B e

/-- Undirected adjacency generated by the constraint multiedges. -/
def constraintAdjacent {V : Type*} [Fintype V] [DecidableEq V]
    (π : V → Equiv.Perm V)
    (x y : Sum (TwoSubset V) (TwoSubset V)) : Prop :=
  ∃ c : ConstraintEdge π,
    (x = constraintLeft c ∧ y = constraintRight π c) ∨
      (x = constraintRight π c ∧ y = constraintLeft c)

/-- Belonging to one connected component of the constraint multigraph. -/
def constraintConnected {V : Type*} [Fintype V] [DecidableEq V]
    (π : V → Equiv.Perm V)
    (x y : Sum (TwoSubset V) (TwoSubset V)) : Prop :=
  Relation.ReflTransGen (constraintAdjacent π) x y

/-- Prescribed card isomorphisms force the induced coloring to be constant on
components of the bipartite constraint multigraph. -/
def prescribedCardIsomorphismsForceComponentConstantColors
    {V : Type*} [Fintype V] [DecidableEq V]
    (π : V → Equiv.Perm V) (A B : TwoSubset V → Bool) : Prop :=
  (∀ i : V, π i i = i) →
    (∀ i : V, pointedCardIsomorphism i π A B) →
      (∀ c : ConstraintEdge π,
          constraintColor A B (constraintLeft c) =
            constraintColor A B (constraintRight π c)) ∧
        (∀ x y : Sum (TwoSubset V) (TwoSubset V),
          constraintConnected π x y →
            constraintColor A B x = constraintColor A B y)

end MathlibPlus.Open.Combinatorics
