import Mathlib
#check PowerSeries.X
#check PowerSeries.C
#check PowerSeries.coeff
#check PowerSeries.log
#check PowerSeries.inv
#check PowerSeries.one_add
#check PowerSeries.coeff_mul
#check PowerSeries.coeff_smul
#check PowerSeries.derivative
#check PowerSeries.deriv
#check PowerSeries.mk
#check PowerSeries.coeff_X_pow
#check PowerSeries.coeff_X
#check PowerSeries.coeff_log
