import Mathlib.GroupTheory.Perm.Cycle.Type
#check Fintype.card_eq_one_iff
#check Fintype.card_ne_one_iff
#check Fintype.card_eq_one_iff_unique
#check Fintype.card_le_one_iff
#check Fintype.card_pos
#check Fintype.card_ne_zero
#check not_nontrivial_iff_subsingleton
#check not_subsingleton_iff_nontrivial
#check Fintype.card_congr
#check Nat.card_eq_fintype_card
