import MathlibPlus
#check MvPolynomial.psum_eq_mul_esymm_sub_sum
#check Multiset.prod_X_sub_C
#check Multiset.prod_X_sub_C_coeff
#check Multiset.prod_X_sub_C_eq_sum_esymm
#check Polynomial.ext_iff
#check Polynomial.eval₂_at
#check Polynomial.eval₂_at_apply
#check Polynomial.eval₂_at_zero
#check Polynomial.eval₂_at_X
#check Polynomial.C_mul_X_sub_C
#check Polynomial.X_sub_C_dvd_iff
#check Multiset.prod_X_sub_C_dvd_iff_le_roots
#check Multiset.count_map_eq_count'
#check Multiset.map_eq_map
#check Multiset.card_map
#check Multiset.erase_cons
#check Multiset.cons_erase
#check Multiset.prod_cons
#check Polynomial.eval₂_at
#check Polynomial.eval₂_mul
#check Polynomial.eval₂_at_apply
