import MathlibPlus
#check MvPolynomial.aeval_esymm_eq_multiset_esymm
#check MvPolynomial.eval₂_at_apply
#check MvPolynomial.eval₂_C
#check MvPolynomial.eval₂_X'
#check MvPolynomial.eval₂_X
#check MvPolynomial.map_esymm
#check Finset.prod_univ_succ
#check Finset.univ_succ
#check Multiset.coe_sort
#check Multiset.sum_map
#check Multiset.map_sum
#check Multiset.map_cons
#check Multiset.map_zero
#check Multiset.map_injective
#check Multiset.card_map
#check Multiset.card_fin
#check Finset.univ_val
#check Finset.univ_succ
#check Finset.sum_univ_succ
#check Finset.sum_univ_two
#check Finset.prod_univ_succ
#check Finset.prod_univ_two
#check Nat.cast_ne_zero
#check CharZero.cast_injective
#check map_natCast
#check Nat.cast_inj
#check Multiset.map_eq_map
#check Multiset.ext
#check Multiset.count_map_eq_count'
#check Multiset.card_pos
#check Multiset.card_eq_zero
#check Multiset.card_cons
#check Multiset.card_map
#check Multiset.map_replicate
#check Multiset.map_replicate
#check Multiset.map_eq_map
#check Matrix.det_vandermonde_ne_zero_iff
#check Matrix.det_vandermonde
#check Matrix.vandermonde
#check Matrix.det_eq_zero_of_vec_mulVec_eq_zero
#check Matrix.mulVecLin
#check Matrix.mulVec
#check Matrix.mulVecLin_injective
#check Matrix.nonsingInv_mul
