import Mathlib

namespace MathlibPlus.Open.CIMixedAbelianIndexThree

abbrev V := Fin 3 → ZMod 3
abbrev G := ZMod 4 × V

/-- The subgroup `C₄ × W`, represented in `G`. -/
def H (W : Submodule (ZMod 3) V) : Set G :=
  Set.univ ×ˢ (W : Set V)

/-- The two-element (or, for an involution, one-element) set generated by `x` and `-x`. -/
def D (x : G) : Set G := {x, -x}

def S (W : Submodule (ZMod 3) V) (x : G) : Set G :=
  H W \ ({0} ∪ D x)

def Q (W : Submodule (ZMod 3) V) (x : G) : Set G :=
  (Set.univ \ ({0} : Set G)) \ S W x

/-- Adjacency in the additive Cayley graph with connection set `R`. -/
def cayleyAdj (R : Set G) (u v : G) : Prop :=
  u ≠ v ∧ v - u ∈ R

/-- Isomorphism of the Cayley graphs with the displayed adjacency relations. -/
def CayleyGraphIso (R T : Set G) : Prop :=
  ∃ e : G ≃ G, ∀ u v : G,
    cayleyAdj R u v ↔ cayleyAdj T (e u) (e v)

def UndirectedConnectionSet (R : Set G) : Prop :=
  R ⊆ (Set.univ : Set G) \ {0} ∧ ∀ g ∈ R, -g ∈ R

def UndirectedCI (R : Set G) : Prop :=
  UndirectedConnectionSet R ∧
    ∀ T : Set G,
      T ⊆ (Set.univ : Set G) \ {0} →
      (∀ g ∈ T, -g ∈ T) →
      CayleyGraphIso R T →
      ∃ α : G ≃+ G, α '' R = T

def SFamily : Set (Set G) :=
  {R | ∃ W : Submodule (ZMod 3) V, ∃ x : G,
    Module.finrank (ZMod 3) W = 2 ∧
      x ∈ H W ∧ x ≠ 0 ∧ R = S W x}

def QFamily : Set (Set G) :=
  {R | ∃ W : Submodule (ZMod 3) V, ∃ x : G,
    Module.finrank (ZMod 3) W = 2 ∧
      x ∈ H W ∧ x ≠ 0 ∧ R = Q W x}

def claim_60245 : Prop :=
  (∀ W : Submodule (ZMod 3) V,
      Module.finrank (ZMod 3) W = 2 →
        ∀ x : G, x ∈ H W → x ≠ 0 →
          UndirectedCI (S W x) ∧ UndirectedCI (Q W x)) ∧
    Nat.card {R : Set G // R ∈ SFamily} = 234 ∧
    Nat.card {R : Set G // R ∈ QFamily} = 234 ∧
    Nat.card {R : Set G // R ∈ SFamily ∧ R.ncard = 34} = 13 ∧
    Nat.card {R : Set G // R ∈ SFamily ∧ R.ncard = 33} = 221 ∧
    Nat.card {R : Set G // R ∈ QFamily ∧ R.ncard = 73} = 13 ∧
    Nat.card {R : Set G // R ∈ QFamily ∧ R.ncard = 74} = 221

end MathlibPlus.Open.CIMixedAbelianIndexThree
