import Mathlib

namespace MathlibPlus.Open

/-- The one-sided Toeplitz matrix generated by a sequence indexed by integers. -/
def oneSidedToeplitz (f : ℤ → ℝ) (r c : ℤ) : ℝ :=
  f (c - r)

/-- The determinant of a minor whose rows and columns are given in order. -/
def toeplitzMinor {n : ℕ} (f : ℤ → ℝ)
    (rows cols : Fin n → ℤ) : ℝ :=
  Matrix.det (fun i j => oneSidedToeplitz f (rows i) (cols j))

/-- Append one last entry to a finitely indexed ordered list. -/
def snoc {α : Type} {n : ℕ} (v : Fin n → α) (x : α) : Fin (n + 1) → α :=
  fun i => if h : i.val < n then v ⟨i.val, h⟩ else x

/-- The residual of the last selected column after eliminating the preceding ones. -/
def toeplitzResidual {k : ℕ} (f : ℤ → ℝ)
    (cols : Fin (k + 1) → ℤ) (coefficients : Fin k → ℝ) (s : ℤ) : ℝ :=
  oneSidedToeplitz f s (cols (Fin.last k)) -
    ∑ i : Fin k, coefficients i * oneSidedToeplitz f s (cols i.castSucc)

/-- Total nonnegativity through the indicated order for a one-sided Toeplitz matrix. -/
def toeplitzTotallyNonnegativeThrough (f : ℤ → ℝ) (bound : ℕ) : Prop :=
  ∀ (m : ℕ), m ≤ bound →
    ∀ (rows cols : Fin m → ℤ), StrictMono rows → StrictMono cols →
      0 ≤ toeplitzMinor f rows cols

/--
The exact enclosing-determinant sign statement.  The coefficients describe the
last-column elimination supplied by the nested-minor context, and the residual
sign is the corresponding consequence of total nonnegativity through order
`k + 1`.
-/
def exactEnclosingDeterminantSign : Prop :=
  ∀ (k : ℕ) (f : ℤ → ℝ)
    (rows cols : Fin (k + 1) → ℤ) (coefficients : Fin k → ℝ),
    (∀ n : ℤ, n < 0 → f n = 0) →
    StrictMono rows → StrictMono cols →
    toeplitzTotallyNonnegativeThrough f (k + 2) →
    (∀ i : Fin (k + 1),
      oneSidedToeplitz f (rows i) (cols (Fin.last k)) =
        ∑ j : Fin k,
          coefficients j * oneSidedToeplitz f (rows i) (cols j.castSucc)) →
    (∀ s : ℤ, rows (Fin.last k) < s →
      0 ≤ toeplitzResidual f cols coefficients s) →
    ∀ N : ℤ, cols (Fin.last k) < N →
      let D_N :=
        toeplitzMinor f rows
          (snoc (fun i : Fin k => cols i.castSucc) N)
      0 ≤ D_N ∧
        ∀ s : ℤ, rows (Fin.last k) < s →
          toeplitzMinor f (snoc rows s) (snoc cols N) =
              -toeplitzResidual f cols coefficients s * D_N ∧
            toeplitzResidual f cols coefficients s * D_N = 0

end MathlibPlus.Open
