import Mathlib

namespace MathlibPlus.Open.PrimeFiber

section Common

universe u v

/-- The subgroup of permutations generated by the projected generators. -/
def generatedBaseGroup (B : Type u) (I : Type v)
    (r : I → Equiv.Perm B) : Subgroup (Equiv.Perm B) :=
  Subgroup.closure (Set.range r)

/-- One signed generator step on the base. `true` means the inverse step. -/
def baseStep (r : I → Equiv.Perm B) (m : I × Bool) (b : B) : B :=
  if m.2 then (r m.1).symm b else r m.1 b

/-- The voltage contributed by one signed generator step. -/
def voltageStep (r : I → Equiv.Perm B) (β : I → B → ZMod p)
    (m : I × Bool) (b : B) : ZMod p :=
  if m.2 then -β m.1 ((r m.1).symm b) else β m.1 b

/-- The base endpoint of a finite signed generator word. -/
def wordBase (r : I → Equiv.Perm B) : List (I × Bool) → B → B
  | [], b => b
  | m :: w, b => wordBase r w (baseStep r m b)

/-- The voltage of a finite signed generator word at a base point. -/
def wordVoltage (r : I → Equiv.Perm B) (β : I → B → ZMod p)
    : List (I × Bool) → B → ZMod p
  | [], _ => 0
  | m :: w, b => voltageStep r β m b + wordVoltage r β w (baseStep r m b)

/-- The lifted endpoint of a signed generator word. -/
def wordLift (r : I → Equiv.Perm B) (β : I → B → ZMod p)
    (w : List (I × Bool)) (x : ZMod p × B) : ZMod p × B :=
  (x.1 + wordVoltage r β w x.2, wordBase r w x.2)

/-- The orbit of a base point under the generated projected group. -/
def baseOrbit (r : I → Equiv.Perm B) (b₀ : B) : Set B :=
  {b | ∃ g : generatedBaseGroup B I r, g.1 b₀ = b}

/-- The orbit of a point under the signed lifted generator words. -/
def liftedOrbit (r : I → Equiv.Perm B) (β : I → B → ZMod p)
    (x : ZMod p × B) : Set (ZMod p × B) :=
  {y | ∃ w : List (I × Bool), wordLift r β w x = y}

/-- The subgroup of voltages of closed signed generator words at `b₀`. -/
def closedVoltageSubgroup (r : I → Equiv.Perm B) (β : I → B → ZMod p)
    (b₀ : B) : AddSubgroup (ZMod p) :=
  AddSubgroup.closure
    {v | ∃ w : List (I × Bool), wordBase r w b₀ = b₀ ∧ wordVoltage r β w b₀ = v}

/-- A path-voltage choice for one projected component. -/
def validPrimeFiberChoice [Fintype B] (r : I → Equiv.Perm B)
    (β : I → B → ZMod p) (O : Set B) (b₀ : B)
    (W : AddSubgroup (ZMod p)) (t : B → ZMod p) : Prop :=
  O = baseOrbit r b₀ ∧
    b₀ ∈ O ∧
    W = closedVoltageSubgroup r β b₀ ∧
    ∀ b, b ∈ O → ∃ w : List (I × Bool),
      wordBase r w b₀ = b ∧ wordVoltage r β w b₀ = t b

/-- The set displayed by the orbit formula for a field representative `a`. -/
def primeFiberFormulaSet [Fintype B] (O : Set B) (W : AddSubgroup (ZMod p))
    (t : B → ZMod p) (a : ZMod p) : Set (ZMod p × B) :=
  {x | ∃ b ∈ O, ∃ w : ZMod p, w ∈ W ∧ x = (a + t b + w, b)}

/-- All lifted orbit sets whose base projection meets `O`. -/
def liftedOrbitsOver [Fintype B] (r : I → Equiv.Perm B)
    (β : I → B → ZMod p) (O : Set B) : Set (Set (ZMod p × B)) :=
  {S | ∃ x : ZMod p × B, x.2 ∈ O ∧ S = liftedOrbit r β x}

/-- The formula set indexed by a coset of `W`, independent of its representative. -/
def primeFiberFormulaClass [Fintype B] (O : Set B) (W : AddSubgroup (ZMod p))
    (t : B → ZMod p) (a : ZMod p ⧸ W) : Set (ZMod p × B) :=
  {x | ∃ a' : ZMod p, QuotientAddGroup.mk a' = a ∧ x ∈ primeFiberFormulaSet O W t a'}

/-- The whole fiber over a projected component. -/
def primeFiberOver (O : Set B) : Set (ZMod p × B) :=
  {x | x.2 ∈ O}

/-- The potential graph in the quiet case. -/
def primeFiberPotentialGraph (O : Set B) (t : B → ZMod p)
    (a : ZMod p) : Set (ZMod p × B) :=
  {x | ∃ b ∈ O, x = (a + t b, b)}

/-- Exact orbit formula, including the quotient indexing and duplicate criterion. -/
def primeFiberOrbitFormula : Prop :=
  ∀ (B : Type u) [Fintype B] (I : Type v) (p : ℕ), Nat.Prime p →
    ∀ (r : I → Equiv.Perm B) (β : I → B → ZMod p)
      (O : Set B) (b₀ : B) (W : AddSubgroup (ZMod p)) (t : B → ZMod p),
      validPrimeFiberChoice r β O b₀ W t →
      liftedOrbitsOver r β O =
          {S | ∃ a : ZMod p ⧸ W, S = primeFiberFormulaClass O W t a} ∧
      (∀ a : ZMod p,
        liftedOrbit r β (a, b₀) = primeFiberFormulaSet O W t a) ∧
      (∀ a a' : ZMod p,
        liftedOrbit r β (a, b₀) = liftedOrbit r β (a', b₀) ↔
          QuotientAddGroup.mk (s := W) a = QuotientAddGroup.mk (s := W) a')

/-- The prime-field saturation/quiet alternative, with its orbit counts. -/
def primeFiberSaturationDichotomy : Prop :=
  ∀ (B : Type u) [Fintype B] (I : Type v) (p : ℕ), Nat.Prime p →
    ∀ (r : I → Equiv.Perm B) (β : I → B → ZMod p)
      (O : Set B) (b₀ : B) (W : AddSubgroup (ZMod p)) (t : B → ZMod p),
      validPrimeFiberChoice r β O b₀ W t →
      (W = ⊤ ∧
          liftedOrbitsOver r β O = {primeFiberOver O} ∧
          Set.Finite (liftedOrbitsOver r β O) ∧
          Set.ncard (liftedOrbitsOver r β O) = 1) ∨
      (W = ⊥ ∧
          liftedOrbitsOver r β O =
            {S | ∃ a : ZMod p, S = primeFiberPotentialGraph O t a} ∧
          Set.Finite (liftedOrbitsOver r β O) ∧
          Set.ncard (liftedOrbitsOver r β O) = p ∧
          (∀ a a' : ZMod p,
            primeFiberPotentialGraph O t a = primeFiberPotentialGraph O t a' ↔
              a = a'))

/-- The affine map used for a proposed repair. -/
def primeFiberAffineMap (e : ZMod p) (ell : B → ZMod p)
    (qbar : Equiv.Perm B) (x : ZMod p × B) : ZMod p × B :=
  (e * x.1 + ell x.2, qbar x.2)

/-- Setwise fixation of every lifted orbit. -/
def fixesEveryPrimeFiberOrbit (r : I → Equiv.Perm B) (β : I → B → ZMod p)
    (e : ZMod p) (ell : B → ZMod p) (qbar : Equiv.Perm B) : Prop :=
  ∀ x : ZMod p × B,
    Set.image (primeFiberAffineMap e ell qbar) (liftedOrbit r β x) = liftedOrbit r β x

/-- Preservation of every projected component by the base permutation. -/
def preservesEveryPrimeFiberComponent (r : I → Equiv.Perm B)
    (qbar : Equiv.Perm B) : Prop :=
  ∀ b : B, Set.image qbar (baseOrbit r b) = baseOrbit r b

/-- The quiet points, defined from the actual closed-word voltage subgroup. -/
def primeFiberQuietPoint {B : Type u} {I : Type v} {p : ℕ}
    (r : I → Equiv.Perm B) (β : I → B → ZMod p)
    (b : B) : Prop :=
  ∃ b₀ : B, b ∈ baseOrbit r b₀ ∧ closedVoltageSubgroup r β b₀ = ⊥

/-- Directions that vanish on quiet components and are free elsewhere. -/
def primeFiberQuietDirections {B : Type u} {I : Type v} {p : ℕ}
    (r : I → Equiv.Perm B) (β : I → B → ZMod p) :
    Set (B → ZMod p) :=
  {f | ∀ b : B, primeFiberQuietPoint r β b → f b = 0}

/-- An explicit translate of a function-direction set. -/
def primeFiberAffineCoset {B : Type u} {p : ℕ}
    (c : B → ZMod p) (D : Set (B → ZMod p)) :
    Set (B → ZMod p) :=
  {ell | ∃ d, d ∈ D ∧ ell = c + d}

/-- The exact criterion on an affine repair, with no condition in the saturated branch. -/
def primeFiberRepairCondition [Fintype B] (r : I → Equiv.Perm B)
    (β : I → B → ZMod p) (e : ZMod p) (ell : B → ZMod p)
    (qbar : Equiv.Perm B) : Prop :=
  preservesEveryPrimeFiberComponent r qbar ∧
    ((∃ b₀ : B, closedVoltageSubgroup r β b₀ = ⊥) → e = 1) ∧
    (∀ (O : Set B) (b₀ : B) (W : AddSubgroup (ZMod p)) (t : B → ZMod p),
      validPrimeFiberChoice r β O b₀ W t → W = ⊥ →
        ∀ b, b ∈ O → ell b = t (qbar b) - t b)

/-- Potentials solving the repair criterion for fixed base map and multiplier. -/
def primeFiberRepairPotentials [Fintype B] (r : I → Equiv.Perm B)
    (β : I → B → ZMod p) (e : ZMod p) (qbar : Equiv.Perm B) :
    Set (B → ZMod p) :=
  {ell | primeFiberRepairCondition r β e ell qbar}

/-- Exact affine-repair criterion and the affine-coset description of repairs. -/
def primeFiberAffineRepairCriterion : Prop :=
  ∀ (B : Type u) [Fintype B] (I : Type v) (p : ℕ), Nat.Prime p →
    ∀ (r : I → Equiv.Perm B) (β : I → B → ZMod p),
      (∀ (e : ZMod p) (ell : B → ZMod p) (qbar : Equiv.Perm B), e ≠ 0 →
        (fixesEveryPrimeFiberOrbit r β e ell qbar ↔
          primeFiberRepairCondition r β e ell qbar)) ∧
      (∀ (e : ZMod p) (qbar : Equiv.Perm B), e ≠ 0 →
        primeFiberRepairPotentials r β e qbar = ∅ ∨
          ∃ c : B → ZMod p,
            primeFiberRepairPotentials r β e qbar =
              primeFiberAffineCoset c (primeFiberQuietDirections r β))

end Common

end MathlibPlus.Open.PrimeFiber
