import Mathlib

<<<<<<< ours
namespace MathlibPlus.Open.ResearchFormalizationBatch

/-- The carrier and multiplication displayed in the prime-field semidirect setup. -/
def semidirectMul {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (u v : ZMod p × H) : ZMod p × H :=
  (u.1 + (↑(χ u.2) : ZMod p) * v.1, u.2 * v.2)

/-- The inverse formula for the displayed semidirect multiplication. -/
def semidirectInv {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (u : ZMod p × H) : ZMod p × H :=
  (-((↑(χ (u.2⁻¹)) : ZMod p) * u.1), u.2⁻¹)

/-- The coprime prime-field hypotheses shared by the semidirect claims. -/
def primeFieldSemidirectContext (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  Nat.Prime p ∧ ¬p ∣ Fintype.card H

/-- A normalized translation changes only the first coordinate. -/
def pureFiberTranslation {p : ℕ} {H : Type*} [Group H]
    (τ : H → ZMod p) (u : ZMod p × H) : ZMod p × H :=
  (u.1 + τ u.2, u.2)

/-- The inverse coordinate formula for a pure fibre translation. -/
def pureFiberTranslationInv {p : ℕ} {H : Type*} [Group H]
    (τ : H → ZMod p) (u : ZMod p × H) : ZMod p × H :=
  (u.1 - τ u.2, u.2)

/-- The coboundary appearing in the relative derivative formula. -/
def coboundaryDelta {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (τ : H → ZMod p) (h k : H) : ZMod p :=
  τ (h * k) - τ h - (↑(χ h) : ZMod p) * τ k

/--
The normalized relative derivative is written out as the usual translated
right-multiplication defect, followed by the inverse fibre translation.
-/
def normalizedRelativeDerivative {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (τ : H → ZMod p)
    (g z : ZMod p × H) : ZMod p × H :=
  pureFiberTranslationInv τ
    (semidirectMul χ
      (pureFiberTranslation τ (semidirectMul χ z g))
      (semidirectInv χ (pureFiberTranslation τ g)))

/-- The orbit generated by all relative-derivative translations in a fibre. -/
def relativeDerivativeFibreOrbit {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (τ : H → ZMod p) (h : H) : Set (ZMod p × H) :=
  {u | u.2 = h ∧
    u.1 ∈ AddSubgroup.closure
      (Set.range (fun k : H => coboundaryDelta χ τ h k))}

/--
Claim 43061: prime-field semidirect setup with the displayed multiplication.
-/
def claim43061 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ ∧
    ∀ (x y : ZMod p × H),
      semidirectMul χ x y =
        (x.1 + (↑(χ x.2) : ZMod p) * y.1, x.2 * y.2)

/--
Claim 43062: every normalized pure fibre translation has the displayed formula
and fixes its displayed H-coordinate.
-/
def claim43062 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ →
    ∀ (τ : H → ZMod p), τ 1 = 0 →
      ∀ (x : ZMod p) (h : H),
        pureFiberTranslation τ (x, h) = (x + τ h, h) ∧
          (pureFiberTranslation τ (x, h)).2 = h

/--
Claim 43063: the exact normalized relative-derivative formula, together with
independence of the first coordinate of g and preservation of each H-fibre.
-/
def claim43063 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ →
    ∀ (τ : H → ZMod p), τ 1 = 0 →
      ∀ (y : ZMod p) (k h : H) (x : ZMod p),
        normalizedRelativeDerivative χ τ (y, k) (x, h) =
            (x + coboundaryDelta χ τ h k, h) ∧
          (∀ y' : ZMod p,
            normalizedRelativeDerivative χ τ (y', k) (x, h) =
              normalizedRelativeDerivative χ τ (y, k) (x, h)) ∧
          (normalizedRelativeDerivative χ τ (y, k) (x, h)).2 = h

/--
Claim 43064: the quiet set is a subgroup, and every non-quiet fibre has the
full prime-field orbit generated by its nonzero relative derivatives.
-/
def claim43064 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ →
    ∀ (τ : H → ZMod p), τ 1 = 0 →
      let P : Set H := {h | ∀ k : H, coboundaryDelta χ τ h k = 0}
      P 1 ∧
        (∀ a b : H, P a → P b → P (a * b)) ∧
        (∀ a : H, P a → P a⁻¹) ∧
        (∀ h : H, ¬P h →
          ∃ k : H,
            coboundaryDelta χ τ h k ≠ 0 ∧
              relativeDerivativeFibreOrbit χ τ h =
                Set.range (fun x : ZMod p => (x, h)))

end MathlibPlus.Open.ResearchFormalizationBatch
=======
namespace MathlibPlus.Open.ResearchFormalizationBatch019ffee2

open scoped BigOperators

/-- The finite complementary form of the positive-offset equation. -/
def complementaryFiniteForm : Prop :=
  ∀ (n m : ℕ) (D : Finset ℕ) (hD : D.Nonempty),
    (∀ d ∈ D, 0 < d) →
    m ∈ D →
    D.max' hD = m →
    ((n : ℚ) =
        D.sum (fun d => ((n + d : ℕ) : ℚ) / (2 : ℚ) ^ d)) ↔
      ((2 : ℚ) ^ (m + 1) =
        (n + m + 2 : ℕ) +
          ((Finset.Icc 1 m).filter (fun d => d ∉ D)).sum
            (fun d => ((n + d : ℕ) : ℚ) * (2 : ℚ) ^ (m - d)))

/-- The residual sequence generated by the greedy branch rule, indexed from the
initial residual at offset zero. -/
def greedyResidualFrom (n : ℕ) : ℕ → ℤ
  | 0 => (n : ℤ)
  | j + 1 =>
      let r := greedyResidualFrom n j
      let k := n + j
      if 2 * r ≥ ((k + 1 : ℕ) : ℤ) then
        2 * r - ((k + 1 : ℕ) : ℤ)
      else
        2 * r

/-- The residual at the original index k (indices before n are immaterial). -/
def greedyResidual (n k : ℕ) : ℤ :=
  if n ≤ k then greedyResidualFrom n (k - n) else 0

/-- The digit selected by the greedy residual branch at offset j. -/
def greedyDigit (n j : ℕ) : Fin 2 :=
  if 2 * greedyResidualFrom n j ≥ ((n + j + 1 : ℕ) : ℤ) then 1 else 0

/-- Finiteness of the greedy representation, expressed as eventual vanishing of
its concrete branch digits. -/
def greedyRepresentationFinite (n : ℕ) : Prop :=
  ∃ J : ℕ, ∀ j : ℕ, J ≤ j → greedyDigit n j = 0

/-- The greedy residual bounds and the finite-representation criterion. -/
def greedyResidualCalculus : Prop :=
  ∀ n : ℕ,
    greedyResidual n n = (n : ℤ) ∧
    (∀ k : ℕ, n ≤ k →
      greedyResidual n (k + 1) =
        if 2 * greedyResidual n k ≥ ((k + 1 : ℕ) : ℤ) then
          2 * greedyResidual n k - ((k + 1 : ℕ) : ℤ)
        else
          2 * greedyResidual n k) ∧
    (∀ k : ℕ, n ≤ k →
      0 ≤ greedyResidual n k ∧
        greedyResidual n k ≤ ((k + 1 : ℕ) : ℤ)) ∧
    (greedyRepresentationFinite n ↔
      ∃ k : ℕ, n ≤ k ∧ greedyResidual n k = 0)

/-- The binary value of a digit stream whose positions start at one. -/
noncomputable def binaryValue (d : ℕ → Fin 2) : ℝ :=
  ∑' j : ℕ, ((d (j + 1)).val : ℝ) / (2 : ℝ) ^ (j + 1)

/-- The first weighted moment of the same binary digit stream. -/
noncomputable def binaryFirstMoment (d : ℕ → Fin 2) : ℝ :=
  ∑' j : ℕ,
    ((j + 1 : ℕ) : ℝ) * ((d (j + 1)).val : ℝ) / (2 : ℝ) ^ (j + 1)

/-- The sawtooth series used in the binary identity. -/
noncomputable def binarySawtooth (y : ℝ) : ℝ :=
  ∑' i : ℕ, Int.fract ((2 : ℝ) ^ i * y) / (2 : ℝ) ^ i

/-- A stream has the terminating/all-ones ambiguity when it has a constant binary tail. -/
def terminatingOrAllOnesTail (d : ℕ → Fin 2) : Prop :=
  ∃ p : ℕ, 1 ≤ p ∧
    ((∀ j : ℕ, p ≤ j → (d j).val = 0) ∨
      (∀ j : ℕ, p ≤ j → (d j).val = 1))

/-- The binary sawtooth identity away from the terminating/all-ones ambiguity. -/
def binarySawtoothIdentity : Prop :=
  ∀ (d : ℕ → Fin 2) (y : ℝ),
    y = binaryValue d →
    ¬ terminatingOrAllOnesTail d →
    Summable (fun j : ℕ =>
      ((j + 1 : ℕ) : ℝ) * ((d (j + 1)).val : ℝ) / (2 : ℝ) ^ (j + 1)) ∧
    Summable (fun i : ℕ =>
      Int.fract ((2 : ℝ) ^ i * y) / (2 : ℝ) ^ i) ∧
    binaryFirstMoment d = binarySawtooth y

/-- The two binary expansions at a dyadic ambiguity have a fixed moment gap. -/
def dyadicAmbiguityMomentGap : Prop :=
  ∀ (p : ℕ) (d₀ d₁ : ℕ → Fin 2),
    1 ≤ p →
    (∀ j : ℕ, j < p → d₀ j = d₁ j) →
    d₀ p = 1 →
    d₁ p = 0 →
    (∀ j : ℕ, p < j → d₀ j = 0) →
    (∀ j : ℕ, p < j → d₁ j = 1) →
    binaryValue d₀ = binaryValue d₁ ∧
    binaryFirstMoment d₁ - binaryFirstMoment d₀ =
      2 / (2 : ℝ) ^ p ∧
    binaryFirstMoment d₁ ≠ binaryFirstMoment d₀

end MathlibPlus.Open.ResearchFormalizationBatch019ffee2
>>>>>>> theirs
