import Mathlib

open scoped LinearAlgebra.Projectivization

noncomputable section

namespace MathlibPlus.Open.ResearchFormalizationBatchR1261Claim30750

abbrev ProjectivePoint (K : Type*) [Field K] (d : ℕ) :=
  ℙ K (Fin d → K)

/-- A semilinear projective permutation is specified by its field automorphism,
its bijective vector map, the semilinear laws, and the induced projective map.
The predicate is used only to form the full semilinear projective carrier. -/
def semilinearProjectiveElement {K : Type*} [Field K] [Fintype K]
    (d : ℕ) (p : Equiv.Perm (ProjectivePoint K d)) : Prop :=
  ∃ (σ : K ≃+* K) (f : (Fin d → K) ≃ (Fin d → K))
    (hf : ∀ v : Fin d → K, v ≠ 0 → f v ≠ 0),
    f 0 = 0 ∧
      (∀ v w : Fin d → K, f (v + w) = f v + f w) ∧
        (∀ (c : K) (v : Fin d → K),
          f (c • v) = σ c • f v) ∧
          (∀ (v : Fin d → K) (hv : v ≠ 0),
            p (Projectivization.mk K v hv) =
              Projectivization.mk K (f v) (hf v hv))

/-- The full `PΓL` carrier on the projective block, generated by all
semilinear projective permutations. -/
def pGammaLGroup (K : Type*) [Field K] [Fintype K] (d : ℕ) :
    Subgroup (Equiv.Perm (ProjectivePoint K d)) :=
  Subgroup.closure
    {p : Equiv.Perm (ProjectivePoint K d) |
      semilinearProjectiveElement d p}

/-- Regularity of a subgroup of the projective semilinear carrier on the
projective block. -/
def regularOnProjectiveBlock {K : Type*} [Field K] [Fintype K]
    (d : ℕ) (U : Subgroup (pGammaLGroup K d)) : Prop :=
  ∀ x y : ProjectivePoint K d,
    ∃! u : U,
      ((u : pGammaLGroup K d) : Equiv.Perm (ProjectivePoint K d)) x = y

/-- The full Singer torus of projective degree `d`: it is the cyclic regular
subgroup of order `m=(q^d-1)/(q-1)` in the full `PΓL` carrier. -/
def fullSingerTorus {K : Type*} [Field K] [Fintype K]
    (d m : ℕ) (U : Subgroup (pGammaLGroup K d)) : Prop :=
  1 < m ∧
    Odd m ∧
      ¬Nat.Prime m ∧
        Squarefree m ∧
          Nat.Coprime m 6 ∧
            m = (Nat.card K ^ d - 1) / (Nat.card K - 1) ∧
              Nat.card U = m ∧
                IsCyclic U ∧
                  regularOnProjectiveBlock d U

/-- Claim 30750: the full Singer torus has itself as its centralizer in the
full projective semilinear group; no containment in the projective special
linear subgroup is imposed. -/
def claim30750 : Prop :=
  ∀ (K : Type*) [Field K] [Fintype K] (d m : ℕ)
    (U : Subgroup (pGammaLGroup K d)),
    fullSingerTorus d m U →
      Subgroup.centralizer (U : Set (pGammaLGroup K d)) = U

end MathlibPlus.Open.ResearchFormalizationBatchR1261Claim30750
