import Mathlib

open scoped BigOperators

namespace MathlibPlus.Open.ResearchFormalizationBatch_01a003d0_6085_7e88_9855_ed1ff0b1b6e8

noncomputable section

/-- The recursively defined divided difference used by the Newton claims. -/
def newtonDividedDifference (f : ℝ → ℝ) : (m : ℕ) → (Fin (m + 1) → ℝ) → ℝ
  | 0, xs => f (xs 0)
  | m + 1, xs =>
      (newtonDividedDifference f m (fun i => xs i.succ) -
          newtonDividedDifference f m (fun i => xs i.castSucc)) /
        (xs (Fin.last (m + 1)) - xs 0)

/-- `L_m f = f[x₀, ..., x_m]` for a supplied sequence of nodes. -/
def newtonL (f : ℝ → ℝ) (x : ℕ → ℝ) (m : ℕ) : ℝ :=
  newtonDividedDifference f m (fun i => x i)

/-- Rising factorial `(y)_n`. -/
def risingFactorial (y : ℝ) (n : ℕ) : ℝ :=
  ∏ j ∈ Finset.range n, (y + (j : ℝ))

/-- The polynomial `Q_e` in the two identical admitted Newton claims. -/
def newtonQ (a : ℝ) (e : ℕ) (x : ℝ) : ℝ :=
  ∏ n ∈ Finset.range e, (x ^ 2 - (a + (n : ℝ)) ^ 2)

/-- The polynomial `F_e` in the two identical admitted Newton claims. -/
def newtonF (a : ℝ) (e : ℕ) : ℝ → ℝ :=
  fun x => newtonQ a e x - newtonQ a e 0

/-- Claim 1235, with all of its displayed carriers and auxiliary definitions. -/
def newton_divided_difference_identity_1235_01a003d0_6085_7e88_9855_ed1ff0b1b6e8 : Prop :=
  ∀ (a : ℝ) (e t : ℕ),
    newtonL (newtonF a e) (fun n => a + (n : ℝ)) (e + t) =
      if t ≤ e then
        (Nat.choose e t : ℝ) *
          risingFactorial (2 * a + (e : ℝ) + (t : ℝ)) (e - t)
      else 0

/-- Claim 1299, independently represented although its admitted statement is identical to Claim 1235. -/
def newton_divided_difference_identity_1299_01a003d0_6085_7e88_9855_ed1ff0b1b6e8 : Prop :=
  ∀ (a : ℝ) (e t : ℕ),
    newtonL (newtonF a e) (fun n => a + (n : ℝ)) (e + t) =
      if t ≤ e then
        (Nat.choose e t : ℝ) *
          risingFactorial (2 * a + (e : ℝ) + (t : ℝ)) (e - t)
      else 0

/-- Least positive residue of a unit modulo `N`, represented by `ZMod.val`. -/
def leastPositiveUnitResidue (N : ℕ) (a : (ZMod N)ˣ) : ℕ :=
  ZMod.val (a : ZMod N)

/-- The unit-stratum sum in Claim 8145. -/
def vasyuninUnitSum (N : ℕ) (r : (ZMod N)ˣ) : ℝ :=
  letI := Fintype.ofFinite (ZMod N)ˣ
  ∑ ell : (ZMod N)ˣ,
    (1 / 2 - (leastPositiveUnitResidue N (ell * r) : ℝ) / (N : ℝ)) *
      Real.cot (Real.pi * (leastPositiveUnitResidue N ell : ℝ) / (N : ℝ))

/-- The scaled kernel in Claim 8145. -/
def vasyuninUnitKernel (N : ℕ) (r : (ZMod N)ˣ) : ℝ :=
  (Real.pi / (N : ℝ)) * vasyuninUnitSum N r

/-- Claim 8145, including the stated range of the least positive residue. -/
def unit_stratum_vasyunin_kernel_01a003d0_6085_7e88_9855_ed1ff0b1b6e8 : Prop :=
  ∀ (N : ℕ), 1 < N →
    letI := Fintype.ofFinite (ZMod N)ˣ
    (∀ a : (ZMod N)ˣ,
      1 ≤ leastPositiveUnitResidue N a ∧
        leastPositiveUnitResidue N a < N) ∧
    (∀ r : (ZMod N)ˣ,
      vasyuninUnitKernel N r =
        (Real.pi / (N : ℝ)) *
          (∑ ell : (ZMod N)ˣ,
            (1 / 2 - (leastPositiveUnitResidue N (ell * r) : ℝ) / (N : ℝ)) *
              Real.cot
                (Real.pi * (leastPositiveUnitResidue N ell : ℝ) / (N : ℝ))))

/-- The incidence support of a ground point in an indexed finite family. -/
def incidenceSupport {α : Type*} [DecidableEq α] {m : ℕ}
    (A : Fin m → Finset α) (x : α) : Finset (Fin m) :=
  Finset.univ.filter (fun i => x ∈ A i)

/-- The finite ground set generated by an indexed family. -/
def indexedGround {α : Type*} [DecidableEq α] {m : ℕ}
    (A : Fin m → Finset α) : Finset α :=
  Finset.univ.biUnion A

/-- The support multiplicity attached to an indexed family. -/
def supportMultiplicity {α : Type*} [DecidableEq α] {m : ℕ}
    (A : Fin m → Finset α) (S : Finset (Fin m)) : ℕ :=
  (indexedGround A).filter (fun x => incidenceSupport A x = S) |>.card

/-- A tuple of finite sets is a sunflower when all pairwise intersections have one core. -/
def isSunflowerTuple {α : Type*} [DecidableEq α] {k : ℕ}
    (S : Fin k → Finset α) : Prop :=
  ∃ C : Finset α,
    (∀ j, C ⊆ S j) ∧
      (∀ j₁ j₂, j₁ ≠ j₂ → S j₁ ∩ S j₂ = C)

/-- The number of tuple positions whose member contains a ground point. -/
def tupleIncidenceCount {α : Type*} [DecidableEq α] {k : ℕ}
    (S : Fin k → Finset α) (x : α) : ℕ :=
  (Finset.univ.filter (fun j => x ∈ S j)).card

/-- Claim 16264: supports characterize sunflower tuples, triples, and separation. -/
def incidence_supports_characterize_sunflowers_01a003d0_6085_7e88_9855_ed1ff0b1b6e8 : Prop :=
  ∀ (α : Type*) [DecidableEq α] (m k : ℕ)
    (A : Fin m → Finset α) (I : Fin k → Fin m),
    (isSunflowerTuple (fun j => A (I j)) ↔
      ∀ x : α,
        tupleIncidenceCount (fun j => A (I j)) x = 0 ∨
          tupleIncidenceCount (fun j => A (I j)) x = 1 ∨
            tupleIncidenceCount (fun j => A (I j)) x = k) ∧
    (k = 3 →
      (¬ isSunflowerTuple (fun j => A (I j)) ↔
        ∃ x : α, tupleIncidenceCount (fun j => A (I j)) x = 2)) ∧
    (∀ i j : Fin m,
      (A i ≠ A j ↔
        ∃ x : α,
          (i ∈ incidenceSupport A x) ≠ (j ∈ incidenceSupport A x)))

/-- The ground set of a finite (unindexed) family. -/
def familyGround {α : Type*} [DecidableEq α]
    (F : Finset (Finset α)) : Finset α :=
  F.biUnion id

/-- The degree of a point in a finite family. -/
def familyDegree {α : Type*} [DecidableEq α]
    (F : Finset (Finset α)) (x : α) : ℕ :=
  (F.filter (fun S => x ∈ S)).card

/-- The number of ground points of degree greater than `D`. -/
def heavyGroundPointCount {α : Type*} [DecidableEq α]
    (F : Finset (Finset α)) (D : ℕ) : ℕ :=
  (familyGround F).filter (fun x => D < familyDegree F x) |>.card

/-- Uniformity for a finite family. -/
def isUniformFamily {α : Type*} [DecidableEq α]
    (F : Finset (Finset α)) (n : ℕ) : Prop :=
  ∀ S ∈ F, S.card = n

/-- Sunflower-freeness for a finite family, with indexed distinct members. -/
def isSunflowerFreeFamily {α : Type*} [DecidableEq α]
    (F : Finset (Finset α)) (k : ℕ) : Prop :=
  ¬ ∃ I : Fin k → Finset α,
      (∀ p q, p ≠ q → I p ≠ I q) ∧
        (∀ p, I p ∈ F) ∧
          isSunflowerTuple I

/-- Claim 16276: the heavy-coordinate exponential bound and its stated `k = 3`
variant. -/
def few_heavy_coordinates_exponential_bound_01a003d0_6085_7e88_9855_ed1ff0b1b6e8 : Prop :=
  ∀ (α : Type*) [DecidableEq α]
    (F : Finset (Finset α)) (n k D : ℕ) (β : ℝ),
    isUniformFamily F n →
    isSunflowerFreeFamily F k →
    ((heavyGroundPointCount F D : ℝ) ≤ β * (n : ℝ)) →
    (F.card : ℝ) ≤
        (((k - 1) * D * n : ℕ) : ℝ) * Real.rpow 2 (β * (n : ℝ)) ∧
      (k = 3 →
        (D = 1 →
          (F.card : ℝ) ≤ (2 : ℝ) * Real.rpow 2 (β * (n : ℝ))) ∧
        (2 ≤ D →
          (F.card : ℝ) ≤
            ((min (2 * D * n) (3 * (D - 1) * n + 3) : ℕ) : ℝ) *
              Real.rpow 2 (β * (n : ℝ))))

end
end MathlibPlus.Open.ResearchFormalizationBatch_01a003d0_6085_7e88_9855_ed1ff0b1b6e8
