import Mathlib
import MathlibPlus.Open.CayleyCI.FormalizationBatch
import MathlibPlus.Open.ProjectsResearch.CayleyCIClaims

namespace MathlibPlus.Open.ResearchFormalization60980

open Set
open MathlibPlus.Open.CayleyCI

/-- The setwise product of two subgroups is all of the ambient group. -/
def factorProduct {G : Type*} [Group G]
    (H K : Subgroup G) : Prop :=
  ∀ g : G, ∃ h k : G, h ∈ H ∧ k ∈ K ∧ h * k = g

/-- Trivial intersection of two subgroups, in elementwise form. -/
def trivialIntersection {G : Type*} [Group G]
    (H K : Subgroup G) : Prop :=
  ∀ x : G, x ∈ H → x ∈ K → x = 1

/-- Setwise stabilization of a subgroup by a group automorphism. -/
def stabilizesSubgroup {G : Type*} [Group G]
    (α : G ≃* G) (H : Subgroup G) : Prop :=
  ∀ x : G, x ∈ H ↔ α x ∈ H

/-- Surjectivity of the simultaneous restriction map. -/
def simultaneousRestrictionSurjective {G : Type*} [Group G]
    (H K : Subgroup G) : Prop :=
  ∀ φ : H ≃* H, ∀ ψ : K ≃* K,
    ∃ α : G ≃* G,
      stabilizesSubgroup α H ∧
        stabilizesSubgroup α K ∧
          (∀ h : H, α (h : G) = (φ h : G)) ∧
            ∀ k : K, α (k : G) = (ψ k : G)

/-- One automorphism carries every admissible factor pair to the displayed pair. -/
def factorPairTransport {G : Type*} [Group G] [Fintype G]
    (H K : Subgroup G) : Prop :=
  ∀ H' K' : Subgroup G,
    Nat.card H' = Nat.card H →
      Nat.card K' = Nat.card K →
        trivialIntersection H' K' →
          factorProduct H' K' →
            ∃ α : G ≃* G,
              Set.image α (H : Set G) = (H' : Set G) ∧
                Set.image α (K : Set G) = (K' : Set G)

/-- The general coprime-factor compression assertion. -/
def coprimeCartesianFactorCompressionCore
    (G : Type*) [Group G] [Fintype G]
    (H K : Subgroup G) (A B : Set G) : Prop := by
  classical
  letI : Fintype H := Fintype.ofFinite H
  letI : Fintype K := Fintype.ofFinite K
  exact H ≠ ⊥ →
    K ≠ ⊥ →
      H.Normal →
        trivialIntersection H K →
          factorProduct H K →
            Nat.Coprime (Nat.card H) (Nat.card K) →
              A ⊆ (H : Set G) \ ({1} : Set G) →
                B ⊆ (K : Set G) \ ({1} : Set G) →
                  InverseClosed G A →
                    InverseClosed G B →
                      Subgroup.closure A = H →
                        Subgroup.closure B = K →
                          (∀ k : G, k ∈ K →
                            Set.image (fun a => k * a * k⁻¹) A = A) →
                            OrdinaryUndirectedCIGroup H →
                              OrdinaryUndirectedCIGroup K →
                                factorPairTransport H K →
                                  simultaneousRestrictionSurjective H K →
                                    OrdinaryUndirectedCIConnectionSet G (A ∪ B) ∧
                                      OrdinaryUndirectedCIConnectionSet G
                                        (IdentityFreeComplement (A ∪ B))

/-- The A6 factor-axis conclusion for `F₂^r × C₉`. -/
def a6BinaryTimesC9 : Prop :=
  ∀ r : ℕ, (r = 3 ∨ r = 4 ∨ r = 5) →
    let V := Fin r → ZMod 2
    let G := V × ZMod 9
    ∀ A : Set V,
      A ⊆ (Set.univ : Set V) \ ({0} : Set V) →
        Submodule.span (ZMod 2) A = ⊤ →
          ∀ B : Set (ZMod 9),
            AddIdentityFreeInverseClosed (ZMod 9) B →
              AddSubgroup.closure B = ⊤ →
                let S :=
                  (A ×ˢ ({0} : Set (ZMod 9))) ∪
                    (({0} : Set V) ×ˢ B)
                AddOrdinaryUndirectedCIConnectionSet G S ∧
                  AddOrdinaryUndirectedCIConnectionSet G
                    (AddIdentityFreeComplement S)

/-- Composite odd square-free natural numbers. -/
def compositeOddSquarefree (m : ℕ) : Prop :=
  1 < m ∧ ¬ Nat.Prime m ∧ Odd m ∧ Squarefree m

/-- The rotation and outer axes in the presentation
`E(C_m,8) = ⟨a,t | a^m=t^8=1, tat⁻¹=a⁻¹⟩`. -/
def eRotationAxis (m : ℕ) : Set (eCarrier m 8) :=
  {x | x.2 = 0}

def eOuterAxis (m : ℕ) : Set (eCarrier m 8) :=
  {x | x.1 = 0}

def eComplement (m : ℕ) (S : Set (eCarrier m 8)) : Set (eCarrier m 8) :=
  {x | x ≠ eIdentity m 8 ∧ x ∉ S}

/-- A subgroup-closed set in the explicit semidirect-product presentation. -/
def eSubgroupClosed (m : ℕ)
    (S U : Set (eCarrier m 8)) : Prop :=
  S ⊆ U ∧
    eIdentity m 8 ∈ U ∧
      (∀ x : eCarrier m 8, x ∈ U →
        ∀ y : eCarrier m 8, y ∈ U → eMul m 8 x y ∈ U) ∧
        (∀ x : eCarrier m 8, x ∈ U → eInv m 8 x ∈ U)

/-- The subgroup generated by a set in the displayed presentation. -/
def eGenerated (m : ℕ) (S : Set (eCarrier m 8)) : Set (eCarrier m 8) :=
  {x | ∀ U : Set (eCarrier m 8), eSubgroupClosed m S U → x ∈ U}

/-- Ordinary undirected CI for the explicit `E(C_m,8)` carrier. -/
def eOrdinaryUndirectedCIConnectionSet (m : ℕ)
    (S : Set (eCarrier m 8)) : Prop :=
  eIdentityFree m 8 S ∧
    eInverseClosed m 8 S ∧
      ∀ T : Set (eCarrier m 8),
        eIdentityFree m 8 T →
          eInverseClosed m 8 T →
            eCayleyGraphIso m 8 S T →
              ∃ α : eCarrier m 8 ≃ eCarrier m 8,
                eAutomorphism m 8 α ∧ eTransports α S T

/-- The N3 factor-axis conclusion for the square-free semidirect family. -/
def n3CoprimeK8Squarefree : Prop :=
  compositeOddSquarefree 35 ∧
    ∀ m : ℕ, compositeOddSquarefree m →
      ∀ A : Set (eCarrier m 8),
        A ⊆ eRotationAxis m \ {eIdentity m 8} →
          eInverseClosed m 8 A →
            eGenerated m A = eRotationAxis m →
              ∀ B : Set (eCarrier m 8),
                B ⊆ eOuterAxis m \ {eIdentity m 8} →
                  eInverseClosed m 8 B →
                    eGenerated m B = eOuterAxis m →
                      let S := A ∪ B
                      eOrdinaryUndirectedCIConnectionSet m S ∧
                        eOrdinaryUndirectedCIConnectionSet m
                          (eComplement m S)

/-- The complete admitted coprime Cartesian-factor theorem and its two
maintained-cell consequences. -/
def CoprimeCartesianFactorCompressionTheorem : Prop :=
  (∀ (G : Type*) [Group G] [Fintype G]
      (H K : Subgroup G) (A B : Set G),
      coprimeCartesianFactorCompressionCore G H K A B) ∧
    a6BinaryTimesC9 ∧
      n3CoprimeK8Squarefree

end MathlibPlus.Open.ResearchFormalization60980
