import Mathlib

noncomputable section

namespace MathlibPlus.Open.ResearchFormalizationBatch_R1346

abbrev Record8Point := ZMod 35 × ZMod 8

/-- The Hall cycle in the explicit `Z₃₅ × Z₈` Record-8 chart. -/
def record8Hall : Equiv.Perm Record8Point :=
  Equiv.addRight ((1 : ZMod 35), (0 : ZMod 8))

/-- The inversion-and-outer-shift permutation in the Record-8 chart. -/
def record8Inversion : Equiv.Perm Record8Point :=
  (Equiv.prodCongr (Equiv.neg (ZMod 35)) (Equiv.refl (ZMod 8))).trans
    (Equiv.addRight ((0 : ZMod 35), (1 : ZMod 8)))

/-- Swap two local coordinates in every outer block. -/
def record8DiagonalTransposition (step : ZMod 35) : Equiv.Perm Record8Point :=
  Equiv.prodCongr (Equiv.swap (0 : ZMod 35) step) (Equiv.refl (ZMod 8))

/-- Conjugation convention used for the marked target copy. -/
def record8Conjugate (g s : Equiv.Perm Record8Point) : Equiv.Perm Record8Point :=
  s⁻¹ * g * s

/-- The source regular-copy generators. -/
def record8SourceGroup : Subgroup (Equiv.Perm Record8Point) :=
  Subgroup.closure ({record8Hall, record8Inversion} : Set (Equiv.Perm Record8Point))

/-- The two generators after replacing the local transposition by `(0 step)`. -/
def record8TargetHall (step : ZMod 35) : Equiv.Perm Record8Point :=
  record8Conjugate record8Hall (record8DiagonalTransposition step)

def record8TargetInversion (step : ZMod 35) : Equiv.Perm Record8Point :=
  record8Conjugate record8Inversion (record8DiagonalTransposition step)

/-- The ambient group generated by the source and marked target copies. -/
def record8AmbientGroup (step : ZMod 35) : Subgroup (Equiv.Perm Record8Point) :=
  Subgroup.closure
    ({record8Hall, record8Inversion, record8TargetHall step,
      record8TargetInversion step} : Set (Equiv.Perm Record8Point))

/-- The order-`r` marked subgroup in a cyclic order-35 copy. -/
def record8MarkedSubgroup (g : Equiv.Perm Record8Point) (r : ℕ) :
    Subgroup (Equiv.Perm Record8Point) :=
  Subgroup.closure ({g ^ (35 / r)} : Set (Equiv.Perm Record8Point))

/-- The orbit of a point under a marked subgroup. -/
def record8SubgroupOrbit
    (H : Subgroup (Equiv.Perm Record8Point)) (x : Record8Point) : Set Record8Point :=
  {y | ∃ h : Equiv.Perm Record8Point, h ∈ H ∧ h x = y}

/-- The orbit partition of a marked subgroup. -/
def record8OrbitPartition
    (H : Subgroup (Equiv.Perm Record8Point)) : Set (Set Record8Point) :=
  {B | ∃ x : Record8Point, record8SubgroupOrbit H x = B}

/-- The outer blocks, indexed by the `Z₈` coordinate. -/
def record8OuterBlocks : Set (Set Record8Point) :=
  {B | ∃ x : ZMod 8, B = {p | p.2 = x}}

/-- The explicit prime-cell refinement in the Record-8 chart. -/
def record8PrimeRefinement (r : ℕ) : Set (Set Record8Point) :=
  {B | ∃ x : ZMod 8, ∃ residue : Fin (35 / r),
      B = {p | p.2 = x ∧
        ∃ index : Fin r,
          p.1 = (residue.val : ZMod 35) +
            ((35 / r : ℕ) : ZMod 35) * (index.val : ZMod 35)}}

/-- A partition condition for a finite family of cells. -/
def record8IsPartition (Q : Set (Set Record8Point)) : Prop :=
  (∀ B ∈ Q, B.Nonempty) ∧
    (∀ B₁ ∈ Q, ∀ B₂ ∈ Q, B₁ ≠ B₂ → Disjoint B₁ B₂) ∧
    ⋃₀ Q = Set.univ

/-- Every cell of a refinement lies in one outer block. -/
def record8RefinesOuter (Q : Set (Set Record8Point)) : Prop :=
  ∀ B ∈ Q, ∃ O ∈ record8OuterBlocks, B ⊆ O

/-- The ambient marked group preserves a cell partition setwise. -/
def record8Preserves
    (G : Subgroup (Equiv.Perm Record8Point)) (Q : Set (Set Record8Point)) : Prop :=
  ∀ g : Equiv.Perm Record8Point, g ∈ G →
    ∀ B : Set Record8Point, B ∈ Q → g '' B ∈ Q

/-- All cells have the displayed cardinality. -/
def record8CellSize (Q : Set (Set Record8Point)) (r : ℕ) : Prop :=
  ∀ B ∈ Q, Nat.card {p : Record8Point // p ∈ B} = r

/-- The exact conclusion for one diagonal-transposition control. -/
def record8PrimeControl
    (step r cells : ℕ) : Prop :=
  let Q := record8PrimeRefinement r
  let sourceMarked := record8MarkedSubgroup record8Hall r
  let targetMarked := record8MarkedSubgroup (record8TargetHall step) r
  record8IsPartition Q ∧
    record8RefinesOuter Q ∧
    record8Preserves (record8AmbientGroup step) Q ∧
    Nat.card {B : Set Record8Point // B ∈ Q} = cells ∧
    record8CellSize Q r ∧
    Q = record8OrbitPartition sourceMarked ∧
    Q = record8OrbitPartition targetMarked

/-- Claim 41183: the `(0 7)` and `(0 5)` diagonal controls give the two
literal global common characteristic-subgroup refinements. -/
def claim41183 : Prop :=
  record8PrimeControl 7 5 56 ∧ record8PrimeControl 5 7 40

end MathlibPlus.Open.ResearchFormalizationBatch_R1346
