import Mathlib

noncomputable section
open scoped BigOperators
open MeasureTheory


namespace MathlibPlus.Open.ResearchFormalizationBatch_01a0014d

section PolynomialSpan

/-- The factor product in `ℚ[X,q]`, viewed as a polynomial in `q` with
coefficients in `ℚ[X]`. -/
def factorProduct (ell : ℕ) (mu : Fin ell → ℕ) : Polynomial (Polynomial ℚ) :=
  ∏ i : Fin ell,
    (1 + Polynomial.C (Polynomial.X : Polynomial ℚ) *
      (Polynomial.X : Polynomial (Polynomial ℚ)) ^ (mu i))

/-- The span indexed by nonnegative `ell`-tuples whose entries total `N`. -/
def factorProductSpan (ell N : ℕ) :
    Submodule ℚ (Polynomial (Polynomial ℚ)) :=
  Submodule.span ℚ {p | ∃ mu : Fin ell → ℕ,
    (∑ i : Fin ell, mu i) = N ∧
      p = factorProduct ell mu}

/-- `D(ell,N)` is the dimension of the fixed-total factor-product span. -/
def fixedTotalFactorProductSpan (D : ℕ → ℕ → ℕ) : Prop :=
  ∀ ell N,
    D ell N = Module.finrank ℚ (factorProductSpan ell N)

end PolynomialSpan

section FiniteActions

abbrev C6Squared := ZMod 6 × ZMod 6

/-- The left regular translation of `C₆²`. -/
def c6Translation (g : C6Squared) : Equiv.Perm C6Squared :=
  { toFun := fun h => g + h
    invFun := fun h => -g + h
    left_inv := by intro h; simp [add_assoc]
    right_inv := by intro h; simp [add_assoc] }

/-- A permutation representation is regular when it is transitive and free. -/
def IsRegularRepresentation {G V : Type*} [Group G]
    (rho : G →* Equiv.Perm V) : Prop :=
  Function.Injective rho ∧
    (∀ x y : V, ∃ g : G, rho g x = y) ∧
    (∀ (g : G) (x : V), rho g x = x → g = 1)

/-- The orbit equivalence relation generated by a permutation. -/
def permOrbitSetoid {V : Type*} (sigma : Equiv.Perm V) : Setoid V :=
  { r := Relation.EqvGen (fun x y : V => sigma x = y)
    iseqv :=
      { refl := fun x => Relation.EqvGen.refl x
        symm := fun {x y} h => Relation.EqvGen.symm x y h
        trans := fun {x y z} h₁ h₂ => Relation.EqvGen.trans x y z h₁ h₂ } }

/-- Number of cycles of a permutation. -/
def permCycleCount {V : Type*} [Fintype V] (sigma : Equiv.Perm V) : ℕ :=
  Nat.card (Quotient (permOrbitSetoid sigma))

/-- A regular additive-group permutation representation. -/
def IsRegularAdditiveRepresentation {V : Type*}
    (rho : C6Squared → Equiv.Perm V) : Prop :=
  (∀ g h : C6Squared, rho (g + h) = (rho g).trans (rho h)) ∧
    Function.Injective rho ∧
    (∀ x y : V, ∃ g : C6Squared, rho g x = y) ∧
    (∀ (g : C6Squared) (x : V), rho g x = x → g = 0)

/-- The regular-action cycle and sign assertion for every copy in `S₃₆`. -/
def everyRegularC6SquaredIsEven : Prop :=
  ∀ (rho : C6Squared → Equiv.Perm (Fin 36)),
    IsRegularAdditiveRepresentation rho →
      ∀ g : C6Squared,
        (addOrderOf g = 1 ∨ addOrderOf g = 2 ∨ addOrderOf g = 3 ∨ addOrderOf g = 6) ∧
        permCycleCount (rho g) = 36 / addOrderOf g ∧
        Equiv.Perm.sign (rho g) =
          (-1 : ℤˣ) ^ ((36 / addOrderOf g) * (addOrderOf g - 1)) ∧
        Equiv.Perm.sign (rho g) = 1

/-- The simultaneous action of `C₆²` on the two blocks. -/
def blockAction (g : C6Squared) : Equiv.Perm (C6Squared × Bool) :=
  { toFun := fun p => (g + p.1, p.2)
    invFun := fun p => (-g + p.1, p.2)
    left_inv := by rintro ⟨h, b⟩; simp [add_assoc]
    right_inv := by rintro ⟨h, b⟩; simp [add_assoc] }

/-- A blockwise permutation with prescribed permutations on the two blocks. -/
def blockwisePermutation (u v : Equiv.Perm C6Squared) :
    Equiv.Perm (C6Squared × Bool) :=
  { toFun := fun p => match p.2 with
      | false => (u p.1, false)
      | true => (v p.1, true)
    invFun := fun p => match p.2 with
      | false => (u.symm p.1, false)
      | true => (v.symm p.1, true)
    left_inv := by
      rintro ⟨h, b⟩
      cases b <;> simp
    right_inv := by
      rintro ⟨h, b⟩
      cases b <;> simp }

/-- The unshifted centralizing block swap. -/
def unshiftedBlockSwap : Equiv.Perm (C6Squared × Bool) :=
  { toFun := fun p => (p.1, !p.2)
    invFun := fun p => (p.1, !p.2)
    left_inv := by rintro ⟨h, b⟩; cases b <;> rfl
    right_inv := by rintro ⟨h, b⟩; cases b <;> rfl }

/-- The complement shift indexed by `a ∈ C₆²`. -/
def complementShift (a : C6Squared) : Equiv.Perm (C6Squared × Bool) :=
  { toFun := fun p => match p.2 with
      | false => (p.1 + a, true)
      | true => (p.1 - a, false)
    invFun := fun p => match p.2 with
      | false => (p.1 + a, true)
      | true => (p.1 - a, false)
    left_inv := by
      rintro ⟨h, b⟩
      cases b <;> simp [sub_eq_add_neg, add_assoc, add_left_comm, add_comm]
    right_inv := by
      rintro ⟨h, b⟩
      cases b <;> simp [sub_eq_add_neg, add_assoc, add_left_comm, add_comm] }

/-- A block swap and its centralizer condition. -/
def IsBlockSwap (f : Equiv.Perm (C6Squared × Bool)) : Prop :=
  ∀ (h : C6Squared) (b : Bool), (f (h, b)).2 = !b

def CentralizesBlockAction (f : Equiv.Perm (C6Squared × Bool)) : Prop :=
  ∀ (g : C6Squared) (x : C6Squared × Bool),
    f (blockAction g x) = blockAction g (f x)

def IsInvolution (f : Equiv.Perm (C6Squared × Bool)) : Prop :=
  ∀ x, f (f x) = x

/-- The explicit product of the alternating groups on the two blocks. -/
def InAlternatingProduct (u v : Equiv.Perm C6Squared) : Prop :=
  Equiv.Perm.sign u = 1 ∧ Equiv.Perm.sign v = 1

def secondBlockTranslation (a : C6Squared) : Equiv.Perm (C6Squared × Bool) :=
  blockwisePermutation (1 : Equiv.Perm C6Squared) (c6Translation a)

/-- Classification and conjugacy of all centralizing complement shifts. -/
def independentProductComplementTorsorCollapse : Prop :=
  (∀ (f : Equiv.Perm (C6Squared × Bool)),
    IsBlockSwap f → IsInvolution f → CentralizesBlockAction f →
      ∃! a : C6Squared,
        (∀ h : C6Squared, f (h, false) = (h + a, true)) ∧
        (∀ h : C6Squared, f (h, true) = (h - a, false))) ∧
  (∀ a : C6Squared,
    InAlternatingProduct (1 : Equiv.Perm C6Squared) (c6Translation a) ∧
      Equiv.Perm.sign (secondBlockTranslation a) = 1 ∧
      (∀ x,
        secondBlockTranslation a (unshiftedBlockSwap
          ((secondBlockTranslation a).symm x)) = complementShift a x)) ∧
  Fintype.card C6Squared = 36 ∧
  (∀ a b : C6Squared, complementShift a = complementShift b ↔ a = b)

end FiniteActions

section RegularConjugators

abbrev C3SquaredAdd := ZMod 3 × ZMod 3
abbrev C3Squared := Multiplicative C3SquaredAdd
abbrev D10 := DihedralGroup 5
abbrev C3SquaredTimesD10 := C3Squared × D10

/-- An action intertwiner through an abstract-group automorphism. -/
def IntertwinesRegularActions {G V : Type*} [Group G]
    (rho sigma : G →* Equiv.Perm V) (p : Equiv.Perm V) : Prop :=
  ∃ phi : G ≃* G, ∀ (g : G) (x : V),
    p (rho g x) = sigma (phi g) (p x)

def RegularActionConjugators (rho sigma : C3SquaredTimesD10 →* Equiv.Perm (Fin 90)) :=
  {p : Equiv.Perm (Fin 90) // IntertwinesRegularActions rho sigma p}

/-- Number of regular-action conjugators between two fixed regular copies. -/
def regularActionConjugatorCount : Prop :=
  ∀ (rho sigma : C3SquaredTimesD10 →* Equiv.Perm (Fin 90)),
    IsRegularRepresentation rho → IsRegularRepresentation sigma →
      Nat.card (RegularActionConjugators rho sigma) =
          90 * Fintype.card (C3SquaredTimesD10 ≃* C3SquaredTimesD10) ∧
      Fintype.card (C3SquaredTimesD10 ≃* C3SquaredTimesD10) = 48 * 20 ∧
      Fintype.card (C3SquaredAdd ≃+ C3SquaredAdd) = 48 ∧
      Fintype.card (D10 ≃* D10) = 20 ∧
      90 * (48 * 20) = 86400

end RegularConjugators

section GraphCriterion

def GraphPreserved {V : Type*} (graph : SimpleGraph V)
    (p : Equiv.Perm V) : Prop :=
  ∀ x y, graph.Adj (p x) (p y) ↔ graph.Adj x y

def GraphInvariantUnder {G V : Type*} [Group G]
    (graph : SimpleGraph V) (rho : G →* Equiv.Perm V) : Prop :=
  ∀ (g : G) (x y : V),
    graph.Adj (rho g x) (rho g y) ↔ graph.Adj x y

/-- Basepoint edge/nonedge incidences determine a graph-preserving regular
action isomorphism. -/
def basepointIncidenceCriterion : Prop :=
  ∀ (graph : SimpleGraph (Fin 90))
    (rho sigma : C3SquaredTimesD10 →* Equiv.Perm (Fin 90))
    (p : Equiv.Perm (Fin 90)) (phi : C3SquaredTimesD10 ≃* C3SquaredTimesD10)
    (base : Fin 90),
    IsRegularRepresentation rho → IsRegularRepresentation sigma →
    GraphInvariantUnder graph rho → GraphInvariantUnder graph sigma →
    (∀ (g : C3SquaredTimesD10) (x : Fin 90),
      p (rho g x) = sigma (phi g) (p x)) →
      (GraphPreserved graph p ↔
        ∀ y : Fin 90, y ≠ base →
          (graph.Adj base y ↔ graph.Adj (p base) (p y)))

end GraphCriterion

section HeatTransform

abbrev HeatM (P : ℕ) := 2 * P + 1

def heatL : ℝ := 1529 / 10000
def heatTStar : ℝ := 1479 / 10000
def heatY : ℝ := 1 / 10
def heatX : ℝ := 6000000185827

def heatEpsilon : ℝ := Real.rpow 2 (-100)
def heatB : ℝ := 4 - 2 * Real.exp heatTStar * Real.cosh heatY

def heatDyadicTail (k : ℕ) : ℝ := Real.rpow 2 (-(k : ℝ) ^ 4)
def heatR (M : ℕ) : ℝ :=
  2 * heatEpsilon * ∑' k : ℕ,
    if M < k then
      (-1 : ℝ) ^ k * heatDyadicTail k *
        Real.exp (heatTStar * (k : ℝ) ^ 2) * Real.cosh ((k : ℝ) * heatY)
    else 0

def heatW (M : ℕ) : ℝ :=
  (heatB + heatR M) /
    (2 * Real.exp (heatTStar * (M : ℝ) ^ 2) *
      Real.cosh ((M : ℝ) * heatY))

def heatAtom (weight location : ℝ) : Measure ℝ :=
  ENNReal.ofReal weight • Measure.dirac location

def heatMeasure (P : ℕ) : Measure ℝ :=
  heatAtom 4 0 + heatAtom 1 1 + heatAtom 1 (-1) +
    heatAtom (heatW (HeatM P)) (HeatM P) +
    heatAtom (heatW (HeatM P)) (-(HeatM P : ℝ)) +
    Measure.sum (fun k : ℕ =>
      if HeatM P < k then
        heatAtom (heatEpsilon * heatDyadicTail k) k +
          heatAtom (heatEpsilon * heatDyadicTail k) (-k)
      else 0)

def integerLattice : Set ℝ := Set.range (fun n : ℤ => (n : ℝ))

def IsEvenRealMeasure (mu : Measure ℝ) : Prop :=
  ∀ A : Set ℝ, MeasurableSet A →
    mu A = mu ((fun x : ℝ => -x) ⁻¹' A)

def heatTailTransformTerm (P : ℕ) (s : ℝ) (k : ℕ) (z : ℂ) : ℂ :=
  if HeatM P < k then
    (heatEpsilon * heatDyadicTail k : ℂ) *
      Complex.exp ((s * (k : ℝ) ^ 2 : ℝ) : ℂ) *
      (Complex.exp (Complex.I * z * (k : ℂ)) +
        Complex.exp (-Complex.I * z * (k : ℂ)))
  else 0

def HeatTailLocallyUniformlyConvergent (P : ℕ) : Prop :=
  ∀ (s : ℝ) (K : Set ℂ), IsCompact K →
    ∀ ε : ℝ, 0 < ε →
      ∃ N : ℕ, ∀ m n : ℕ, N ≤ m → N ≤ n →
        ∀ z : ℂ, z ∈ K →
          ‖Finset.sum (Finset.Icc m n)
              (fun k => heatTailTransformTerm P s k z)‖ < ε

def heatTransform (P : ℕ) (s : ℝ) (z : ℂ) : ℂ :=
  ∫ u : ℝ,
    Complex.exp ((s * u ^ 2 : ℝ) : ℂ) *
      Complex.exp (Complex.I * z * (u : ℂ)) ∂(heatMeasure P)

/-- The exact positive even source and its locally uniform heat-transform tail. -/
def exactPositiveEvenSource : Prop :=
  ∀ P : ℕ, 1 ≤ P →
    let M := HeatM P
    0 < heatEpsilon ∧ M = 2 * P + 1 ∧
      0 < heatW M ∧
      (∀ k : ℕ, M < k → 0 < heatEpsilon * heatDyadicTail k) ∧
      IsFiniteMeasure (heatMeasure P) ∧
      IsEvenRealMeasure (heatMeasure P) ∧
      heatMeasure P (integerLatticeᶜ) = 0 ∧
      HeatTailLocallyUniformlyConvergent P ∧
      ∀ s : ℝ, Differentiable ℂ (heatTransform P s)

/-- Positivity of the cancellation weight. -/
def heatTailExponent (k : ℕ) : ℝ :=
  (k : ℝ) ^ 4 - 2 * (k : ℝ) ^ 2 - 2 * (k : ℝ)

def positivityBoundsForCancellationWeight : Prop :=
  (heatTailExponent 4 = 216 ∧
    ∀ k : ℕ, 4 ≤ k → heatTailExponent (k + 1) - heatTailExponent k > 1) ∧
  ∀ M : ℕ, 3 ≤ M →
    |heatR M| < Real.rpow 2 (-314) ∧
      Real.rpow 2 (-314) < 1 ∧
      heatB > 146 / 99 ∧
      146 / 99 > (1 : ℝ) ∧
      heatB + heatR M > 0 ∧
      0 < heatW M

/-- Positive definiteness of every finite weighted moment Hankel form. -/
def finiteWeightedMomentHankelPositiveDefinite : Prop :=
  ∀ P : ℕ, 1 ≤ P → ∀ m : ℕ, ∀ q : Fin (m + 1) → ℝ,
    q ≠ 0 →
      (∑ i : Fin (m + 1), ∑ j : Fin (m + 1),
        q i * q j *
          ∫ u : ℝ, u ^ ((i : ℕ) + (j : ℕ)) *
            Real.exp (heatL * u ^ 2) ∂(heatMeasure P)) =
        (∫ u : ℝ,
          (∑ i : Fin (m + 1), q i * u ^ (i : ℕ)) ^ 2 *
            Real.exp (heatL * u ^ 2) ∂(heatMeasure P)) ∧
      0 < (∫ u : ℝ,
          (∑ i : Fin (m + 1), q i * u ^ (i : ℕ)) ^ 2 *
            Real.exp (heatL * u ^ 2) ∂(heatMeasure P))

def heatTargetZ : ℂ :=
  ((2 * heatX + 1) * Real.pi : ℝ) + heatY * Complex.I

/-- Backward heat transform properties and the exact target-ray zero. -/
def backwardHeatTransformAndTargetZero : Prop :=
  ∀ P : ℕ, 1 ≤ P →
    (∀ s : ℝ,
      (∀ z : ℂ, heatTransform P s (-z) = heatTransform P s z) ∧
      (∀ x : ℝ, (heatTransform P s (x : ℂ)).im = 0) ∧
      Differentiable ℂ (heatTransform P s) ∧
      (∀ z : ℂ,
        deriv (fun s' : ℝ => heatTransform P s' z) s =
          -deriv (fun z' : ℂ =>
            deriv (fun w : ℂ => heatTransform P s w) z') z)) ∧
      (∀ k : ℕ,
        Complex.cos ((k : ℂ) * heatTargetZ) =
          (((-1 : ℝ) ^ k * Real.cosh ((k : ℝ) * heatY)) : ℂ)) ∧
    heatTransform P heatTStar heatTargetZ =
      ((heatB -
        2 * heatW (HeatM P) *
          Real.exp (heatTStar * (HeatM P : ℝ) ^ 2) *
          Real.cosh ((HeatM P : ℝ) * heatY) +
        heatR (HeatM P) : ℝ) : ℂ) ∧
    (heatB -
        2 * heatW (HeatM P) *
          Real.exp (heatTStar * (HeatM P : ℝ) ^ 2) *
          Real.cosh ((HeatM P : ℝ) * heatY) +
        heatR (HeatM P) = 0)

/-- Exact target identity and final-ray placement. -/
def exactTargetIdentityAndFinalRayPlacement : Prop :=
  heatTStar + heatY ^ 2 / 2 = heatL ∧
    heatY ^ 2 = 1 / 100 ∧
    heatY ^ 2 < 1 - 2 * heatTStar ∧
    heatTargetZ.re = (2 * heatX + 1) * Real.pi ∧
    (2 * heatX + 1) * Real.pi > heatX + Real.sqrt (1 - heatY ^ 2)

end HeatTransform

end MathlibPlus.Open.ResearchFormalizationBatch_01a0014d
