import Mathlib

namespace MathlibPlus.Open.ResearchFormalizationBatch_01a001b7_8151_7192_bf7c_77d39208c988

/-- The fiberwise map determined by a family of permutations. -/
def normalizedIdentityBaseFiberMap
    (A B : Type*) [AddCommGroup A] [AddCommGroup B]
    (p : A → Equiv.Perm B) : A × B → A × B :=
  fun ab => (ab.1, p ab.1 ab.2)

/-- Exact statement of the normalized identity-base fiber-map claim. -/
def normalizedIdentityBaseFiberMapClaim
    (A B : Type*) [Fintype A] [AddCommGroup A]
    [Fintype B] [AddCommGroup B]
    (_elementaryTwo : ∀ a : A, a + a = 0)
    (_oddOrder : Odd (Fintype.card B))
    (p : A → Equiv.Perm B)
    (_normalized : p 0 = Equiv.refl B) : Prop :=
  let f := normalizedIdentityBaseFiberMap A B p
  (∀ a : A,
      Set.image f {z : A × B | z.1 = a} = {z : A × B | z.1 = a}) ∧
    ∀ (a : A) (b : B), (f (a, b)).1 = a

/-- The subgroup generated by the stated displacements. -/
def displacementSubgroup
    (B : Type*) [AddCommGroup B] (p : Equiv.Perm B) : AddSubgroup B :=
  AddSubgroup.closure (Set.range (fun t : B => t - p t + p 0))

/-- The additive Cayley adjacency relation for a connection set. -/
def c2PowC9CayleyAdjacency
    (r : ℕ) (S : Set ((Fin r → ZMod 2) × ZMod 9))
    (x y : (Fin r → ZMod 2) × ZMod 9) : Prop :=
  x ≠ y ∧ y - x ∈ S

/-- Isomorphism of the concrete undirected Cayley relations. -/
def c2PowC9CayleyIsomorphism
    (r : ℕ)
    (S T : Set ((Fin r → ZMod 2) × ZMod 9)) : Prop :=
  ∃ e : ((Fin r → ZMod 2) × ZMod 9) ≃ ((Fin r → ZMod 2) × ZMod 9),
    ∀ x y,
      c2PowC9CayleyAdjacency r S x y ↔
        c2PowC9CayleyAdjacency r T (e x) (e y)

/-- The CI assertion at one rank. -/
def c2PowC9CIAt (r : ℕ) : Prop :=
  ∀ (S T : Set ((Fin r → ZMod 2) × ZMod 9)),
    (∀ s, s ∈ S → s ≠ 0) →
    (∀ t, t ∈ T → t ≠ 0) →
    (∀ s, s ∈ S → -s ∈ S) →
    (∀ t, t ∈ T → -t ∈ T) →
    S.ncard ≤ 2 →
    c2PowC9CayleyIsomorphism r S T →
    ∃ α : ((Fin r → ZMod 2) × ZMod 9) ≃+ ((Fin r → ZMod 2) × ZMod 9),
      α '' S = T

/-- Exact CI-graph claim, including its stated residual-rank instance. -/
def c2PowC9CIClaim : Prop :=
  (∀ r : ℕ, 0 ≤ r → c2PowC9CIAt r) ∧
    (∀ r : ℕ, r = 3 ∨ r = 4 ∨ r = 5 → c2PowC9CIAt r)

/-- The uniform clearance and sharpness assertion at the stated threshold. -/
def sharpStrictThresholdClearance : Prop :=
  ∀ (c : ℝ), c > (1629 : ℝ) / 10000 →
    ((∀ Λ : ℝ, Λ ≤ (1629 : ℝ) / 10000 →
        0 < c - Λ ∧
          c - (1629 : ℝ) / 10000 ≤ c - Λ) ∧
      (∀ d : ℝ,
        (∀ Λ : ℝ, Λ ≤ (1629 : ℝ) / 10000 → d ≤ c - Λ) →
          d ≤ c - (1629 : ℝ) / 10000))

end MathlibPlus.Open.ResearchFormalizationBatch_01a001b7_8151_7192_bf7c_77d39208c988
