import Mathlib

namespace MathlibPlus.Open.ResearchFormalizationBatch

/-- The carrier and multiplication displayed in the prime-field semidirect setup. -/
def semidirectMul {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (u v : ZMod p × H) : ZMod p × H :=
  (u.1 + (↑(χ u.2) : ZMod p) * v.1, u.2 * v.2)

/-- The inverse formula for the displayed semidirect multiplication. -/
def semidirectInv {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (u : ZMod p × H) : ZMod p × H :=
  (-((↑(χ (u.2⁻¹)) : ZMod p) * u.1), u.2⁻¹)

/-- The coprime prime-field hypotheses shared by the semidirect claims. -/
def primeFieldSemidirectContext (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  Nat.Prime p ∧ ¬p ∣ Fintype.card H

/-- A normalized translation changes only the first coordinate. -/
def pureFiberTranslation {p : ℕ} {H : Type*} [Group H]
    (τ : H → ZMod p) (u : ZMod p × H) : ZMod p × H :=
  (u.1 + τ u.2, u.2)

/-- The inverse coordinate formula for a pure fibre translation. -/
def pureFiberTranslationInv {p : ℕ} {H : Type*} [Group H]
    (τ : H → ZMod p) (u : ZMod p × H) : ZMod p × H :=
  (u.1 - τ u.2, u.2)

/-- The coboundary appearing in the relative derivative formula. -/
def coboundaryDelta {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (τ : H → ZMod p) (h k : H) : ZMod p :=
  τ (h * k) - τ h - (↑(χ h) : ZMod p) * τ k

/--
The normalized relative derivative is written out as the usual translated
right-multiplication defect, followed by the inverse fibre translation.
-/
def normalizedRelativeDerivative {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (τ : H → ZMod p)
    (g z : ZMod p × H) : ZMod p × H :=
  pureFiberTranslationInv τ
    (semidirectMul χ
      (pureFiberTranslation τ (semidirectMul χ z g))
      (semidirectInv χ (pureFiberTranslation τ g)))

/-- The orbit generated by all relative-derivative translations in a fibre. -/
def relativeDerivativeFibreOrbit {p : ℕ} {H : Type*} [Group H]
    (χ : H →* (ZMod p)ˣ) (τ : H → ZMod p) (h : H) : Set (ZMod p × H) :=
  {u | u.2 = h ∧
    u.1 ∈ AddSubgroup.closure
      (Set.range (fun k : H => coboundaryDelta χ τ h k))}

/--
Claim 43061: prime-field semidirect setup with the displayed multiplication.
-/
def claim43061 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ ∧
    ∀ (x y : ZMod p × H),
      semidirectMul χ x y =
        (x.1 + (↑(χ x.2) : ZMod p) * y.1, x.2 * y.2)

/--
Claim 43062: every normalized pure fibre translation has the displayed formula
and fixes its displayed H-coordinate.
-/
def claim43062 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ →
    ∀ (τ : H → ZMod p), τ 1 = 0 →
      ∀ (x : ZMod p) (h : H),
        pureFiberTranslation τ (x, h) = (x + τ h, h) ∧
          (pureFiberTranslation τ (x, h)).2 = h

/--
Claim 43063: the exact normalized relative-derivative formula, together with
independence of the first coordinate of g and preservation of each H-fibre.
-/
def claim43063 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ →
    ∀ (τ : H → ZMod p), τ 1 = 0 →
      ∀ (y : ZMod p) (k h : H) (x : ZMod p),
        normalizedRelativeDerivative χ τ (y, k) (x, h) =
            (x + coboundaryDelta χ τ h k, h) ∧
          (∀ y' : ZMod p,
            normalizedRelativeDerivative χ τ (y', k) (x, h) =
              normalizedRelativeDerivative χ τ (y, k) (x, h)) ∧
          (normalizedRelativeDerivative χ τ (y, k) (x, h)).2 = h

/--
Claim 43064: the quiet set is a subgroup, and every non-quiet fibre has the
full prime-field orbit generated by its nonzero relative derivatives.
-/
def claim43064 (p : ℕ) {H : Type*} [Fintype H] [Group H]
    (χ : H →* (ZMod p)ˣ) : Prop :=
  primeFieldSemidirectContext p χ →
    ∀ (τ : H → ZMod p), τ 1 = 0 →
      let P : Set H := {h | ∀ k : H, coboundaryDelta χ τ h k = 0}
      P 1 ∧
        (∀ a b : H, P a → P b → P (a * b)) ∧
        (∀ a : H, P a → P a⁻¹) ∧
        (∀ h : H, ¬P h →
          ∃ k : H,
            coboundaryDelta χ τ h k ≠ 0 ∧
              relativeDerivativeFibreOrbit χ τ h =
                Set.range (fun x : ZMod p => (x, h)))

end MathlibPlus.Open.ResearchFormalizationBatch
