import Mathlib

open scoped BigOperators Matrix

namespace MathlibPlus.Open.Analysis.Claim15188

noncomputable section

/-- The coefficient vector of a polynomial in the monomial basis through order `m`. -/
def coefficientVector (m : ℕ) (p : Polynomial ℝ) : Fin m → ℝ :=
  fun i => p.coeff i.1

/-- The last-coordinate vector used for a monic formal extremal equation. -/
def terminalVector (n : ℕ) (a : ℝ) : Fin (n + 1) → ℝ :=
  fun i => if i = Fin.last n then a else 0

/-- The finite Hankel section with the coefficient convention of the packet. -/
def hankelSection (μ : ℕ → ℝ) (m : ℕ) : Matrix (Fin m) (Fin m) ℝ :=
  fun i j => μ (i.1 + j.1)

/-- The lower triangular Toeplitz section generated by `P`. -/
def toeplitzSection (P : Polynomial ℝ) (m : ℕ) : Matrix (Fin m) (Fin m) ℝ :=
  fun i j => if j.1 ≤ i.1 then P.coeff (i.1 - j.1) else 0

/-- The scalar coupling in the finite Uvarov data. -/
def uvarovLambda (v : ℕ → ℝ) (π : ℕ → Polynomial ℝ) (k : ℕ) : ℝ :=
  ∑ i : Fin (k + 1), v i.1 * (π k).coeff i.1

/-- The cumulative Uvarov normalizing factor. -/
def uvarovEta (α : ℝ) (v h : ℕ → ℝ) (π : ℕ → Polynomial ℝ) (m : ℕ) : ℝ :=
  1 + α * ∑ k ∈ Finset.range m,
    uvarovLambda v π k ^ 2 / h k

/-- The monic updated extremal displayed by the finite Uvarov formula. -/
def updatedExtremal (α : ℝ) (v h : ℕ → ℝ) (π : ℕ → Polynomial ℝ) (n : ℕ) : Polynomial ℝ :=
  π n -
    (α * uvarovLambda v π n / uvarovEta α v h π n) •
      ∑ k ∈ Finset.range n,
        (uvarovLambda v π k / h k) • π k

/--
The pullback of the active monic extremal and the two stated terminal-pivot
normalizations.  The scalar Hankel and rank-one-update carriers, the lower
Toeplitz congruence, the formal Uvarov polynomial, and the Schur-complement
active vector are all made explicit; the pullback is a conclusion, not a
hypothesis.
-/
def pullbackActiveExtremalAndTerminalPivot_claim15188 : Prop :=
  ∀ (n : ℕ) (P C : Polynomial ℝ) (α : ℝ)
    (π : ℕ → Polynomial ℝ) (h : ℕ → ℝ),
    P.coeff 0 ≠ 0 →
    let p0 : ℝ := P.coeff 0
    let Pseries : PowerSeries ℝ := Polynomial.toPowerSeries P
    let invP : PowerSeries ℝ := PowerSeries.inv Pseries
    let Qseries : PowerSeries ℝ :=
      -(PowerSeries.X * PowerSeries.derivative ℝ Pseries * invP)
    let Vseries : PowerSeries ℝ := Polynomial.toPowerSeries C * invP
    let μ : ℕ → ℝ := fun j => PowerSeries.coeff (j + 1) Qseries
    let v : ℕ → ℝ := fun j => PowerSeries.coeff j Vseries
    let T : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ :=
      toeplitzSection P (n + 1)
    let H : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ :=
      hankelSection μ (n + 1)
    let M : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ :=
      fun i j => H i j + α * v i.1 * v j.1
    let pihat : Polynomial ℝ := updatedExtremal α v h π n
    let hhat : ℝ :=
      h n + α * uvarovLambda v π n ^ 2 / uvarovEta α v h π n
    (∀ k : ℕ, k ≤ n →
      (π k).Monic ∧
        (π k).natDegree = k ∧
        Matrix.det (hankelSection μ (k + 1)) ≠ 0 ∧
        h k ≠ 0 ∧
        hankelSection μ (k + 1) *ᵥ coefficientVector (k + 1) (π k) =
          terminalVector k (h k)) →
    uvarovEta α v h π n ≠ 0 →
    pihat.Monic ∧
      pihat.natDegree = n ∧
      Matrix.det M ≠ 0 ∧
      M *ᵥ coefficientVector (n + 1) pihat = terminalVector n hhat →
    let G : Matrix (Fin (n + 1)) (Fin (n + 1)) ℝ :=
      T * M * T.transpose
    let last : Fin (n + 1) := Fin.last n
    let K : Matrix (Fin n) (Fin n) ℝ :=
      fun i j => G i.castSucc j.castSucc
    let b : Fin n → ℝ := fun i => G i.castSucc last
    let c : ℝ := G last last
    ∀ hK : K.PosDef,
    letI := hK.isUnit.invertible
    let q : Fin (n + 1) → ℝ :=
      Fin.lastCases (1 : ℝ)
        (fun i : Fin n => -(K⁻¹ *ᵥ b) i)
    let pG : ℝ := c - b ⬝ᵥ (K⁻¹ *ᵥ b)
    T.transpose *ᵥ q = (fun i => p0 * coefficientVector (n + 1) pihat i) ∧
      pG = p0 ^ 2 * hhat ∧
      pG = p0 ^ 2 * h n *
        (uvarovEta α v h π (n + 1) / uvarovEta α v h π n)

end

end MathlibPlus.Open.Analysis.Claim15188
