import Mathlib

namespace MathlibPlus.Open.Analysis

open scoped BigOperators ENNReal MeasureTheory ProbabilityTheory
open MeasureTheory

noncomputable section

/-- The two signs, represented by their integer values. -/
def Sign : Type := {x : ℤ // x = -1 ∨ x = 1}

instance : MeasurableSpace Sign := ⊤

noncomputable instance : DecidableEq Sign := Classical.decEq Sign

instance : LE Sign := ⟨fun a b => a.1 ≤ b.1⟩

def negSign : Sign := ⟨-1, Or.inl rfl⟩

def posSign : Sign := ⟨1, Or.inr rfl⟩

def signValue (s : Sign) : ℝ := (s.1 : ℝ)

/-- A deterministic sign decision tree. -/
inductive SignDecisionTree (I : Type*) where
  | leaf (value : Sign)
  | query (coordinate : I) (negative positive : SignDecisionTree I)

def SignDecisionTree.depth {I : Type*} : SignDecisionTree I → ℕ
  | .leaf _ => 0
  | .query _ negative positive => max negative.depth positive.depth + 1

def SignDecisionTree.evaluate {I : Type*} :
    SignDecisionTree I → (I → Sign) → Sign
  | .leaf value, _ => value
  | .query coordinate negative positive, O =>
      if O coordinate = negSign then negative.evaluate O else positive.evaluate O

def ComputableBySignDecisionTreeDepthTwo {I : Type*}
    (f : (I → Sign) → Sign) : Prop :=
  ∃ tree : SignDecisionTree I,
    tree.depth ≤ 2 ∧ ∀ O, tree.evaluate O = f O

def CoordinatewiseNondecreasing {I : Type*}
    (f : (I → Sign) → Sign) : Prop :=
  ∀ ⦃O O'⦄, (∀ i, O i ≤ O' i) → f O ≤ f O'

def SignFunctionDependsOn {I : Type*}
    (f : (I → Sign) → Sign) (i : I) : Prop :=
  ∃ O O',
    (∀ j, j ≠ i → O j = O' j) ∧ O i ≠ O' i ∧ f O ≠ f O'

/-- A finite list/weight presentation of a probability law on sign functions. -/
def FiniteMonotoneDepthTwoLaw {I : Type*} {n : ℕ}
    (p : Fin n → ℝ) (f : Fin n → (I → Sign) → Sign) : Prop :=
  (∀ j, 0 ≤ p j) ∧
    (∑ j, p j = 1) ∧
      ∀ j, p j ≠ 0 →
        CoordinatewiseNondecreasing (f j) ∧
          ComputableBySignDecisionTreeDepthTwo (f j)

/-- Independent uniform signs, stated by all finite cylinder probabilities. -/
def IndependentUniformSigns {I : Type*}
    (P : Measure (I → Sign)) : Prop :=
  P Set.univ = 1 ∧
    ∀ (s : Finset I) (a : I → Sign),
      P {O | ∀ i ∈ s, O i = a i} = ((1 : ℝ≥0∞) / 2) ^ s.card

noncomputable def signMixture {I : Type*} {n : ℕ}
    (p : Fin n → ℝ) (f : Fin n → (I → Sign) → Sign)
    (O : I → Sign) : ℝ :=
  ∑ j, p j * signValue (f j O)

noncomputable def signCorrelation {I : Type*} {n : ℕ}
    (P : Measure (I → Sign)) (p : Fin n → ℝ)
    (f : Fin n → (I → Sign) → Sign) (i : I) : ℝ :=
  ∫ O, signMixture p f O * signValue (O i) ∂P

def SignFunctionNonconstant {I : Type*}
    (f : (I → Sign) → Sign) : Prop :=
  ∃ O O', f O ≠ f O'

noncomputable def nonconstantMass {I : Type*} {n : ℕ}
    (p : Fin n → ℝ) (f : Fin n → (I → Sign) → Sign) : ℝ := by
  classical
  exact ∑ j, if SignFunctionNonconstant (f j) then p j else 0

/-- The sigma algebra generated by the first `m` coordinates in an ordered list. -/
def signFiltration {I : Type*}
    (coordinates : List I) (m : ℕ) : MeasurableSpace (I → Sign) :=
  MeasurableSpace.comap
    (fun O : I → Sign =>
      fun j : Fin (coordinates.take m).length =>
        O ((coordinates.take m).get j))
    (inferInstance : MeasurableSpace (Fin (coordinates.take m).length → Sign))

noncomputable def expectedConditionalVariance
    {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (F : MeasurableSpace Ω) (X : Ω → ℝ) : ℝ :=
  ∫ O, (X O - (MeasureTheory.condExp F P X) O) ^ 2 ∂P

def OrderedRelevantCoordinates {I : Type*} {n : ℕ}
    (P : Measure (I → Sign)) (p : Fin n → ℝ)
    (f : Fin n → (I → Sign) → Sign) (coordinates : List I) : Prop :=
  coordinates.Nodup ∧
    (∀ i, i ∈ coordinates ↔
      ∃ j, 0 < p j ∧ SignFunctionDependsOn (f j) i) ∧
      List.Pairwise
        (fun i j => signCorrelation P p f i ≥ signCorrelation P p f j)
        coordinates

def MixtureMeasurableAt {I : Type*} {n : ℕ}
    (p : Fin n → ℝ) (f : Fin n → (I → Sign) → Sign)
    (coordinates : List I) (m : ℕ) : Prop :=
  Measurable[signFiltration coordinates m] (signMixture p f)

def StoppedVarianceBound {I : Type*} {n : ℕ}
    (P : Measure (I → Sign)) (p : Fin n → ℝ)
    (f : Fin n → (I → Sign) → Sign) (coordinates : List I) : Prop :=
  ∃ N : ℕ,
    MixtureMeasurableAt p f coordinates N ∧
      (∀ m, N ≤ m →
        MixtureMeasurableAt p f coordinates m ∧
          expectedConditionalVariance P (signFiltration coordinates m)
              (signMixture p f) = 0) ∧
      (∑ m ∈ Finset.range (N + 1),
          expectedConditionalVariance P (signFiltration coordinates m)
            (signMixture p f)) ≤
        (5 / 4 : ℝ) * (nonconstantMass p f) ^ 2 ∧
      (5 / 4 : ℝ) * (nonconstantMass p f) ^ 2 ≤ (5 / 4 : ℝ)

def twoCoordinateAnd : (Fin 2 → Sign) → Sign :=
  fun O => if O 0 = posSign ∧ O 1 = posSign then posSign else negSign

def AndPointMassOptimality : Prop :=
  ∃ P : Measure (Fin 2 → Sign),
    IndependentUniformSigns P ∧
      let p : Fin 1 → ℝ := fun _ => 1
      let f : Fin 1 → (Fin 2 → Sign) → Sign := fun _ => twoCoordinateAnd
      FiniteMonotoneDepthTwoLaw p f ∧
        ∃ coordinates : List (Fin 2),
          OrderedRelevantCoordinates P p f coordinates ∧
            ∃ N : ℕ,
              MixtureMeasurableAt p f coordinates N ∧
                (∀ m, N ≤ m →
                  MixtureMeasurableAt p f coordinates m ∧
                    expectedConditionalVariance P
                        (signFiltration coordinates m) (signMixture p f) = 0) ∧
                (∑ m ∈ Finset.range (N + 1),
                    expectedConditionalVariance P (signFiltration coordinates m)
                      (signMixture p f)) = (5 / 4 : ℝ)

/--
Claim 59848: depth-two monotone decision-tree mixtures of independent uniform
signs have the stated ordered-coordinate conditional-variance bound, with the
constant attained by the two-coordinate AND point mass.
-/
def claim59848 : Prop :=
  (∀ (I : Type*) [Countable I] (P : Measure (I → Sign))
      (n : ℕ) (p : Fin n → ℝ)
      (f : Fin n → (I → Sign) → Sign),
      IndependentUniformSigns P →
        FiniteMonotoneDepthTwoLaw p f →
          ∃ coordinates : List I,
            OrderedRelevantCoordinates P p f coordinates ∧
              StoppedVarianceBound P p f coordinates) ∧
    AndPointMassOptimality

end
end MathlibPlus.Open.Analysis
