import Mathlib

namespace MathlibPlus.Open.BatchFormalization

universe u

/-- A subgroup of permutations acts regularly when each ordered pair has a unique transporter. -/
def IsRegularOn {α : Type u}
    (P : Subgroup (Equiv.Perm α)) : Prop :=
  ∀ x y : α, ∃! g : P, (g : Equiv.Perm α) x = y

/-- The subgroup is generated by one permutation. -/
def IsCyclicPermutationSubgroup {α : Type u}
    (P : Subgroup (Equiv.Perm α)) : Prop :=
  ∃ g : Equiv.Perm α, P = Subgroup.closure ({g} : Set (Equiv.Perm α))

/-- A regular cyclic permutation group of the indicated order. -/
def IsRegularCyclicAction (n : ℕ) {α : Type u}
    (P : Subgroup (Equiv.Perm α)) : Prop :=
  Nat.card P = n ∧ IsCyclicPermutationSubgroup P ∧ IsRegularOn P

/-- The restriction of a permutation subgroup to a subset, including invariance. -/
def IsRegularCyclicOn (n : ℕ) {α : Type u}
    (P : Subgroup (Equiv.Perm α)) (B : Set α) : Prop :=
  Nat.card P = n ∧ IsCyclicPermutationSubgroup P ∧
    (∀ g : P, ∀ x : B, (g : Equiv.Perm α) x ∈ B) ∧
    ∀ x y : B, ∃! g : P, (g : Equiv.Perm α) x = y

/-- A partition into the stated number and size of blocks. -/
def IsBlockSystem {α : Type u} [Finite α]
    (blocks : Set (Set α)) (r s : ℕ) : Prop :=
  Nat.card blocks = s ∧
    (∀ B : Set α, B ∈ blocks → Nat.card B = r) ∧
    (∀ x : α, ∃! B : blocks, x ∈ (B : Set α))

/-- Every element of a permutation subgroup permutes the blocks. -/
def PreservesBlocks {α : Type u}
    (P : Subgroup (Equiv.Perm α)) (blocks : Set (Set α)) : Prop :=
  ∀ g : P, ∀ B : blocks,
    (g : Equiv.Perm α) '' (B : Set α) ∈ blocks

/-- Invariance under every automorphism of the parent subgroup. -/
def IsCharacteristicSubgroup {G : Type u} [Group G]
    (P C : Subgroup G) : Prop :=
  P ≤ C ∧
    ∀ e : C ≃* C,
      Subgroup.map e.toMonoidHom (P.comap C.subtype) = P.comap C.subtype

/-- The regular cyclic subgroup conclusion of Claim 41163. -/
def claim41163 : Prop :=
  ∀ {r s : ℕ}, Nat.Prime r → Nat.Prime s → r ≠ s →
    ∀ {α : Type u} [Finite α],
      ∀ (blocks : Set (Set α)), IsBlockSystem blocks r s →
        ∀ (C D : Subgroup (Equiv.Perm α)),
          IsRegularCyclicAction (r * s) C →
          IsRegularCyclicAction (r * s) D →
          PreservesBlocks C blocks →
          PreservesBlocks D blocks →
          ∀ (P Q : Subgroup (Equiv.Perm α)),
            IsCharacteristicSubgroup P C → Nat.card P = r →
            IsCharacteristicSubgroup Q D → Nat.card Q = r →
            ∀ (B : Set α), B ∈ blocks →
              IsRegularCyclicOn r P B ∧ IsRegularCyclicOn r Q B

/-- The actual restrictions represented by permutations of a subset. -/
def RestrictionImage {α : Type u}
    (P : Subgroup (Equiv.Perm α)) (B : Set α) : Set (Equiv.Perm B) :=
  {q | ∃ g : P,
    (∀ x : B, (g : Equiv.Perm α) x ∈ B) ∧
      ∀ x : B, (q x : α) = (g : Equiv.Perm α) x}

/-- The subgroup generated by all well-defined restrictions of P to B. -/
def RestrictionSubgroup {α : Type u}
    (P : Subgroup (Equiv.Perm α)) (B : Set α) : Subgroup (Equiv.Perm B) :=
  Subgroup.closure (RestrictionImage P B)

/-- Transitivity predicates for permutation subgroups. -/
def IsTransitiveSubgroup {α : Type u}
    (G : Subgroup (Equiv.Perm α)) : Prop :=
  ∀ x y : α, ∃ g : G, (g : Equiv.Perm α) x = y

def IsTwoTransitiveSubgroup {α : Type u}
    (G : Subgroup (Equiv.Perm α)) : Prop :=
  ∀ ⦃x₁ x₂ y₁ y₂ : α⦄,
    x₁ ≠ x₂ → y₁ ≠ y₂ →
      ∃ g : G, (g : Equiv.Perm α) x₁ = y₁ ∧
        (g : Equiv.Perm α) x₂ = y₂

/-- The 2-transitivity conclusion for the locally generated group in Claim 41164. -/
def claim41164 : Prop :=
  ∀ {r s : ℕ}, Nat.Prime r → Nat.Prime s → r ≠ s →
    ∀ {α : Type u} [Finite α],
      ∀ (blocks : Set (Set α)), IsBlockSystem blocks r s →
        ∀ (C D : Subgroup (Equiv.Perm α)),
          IsRegularCyclicAction (r * s) C →
          IsRegularCyclicAction (r * s) D →
          PreservesBlocks C blocks →
          PreservesBlocks D blocks →
          ∀ (P Q : Subgroup (Equiv.Perm α)),
            IsCharacteristicSubgroup P C → Nat.card P = r →
            IsCharacteristicSubgroup Q D → Nat.card Q = r →
            ∀ (B : Set α), B ∈ blocks →
              RestrictionSubgroup P B ≠ RestrictionSubgroup Q B →
                IsTwoTransitiveSubgroup
                  (RestrictionSubgroup P B ⊔ RestrictionSubgroup Q B)

/-- A transitive action of prime degree is affine or 2-transitive, with the
unique regular prime-order subgroup in the affine branch. -/
def IsAffinePermutation (p : ℕ)
    (g : Equiv.Perm (ZMod p)) : Prop :=
  ∃ a : (ZMod p)ˣ, ∃ b : ZMod p,
    ∀ x : ZMod p, g x = (a : ZMod p) * x + b

def IsContainedInAffine (p : ℕ) {α : Type u}
    (G : Subgroup (Equiv.Perm α)) : Prop :=
  ∃ e : α ≃ ZMod p,
    ∀ g : G,
      IsAffinePermutation p ((e.symm.trans (g : Equiv.Perm α)).trans e)

def IsRegularPrimeSubgroup (p : ℕ) {α : Type u}
    (G P : Subgroup (Equiv.Perm α)) : Prop :=
  P ≤ G ∧ Nat.card P = p ∧ IsRegularOn P

def claim41165 : Prop :=
  ∀ {p : ℕ} {α : Type u} [Fintype α],
    Nat.Prime p → Fintype.card α = p →
      ∀ G : Subgroup (Equiv.Perm α), IsTransitiveSubgroup G →
        (IsContainedInAffine p G ∨ IsTwoTransitiveSubgroup G) ∧
        (IsContainedInAffine p G →
          ∃! P : Subgroup (Equiv.Perm α), IsRegularPrimeSubgroup p G P) ∧
        (∀ P Q : Subgroup (Equiv.Perm α),
          IsRegularPrimeSubgroup p G P → IsRegularPrimeSubgroup p G Q →
          P ≠ Q → ¬ IsContainedInAffine p G)

/-- The degree-five regular cyclic subgroups in the natural permutation action. -/
def claim41169 : Prop :=
  ∀ (P : Subgroup (Equiv.Perm (Fin 5))),
    IsRegularCyclicAction 5 P →
      (∀ (Q : Subgroup (Equiv.Perm (Fin 5))),
        IsRegularCyclicAction 5 Q → Q ≠ P →
          P ⊔ Q = alternatingGroup (Fin 5)) ∧
      Nat.card {Q : Subgroup (Equiv.Perm (Fin 5)) //
        IsRegularCyclicAction 5 Q ∧ Q ≠ P} = 5

end MathlibPlus.Open.BatchFormalization
