import Mathlib

namespace MathlibPlus.LinearAlgebra.CyclicSameLineProfile

open scoped BigOperators

noncomputable section

abbrev TernaryBase (d : ℕ) := Fin d → ZMod 3
abbrev Plane := Fin 2 → ZMod 3

/-- The order-three line generated by a nonzero ternary vector. -/
def ternaryLine {d : ℕ} (u : TernaryBase d) : AddSubgroup (TernaryBase d) :=
  AddSubgroup.closure {u}

/-- Sum of a profile over the coset of `x` modulo `U`. -/
noncomputable def cosetSum {d : ℕ} (U : AddSubgroup (TernaryBase d))
    (x : TernaryBase d) (w : TernaryBase d → ZMod 3) : ZMod 3 := by
  classical
  exact (Finset.univ.filter (fun y : TernaryBase d => y - x ∈ U)).sum (fun y => w y)

/-- Profiles whose sum is zero on every `U`-coset. -/
def augmentationModule {d : ℕ} (U : AddSubgroup (TernaryBase d)) :
    Submodule (ZMod 3) (TernaryBase d → ZMod 3) where
  carrier := {w | ∀ x, cosetSum U x w = 0}
  zero_mem' := by
    classical
    intro x
    simp [cosetSum]
  add_mem' := by
    classical
    intro w v hw hv x
    let s := Finset.univ.filter (fun y : TernaryBase d => y - x ∈ U)
    have hwx : s.sum (fun y => w y) = 0 := by
      simpa [s, cosetSum] using hw x
    have hvx : s.sum (fun y => v y) = 0 := by
      simpa [s, cosetSum] using hv x
    change s.sum (fun y => w y + v y) = 0
    rw [Finset.sum_add_distrib, hwx, hvx, add_zero]
  smul_mem' := by
    classical
    intro c w hw x
    let s := Finset.univ.filter (fun y : TernaryBase d => y - x ∈ U)
    have hwx : s.sum (fun y => w y) = 0 := by
      simpa [s, cosetSum] using hw x
    change s.sum (fun y => c * w y) = 0
    rw [← Finset.mul_sum, hwx, mul_zero]

/-- The profile `k_w(x)=a w(x)+b w(x-h)`, with the two basis vectors
represented by the first two elements of a `Fin 2`-indexed basis. -/
def profile {d : ℕ} (basis : Module.Basis (Fin 2) (ZMod 3) Plane)
    (h : TernaryBase d) (w : TernaryBase d → ZMod 3)
    (x : TernaryBase d) : Plane :=
  w x • basis 0 + w (x - h) • basis 1

/-- The linear map `w ↦ k_w`. -/
def profileMap {d : ℕ} (basis : Module.Basis (Fin 2) (ZMod 3) Plane)
    (h : TernaryBase d) :
    (TernaryBase d → ZMod 3) →ₗ[ZMod 3] (TernaryBase d → Plane) where
  toFun w := profile basis h w
  map_add' := by
    intro w v
    funext x
    simp only [profile, Pi.add_apply, add_smul]
    ac_rfl
  map_smul' := by
    intro c w
    funext x
    simp [profile, smul_add, mul_smul]

/-- The cyclic same-line profile module `M_h`. -/
def profileModule {d : ℕ} (u : TernaryBase d) (hu : u ≠ 0)
    (basis : Module.Basis (Fin 2) (ZMod 3) Plane)
    (h : TernaryBase d) (hh : h ∈ ternaryLine u) (hh0 : h ≠ 0) :
    Submodule (ZMod 3) (TernaryBase d → Plane) :=
  (augmentationModule (ternaryLine u)).map (profileMap basis h)

end

end MathlibPlus.LinearAlgebra.CyclicSameLineProfile
