import MathlibPlus.Open.ResearchFormalization.R1182.Claim31941

namespace MathlibPlus.Open.ResearchFormalization.R1285

open MathlibPlus.Open.ResearchFormalization.R1182.Claim31941

abbrev HallQ12Carrier (n : ℕ) := ZMod n × Q12

/-- The displayed `Cₙ ⋊χ Q₁₂` multiplication, with the sign character on
 the `C₄` coordinate of the exact `F₃⁺ ⋊ C₄` model. -/
def hallQ12Multiply (n : ℕ) (x y : HallQ12Carrier n) : HallQ12Carrier n :=
  (x.1 + q12Sign n x.2 * y.1, q12Mul x.2 y.2)

/-- The inverse in the displayed Hall--`Q₁₂` coordinates. -/
def hallQ12Inverse (n : ℕ) (x : HallQ12Carrier n) : HallQ12Carrier n :=
  (-q12Sign n (x.2⁻¹) * x.1, q12Inv x.2)

def hallQ12Identity (n : ℕ) : HallQ12Carrier n := (0, q12One)

/-- Inverse closure and the loopless condition for ordinary connection sets in
 the displayed semidirect coordinates. -/
def hallQ12InverseClosed (n : ℕ) (S : Set (HallQ12Carrier n)) : Prop :=
  ∀ x, x ∈ S ↔ hallQ12Inverse n x ∈ S

def hallQ12IdentityFree (n : ℕ) (S : Set (HallQ12Carrier n)) : Prop :=
  hallQ12Identity n ∉ S

/-- The two exact orientations of the exceptional cubic switch. -/
def exceptionalCubicSwitch (σ : Equiv.Perm Q12) : Prop :=
  (∀ h : Q12, σ h = q12Sigma h) ∨
    (∀ h : Q12, σ h = q12SigmaInv h)

/-- The normalized affine lift in the exact coordinates of `Gₙ`. -/
def normalizedHallQ12AffineLift (n : ℕ)
    (lam : Q12 → (ZMod n)ˣ) (tau : Q12 → ZMod n)
    (σ : Equiv.Perm Q12)
    (f : Equiv.Perm (HallQ12Carrier n)) : Prop :=
  lam q12One = 1 ∧
    tau q12One = 0 ∧
    exceptionalCubicSwitch σ ∧
    (∀ x : ZMod n, ∀ h : Q12,
      f (x, h) = ((lam h : ZMod n) * x + tau h, σ h))

/-- A normalized relative derivative, written directly from the displayed
semidirect product law. -/
def hallQ12RelativeDerivative (n : ℕ)
    (f : Equiv.Perm (HallQ12Carrier n))
    (a x : HallQ12Carrier n) : HallQ12Carrier n :=
  hallQ12Multiply n (hallQ12Inverse n (f a))
    (f (hallQ12Multiply n a (f.symm x)))

/-- The relative-derivative generators, represented as permutations of the
 displayed group carrier. -/
def hallQ12DerivativeGenerators (n : ℕ)
    (f : Equiv.Perm (HallQ12Carrier n)) : Set (Equiv.Perm (HallQ12Carrier n)) :=
  {d | ∃ a : HallQ12Carrier n, ∀ x,
    d x = hallQ12RelativeDerivative n f a x}

/-- Invariance under the subgroup generated by the relative derivatives. -/
def hallQ12DerivativeInvariant (n : ℕ)
    (f : Equiv.Perm (HallQ12Carrier n))
    (S : Set (HallQ12Carrier n)) : Prop :=
  ∀ d ∈ Subgroup.closure (hallQ12DerivativeGenerators n f),
    d '' S = S

/-- The coboundary automorphism from the admitted Q₁₂ cubic repair. -/
def hallQ12Coboundary (n : ℕ) (c : ZMod n) : HallQ12Carrier n → HallQ12Carrier n :=
  fun x => (x.1 + c * (1 - q12Sign n x.2), x.2)

/-- Group-automorphism equations for the displayed semidirect coordinates. -/
def hallQ12Automorphism (n : ℕ)
    (g : HallQ12Carrier n → HallQ12Carrier n) : Prop :=
  Function.Bijective g ∧
    g (hallQ12Identity n) = hallQ12Identity n ∧
    ∀ x y : HallQ12Carrier n,
      g (hallQ12Multiply n x y) =
        hallQ12Multiply n (g x) (g y)

/-- Claim 39994: every normalized affine lift of either exceptional cubic
switch is harmless on an inverse-closed identity-free connection set. -/
def claim39994_q12CubicAffineRepair : Prop :=
  ∀ n : ℕ, Squarefree n → Nat.Coprime n 6 →
    ∀ (lam : Q12 → (ZMod n)ˣ) (tau : Q12 → ZMod n)
      (σ : Equiv.Perm Q12)
      (f : Equiv.Perm (HallQ12Carrier n)),
      normalizedHallQ12AffineLift n lam tau σ f →
      ∀ S : Set (HallQ12Carrier n),
        hallQ12IdentityFree n S →
        hallQ12InverseClosed n S →
        hallQ12DerivativeInvariant n f S →
        ∃ c : ZMod n,
          hallQ12Automorphism n (hallQ12Coboundary n c) ∧
            Set.image f S = Set.image (hallQ12Coboundary n c) S

end MathlibPlus.Open.ResearchFormalization.R1285
