import Mathlib

namespace MathlibPlus.Algebra.AffinePower

abbrev V (p : ℕ) := ZMod p × ZMod p

/-- The two affine transformations from the rank-two witness in claim 41959. -/
def q₁ (p : ℕ) : V p ≃ V p :=
  { toFun := fun z => (z.1 + 1, z.2 + z.1)
    invFun := fun z => (z.1 - 1, z.2 - (z.1 - 1))
    left_inv := by
      intro z
      ext <;> simp
    right_inv := by
      intro z
      ext <;> simp }

def q₂ (p : ℕ) : V p ≃ V p :=
  { toFun := fun z => (z.1, z.2 + 1)
    invFun := fun z => (z.1, z.2 - 1)
    left_inv := by
      intro z
      ext <;> simp
    right_inv := by
      intro z
      ext <;> simp }

/-- The subgroup generated by the two displayed affine transformations. -/
def Q (p : ℕ) : Subgroup (Equiv.Perm (V p)) :=
  Subgroup.closure ({q₁ p, q₂ p} : Set (Equiv.Perm (V p)))

theorem q₁_pow_origin (p n : ℕ) :
    ((q₁ p) ^ n) (0, 0) =
      ((n : ZMod p), (Nat.choose n 2 : ZMod p)) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pow_succ']
    rw [Equiv.Perm.mul_apply, ih]
    change ((n : ZMod p) + 1, (Nat.choose n 2 : ZMod p) + (n : ZMod p)) = _
    congr 1
    · norm_num [Nat.cast_add, Nat.cast_one]
    · rw [Nat.choose_succ_succ, Nat.choose_one_right]
      push_cast
      ring

theorem q₁_pow_apply_zero (p n : ℕ) (b : ZMod p) :
    ((q₁ p) ^ n) (0, b) =
      ((n : ZMod p), b + (Nat.choose n 2 : ZMod p)) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pow_succ']
    rw [Equiv.Perm.mul_apply, ih]
    change ((n : ZMod p) + 1, (b + (Nat.choose n 2 : ZMod p)) + (n : ZMod p)) = _
    congr 1
    · norm_num [Nat.cast_add, Nat.cast_one]
    · rw [Nat.choose_succ_succ, Nat.choose_one_right]
      push_cast
      ring

theorem q₂_pow_origin (p n : ℕ) :
    ((q₂ p) ^ n) (0, 0) = ((0 : ZMod p), (n : ZMod p)) := by
  induction n with
  | zero => simp
  | succ n ih =>
    rw [pow_succ']
    rw [Equiv.Perm.mul_apply, ih]
    change ((0 : ZMod p), (n : ZMod p) + 1) = _
    congr 1
    norm_num [Nat.cast_add, Nat.cast_one]

theorem q_power_formula (p : ℕ) (a b : Fin p) :
    (((q₁ p) ^ a.val) * ((q₂ p) ^ b.val)) (0, 0) =
      ((a.val : ZMod p),
        (Nat.choose a.val 2 : ZMod p) + (b.val : ZMod p)) := by
  rw [Equiv.Perm.mul_apply, q₂_pow_origin]
  simpa [add_comm] using q₁_pow_apply_zero p a.val (b.val : ZMod p)

end MathlibPlus.Algebra.AffinePower

namespace MathlibPlus.Open.Algebra.AffinePower

open MathlibPlus.Algebra.AffinePower

/-- Claim 41960.  The finite-field parameters are represented by their unique
`Fin p` representatives; `p` is explicitly required to be an odd prime as in
claim 41959.  Regularity is expressed by bijectivity of evaluation at the
origin, and elementary abelianness is expanded into commutativity and exponent
`p`. -/
def explicitPowerFormulaAndRegularity : Prop :=
  ∀ (p : ℕ), Nat.Prime p → 2 < p →
    (∀ (a b : Fin p),
      (((q₁ p) ^ a.val) * ((q₂ p) ^ b.val)) (0, 0) =
        ((a.val : ZMod p),
          (Nat.choose a.val 2 : ZMod p) + (b.val : ZMod p))) ∧
    Function.Bijective (fun q : Q p => q.1 (0, 0)) ∧
    Nat.card (Q p) = p ^ 2 ∧
    (∀ q : Q p, q ^ p = 1) ∧
    (∀ q₁ q₂ : Q p, q₁ * q₂ = q₂ * q₁)

end MathlibPlus.Open.Algebra.AffinePower
