import MathlibPlus.Open.Algebra.ConductorRees

namespace MathlibPlus.Open.Algebra.ConductorRees

noncomputable section

/-- The total exponent of the `e`-variables in a finite multi-index. -/
def eMultiplicity (μ : eIndex →₀ ℕ) : ℕ :=
  μ.sum (fun _ n => n)

/-- Indices for the monomials in the asserted Rees-algebra basis. -/
structure ReesMonomialIndex where
  sExponent : ℕ
  zExponent : ℕ
  eExponents : eIndex →₀ ℕ
  reesDegree : ℕ
  admissible :
    (eExponents = 0 ∧ zExponent = 0 ∧ reesDegree = 0) ∨
      (eExponents ≠ 0 ∧
        0 ≤ reesDegree ∧ reesDegree ≤ eMultiplicity eExponents)

/-- The concrete monomial `s^b z^a e^μ T^m` in the polynomial Rees carrier. -/
def reesMonomial (i : ReesMonomialIndex) : ReesPolynomial :=
  Polynomial.C
      (MvPolynomial.X sVar ^ i.sExponent *
        MvPolynomial.X zVar ^ i.zExponent *
        i.eExponents.prod
          (fun k n => MvPolynomial.X (eVar k.1) ^ n)) *
    Polynomial.X ^ i.reesDegree

/-- The Q-linear carrier generated by the reviewed Rees-algebra predicate. -/
def reesAlgebraSubmodule : Submodule ℚ ReesPolynomial :=
  Submodule.span ℚ {P : ReesPolynomial | reesCarrier P}

/-- Claim 23533: the reviewed Rees algebra has the asserted exact monomial
basis, with the stated restrictions on the finite `e`-multi-index and Rees
degree. -/
def claim_23533 : Prop :=
  (∀ P : ReesPolynomial,
    reesCarrier P ↔ P ∈ reesAlgebraSubmodule) ∧
    ∃ b : Module.Basis ReesMonomialIndex ℚ (reesAlgebraSubmodule : Type),
      ∀ i, (b i : ReesPolynomial) = reesMonomial i

end

end MathlibPlus.Open.Algebra.ConductorRees
