import Mathlib

namespace MathlibPlus.Open.Algebra

/-- Formal-series version of the modulo-`w^n` calculation in claim 50237.
The source's implicit hypotheses are made explicit: `L` starts in degree `r`
and `P = Q(1+L)`.  Congruence modulo `w^n` is represented by membership of
the difference in the principal ideal generated by `X^n`. -/
def truncatedFormalSeriesCongruenceClaim50237 : Prop :=
  ∀ (B : Type*) [Field B] (n r : ℕ),
    2 * r ≥ n →
    (2 : B) ≠ 0 →
    ∀ (L P Q : PowerSeries B),
      (∃ A : PowerSeries B, L = PowerSeries.X ^ r * A) →
      P = Q * (1 + L) →
      let I : Ideal (PowerSeries B) :=
        Ideal.span ({PowerSeries.X ^ n} : Set (PowerSeries B))
      (∀ j : ℕ, 2 ≤ j → L ^ j - 0 ∈ I) ∧
        (P - Q - Q * L ∈ I) ∧
        (P * L - Q * L ∈ I) ∧
        (P * L - ((2 : B)⁻¹ • ((P + Q) * L)) ∈ I)

end MathlibPlus.Open.Algebra
