import Mathlib

namespace MathlibPlus.Open.Algebra

open scoped BigOperators TensorProduct

universe u v w

/-- The additive group algebra `𝔽_p[B]`, with the prime and oddness hypotheses
kept as explicit parameters of the admitted setup. -/
abbrev modularGroupAlgebra
    (p : ℕ) (hp : Nat.Prime p) (hop : Odd p) [Fact (Nat.Prime p)]
    (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
    [FiniteDimensional (ZMod p) B] : Type u :=
  AddMonoidAlgebra (ZMod p) B

noncomputable def augmentationHom (K : Type v) (B : Type u)
    [CommSemiring K] [AddMonoid B] :
    AddMonoidAlgebra K B →ₐ[K] K :=
  AddMonoidAlgebra.lift K K B
    { toFun := fun _ : Multiplicative B => 1
      map_one' := by simp
      map_mul' := by intro _ _; simp }

/-- The augmentation ideal `ker ε` in the modular group algebra. -/
noncomputable def modularAugmentationIdeal
    (p : ℕ) (hp : Nat.Prime p) (hop : Odd p) [Fact (Nat.Prime p)]
    (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
    [FiniteDimensional (ZMod p) B] :
    Ideal (modularGroupAlgebra p hp hop B) :=
  RingHom.ker (augmentationHom (ZMod p) B).toRingHom

/-- A one-dimensional subspace of a finite-dimensional `𝔽_p`-space. -/
noncomputable def modularProjectiveLine
    (p : ℕ) (hp : Nat.Prime p) (hop : Odd p) [Fact (Nat.Prime p)]
    (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
    [FiniteDimensional (ZMod p) B] :=
  {L : Submodule (ZMod p) B // Module.finrank (ZMod p) L = 1}

/-- The chosen nonzero representative `d_L ∈ L` for every one-dimensional subspace. -/
noncomputable def modularLineRepresentative
    (p : ℕ) (hp : Nat.Prime p) (hop : Odd p) [Fact (Nat.Prime p)]
    (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
    [FiniteDimensional (ZMod p) B] : Type u :=
  {d : modularProjectiveLine p hp hop B → B //
    ∀ L, d L ∈ L.1 ∧ d L ≠ 0}

/-- The group-algebra basis element `τ_d`. -/
noncomputable def tau (K : Type v) (B : Type u)
    [Semiring K] [AddMonoid B] (d : B) : AddMonoidAlgebra K B :=
  AddMonoidAlgebra.single d 1

/-- The principal relation ideal generated by `τ_d - 1`. -/
noncomputable def relationIdeal (K : Type v) (B : Type u)
    [CommRing K] [AddCommGroup B] (d : B) : Ideal (AddMonoidAlgebra K B) :=
  Ideal.span ({tau K B d - (1 : AddMonoidAlgebra K B)} :
    Set (AddMonoidAlgebra K B))

noncomputable def modularRelationIdeal
    (p : ℕ) (hp : Nat.Prime p) (hop : Odd p) [Fact (Nat.Prime p)]
    (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
    [FiniteDimensional (ZMod p) B]
    (d : modularLineRepresentative p hp hop B)
    (L : modularProjectiveLine p hp hop B) :
    Ideal (modularGroupAlgebra p hp hop B) :=
  relationIdeal (ZMod p) B (d.1 L)

/-- The submodule generated by pure tensors with one factor in each supplied
submodule. -/
noncomputable def tensorProductSubmodule
    (K : Type v) (V : Type w) (R : Type u) [CommSemiring K]
    [AddCommMonoid V] [Module K V] [Semiring R] [Module K R]
    (U : Submodule K V) (J : Submodule K R) :
    Submodule K (V ⊗[K] R) :=
  Submodule.span K
    {z | ∃ u : U, ∃ j : J, z = (u : V) ⊗ₜ[K] (j : R)}

/-- The line-indexed coefficient/relation module `C`. -/
noncomputable def modularLineRelationModule
    (p : ℕ) (hp : Nat.Prime p) (hop : Odd p) [Fact (Nat.Prime p)]
    (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
    [FiniteDimensional (ZMod p) B]
    (V : Type w) [AddCommGroup V] [Module (ZMod p) V]
    [FiniteDimensional (ZMod p) V]
    (d : modularLineRepresentative p hp hop B)
    (U : modularProjectiveLine p hp hop B → Submodule (ZMod p) V) :
    Submodule (ZMod p)
      (V ⊗[ZMod p] modularGroupAlgebra p hp hop B) :=
  ⨆ L : modularProjectiveLine p hp hop B,
    tensorProductSubmodule (ZMod p) V
      (modularGroupAlgebra p hp hop B) (U L)
      (Submodule.restrictScalars (ZMod p)
        (modularRelationIdeal p hp hop B d L))

/-- The first-moment map on the additive group algebra. -/
noncomputable def momentMap (K : Type v) (B : Type u)
    [CommSemiring K] [AddCommMonoid B] [Module K B] :
    AddMonoidAlgebra K B →ₗ[K] B :=
  (Finsupp.lsum K
      (fun x : B => LinearMap.toSpanSingleton K B x)).comp
    (AddMonoidAlgebra.coeffLinearEquiv K).toLinearMap

/-- The tensor-level first-moment map for the modular relation problem. -/
noncomputable def modularFirstMomentMap
    (p : ℕ) (hp : Nat.Prime p) (hop : Odd p) [Fact (Nat.Prime p)]
    (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
    [FiniteDimensional (ZMod p) B]
    (V : Type w) [AddCommGroup V] [Module (ZMod p) V]
    [FiniteDimensional (ZMod p) V] :
    V ⊗[ZMod p] modularGroupAlgebra p hp hop B →ₗ[ZMod p]
      V ⊗[ZMod p] B :=
  TensorProduct.map (LinearMap.id : V →ₗ[ZMod p] V)
    (momentMap (ZMod p) B)

noncomputable def rightMultiplication
    (K : Type v) (R : Type u) [CommSemiring K] [Semiring R]
    [Algebra K R] (r : R) : R →ₗ[K] R :=
  { toFun := fun s => s * r
    map_add' := by intro a b; simp [add_mul]
    map_smul' := by
      intro c s
      simp only [Algebra.smul_def]
      simp [mul_assoc] }

/-- Multiplication of a relation submodule by an ideal in the group-algebra
factor. -/
noncomputable def idealTimesSubmodule
    (K : Type v) (V : Type w) (R : Type u) [CommSemiring K]
    [AddCommMonoid V] [Module K V] [Semiring R] [Algebra K R]
    (I : Ideal R) (C : Submodule K (V ⊗[K] R)) :
    Submodule K (V ⊗[K] R) :=
  Submodule.span K
    {z | ∃ i : I, ∃ c : C,
      z = TensorProduct.map (LinearMap.id : V →ₗ[K] V)
        (rightMultiplication K R (i : R)) (c : V ⊗[K] R)}

noncomputable def restrictedKernel
    (K : Type v) (M : Type u) (N : Type w) [Semiring K]
    [AddCommMonoid M] [Module K M] [AddCommMonoid N] [Module K N]
    (μ : M →ₗ[K] N) (C : Submodule K M) : Submodule K M :=
  LinearMap.ker μ ⊓ C

/-- Claim 6379: the characteristic-`p` jet reduction identity. -/
def characteristicPJetReduction : Prop :=
  ∀ (p : ℕ) (hp : Nat.Prime p) (hop : Odd p),
    letI : Fact (Nat.Prime p) := ⟨hp⟩
    ∀ (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
      [FiniteDimensional (ZMod p) B]
      (V : Type w) [AddCommGroup V] [Module (ZMod p) V]
      [FiniteDimensional (ZMod p) V],
      ∀ (d : modularLineRepresentative p hp hop B)
        (U : modularProjectiveLine p hp hop B → Submodule (ZMod p) V),
        let R := modularGroupAlgebra p hp hop B
        let I := modularAugmentationIdeal p hp hop B
        let C := modularLineRelationModule p hp hop B V d U
        let μ := modularFirstMomentMap p hp hop B V
        restrictedKernel (ZMod p) (V ⊗[ZMod p] R)
            (V ⊗[ZMod p] B) μ C =
          idealTimesSubmodule (ZMod p) V R I C ⊔
            (C ⊓ tensorProductSubmodule (ZMod p) V R ⊤
              (Submodule.restrictScalars (ZMod p) (I ^ p)))

/-- Claim 6380: every first-moment defect modulo ideal multiplication has a
representative in augmentation degree at least `p`. -/
def degreePRepresentativeTheorem : Prop :=
  ∀ (p : ℕ) (hp : Nat.Prime p) (hop : Odd p),
    letI : Fact (Nat.Prime p) := ⟨hp⟩
    ∀ (B : Type u) [AddCommGroup B] [Module (ZMod p) B]
      [FiniteDimensional (ZMod p) B]
      (V : Type w) [AddCommGroup V] [Module (ZMod p) V]
      [FiniteDimensional (ZMod p) V],
      ∀ (d : modularLineRepresentative p hp hop B)
        (U : modularProjectiveLine p hp hop B → Submodule (ZMod p) V),
        let R := modularGroupAlgebra p hp hop B
        let I := modularAugmentationIdeal p hp hop B
        let C := modularLineRelationModule p hp hop B V d U
        let μ := modularFirstMomentMap p hp hop B V
        ∀ z, z ∈ restrictedKernel (ZMod p) (V ⊗[ZMod p] R)
            (V ⊗[ZMod p] B) μ C →
          ∃ y,
            y ∈ C ⊓ tensorProductSubmodule (ZMod p) V R ⊤
              (Submodule.restrictScalars (ZMod p) (I ^ p)) ∧
            z - y ∈ idealTimesSubmodule (ZMod p) V R I C

end MathlibPlus.Open.Algebra
