import Mathlib

namespace MathlibPlus.Open.Algebra.FormalizationBatch

/-- The subgroup generated by all prescribed maps other than j that fix j. -/
def prescribedTransportSubgroup {V : Type*}
    (π : V → Equiv.Perm V) (j : V) : Subgroup (Equiv.Perm V) :=
  Subgroup.closure {σ | ∃ i : V, i ≠ j ∧ π i j = j ∧ σ = π i}

/-- The eight image tables in Claim 17066. -/
def explicitTransportTables : Fin 8 → Fin 8 → Fin 8 :=
  ![ ![0, 3, 2, 1, 5, 4, 7, 6],
     ![2, 1, 0, 3, 6, 5, 4, 7],
     ![0, 3, 2, 1, 4, 5, 7, 6],
     ![2, 1, 0, 3, 6, 7, 4, 5],
     ![0, 3, 2, 1, 4, 7, 6, 5],
     ![2, 1, 0, 3, 4, 5, 6, 7],
     ![2, 1, 0, 3, 7, 5, 6, 4],
     ![0, 3, 2, 1, 6, 5, 4, 7] ]

/-- Claim 17066: the table family is realized by involutive permutations. -/
def explicitOrderEightInvolutionFamily : Prop :=
  ∃ π : Fin 8 → Equiv.Perm (Fin 8),
    (∀ i, Function.Involutive (π i)) ∧
      ∀ i x, π i x = explicitTransportTables i x

/-- Claim 17069: no table-prescribed map lies in its transport subgroup. -/
def explicitWitnessAvoidsTransportSubgroups : Prop :=
  ∃ π : Fin 8 → Equiv.Perm (Fin 8),
    (∀ i, Function.Involutive (π i)) ∧
      (∀ i x, π i x = explicitTransportTables i x) ∧
        ∀ j, π j ∉ prescribedTransportSubgroup π j

end MathlibPlus.Open.Algebra.FormalizationBatch
