import Mathlib

namespace MathlibPlus.Open.Algebra

noncomputable section

abbrev Scalar := ℂ

abbrev SymPower (σ : Type) (r : ℕ) : Type :=
  ↥(MvPolynomial.homogeneousSubmodule σ Scalar r)

abbrev Four := Fin 4
abbrev Five := Fin 5
abbrev Two := Fin 2

/-- The split quadratic in symplectic coordinates on the tensor four-space. -/
def splitQuadratic : MvPolynomial Four Scalar :=
  MvPolynomial.X 0 * MvPolynomial.X 3 - MvPolynomial.X 1 * MvPolynomial.X 2

/-- The distinguished coordinate in `1 ⊕ V`. -/
def distinguishedCoordinate : MvPolynomial Five Scalar :=
  MvPolynomial.X 0

/-- Images of the generators after setting the distinguished coordinate to zero. -/
def restrictionVariables : Five → MvPolynomial Four Scalar :=
  Fin.cases 0 (fun i : Fin 4 => MvPolynomial.X i)

/-- Images of the generators under inclusion of the four-space. -/
def inclusionVariables : Four → MvPolynomial Five Scalar :=
  fun i : Fin 4 => MvPolynomial.X i.succ

/-- Evaluation at the distinguished coordinate equal to zero. -/
def restrictionToV : MvPolynomial Five Scalar →ₐ[Scalar] MvPolynomial Four Scalar :=
  MvPolynomial.aeval restrictionVariables

/-- Inclusion of the four-space as the non-distinguished coordinates. -/
def inclusionOfV : MvPolynomial Four Scalar →ₐ[Scalar] MvPolynomial Five Scalar :=
  MvPolynomial.aeval inclusionVariables

/-- The submodule generated by multiplication by `t` in degree `r`. -/
def distinguishedSubmodule (r : ℕ) :
    Submodule Scalar (MvPolynomial Five Scalar) :=
  Submodule.span Scalar
    {x | ∃ y : MvPolynomial Five Scalar,
      y ∈ MvPolynomial.homogeneousSubmodule Five Scalar (r - 1) ∧
      r ≠ 0 ∧ x = distinguishedCoordinate * y}

/-- The submodule generated by multiplication by the split quadratic in degree `r`. -/
def quadraticSubmodule (r : ℕ) :
    Submodule Scalar (MvPolynomial Four Scalar) :=
  Submodule.span Scalar
    {x | ∃ y : MvPolynomial Four Scalar,
      y ∈ MvPolynomial.homogeneousSubmodule Four Scalar (r - 2) ∧
      2 ≤ r ∧ x = splitQuadratic * y}

/-- Contraction by the inverse split quadratic, in the chosen coordinates. -/
def quadraticContraction :
    MvPolynomial Four Scalar →ₗ[Scalar] MvPolynomial Four Scalar :=
  (MvPolynomial.pderiv 0).toLinearMap.comp (MvPolynomial.pderiv 3).toLinearMap -
    (MvPolynomial.pderiv 1).toLinearMap.comp (MvPolynomial.pderiv 2).toLinearMap

/-- The degree-`r` harmonic subspace. -/
def harmonicSubmodule (r : ℕ) :
    Submodule Scalar (MvPolynomial Four Scalar) :=
  MvPolynomial.homogeneousSubmodule Four Scalar r ⊓
    LinearMap.ker quadraticContraction

abbrev Harmonic (r : ℕ) : Type := ↥(harmonicSubmodule r)

abbrev CartanComponent (r : ℕ) : Type :=
  TensorProduct Scalar (SymPower Two r) (SymPower Two r)

/--
A displayed map is a split quotient on the displayed homogeneous carriers when its
kernel is the displayed multiplication submodule and it has a displayed section.
-/
def IsAmbientSplitQuotient {A B : Type} [AddCommGroup A] [AddCommGroup B]
    [Module Scalar A] [Module Scalar B]
    (P S : Submodule Scalar A) (Q : Submodule Scalar B)
    (f : A →ₗ[Scalar] B) (g : B →ₗ[Scalar] A) : Prop :=
  (∀ x, x ∈ P → f x ∈ Q) ∧
  (∀ y, y ∈ Q → ∃ x, x ∈ P ∧ f x = y) ∧
  (∀ x, x ∈ P → (f x = 0 ↔ x ∈ S)) ∧
  (∀ y, y ∈ Q → g y ∈ P ∧ f (g y) = y)

/--
Two-step split quotient from the symmetric powers of `1 ⊕ V`:
restriction by the distinguished coordinate gives `Sym^r(V)`, and quotienting by
multiplication by the split quadratic gives the harmonic/Cartan component.
-/
def twoStepSplitQuotient : Prop :=
  ∀ r : ℕ,
    IsAmbientSplitQuotient
      (MvPolynomial.homogeneousSubmodule Five Scalar r)
      (distinguishedSubmodule r)
      (MvPolynomial.homogeneousSubmodule Four Scalar r)
      (restrictionToV : MvPolynomial Five Scalar →ₗ[Scalar] MvPolynomial Four Scalar)
      (inclusionOfV : MvPolynomial Four Scalar →ₗ[Scalar] MvPolynomial Five Scalar) ∧
    (∃ f g : MvPolynomial Four Scalar →ₗ[Scalar] MvPolynomial Four Scalar,
      IsAmbientSplitQuotient
        (MvPolynomial.homogeneousSubmodule Four Scalar r)
        (quadraticSubmodule r)
        (harmonicSubmodule r) f g) ∧
    Nonempty (Harmonic r ≃ₗ[Scalar] CartanComponent r)

end
end MathlibPlus.Open.Algebra
