import Mathlib

namespace MathlibPlus.Open.ResearchFormalizationBatch

open scoped BigOperators

noncomputable section

abbrev ResearchG := ((ZMod 2 × ZMod 2 × ZMod 2) × ZMod 9)

/-- The inverse atom generated by a nonzero element of the admitted group. -/
def inverseAtom (g : ResearchG) : Finset ResearchG := {g, -g}

/-- The finite collection of distinct inverse atoms on the nonidentity elements. -/
def inverseAtoms : Finset (Finset ResearchG) :=
  (Finset.univ.filter (fun g : ResearchG => g ≠ 0)).image inverseAtom

abbrev ResearchAtom := {A : Finset ResearchG // A ∈ inverseAtoms}

/-- The action of an additive automorphism on inverse atoms. -/
def atomMap (e : ResearchG ≃+ ResearchG) (A : ResearchAtom) : ResearchAtom :=
  ⟨A.1.image e, by
    rcases Finset.mem_image.mp A.2 with ⟨g, hg, hA⟩
    apply Finset.mem_image.mpr
    refine ⟨e g, ?_, ?_⟩
    · exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, by
        intro h
        apply (Finset.mem_filter.mp hg).2
        apply e.injective
        simpa using h⟩
    · rw [← hA]
      simp [inverseAtom]
  ⟩

/-- The induced permutation of inverse atoms. -/
def atomMapEquiv (e : ResearchG ≃+ ResearchG) : ResearchAtom ≃ ResearchAtom where
  toFun := atomMap e
  invFun := atomMap e.symm
  left_inv := by
    intro A
    apply Subtype.ext
    simp [atomMap, Finset.image_image]
  right_inv := by
    intro A
    apply Subtype.ext
    simp [atomMap, Finset.image_image]

/-- The inverse automorphism of the additive group. -/
def inversionEquiv : ResearchG ≃+ ResearchG where
  toFun := Neg.neg
  invFun := Neg.neg
  left_inv := by intro x; simp
  right_inv := by intro x; simp
  map_add' := by intro x y; simp [add_comm]

/-- The faithful image of the automorphism action on inverse atoms. -/
def inverseAtomActionImage : Finset (ResearchAtom ≃ ResearchAtom) :=
  (Finset.univ : Finset (ResearchG ≃+ ResearchG)).image atomMapEquiv

/-- Inverse-closed connection sets of valency seventeen. -/
def inverseClosed (S : Finset ResearchG) : Prop :=
  ∀ ⦃g : ResearchG⦄, g ∈ S → -g ∈ S

def connectionSets : Finset (Finset ResearchG) := by
  classical
  exact Finset.univ.filter (fun S : Finset ResearchG =>
    S.card = 17 ∧ 0 ∉ S ∧ inverseClosed S)

abbrev ResearchConnectionSet := {S : Finset ResearchG // S ∈ connectionSets}

/-- The induced permutation of valency-seventeen connection sets. -/
def connectionMap (e : ResearchG ≃+ ResearchG)
    (S : ResearchConnectionSet) : ResearchConnectionSet := by
  classical
  have hS : S.1.card = 17 ∧ 0 ∉ S.1 ∧ inverseClosed S.1 := by
    simpa [connectionSets] using S.2
  refine ⟨S.1.image e, ?_⟩
  change S.1.image e ∈ Finset.univ.filter (fun S : Finset ResearchG =>
    S.card = 17 ∧ 0 ∉ S ∧ inverseClosed S)
  apply Finset.mem_filter.mpr
  refine ⟨Finset.mem_univ _, ?_⟩
  refine ⟨?_, ?_, ?_⟩
  · calc
      (S.1.image e).card = S.1.card := Finset.card_image_of_injective S.1 e.injective
      _ = 17 := hS.1
  · intro h
    rcases Finset.mem_image.mp h with ⟨g, hg, hge⟩
    apply hS.2.1
    have hg0 : g = 0 := e.injective (by simpa using hge)
    exact hg0 ▸ hg
  · intro g hg
    rcases Finset.mem_image.mp hg with ⟨x, hx, rfl⟩
    have hneg : -x ∈ S.1 := hS.2.2 hx
    have hmem : e (-x) ∈ S.1.image e :=
      Finset.mem_image.mpr ⟨-x, hneg, rfl⟩
    simpa using hmem

 def connectionMapEquiv (e : ResearchG ≃+ ResearchG) :
    ResearchConnectionSet ≃ ResearchConnectionSet where
  toFun := connectionMap e
  invFun := connectionMap e.symm
  left_inv := by
    intro S
    apply Subtype.ext
    simp [connectionMap, Finset.image_image]
  right_inv := by
    intro S
    apply Subtype.ext
    simp [connectionMap, Finset.image_image]

/-- The fixed-set count for an automorphism. -/
def fixedConnectionSetCount (e : ResearchG ≃+ ResearchG) : Nat :=
  (Finset.univ.filter (fun S : Finset ResearchG => S.image e = S)).card

/-- The faithful action image on the connection-set carrier. -/
def connectionActionImage : Finset (ResearchConnectionSet ≃ ResearchConnectionSet) :=
  (Finset.univ : Finset (ResearchG ≃+ ResearchG)).image connectionMapEquiv

def fixedConnectionSetCountOnAction (p : ResearchConnectionSet ≃ ResearchConnectionSet) : Nat :=
  (Finset.univ.filter (fun S : ResearchConnectionSet => p S = S)).card

def weightedCycleBurnsideFixedSetSum : Nat :=
  (connectionActionImage.sum fixedConnectionSetCountOnAction)

def connectionOrbit (S : ResearchConnectionSet) : Finset ResearchConnectionSet :=
  (Finset.univ : Finset (ResearchG ≃+ ResearchG)).image (fun e => connectionMapEquiv e S)

def connectionOrbits : Finset (Finset ResearchConnectionSet) := by
  classical
  exact (Finset.univ : Finset ResearchConnectionSet).image connectionOrbit

def claim_31053 : Prop :=
  Fintype.card ResearchG = 72 ∧
    inverseAtoms.card = 39 ∧
    (inverseAtoms.filter (fun A => A.card = 1)).card = 7 ∧
    (inverseAtoms.filter (fun A => A.card = 2)).card = 32 ∧
    Fintype.card (ResearchG ≃+ ResearchG) = 1008 ∧
    (∀ A : ResearchAtom, atomMapEquiv inversionEquiv A = A) ∧
    inverseAtomActionImage.card = 504

def claim_31054 : Prop :=
  connectionSets.card = 210664468 ∧
    weightedCycleBurnsideFixedSetSum = 231821352 ∧
    inverseAtomActionImage.card = 504 ∧
    weightedCycleBurnsideFixedSetSum / inverseAtomActionImage.card = 459963 ∧
    connectionOrbits.card = 459963

end

end MathlibPlus.Open.ResearchFormalizationBatch
