-- UNVERIFIED (does-not-elaborate): submitted but not kernel-verified, so it is not built and MathlibPlus.lean does not import it. See unverified.txt.
import Mathlib
import MathlibPlus.Open.ResearchFormalizationBatch.MixedSquare

namespace MathlibPlus.Open.ResearchFormalizationBatch

abbrev F18 := Fin 18
abbrev FiveOmega := ZMod 5 × F18

/-- The alternating subgroup used in the marked five-block construction. -/
def alternating18 : Subgroup (Equiv.Perm F18) :=
  MonoidHom.ker (Equiv.Perm.sign : Equiv.Perm F18 →* ℤˣ)

/-- The subgroup generated by commutators from a subgroup. -/
def derivedSubgroup {α : Type} [Group α] (J : Subgroup α) : Subgroup α :=
  ⁅J, J⁆

/-- Normal closure inside `J`, represented back in the ambient group. -/
def normalClosureWithin {α : Type} [Group α] (J : Subgroup α) (S : Set α) : Subgroup α :=
  Subgroup.map J.subtype (Subgroup.normalClosure {j : J | (j : α) ∈ S})

/-- The marked commutator used in the five-block construction. -/
def markedCommutator (l h : Equiv.Perm F18) : Equiv.Perm F18 :=
  h⁻¹ * (if Equiv.Perm.sign h = 1 then l else l⁻¹) * h * l⁻¹

/-- The subgroup generated by `H` and the marked order-five element. -/
def markedAmbient (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18) :
    Subgroup (Equiv.Perm F18) :=
  Subgroup.closure ((H : Set (Equiv.Perm F18)) ∪ {l})

/-- The even part of the marked ambient group. -/
def markedJ (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18) :
    Subgroup (Equiv.Perm F18) :=
  markedAmbient H l ⊓ alternating18

/-- The marked commutator core, normalised in `J`. -/
def markedCore (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18) :
    Subgroup (Equiv.Perm F18) :=
  normalClosureWithin (markedJ H l)
    {x | ∃ h : H, x = markedCommutator l (h : Equiv.Perm F18)}

/-- Multiplication by the sign on the five block coordinate. -/
def signedBlockEquiv (h : Equiv.Perm F18) : Equiv.Perm (ZMod 5) :=
  if Equiv.Perm.sign h = 1 then Equiv.refl _ else
    { toFun := fun z => -z
      invFun := fun z => -z
      left_inv := by intro z; simp
      right_inv := by intro z; simp }

/-- The marked lift of a permutation of the eighteen points. -/
def markedLift (h : Equiv.Perm F18) : Equiv.Perm FiveOmega :=
  Equiv.prodCongr (signedBlockEquiv h) h

/-- Translation of the five blocks. -/
def blockTranslation : Equiv.Perm FiveOmega where
  toFun p := (p.1 + 1, p.2)
  invFun p := (p.1 - 1, p.2)
  left_inv p := by rcases p with ⟨z, x⟩; simp
  right_inv p := by rcases p with ⟨z, x⟩; simp

/-- The natural regular copy generated by the block translation and marked lifts. -/
def naturalCopy (H : Subgroup (Equiv.Perm F18)) : Subgroup (Equiv.Perm FiveOmega) :=
  Subgroup.closure
    ({blockTranslation} ∪ Set.image markedLift (H : Set (Equiv.Perm F18)))

/-- The shear `(z,x) ↦ (z,x^{l^z})`, with the canonical representative of `z`. -/
def markedShear (l : Equiv.Perm F18) : Equiv.Perm FiveOmega where
  toFun p := (p.1, (l ^ p.1.val) p.2)
  invFun p := (p.1, (l ^ p.1.val)⁻¹ p.2)
  left_inv p := by rcases p with ⟨z, x⟩; simp
  right_inv p := by rcases p with ⟨z, x⟩; simp

/-- Conjugation of a subgroup in the convention `R^s = s⁻¹ R s`. -/
def conjugateSubgroup {α : Type} [Group α] (R : Subgroup α) (s : α) : Subgroup α :=
  Subgroup.map (MulAut.conj s⁻¹) R

/-- The sheared regular copy and the group generated by the two copies. -/
def shearedCopy (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18) :
    Subgroup (Equiv.Perm FiveOmega) :=
  conjugateSubgroup (naturalCopy H) (markedShear l)

def generatedMarkedCopies (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18) :
    Subgroup (Equiv.Perm FiveOmega) :=
  Subgroup.closure
    ((naturalCopy H : Set (Equiv.Perm FiveOmega)) ∪
      (shearedCopy H l : Set (Equiv.Perm FiveOmega)))

/-- The subgroup of permutations that fix every block coordinate. -/
def blockFixing : Subgroup (Equiv.Perm FiveOmega) where
  carrier := {g | ∀ p, (g p).1 = p.1}
  one_mem' := by intro p; simp
  mul_mem' := by
    intro f g hf hg p
    simp only [Equiv.Perm.mul_apply]
    rw [hf, hg]
  inv_mem' := by
    intro f hf p
    have h := hf (f⁻¹ p)
    simpa using h.symm

/-- The kernel of the action of a generated copy on the five blocks. -/
def blockKernel (Y : Subgroup (Equiv.Perm FiveOmega)) :
    Subgroup (Equiv.Perm FiveOmega) :=
  Y ⊓ blockFixing

/-- An arbitrary five-tuple of permutations from `J`, acting blockwise. -/
def blockwiseAction {J : Subgroup (Equiv.Perm F18)} (a : ZMod 5 → J) :
    Equiv.Perm FiveOmega where
  toFun p := (p.1, (a p.1 : Equiv.Perm F18) p.2)
  invFun p := (p.1, ((a p.1)⁻¹ : Equiv.Perm F18) p.2)
  left_inv p := by rcases p with ⟨z, x⟩; simp
  right_inv p := by rcases p with ⟨z, x⟩; simp

/-- The homomorphism from five-tuples to their blockwise permutations. -/
def blockwiseActionHom (J : Subgroup (Equiv.Perm F18)) :
    (ZMod 5 → J) →* Equiv.Perm FiveOmega where
  toFun a := blockwiseAction a
  map_one' := by
    apply Equiv.ext
    intro p
    rcases p with ⟨z, x⟩
    apply Prod.ext
    · rfl
    · change (1 : Equiv.Perm F18) x = x
      simp
  map_mul' := by
    intro a b
    apply Equiv.ext
    intro p
    rcases p with ⟨z, x⟩
    apply Prod.ext
    · rfl
    · change ((a z : Equiv.Perm F18) * (b z : Equiv.Perm F18)) x =
        (a z : Equiv.Perm F18) ((b z : Equiv.Perm F18) x)
      simp [Equiv.Perm.mul_apply]

/-- The embedded direct power `J⁵` acting independently on the five blocks. -/
def blockwisePower (J : Subgroup (Equiv.Perm F18)) :
    Subgroup (Equiv.Perm FiveOmega) :=
  Subgroup.map (blockwiseActionHom J) ⊤

/-- The diagonal copy of `J` on all five blocks. -/
def diagonalActionHom (J : Subgroup (Equiv.Perm F18)) :
    J →* Equiv.Perm FiveOmega where
  toFun j := blockwiseAction (fun _ => j)
  map_one' := by
    apply Equiv.ext
    intro p
    rcases p with ⟨z, x⟩
    apply Prod.ext
    · rfl
    · change (1 : Equiv.Perm F18) x = x
      simp
  map_mul' := by
    intro a b
    apply Equiv.ext
    intro p
    rcases p with ⟨z, x⟩
    apply Prod.ext
    · rfl
    · change ((a : Equiv.Perm F18) * (b : Equiv.Perm F18)) x =
        (a : Equiv.Perm F18) ((b : Equiv.Perm F18) x)
      simp [Equiv.Perm.mul_apply]

def diagonalPower (J : Subgroup (Equiv.Perm F18)) :
    Subgroup (Equiv.Perm FiveOmega) :=
  Subgroup.map (diagonalActionHom J) ⊤

/-- Claim 39510: the marked five-block setup, with the named objects above. -/
def claim39510 (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18) : Prop :=
  IsRegularCopy H ∧
    Nonempty (H ≃* Multiplicative ((ZMod 3 × ZMod 3) × ZMod 2)) ∧
    orderOf l = 5

/-- The hypotheses shared by the marked shear-generation records. -/
def markedRecordTwoHypotheses (H : Subgroup (Equiv.Perm F18))
    (l : Equiv.Perm F18) : Prop :=
  IsRegularCopy H ∧
    Nonempty (H ≃* Multiplicative ((ZMod 3 × ZMod 3) × ZMod 2)) ∧
    orderOf l = 5 ∧
    markedCore H l = derivedSubgroup (markedJ H l) ∧
    derivedSubgroup (markedJ H l) =
      derivedSubgroup (derivedSubgroup (markedJ H l)) ∧
    l ∈ derivedSubgroup (markedJ H l)

/-- Claim 39511: the marked shear is generated under the stated hypotheses. -/
def claim39511 : Prop :=
  ∀ (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18),
    IsRegularCopy H ∧
      Nonempty (H ≃* Multiplicative ((ZMod 3 × ZMod 3) × ZMod 2)) ∧
      orderOf l = 5 →
    markedCore H l = derivedSubgroup (markedJ H l) →
    derivedSubgroup (markedJ H l) =
      derivedSubgroup (derivedSubgroup (markedJ H l)) →
    l ∈ derivedSubgroup (markedJ H l) →
    markedShear l ∈ generatedMarkedCopies H l

/-- Claim 39514: the derived block kernel is the full direct power and contains the shear. -/
def claim39514 : Prop :=
  ∀ (H : Subgroup (Equiv.Perm F18)) (l : Equiv.Perm F18),
    markedRecordTwoHypotheses H l →
    let N := blockKernel (generatedMarkedCopies H l)
    let D := derivedSubgroup (markedJ H l)
    derivedSubgroup N = blockwisePower D ∧
      markedShear l ∈ blockwisePower D

end MathlibPlus.Open.ResearchFormalizationBatch
