import MathlibPlus.Open.ResearchFormalizationBatch.GroupTheory

open scoped BigOperators
noncomputable section

namespace MathlibPlus.Open.ResearchFormalizationBatch.CentralShear31634

open MathlibPlus.Open.ResearchFormalizationBatch

abbrev K2 := ZMod 2
abbrev H2 (A : Type*) := BooleanQuotient A
abbrev TwistedCarrier (A : Type*) := H2 A × K2

/-- The normalized cocycle for the nonsplit quaternion extension on the
`C₂²` factor, extended trivially over the odd Hall factor. -/
def quaternionCocycle {A : Type*} [AddCommGroup A]
    (h u : H2 A) : K2 :=
  h.2.1 * u.2.1 + h.2.2 * u.2.2 + h.2.2 * u.2.1

/-- Multiplication in the displayed twisted quaternion extension. -/
def twistedMul {A : Type*} [AddCommGroup A]
    (x y : TwistedCarrier A) : TwistedCarrier A :=
  (x.1 + y.1, x.2 + y.2 + quaternionCocycle x.1 y.1)

/-- Inversion in the displayed twisted extension. -/
def twistedInv {A : Type*} [AddCommGroup A]
    (x : TwistedCarrier A) : TwistedCarrier A :=
  (-x.1, -x.2 - quaternionCocycle x.1 (-x.1))

/-- The normalized Boolean switching `f_b`. -/
def liftSwitch {A : Type*} [AddCommGroup A]
    (b : H2 A → K2) : TwistedCarrier A → TwistedCarrier A :=
  fun x => (x.1, x.2 + b x.1)

/-- The central character shear `αχ`. -/
def characterShear {A : Type*} [AddCommGroup A]
    (χ : H2 A →+ K2) : TwistedCarrier A → TwistedCarrier A :=
  fun x => (x.1, x.2 + χ x.1)

/-- Automorphism of the displayed twisted multiplication. -/
def twistedAutomorphism {A : Type*} [AddCommGroup A]
    (f : TwistedCarrier A → TwistedCarrier A) : Prop :=
  Function.Bijective f ∧
    ∀ x y, f (twistedMul x y) = twistedMul (f x) (f y)

/-- The cocycle-cancelled relative derivative in direction `u`. -/
def derivativeStep {A : Type*} [AddCommGroup A]
    (b : H2 A → K2) (u : H2 A) (x : TwistedCarrier A) : TwistedCarrier A :=
  (x.1, x.2 + b (x.1 + u) + b x.1 + b u)

/-- The orbit generated by relative derivatives in all quotient directions. -/
def derivativeOrbit {A : Type*} [AddCommGroup A]
    (b : H2 A → K2) (x : TwistedCarrier A) : Set (TwistedCarrier A) :=
  {y | Relation.ReflTransGen
      (fun s t => ∃ u : H2 A, t = derivativeStep b u s) x y}

/-- The two maps have the same image on every complete relative-derivative
orbit. -/
def orbitShadow {A : Type*} [AddCommGroup A]
    (b : H2 A → K2) (χ : H2 A →+ K2) : Prop :=
  ∀ x : TwistedCarrier A,
    Set.image (liftSwitch b) (derivativeOrbit b x) =
      Set.image (characterShear χ) (derivativeOrbit b x)

/-- Directed Cayley relation for the displayed twisted multiplication. -/
def twistedCayleyRelation {A : Type*} [AddCommGroup A]
    (S : Set (TwistedCarrier A))
    (x y : TwistedCarrier A) : Prop :=
  ∃ s, s ∈ S ∧ y = twistedMul x s

/-- Transport of a directed Cayley relation by a relabeling. -/
def carriesTwistedCayley {A : Type*} [AddCommGroup A]
    (f : TwistedCarrier A → TwistedCarrier A)
    (S T : Set (TwistedCarrier A)) : Prop :=
  ∀ x y,
    twistedCayleyRelation S x y ↔
      twistedCayleyRelation T (f x) (f y)

/-- Inverse-closed connection sets, for the undirected subfamily. -/
def twistedInverseClosed {A : Type*} [AddCommGroup A]
    (S : Set (TwistedCarrier A)) : Prop :=
  ∀ x, x ∈ S → twistedInv x ∈ S

/-- Claim 31634: the central character shear is an automorphism, shadows the
complete all-direction relative-derivative orbit of `f_b`, and replaces
`f_b` on both directed and inverse-closed undirected Cayley relations. -/
def claim31634 : Prop :=
  ∀ (A : Type*) [Fintype A] [AddCommGroup A],
    Odd (Fintype.card A) →
      ∀ b : H2 A → K2,
        b 0 = 0 →
          ∃ χ : H2 A →+ K2,
            (∀ h, h ∈ linearitySet31633 b → χ h = b h) ∧
              twistedAutomorphism (characterShear χ) ∧
                orbitShadow b χ ∧
                  (∀ S T : Set (TwistedCarrier A),
                    carriesTwistedCayley (liftSwitch b) S T →
                      carriesTwistedCayley (characterShear χ) S T) ∧
                    (∀ S T : Set (TwistedCarrier A),
                      twistedInverseClosed S →
                        twistedInverseClosed T →
                          carriesTwistedCayley (liftSwitch b) S T →
                            carriesTwistedCayley (characterShear χ) S T)

end MathlibPlus.Open.ResearchFormalizationBatch.CentralShear31634
