import Mathlib
import MathlibPlus.Open.ResearchFormalization.NCDCorner

namespace MathlibPlus.Open.ResearchFormalizationBatch.Retry39484

open MathlibPlus.Open.ResearchFormalization.NCDCorner

private noncomputable def generator39484 (i : Fin 13) : Fin 11 → A :=
  if i = 0 then standardBasis 0 else
  if i = 1 then standardBasis 2 else
  if i = 2 then standardBasis 4 else
  if i = 3 then standardBasis 6 else
  if i = 4 then standardBasis 8 else
  if i = 5 then standardBasis 10 else
  if i = 6 then (u - t ^ 2) • standardBasis 1 else
  if i = 7 then (u - t ^ 2) • standardBasis 3 else
  if i = 8 then (u - t ^ 2) • standardBasis 5 else
  if i = 9 then (u - t ^ 2) • standardBasis 7 else
  if i = 10 then (u - t ^ 2) • standardBasis 9 else
  if i = 11 then -(t • standardBasis 3) + (3 : A) • standardBasis 5 else
  -(t • standardBasis 7) + (3 : A) • standardBasis 9

private def completeKernelCriterion (f : Fin 11 → A) : Prop :=
  quotientMapA (f 1) = 0 ∧
  quotientMapA (3 : A) * quotientMapA (f 3) +
      quotientMapA t * quotientMapA (f 5) = 0 ∧
  quotientMapA (3 : A) * quotientMapA (f 7) +
      quotientMapA t * quotientMapA (f 9) = 0

/-- The complete corner kernel is generated by the six invisible states and
all seven displayed visible generators. -/
def claim39484 : Prop :=
  ∀ f : Fin 11 → A,
    completeKernelCriterion f ↔
      f ∈ Submodule.span A (Set.range generator39484)

end MathlibPlus.Open.ResearchFormalizationBatch.Retry39484
