import Mathlib

namespace MathlibPlus.Open.NewResearch2.R0316HeightTwo

noncomputable section

open scoped BigOperators
open Classical

abbrev Six := Fin 6

private def unionClosed {α : Type*} [DecidableEq α]
    (F : Finset (Finset α)) : Prop :=
  ∀ ⦃A B : Finset α⦄, A ∈ F → B ∈ F → A ∪ B ∈ F

/-- The finite-family version of `A ⊎ B = {a ∪ b}`. -/
private def fiberJoin {X : Type*} [DecidableEq X]
    (A B : Finset (Finset X)) : Finset (Finset X) :=
  A.biUnion (fun a => B.image (fun b => a ∪ b))

private def baseT : Finset Six :=
  {0, 1, 2}

private def baseZ : Finset Six :=
  {3, 4, 5}

/-- The eight-member base type generated by `Z ∪ {t_i}`. -/
private def baseH : Finset (Finset Six) :=
  insert ∅ ((baseT.powerset.erase ∅).image (fun A => baseZ ∪ A))

/-- The punctured type `P_x = H ⊎ 2^(X \ {x})`. -/
private def punctured (x : Six) : Finset (Finset Six) :=
  fiberJoin baseH ((Finset.univ.erase x).powerset)

private def fullCube : Finset (Finset Six) :=
  (Finset.univ : Finset Six).powerset

private def allowedTypes : Finset (Finset (Finset Six)) :=
  insert baseH
    (insert fullCube
      (insert (punctured 0) (insert (punctured 1) (insert (punctured 2)
        (insert (punctured 3) (insert (punctured 4)
          (insert (punctured 5) ∅)))))))

private def countType {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six))
    (A : Finset (Finset Six)) : ℕ :=
  (support.filter (fun S => fiber S = A)).card

private def totalWeight {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)) : ℕ :=
  support.sum (fun S => (fiber S).card)

private def principalWeight {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six))
    (S : Finset Y) : ℕ :=
  (support.filter (fun T => T ⊆ S)).sum (fun T => (fiber T).card)

private def coupled {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)) : Prop :=
  unionClosed support ∧
    (∀ S ∈ support, (fiber S).Nonempty) ∧
    (∀ S ∈ support, ∀ T ∈ support,
      fiberJoin (fiber S) (fiber T) ⊆ fiber (S ∪ T))

/-- A completion using exactly the seven allowed inner types, with its base
trace fixed at the empty outside trace. -/
private def sevenTypeCompletion {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)) : Prop :=
  coupled support fiber ∧
    (∀ S ∈ support, fiber S ∈ allowedTypes) ∧
    ∅ ∈ support ∧ fiber ∅ = baseH ∧
    countType support fiber baseH = 1

/-- The balanced completion with one base fiber, the six stated punctured
multiplicities, and `q` full fibers. -/
private def balancedCompletion {Y : Type*} [DecidableEq Y]
    (q : ℕ) (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)) : Prop :=
  sevenTypeCompletion support fiber ∧
    support.card = 31 + q ∧
    countType support fiber (punctured 0) = 1 ∧
    countType support fiber (punctured 1) = 1 ∧
    countType support fiber (punctured 2) = 1 ∧
    countType support fiber (punctured 3) = 13 ∧
    countType support fiber (punctured 4) = 7 ∧
    countType support fiber (punctured 5) = 7 ∧
    countType support fiber fullCube = q ∧
    totalWeight support fiber = 1169 + 64 * q

private def supportTop {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y)) : Finset Y :=
  support.biUnion id

private def heavyProperTraces {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six))
    (top : Finset Y) : Finset (Finset Y) :=
  support.filter (fun R =>
    R ≠ top ∧ 2 * principalWeight support fiber R > totalWeight support fiber)

private def traceSignature {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six))
    (top S : Finset Y) : Finset (Finset Y) :=
  (heavyProperTraces support fiber top).filter (fun R => ¬ S ⊆ R)

private def signatureInjectiveOnSupport {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six))
    (top : Finset Y) : Prop :=
  ∀ ⦃S T : Finset Y⦄, S ∈ support → T ∈ support →
    traceSignature support fiber top S = traceSignature support fiber top T → S = T

private def strictOutsideSubhalf {Y : Type*} [DecidableEq Y]
    (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)) : Prop :=
  ∀ y : Y,
    2 * support.sum (fun S => if y ∈ S then (fiber S).card else 0) <
      totalWeight support fiber

/-- Claim 19748: under inclusion the seven types have bottom `H`, six
incomparable punctured atoms, and top `Q`; in any seven-type completion the
full fibers form an upper ideal, comparable non-base non-full traces have one
punctured type, and the non-full support is the six-branch bouquet over the
base. -/
def claim19748 : Prop :=
  (∀ B ∈ allowedTypes, baseH ⊆ B ∧ B ⊆ fullCube) ∧
    (∀ x y : Six, x ≠ y →
      ¬ punctured x ⊆ punctured y ∧ ¬ punctured y ⊆ punctured x) ∧
    (∀ x : Six, ∀ B ∈ allowedTypes,
      baseH ⊆ B → B ⊆ punctured x → B = baseH ∨ B = punctured x) ∧
    ∀ {Y : Type*} [Fintype Y] [DecidableEq Y]
      (support : Finset (Finset Y))
      (fiber : Finset Y → Finset (Finset Six)),
      sevenTypeCompletion support fiber →
        (∀ S ∈ support, fiber S = fullCube →
          ∀ T ∈ support, S ⊆ T → fiber T = fullCube) ∧
        (∀ S ∈ support, ∀ T ∈ support, S ⊆ T →
          fiber S ≠ baseH → fiber T ≠ baseH →
          fiber S ≠ fullCube → fiber T ≠ fullCube → fiber S = fiber T) ∧
        (∀ S ∈ support, fiber S ≠ fullCube →
          S = ∅ ∨ ∃ x : Six, fiber S = punctured x)

/-- Claim 19752: for `q ≥ 1`, every non-full trace has a principal ideal
containing only the base and punctured traces of one type, of weight at most
`8 + 507 = 515`, strictly below half the total. -/
def claim19752 : Prop :=
  ∀ {Y : Type*} [Fintype Y] [DecidableEq Y]
    (q : ℕ) (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)),
    balancedCompletion q support fiber → 1 ≤ q →
      ∀ S ∈ support, fiber S ≠ fullCube →
        (∃ x : Six, ∀ T ∈ support, T ⊆ S →
          fiber T = baseH ∨ fiber T = punctured x) ∧
        principalWeight support fiber S ≤ 515 ∧
        2 * principalWeight support fiber S < totalWeight support fiber

/-- Claim 19753: strict sub-half outside coordinates make the majority
signature injective; excluding the top full trace leaves at most `q - 1`
proper heavy traces, so `31 + q ≤ 2^(q-1)` and `q ≥ 7`. -/
def claim19753 : Prop :=
  ∀ {Y : Type*} [Fintype Y] [DecidableEq Y]
    (q : ℕ) (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)),
    balancedCompletion q support fiber →
      strictOutsideSubhalf support fiber →
        let top := supportTop support
        top ∈ support ∧ fiber top = fullCube ∧
          signatureInjectiveOnSupport support fiber top ∧
          (heavyProperTraces support fiber top).card ≤ q - 1 ∧
          31 + q ≤ 2 ^ (q - 1) ∧ q ≥ 7

/-- Claim 19755: every balanced coupling completion with all outside
coordinates strictly below half has full-fiber debt at least eight. -/
def claim19755 : Prop :=
  ∀ {Y : Type*} [Fintype Y] [DecidableEq Y]
    (q : ℕ) (support : Finset (Finset Y))
    (fiber : Finset Y → Finset (Finset Six)),
    balancedCompletion q support fiber →
      strictOutsideSubhalf support fiber → q ≥ 8

end

end MathlibPlus.Open.NewResearch2.R0316HeightTwo
