import MathlibPlus.Open.NewResearch2.R1151NormalizedCollisionDataClaim41353

namespace MathlibPlus.Open.NewResearch2.R1151NormalizedCollisionData

noncomputable section

open Classical

/-- The exact active support in the displayed base-mask coordinates. -/
def activeMask31591 (u : Base41353) : Prop :=
  u = baseMasks41353 1 ∨
    u = baseMasks41353 2 ∨
      u = baseMasks41353 3

/-- The normalized displacement subgroup in the exact fiber `B=C₃²`. -/
def activeDisplacementSubgroup31591
    (q : Base41353 → Equiv.Perm Fiber41353) (u : Base41353) :
    AddSubgroup Fiber41353 :=
  AddSubgroup.closure (Set.range (fun t : Fiber41353 => t - q u t + q u 0))

/-- Full and proper are the two row classifications attached to the displayed
subgroup, with proper meaning not equal to the whole fiber. -/
def fullActiveRow31591
    (q : Base41353 → Equiv.Perm Fiber41353) (u : Base41353) : Prop :=
  activeDisplacementSubgroup31591 q u = ⊤

def properActiveRow31591
    (q : Base41353 → Equiv.Perm Fiber41353) (u : Base41353) : Prop :=
  activeDisplacementSubgroup31591 q u ≠ ⊤

/-- The exact normalized fiber-preserving row form supplied by the
collision data. -/
def normalizedRowWitness31591
    (f : Equiv.Perm G41353)
    (q : Base41353 → Equiv.Perm Fiber41353) : Prop :=
  (∀ a : Base41353, q a ≠ 1 ↔ activeMask31591 a) ∧
    (∀ (a : Base41353) (b : Fiber41353),
      f (a, b) = (rho041353 a, q a b))

/-- Claim 31591: for each active row of the supplied normalized collision
class, the subgroup is generated by the exact displacements
`t-q_u(t)+q_u(0)`, and full/proper use equality or inequality with `B`. -/
def claim31591 : Prop :=
  ∀ (f : Equiv.Perm G41353)
    (q : Base41353 → Equiv.Perm Fiber41353),
    normalizedRowWitness31591 f q →
      ∀ u : Base41353, activeMask31591 u →
        (activeDisplacementSubgroup31591 q u =
          AddSubgroup.closure (Set.range
            (fun t : Fiber41353 => t - q u t + q u 0))) ∧
          (fullActiveRow31591 q u ↔
            activeDisplacementSubgroup31591 q u = (⊤ : AddSubgroup Fiber41353)) ∧
          (properActiveRow31591 q u ↔
            activeDisplacementSubgroup31591 q u ≠ (⊤ : AddSubgroup Fiber41353))

end

end MathlibPlus.Open.NewResearch2.R1151NormalizedCollisionData
