import MathlibPlus.Open.ResearchFormalization.R1900.Claim31268

namespace MathlibPlus.Open.ResearchFormalization.R1900.Claims31270_31272

noncomputable section

open scoped BigOperators
open MathlibPlus.Open.ResearchFormalization.R1900.Claim31268

/-- The exact trace class of members other than the pivot. -/
def exactTraceClass {α : Type*} [DecidableEq α]
    (A T : Finset α) (G : Finset (Finset α)) : Finset (Finset α) :=
  (G.erase A).filter (fun B => A ∩ B = T)

/-- The residual family obtained by deleting the common exact trace class. -/
def exactResidualFamily {α : Type*} [DecidableEq α]
    (A T : Finset α) (G : Finset (Finset α)) : Finset (Finset α) :=
  (exactTraceClass A T G).image (fun B => B \ A)

/-- Distinctness of residual members on one exact trace class. -/
def residualMembersDistinct {α : Type*} [DecidableEq α]
    (A T : Finset α) (G : Finset (Finset α)) : Prop :=
  ∀ B₁ B₂ : Finset α,
    B₁ ∈ G → B₂ ∈ G →
      A ∩ B₁ = T → A ∩ B₂ = T →
        B₁ \ A = B₂ \ A → B₁ = B₂

/-- Pairwise intersection for the three-petal specialization. -/
def pairwiseIntersecting {α : Type*} [DecidableEq α]
    (G : Finset (Finset α)) : Prop :=
  ∀ ⦃B D : Finset α⦄,
    B ∈ G → D ∈ G → B ≠ D → ¬ Disjoint B D

/-- The number `N_p(A)` of distinct occupied exact traces of rank `p`. -/
def traceRankCount {α : Type*} [DecidableEq α]
    (A : Finset α) (G : Finset (Finset α)) (p : ℕ) : ℕ :=
  (occupiedExactTraces A G).filter (fun T => T.card = p) |>.card

/-- The positive-rank geometric series in the trace-count estimate. -/
def positiveGeometricSum : ℝ :=
  ∑' p : ℕ, if 1 ≤ p then ((1 : ℝ) / 2) ^ p else 0

/-- A family together with its rank, on the fixed finite set carrier. -/
abbrev FamilyNode (α : Type*) := ℕ × Finset (Finset α)

/-- The validity condition for a node in a bounded-matching sunflower class. -/
def nodeIsValid {α : Type*} [DecidableEq α]
    (k : ℕ) (node : FamilyNode α) : Prop :=
  boundedMatchingSunflowerFamily node.1 k node.2

/-- The rank and exact residual node generated by a pivot and trace. -/
def residualNode {α : Type*} [DecidableEq α]
    (r : ℕ) (A T : Finset α) (G : Finset (Finset α)) : FamilyNode α :=
  (r - T.card, exactResidualFamily A T G)

/-- Every exact residual of every actual pivot remains in the class. -/
def residualHereditaryClass {α : Type*} [DecidableEq α]
    (𝒞 : Set (FamilyNode α)) : Prop :=
  ∀ (r : ℕ) (G : Finset (Finset α)),
    (r, G) ∈ 𝒞 →
      ∀ A ∈ G, ∀ T ∈ occupiedExactTraces A G,
        residualNode r A T G ∈ 𝒞

/-- The rankwise trace-count hypothesis at every nonterminal class node.
It records an actual pivot and the `N₀=0`/positive-rank bounds, without
assuming the Kraft conclusion. -/
def rankwisePivotClass {α : Type*} [DecidableEq α]
    (S : ℝ) (𝒞 : Set (FamilyNode α))
    (Terminal : Set (FamilyNode α)) : Prop :=
  ∀ (r : ℕ) (G : Finset (Finset α)),
    (r, G) ∈ 𝒞 →
      (r, G) ∉ Terminal →
        ∃ A : Finset α,
          A ∈ G ∧
            traceRankCount A G 0 = 0 ∧
              ∀ p : ℕ, 1 ≤ p →
                (traceRankCount A G p : ℝ) ≤ S ^ p

/-- The terminal rank bound in the hereditary recursion. -/
def terminalRankBound {α : Type*} [DecidableEq α]
    (C : ℝ) (𝒞 : Set (FamilyNode α))
    (Terminal : Set (FamilyNode α)) : Prop :=
  ∀ (r : ℕ) (G : Finset (Finset α)),
    (r, G) ∈ 𝒞 →
      (r, G) ∈ Terminal →
        (G.card : ℝ) ≤ C ^ r

/-- The explicit class interface for the hereditary Kraft conclusion. -/
def hereditaryTraceClassHypotheses {α : Type*} [DecidableEq α]
    (k : ℕ) (S C : ℝ) (𝒞 : Set (FamilyNode α))
    (Terminal : Set (FamilyNode α)) : Prop :=
  (∀ (r : ℕ) (G : Finset (Finset α)),
    (r, G) ∈ 𝒞 → nodeIsValid k (r, G)) ∧
    rankwisePivotClass S 𝒞 Terminal ∧
      residualHereditaryClass 𝒞 ∧
        terminalRankBound C 𝒞 Terminal

/-- The concrete two-disjoint-2-set witness for the rank-zero obstruction. -/
def twoDisjointTwoSetFamily : Finset (Finset (Fin 4)) :=
  {{0, 1}, {2, 3}}

def firstTwoSet : Finset (Fin 4) :=
  {0, 1}

/-- Claim 31270: exact residuals retain distinctness, uniformity,
`k`-sunflower-freeness, and the matching-number bound; the full trace is the
empty branch; Kraft-good nonterminal branches use proper traces; and the
positive-rank `k=3` statement excludes empty traces without a nonterminal
hypothesis. -/
def claim31270_residualKraftRecursion : Prop :=
  ∀ {α : Type*} [Fintype α] [DecidableEq α]
    (r k : ℕ) (G : Finset (Finset α)) (A : Finset α) (K : ℝ),
    3 ≤ k →
      0 < r →
        boundedMatchingSunflowerFamily r k G →
          A ∈ G →
            1 < K →
              (∀ T ∈ occupiedExactTraces A G,
                residualMembersDistinct A T G ∧
                  (∀ R ∈ exactResidualFamily A T G,
                    R.card = r - T.card) ∧
                  kSunflowerFree k (exactResidualFamily A T G) ∧
                    matchingAtMost k (exactResidualFamily A T G)) ∧
                exactResidualFamily A A G = ∅ ∧
                A ∈ occupiedExactTraces A G ∧
                (isKraftGood K A G →
                  1 < G.card →
                    ¬ (∅ ∈ occupiedExactTraces A G ∧
                      A ∈ occupiedExactTraces A G) ∧
                      (∀ T ∈ occupiedExactTraces A G,
                        T ≠ A → T.card < r)) ∧
                (k = 3 →
                  pairwiseIntersecting G →
                    ∅ ∉ occupiedExactTraces A G)

/-- Claim 31272: rank-count bounds give the geometric Kraft estimate; the
sequence form includes rank zero; a hereditary class with those rank-count
pivots has base `max {2S,C}` without assuming Kraft-goodness in the pivot
hypothesis; and two disjoint 2-sets exhibit the general-k rank-zero failure. -/
def claim31272_traceCountSufficientCondition : Prop :=
  (∀ {α : Type*} [Fintype α] [DecidableEq α]
    (r k : ℕ) (G : Finset (Finset α)) (A : Finset α) (S : ℝ),
    3 ≤ k →
      0 < r →
        boundedMatchingSunflowerFamily r k G →
          A ∈ G →
            traceRankCount A G 0 = 0 →
              (∀ p : ℕ, 1 ≤ p →
                (traceRankCount A G p : ℝ) ≤ S ^ p) →
                kraftTracePartitionFunction (2 * S) A G ≤
                  positiveGeometricSum ∧
                    positiveGeometricSum = 1 ∧
                      isKraftGood (2 * S) A G) ∧
  (∀ {α : Type*} [Fintype α] [DecidableEq α]
    (r k : ℕ) (G : Finset (Finset α)) (A : Finset α) (K : ℝ)
      (a : ℕ → ℝ),
    3 ≤ k →
      0 < r →
        boundedMatchingSunflowerFamily r k G →
          A ∈ G →
            1 < K →
              (∀ p : ℕ, 0 ≤ a p) →
                (∑' p : ℕ, a p) ≤ 1 →
                  (∀ p : ℕ,
                    (traceRankCount A G p : ℝ) ≤ a p * K ^ p) →
                    isKraftGood K A G) ∧
  (∀ {α : Type*} [Fintype α] [DecidableEq α]
    (k : ℕ) (S C : ℝ) (𝒞 : Set (FamilyNode α))
      (Terminal : Set (FamilyNode α)),
    3 ≤ k →
      1 < 2 * S →
        1 ≤ C →
          hereditaryTraceClassHypotheses k S C 𝒞 Terminal →
            ∀ (r : ℕ) (G : Finset (Finset α)),
              (r, G) ∈ 𝒞 →
                (G.card : ℝ) ≤ (max (2 * S) C) ^ r) ∧
  (∀ {α : Type*} [Fintype α] [DecidableEq α]
    (r : ℕ) (G : Finset (Finset α)) (A : Finset α),
    0 < r →
      boundedMatchingSunflowerFamily r 3 G →
        A ∈ G →
          ∅ ∉ occupiedExactTraces A G) ∧
  (∀ K : ℝ, 1 < K →
    boundedMatchingSunflowerFamily 2 4 twoDisjointTwoSetFamily ∧
      firstTwoSet ∈ twoDisjointTwoSetFamily ∧
        traceRankCount firstTwoSet twoDisjointTwoSetFamily 0 = 1 ∧
          (∀ p : ℕ, 1 ≤ p →
            (traceRankCount firstTwoSet twoDisjointTwoSetFamily p : ℝ) ≤
              (1 : ℝ) ^ p) ∧
            kraftTracePartitionFunction K firstTwoSet
                twoDisjointTwoSetFamily = 1 + K⁻¹ ^ 2 ∧
              kraftTracePartitionFunction K firstTwoSet
                twoDisjointTwoSetFamily > 1)

end

end MathlibPlus.Open.ResearchFormalization.R1900.Claims31270_31272
