import Mathlib

namespace MathlibPlus.Open.R1121

abbrev F7 := ZMod 7

private def normalizedOuter :=
  {p : Equiv.Perm F7 // p 0 = 0}

private def outerDerivative (p q : Equiv.Perm F7) (u : F7) : Equiv.Perm F7 :=
  (((Equiv.addRight (2 * u)).trans p).trans
      (Equiv.addRight (-2 * q u))).trans p.symm

private def derivativeStep (p q : normalizedOuter) (x y : F7) : Prop :=
  ∃ u : F7, y = outerDerivative p.1 q.1 u x

private def derivativeReachable (p q : normalizedOuter) (x y : F7) : Prop :=
  Relation.ReflTransGen (derivativeStep p q) x y

private noncomputable def derivativeOrbitCard
    (p q : normalizedOuter) (x : F7) : Nat := by
  classical
  exact (Finset.univ.filter (derivativeReachable p q x)).card

private def singletonOrbitShape (p q : normalizedOuter) : Prop :=
  ∀ x : F7, derivativeOrbitCard p q x = 1

private def oneSixOrbitShape (p q : normalizedOuter) : Prop :=
  ∃ x y : F7,
    derivativeOrbitCard p q x = 1 ∧
    derivativeOrbitCard p q y = 6

private def threeFourOrbitShape (p q : normalizedOuter) : Prop :=
  ∃ x y : F7,
    derivativeOrbitCard p q x = 3 ∧
    derivativeOrbitCard p q y = 4

private def transitiveOrbitShape (p q : normalizedOuter) : Prop :=
  ∀ x : F7, derivativeOrbitCard p q x = 7

/-- Claim 29148: the orbits generated by all relative outer derivatives have
exactly the four displayed shapes and census over the normalized pairs. -/
def claim29148 : Prop :=
  Nat.card normalizedOuter = 720 ∧
  Nat.card (normalizedOuter × normalizedOuter) = 518400 ∧
  Nat.card {pq : normalizedOuter × normalizedOuter //
    singletonOrbitShape pq.1 pq.2} = 6 ∧
  Nat.card {pq : normalizedOuter × normalizedOuter //
    oneSixOrbitShape pq.1 pq.2} = 4998 ∧
  Nat.card {pq : normalizedOuter × normalizedOuter //
    threeFourOrbitShape pq.1 pq.2} = 588 ∧
  Nat.card {pq : normalizedOuter × normalizedOuter //
    transitiveOrbitShape pq.1 pq.2} = 512808

end MathlibPlus.Open.R1121
