import Mathlib

namespace MathlibPlus.GroupTheory.NormalizedDerivative

/-- If two permutations have the same image on every orbit of `Delta`, then
any `Delta`-invariant set has the same image under both permutations. This is
the abstract orbit-shadow mechanism used by finite fixed-group CI certificates. -/
theorem orbitShadow_transports_invariantSet
    {X : Type*} (Delta : Subgroup (Equiv.Perm X)) (q alpha : X ≃ X)
    (S : Set X)
    (hshadow : ∀ c : X,
      alpha '' {y : X | ∃ p : Delta, p.1 c = y} =
        q '' {y : X | ∃ p : Delta, p.1 c = y})
    (hinvariant : ∀ c : X, ∀ p : Delta, c ∈ S ↔ p.1 c ∈ S) :
    alpha '' S = q '' S := by
  ext y
  constructor
  · rintro ⟨s, hs, rfl⟩
    have hsOrbit : s ∈ {y : X | ∃ p : Delta, p.1 s = y} :=
      ⟨⟨1, Delta.one_mem⟩, rfl⟩
    have hmem : alpha s ∈
        alpha '' {y : X | ∃ p : Delta, p.1 s = y} :=
      ⟨s, hsOrbit, rfl⟩
    rw [hshadow s] at hmem
    rcases hmem with ⟨t, ⟨p, hp⟩, ht⟩
    refine ⟨t, ?_, ht⟩
    rw [← hp]
    exact (hinvariant s p).mp hs
  · rintro ⟨s, hs, rfl⟩
    have hsOrbit : s ∈ {y : X | ∃ p : Delta, p.1 s = y} :=
      ⟨⟨1, Delta.one_mem⟩, rfl⟩
    have hmem : q s ∈ q '' {y : X | ∃ p : Delta, p.1 s = y} :=
      ⟨s, hsOrbit, rfl⟩
    rw [← hshadow s] at hmem
    rcases hmem with ⟨t, ⟨p, hp⟩, ht⟩
    refine ⟨t, ?_, ht⟩
    rw [← hp]
    exact (hinvariant s p).mp hs

/-- The directed normalized-relative-derivative criterion from admitted claim 29205.
The left Cayley convention has an arc from `x` to `c * x` for `c ∈ S`.
The final condition says exactly that `S` is a union of orbits of the subgroup
`Delta` generated by the normalized relative derivatives. -/
theorem directedNormalizedDerivativeCriterion_claim29205
    {X : Type*} [Group X] [Finite X]
    (S : Set X) (_hS : 1 ∉ S) (q : X ≃ X) (_hq : q 1 = 1) :
    let derivative : X → X → X := fun x c => q (c * x) * (q x)⁻¹
    let generator : X → Equiv.Perm X := fun x =>
      (((Equiv.mulRight x).trans q).trans
        (Equiv.mulRight ((q x)⁻¹))).trans q.symm
    let Delta : Subgroup (Equiv.Perm X) := Subgroup.closure (Set.range generator)
    (∀ x c : X, c ∈ S ↔ derivative x c ∈ q '' S) ↔
      ∀ c : X, ∀ p : Delta, c ∈ S ↔ p.1 c ∈ S := by
  dsimp only
  let generator : X → Equiv.Perm X := fun x =>
    (((Equiv.mulRight x).trans q).trans
      (Equiv.mulRight ((q x)⁻¹))).trans q.symm
  let Delta : Subgroup (Equiv.Perm X) := Subgroup.closure (Set.range generator)
  have image_iff (y : X) : y ∈ q '' S ↔ q.symm y ∈ S := by
    constructor
    · rintro ⟨s, hs, rfl⟩
      simpa using hs
    · intro hy
      exact ⟨q.symm y, hy, q.apply_symm_apply y⟩
  have generator_apply (x c : X) :
      generator x c = q.symm (q (c * x) * (q x)⁻¹) := by
    rfl
  constructor
  · intro hgraph c p
    let P : (r : Equiv.Perm X) → r ∈ Delta → Prop :=
      fun r _ => ∀ z : X, z ∈ S ↔ r z ∈ S
    have hp : P p.1 p.2 := by
      apply Subgroup.closure_induction (p := P)
      · intro r hr
        rcases hr with ⟨x, rfl⟩
        intro z
        rw [generator_apply]
        rw [← image_iff]
        exact hgraph x z
      · intro z
        simp
      · intro r t hr ht hir hit z
        simpa only [Equiv.Perm.mul_apply] using (hit z).trans (hir (t z))
      · intro r hr hir z
        have h := hir (r⁻¹ z)
        simpa using h.symm
      · simpa [Delta, generator] using p.2
    exact hp c
  · intro horbit x c
    rw [image_iff]
    rw [← generator_apply]
    exact horbit c ⟨generator x, Subgroup.subset_closure (Set.mem_range_self x)⟩

/-- A fixed-group orbit-shadow certificate supplies a genuine group-automorphism
transporter for every directed Cayley connection set carried by `q`. This
connects the normalized-derivative criterion to simultaneous finite orbit
certificates such as the `Q_8` computation. -/
theorem directedCayley_orbitShadow_transport
    {X : Type*} [Group X] [Finite X]
    (S : Set X) (hS : 1 ∉ S) (q : X ≃ X) (hq : q 1 = 1)
    (alpha : X ≃* X) :
    let derivative : X → X → X := fun x c => q (c * x) * (q x)⁻¹
    let generator : X → Equiv.Perm X := fun x =>
      (((Equiv.mulRight x).trans q).trans
        (Equiv.mulRight ((q x)⁻¹))).trans q.symm
    let Delta : Subgroup (Equiv.Perm X) := Subgroup.closure (Set.range generator)
    (∀ x c : X, c ∈ S ↔ derivative x c ∈ q '' S) →
    (∀ c : X,
      alpha '' {y : X | ∃ p : Delta, p.1 c = y} =
        q '' {y : X | ∃ p : Delta, p.1 c = y}) →
    alpha '' S = q '' S := by
  dsimp only
  let generator : X → Equiv.Perm X := fun x =>
    (((Equiv.mulRight x).trans q).trans
      (Equiv.mulRight ((q x)⁻¹))).trans q.symm
  let Delta : Subgroup (Equiv.Perm X) := Subgroup.closure (Set.range generator)
  intro hgraph hshadow
  have hinvariant : ∀ c : X, ∀ p : Delta, c ∈ S ↔ p.1 c ∈ S := by
    simpa [Delta, generator] using
      (directedNormalizedDerivativeCriterion_claim29205 S hS q hq).mp hgraph
  exact orbitShadow_transports_invariantSet Delta q alpha.toEquiv S hshadow hinvariant

end MathlibPlus.GroupTheory.NormalizedDerivative
