import MathlibPlus.Open.ResearchFormalization.R1159.Claim41462

namespace MathlibPlus.Open.ResearchFormalization.R1159.ScalarQuietMultipliers

noncomputable section

open MathlibPlus.Open.ResearchFormalization.R1159.Claim41462

/-- The multiplier conclusion on the exact derivative/inversion-edge and
scalar-quiet-component carrier supplied by the normalized affine family. -/
def scalarQuietMultiplierConclusion {p : ℕ}
    (ω : (ZMod p)ˣ) (σ : Equiv.Perm SThree)
    (e : SThree → ZMod 3) (τ : SThree → ZMod p)
    (L : Set (AffineLoop p)) : Prop :=
  scalarQuietComponent ω σ e τ L →
    ∀ f : AffineLoop p, f ∈ L →
      ∃ a : (ZMod p)ˣ, ∃ b : ZMod p,
        affineLoopForm f a b ∧
          a ∈ orderThreeMultiplierSubgroup ω

/-- Claim 31694: every derivative or inversion edge in a scalar-quiet
component has an affine prime-fiber multiplier in the subgroup generated by
`ω` and `-1`. -/
def claim31694 : Prop :=
  ∀ p : ℕ, primeOneModThree p →
    ∀ (ω : (ZMod p)ˣ), orderOf ω = 3 →
      ∀ (σ : Equiv.Perm SThree), identityFixingNonautomorphic σ →
        ∀ (e : SThree → ZMod 3), normalizedScalarProfile e →
          ∀ (τ : SThree → ZMod p), normalizedTranslationProfile τ →
            ∀ L : Set (AffineLoop p),
              scalarQuietMultiplierConclusion ω σ e τ L

/-- Claim 41458: the duplicate admitted scalar-quiet multiplier statement,
with the same concrete prime-fiber, edge, component, and multiplier carriers. -/
def claim41458 : Prop :=
  ∀ p : ℕ, primeOneModThree p →
    ∀ (ω : (ZMod p)ˣ), orderOf ω = 3 →
      ∀ (σ : Equiv.Perm SThree), identityFixingNonautomorphic σ →
        ∀ (e : SThree → ZMod 3), normalizedScalarProfile e →
          ∀ (τ : SThree → ZMod p), normalizedTranslationProfile τ →
            ∀ L : Set (AffineLoop p),
              scalarQuietMultiplierConclusion ω σ e τ L

end

end MathlibPlus.Open.ResearchFormalization.R1159.ScalarQuietMultipliers
