import Mathlib

namespace MathlibPlus.Open.ResearchFormalization

section AffineOrbitals

variable {A B : Type*} [AddCommGroup A] [AddCommGroup B]

/-- Translation of a function, `(τ_h f)(x) = f(x+h)`. -/
def tau (h : B) (f : B → A) : B → A :=
  fun x => f (x + h)

/-- The invariant-function set `M_L`. -/
def invariantFunctions (L : AddSubgroup B) : Set (B → A) :=
  {f | ∀ ℓ, ℓ ∈ L → tau ℓ f = f}

/-- The constant-function subspace `C_A`. -/
def constantFunctions : AddSubgroup (B → A) :=
  { carrier := Set.range (fun c : A => fun _ : B => c)
    zero_mem' := by
      refine ⟨0, ?_⟩
      funext x
      simp
    add_mem' := by
      rintro f g ⟨a, rfl⟩ ⟨b, rfl⟩
      refine ⟨a + b, ?_⟩
      funext x
      simp
    neg_mem' := by
      rintro f ⟨a, rfl⟩
      refine ⟨-a, ?_⟩
      funext x
      simp }

/-- The affine permutation `(a,x) ↦ (a+f(x),x+h)`. -/
def affinePerm (f : B → A) (h : B) : Equiv.Perm (A × B) :=
  { toFun := fun p => (p.1 + f p.2, p.2 + h)
    invFun := fun p => (p.1 - f (p.2 - h), p.2 - h)
    left_inv := by
      rintro ⟨a, x⟩
      simp [sub_eq_add_neg, add_assoc, add_comm, add_left_comm]
    right_inv := by
      rintro ⟨a, x⟩
      simp [sub_eq_add_neg, add_assoc, add_comm, add_left_comm] }

/-- The permutation set denoted by `G_L = M_L ⋊ B`. -/
def affineGroup (L : AddSubgroup B) : Set (Equiv.Perm (A × B)) :=
  {q | ∃ f h, f ∈ invariantFunctions L ∧ q = affinePerm f h}

/-- Ordered pairs of points, the domain of orbitals. -/
abbrev OrderedPointPair (A B : Type*) := (A × B) × (A × B)

/-- The orbital of an ordered pair under `G_L`. -/
def orbital (L : AddSubgroup B) (p : OrderedPointPair A B) :
    Set (OrderedPointPair A B) :=
  {q | ∃ f h, f ∈ invariantFunctions L ∧
    q = ((affinePerm f h) p.1, (affinePerm f h) p.2)}

/-- The set of orbitals of the action. -/
def orbitals (L : AddSubgroup B) : Set (Set (OrderedPointPair A B)) :=
  {O | ∃ p, O = orbital L p}

/-- The listed orbital with displacement `(t,d)` when `t ∈ L`. -/
def orbitalTD (t : B) (d : A) : Set (OrderedPointPair A B) :=
  {q | ∃ (a : A) (x : B), q = ((a, x), (a + d, x + t))}

/-- The listed orbital with displacement `t` when `t ∉ L`. -/
def orbitalT (t : B) : Set (OrderedPointPair A B) :=
  {q | ∃ (a a' : A) (x : B), q = ((a, x), (a', x + t))}

/-- The standard translations `C_A ⋊ B`, generated by constant functions. -/
def standardTranslationPermutations : Set (Equiv.Perm (A × B)) :=
  {q | ∃ c h, q = affinePerm (fun _ : B => c) h}

def standardTranslationSubgroup : Subgroup (Equiv.Perm (A × B)) :=
  Subgroup.closure standardTranslationPermutations

/--
Claim 58190: the displayed relations are precisely all orbitals of `G_L`.
The accompanying definitions make the final identification
`R = C_A ⋊ B` explicit.
-/
def claim58190 (L : AddSubgroup B) : Prop :=
  (∀ t : B, t ∈ L → ∀ d : A,
      orbital L (((0 : A), (0 : B)), (d, t)) = orbitalTD t d) ∧
    (∀ t : B, t ∉ L →
      orbital L (((0 : A), (0 : B)), ((0 : A), t)) = orbitalT t) ∧
    (∀ O : Set (OrderedPointPair A B), O ∈ orbitals L →
      ((∃ t : B, t ∈ L ∧ ∃ d : A, O = orbitalTD t d) ∨
        (∃ t : B, t ∉ L ∧ O = orbitalT t)))

/-- Preservation of one orbital by a permutation of the point set. -/
def preservesOrbital (q : Equiv.Perm (A × B))
    (O : Set (OrderedPointPair A B)) : Prop :=
  ∀ p, p ∈ O ↔ (q p.1, q p.2) ∈ O

/-- The 2-closure of `G_L`, as permutations preserving every orbital. -/
def twoClosure (L : AddSubgroup B) : Set (Equiv.Perm (A × B)) :=
  {q | ∀ O, O ∈ orbitals L → preservesOrbital q O}

/--
Claim 58191: orbital preservation forces the displayed affine form, the
translation labels force `ψ(x+t)-ψ(x)=t`, and exact `L` labels force
`u ∈ M_L`; equivalently the branch is 2-closed.
-/
def claim58191 (L : AddSubgroup B) : Prop :=
  (∀ q : Equiv.Perm (A × B), q ∈ twoClosure (A := A) (B := B) L →
    ∃ u : B → A, ∃ ψ : Equiv.Perm B,
      (∀ (a : A) (x : B), q (a, x) = (a + u x, ψ x)) ∧
        (∀ (x t : B), ψ (x + t) - ψ x = t) ∧
        (∃ c : B, ∀ x, ψ x = x + c) ∧
        u ∈ invariantFunctions L) ∧
    twoClosure (A := A) (B := B) L = affineGroup (A := A) (B := B) L

end AffineOrbitals

end MathlibPlus.Open.ResearchFormalization
