import Mathlib

namespace MathlibPlus.Open.ResearchFormalization

/-- A partition-like family of nonempty subsets of `Ω`. -/
def IsBlockSystem {Ω : Type*} (blocks : Set (Set Ω)) : Prop :=
  (∀ B ∈ blocks, B.Nonempty) ∧
    (∀ B₁ ∈ blocks, ∀ B₂ ∈ blocks, B₁ ≠ B₂ → Disjoint B₁ B₂) ∧
    ⋃₀ blocks = Set.univ

/-- The subgroup `G` permutes the blocks of a block system. -/
def PreservesBlockSystem {Ω : Type*}
    (G : Subgroup (Equiv.Perm Ω)) (blocks : Set (Set Ω)) : Prop :=
  ∀ g : Equiv.Perm Ω, g ∈ G → ∀ B : Set Ω, B ∈ blocks → g '' B ∈ blocks

/-- The orbit of a point under a permutation subgroup. -/
def subgroupOrbit {Ω : Type*} (A : Subgroup (Equiv.Perm Ω)) (x : Ω) : Set Ω :=
  {y | ∃ a : Equiv.Perm Ω, a ∈ A ∧ a x = y}

/-- A subgroup is cyclic of the stated finite order, with a named generator. -/
def CyclicPermutationSubgroupOfOrder {Ω : Type*}
    (A : Subgroup (Equiv.Perm Ω)) (m : ℕ) : Prop :=
  ∃ a : Equiv.Perm Ω, a ∈ A ∧ orderOf a = m ∧
    Subgroup.closure ({a} : Set (Equiv.Perm Ω)) = A

/-- The members of `blocks` are exactly the orbits of `A`. -/
def HasBlockOrbits {Ω : Type*}
    (A : Subgroup (Equiv.Perm Ω)) (blocks : Set (Set Ω)) : Prop :=
  ∀ B : Set Ω, B ∈ blocks ↔ ∃ x : Ω, subgroupOrbit A x = B

def conjugateElement {Ω : Type*} (g a : Equiv.Perm Ω) : Equiv.Perm Ω :=
  g * a * g⁻¹

/-- Every element of every `G`-conjugate of either subgroup fixes every block. -/
def ConjugatesFixBlocks {Ω : Type*}
    (G : Subgroup (Equiv.Perm Ω)) (blocks : Set (Set Ω))
    (A : Fin 2 → Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ i : Fin 2, ∀ g : Equiv.Perm Ω, g ∈ G →
    ∀ B : Set Ω, B ∈ blocks →
      ∀ a : Equiv.Perm Ω, a ∈ A i → conjugateElement g a '' B = B

/-- The subgroup generated by all conjugates of the two given subgroups. -/
def normalClosureOfConjugates {Ω : Type*}
    (G : Subgroup (Equiv.Perm Ω))
    (A : Fin 2 → Subgroup (Equiv.Perm Ω)) : Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure
    {h : Equiv.Perm Ω |
      ∃ i : Fin 2, ∃ g : Equiv.Perm Ω, g ∈ G ∧
        ∃ a : Equiv.Perm Ω, a ∈ A i ∧ h = conjugateElement g a}

def blockKernel {Ω : Type*}
    (G : Subgroup (Equiv.Perm Ω)) (blocks : Set (Set Ω)) : Set (Equiv.Perm Ω) :=
  {g | g ∈ G ∧ ∀ B : Set Ω, B ∈ blocks → g '' B = B}

/-- The admitted block-system normal-closure claim. -/
def claim40940 : Prop :=
  ∀ (Ω : Type*) (G : Subgroup (Equiv.Perm Ω)) (blocks : Set (Set Ω))
    (m : ℕ) (A : Fin 2 → Subgroup (Equiv.Perm Ω)),
    IsBlockSystem blocks →
    PreservesBlockSystem G blocks →
    (∀ i : Fin 2,
      A i ≤ G ∧
      CyclicPermutationSubgroupOfOrder (A i) m ∧
      HasBlockOrbits (A i) blocks) →
    ConjugatesFixBlocks G blocks A ∧
      (∀ h : Equiv.Perm Ω,
        h ∈ normalClosureOfConjugates G A → h ∈ blockKernel G blocks)

/-- The regularity condition for a permutation subgroup. -/
def IsRegularPermutationSubgroup {Ω : Type*}
    (H : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ x y : Ω, ∃! h : Equiv.Perm Ω, h ∈ H ∧ h x = y

def standardCycle35 : Equiv.Perm (ZMod 35) := Equiv.addRight 1

def transposition01 : Equiv.Perm (ZMod 35) := Equiv.swap 0 1

def conjugateCycle35 : Equiv.Perm (ZMod 35) :=
  transposition01 * standardCycle35 * transposition01⁻¹

def translationSubgroup35 : Subgroup (Equiv.Perm (ZMod 35)) :=
  Subgroup.closure ({standardCycle35} : Set (Equiv.Perm (ZMod 35)))

def standardHolomorph35 : Subgroup (Equiv.Perm (ZMod 35)) :=
  Subgroup.normalizer (translationSubgroup35 : Set (Equiv.Perm (ZMod 35)))

def conjugateSubgroup35 : Subgroup (Equiv.Perm (ZMod 35)) :=
  Subgroup.closure ({conjugateCycle35} : Set (Equiv.Perm (ZMod 35)))

def commutator35 : Equiv.Perm (ZMod 35) :=
  conjugateCycle35 * standardCycle35 * conjugateCycle35⁻¹ * standardCycle35⁻¹

/-- The admitted conjugate-cycle and commutator claim. -/
def claim40946 : Prop :=
  IsRegularPermutationSubgroup translationSubgroup35 ∧
    IsRegularPermutationSubgroup conjugateSubgroup35 ∧
    CyclicPermutationSubgroupOfOrder conjugateSubgroup35 35 ∧
    conjugateSubgroup35 ≠ translationSubgroup35 ∧
    conjugateCycle35 ∉ standardHolomorph35 ∧
    orderOf commutator35 = 3 ∧
    (Equiv.Perm.support commutator35).card = 3

end MathlibPlus.Open.ResearchFormalization
