import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.BatchR1267

abbrev Perm (Ω : Type*) := Equiv.Perm Ω

def regularPermutationSubgroup {Ω : Type*} [Fintype Ω]
    (R : Subgroup (Perm Ω)) : Prop :=
  ∀ x y : Ω, ∃! r : R, (r : Perm Ω) x = y

def semiregularPermutationSubgroup {Ω : Type*}
    (U : Subgroup (Perm Ω)) : Prop :=
  ∀ u : U, u ≠ 1 → ∀ x : Ω, (u : Perm Ω) x ≠ x

def abelianPermutationSubgroup {Ω : Type*}
    (U : Subgroup (Perm Ω)) : Prop :=
  ∀ u v : U, (u : Perm Ω) * (v : Perm Ω) =
    (v : Perm Ω) * (u : Perm Ω)

def orbitOf {Ω : Type*}
    (U : Subgroup (Perm Ω)) (x : Ω) : Set Ω :=
  {y | ∃ u : U, (u : Perm Ω) x = y}

def orbitPartition {Ω : Type*}
    (U : Subgroup (Perm Ω)) : Set (Set Ω) :=
  {B | ∃ x : Ω, B = orbitOf U x}

def centralInvolution {Ω : Type*}
    (R : Subgroup (Perm Ω)) (z : Perm Ω) : Prop :=
  z ∈ R ∧ orderOf z = 2 ∧
    ∀ g : R, z * (g : Perm Ω) = (g : Perm Ω) * z

def centralizesSubgroup {Ω : Type*}
    (U : Subgroup (Perm Ω)) (k : Perm Ω) : Prop :=
  ∀ u : U, k * (u : Perm Ω) = (u : Perm Ω) * k

def fixesOrbitPartition {Ω : Type*}
    (U : Subgroup (Perm Ω)) (k : Perm Ω) : Prop :=
  ∀ B : Set Ω, B ∈ orbitPartition U → k '' B = B

def sameOrbitQuotientAction {Ω : Type*}
    (U : Subgroup (Perm Ω)) (zR zT : Perm Ω) : Prop :=
  ∀ B : Set Ω, B ∈ orbitPartition U → zR '' B = zT '' B

def generatedPermutationGroup {Ω : Type*}
    (R T : Subgroup (Perm Ω)) : Subgroup (Perm Ω) :=
  Subgroup.closure ((R : Set (Perm Ω)) ∪ (T : Set (Perm Ω)))

def conjugatedTarget {Ω : Type*}
    (T : Subgroup (Perm Ω)) (k : Perm Ω) : Set (Perm Ω) :=
  {p | ∃ t : T, p = k⁻¹ * (t : Perm Ω) * k}

def literalUContainedAfterConjugation {Ω : Type*}
    (U T : Subgroup (Perm Ω)) (k : Perm Ω) : Prop :=
  ∀ u : U, (u : Perm Ω) ∈ conjugatedTarget T k

def quotientActionsUnchanged {Ω : Type*}
    (U R T : Subgroup (Perm Ω)) (k : Perm Ω) : Prop :=
  (∀ r : R, ∀ B : Set Ω, B ∈ orbitPartition U →
    (r : Perm Ω) '' B = (r : Perm Ω) '' B) ∧
  (∀ t : T, ∀ B : Set Ω, B ∈ orbitPartition U →
    (k⁻¹ * (t : Perm Ω) * k) '' B = (t : Perm Ω) '' B)

/-- Claim 30811: an odd semiregular literal abelian subgroup synchronizes
central involutions of two regular permutation copies by an orbit-fixing
half-rotation, without changing the literal subgroup or quotient actions. -/
def claim30811 {Ω : Type*} [Fintype Ω]
    (U R T : Subgroup (Perm Ω)) (zR zT : Perm Ω) : Prop :=
  (abelianPermutationSubgroup U ∧
    Odd (Nat.card U) ∧
    semiregularPermutationSubgroup U ∧
    regularPermutationSubgroup R ∧
    regularPermutationSubgroup T ∧
    U ≤ R ∧ U ≤ T ∧
    centralInvolution R zR ∧
    centralInvolution T zT ∧
    sameOrbitQuotientAction U zR zT) →
    ∃ k : Perm Ω,
      k ∈ Subgroup.closure ({zR, zT} : Set (Perm Ω)) ∧
      Subgroup.closure ({zR, zT} : Set (Perm Ω)) ≤
        generatedPermutationGroup R T ∧
      k⁻¹ * zT * k = zR ∧
      centralizesSubgroup U k ∧
      fixesOrbitPartition U k ∧
      literalUContainedAfterConjugation U T k ∧
      quotientActionsUnchanged U R T k

/-- The induced copy of `U` in the symmetric group on an orbit `B`, stated
by its exact restriction carrier rather than by a canonical action on `U`. -/
def inducedOrbitAction {Ω : Type*}
    (U : Subgroup (Perm Ω)) (B : Set Ω)
    (A : Subgroup (Perm B)) : Prop :=
  ∀ p : Perm B, p ∈ A ↔
    ∃ u : U, ∀ b : B, (p b : Ω) = (u : Perm Ω) b

/-- The right/opposite regular action on the same orbit carrier, relative to a
basepoint `b₀`. -/
def oppositeOrbitAction {Ω : Type*}
    (U : Subgroup (Perm Ω)) (B : Set Ω)
    (O : Subgroup (Perm B)) (b₀ : B) : Prop :=
  ∀ p : Perm B, p ∈ O ↔
    ∃ v : U, ∀ u : U, ∀ hu : (u : Perm Ω) (b₀ : Ω) ∈ B,
      (p ⟨(u : Perm Ω) (b₀ : Ω), hu⟩ : Ω) =
        ((u * v : U) : Perm Ω) (b₀ : Ω)

/-- Claim 30812: on every literal `U`-orbit, the exact restricted action is
regular and its full symmetric-group centralizer is the opposite regular
action, hence another copy of `U`. -/
def claim30812 {Ω : Type*} [Fintype Ω]
    (U : Subgroup (Perm Ω)) : Prop :=
  (abelianPermutationSubgroup U ∧
    Odd (Nat.card U) ∧
    semiregularPermutationSubgroup U) →
    ∀ B : Set Ω, B ∈ orbitPartition U →
      ∀ A O : Subgroup (Perm B), ∀ b₀ : B,
        inducedOrbitAction U B A →
        oppositeOrbitAction U B O b₀ →
          (∀ b c : B, ∃! a : A, (a : Perm B) b = c) ∧
          Subgroup.centralizer A = O ∧
          Nonempty (O ≃* U)

/-- The normal-form description of a dihedral subgroup generated by two
involutions, with the displayed rotation as its rotation. -/
def dihedralWithRotation {Ω : Type*}
    (zR zT r : Perm Ω) : Prop :=
  r = zR * zT ∧
    zR * r * zR = r⁻¹ ∧
    (∀ g : Subgroup.closure ({zR, zT} : Set (Perm Ω)),
      ∃ n : ℕ,
        (g : Perm Ω) = r ^ n ∨
          (g : Perm Ω) = zR * r ^ n) ∧
    (∀ n : ℕ,
      r ^ n ∈ Subgroup.closure ({zR, zT} : Set (Perm Ω)) ∧
        zR * r ^ n ∈ Subgroup.closure ({zR, zT} : Set (Perm Ω))) ∧
    Nat.card (Subgroup.closure ({zR, zT} : Set (Perm Ω))) =
      2 * orderOf r

/-- Claim 30814: the generated involution group has the stated dihedral
rotation, and for odd rotation order its explicit half-rotation aligns the
involutions while preserving the literal `U`-orbit quotient. -/
def claim30814 {Ω : Type*} [Fintype Ω]
    (U R T : Subgroup (Perm Ω)) (zR zT : Perm Ω) : Prop :=
  (abelianPermutationSubgroup U ∧
    Odd (Nat.card U) ∧
    semiregularPermutationSubgroup U ∧
    regularPermutationSubgroup R ∧
    regularPermutationSubgroup T ∧
    U ≤ R ∧ U ≤ T ∧
    centralInvolution R zR ∧
    centralInvolution T zT ∧
    sameOrbitQuotientAction U zR zT) →
    let r : Perm Ω := zR * zT
    let d : ℕ := orderOf r
    dihedralWithRotation zR zT r ∧
      (centralizesSubgroup U r ∧ fixesOrbitPartition U r ∧ Odd d →
        let k : Perm Ω := r ^ ((d - 1) / 2)
        k ∈ Subgroup.closure ({zR, zT} : Set (Perm Ω)) ∧
          k⁻¹ * zT * k = zR ∧
          centralizesSubgroup U k ∧
          fixesOrbitPartition U k)

end MathlibPlus.Open.ResearchFormalization.BatchR1267
