import Mathlib
import MathlibPlus.Open.ResearchFormalization.AdmittedBatch_01a000eb525ca7c34f4fffd55f6717fb0

namespace MathlibPlus.Open.ResearchFormalization.BatchR1075Claims

attribute [local instance] Classical.propDecidable Classical.decEq

noncomputable section

abbrev B := ZMod 3 × ZMod 3

private def displacementSpan (p : Equiv.Perm B) : AddSubgroup B :=
  AddSubgroup.closure (Set.range (fun t : B => t - p t + p 0))

private def firstCoordinateLine : AddSubgroup B :=
  (⊤ : AddSubgroup (ZMod 3)).prod (⊥ : AddSubgroup (ZMod 3))

private def secondCoordinateLine : AddSubgroup B :=
  (⊥ : AddSubgroup (ZMod 3)).prod (⊤ : AddSubgroup (ZMod 3))

private def diagonalLine : AddSubgroup B :=
  AddSubgroup.closure ({((1 : ZMod 3), (1 : ZMod 3))} : Set B)

private def antidiagonalLine : AddSubgroup B :=
  AddSubgroup.closure ({((1 : ZMod 3), (2 : ZMod 3))} : Set B)

private def isSpecifiedNonzeroLine (L : AddSubgroup B) : Prop :=
  L = firstCoordinateLine ∨
    L = secondCoordinateLine ∨
    L = diagonalLine ∨
    L = antidiagonalLine

private def reflection : Equiv.Perm B :=
  Equiv.prodCongr (Equiv.neg (ZMod 3)) (Equiv.refl (ZMod 3))

private def actionOrbit
    (Γ : Subgroup (Equiv.Perm B)) (x : B) : Set B :=
  {y | ∃ g : Equiv.Perm B, g ∈ Γ ∧ g x = y}

private def orbitBlocks (Γ : Subgroup (Equiv.Perm B)) : Set (Set B) :=
  {S | ∃ x : B, S = actionOrbit Γ x}

private def firstCoordinateZeroBlock : Set B :=
  {v : B | v.1 = 0}

private def firstCoordinateNonzeroBlock : Set B :=
  {v : B | v.1 = 1 ∨ v.1 = 2}

private def inversePairBlocks : Set (Set B) :=
  {S | ∃ x : B, x ≠ 0 ∧ S = {x, -x}}

private def spanThree
    (q r : Equiv.Perm B) (L : AddSubgroup B) : Prop :=
  displacementSpan q ⊔ displacementSpan r ⊔ L = ⊤

private def transitiveAction
    (Γ : Subgroup (Equiv.Perm B)) : Prop :=
  ∀ x : B, actionOrbit Γ x = Set.univ

private def translationsPreserveFirstCoordinate
    (L : AddSubgroup B) : Prop :=
  ∀ ell : L, ∀ x : B,
    (Equiv.addRight (ell : B) x).1 = x.1

/-- Claim 28647: the exact displacement-span census over all permutations of
`F₃²`, including each of the four specified nonzero line spans. -/
def claim28647_displacementSpanCensus : Prop :=
  Fintype.card (Equiv.Perm B) = Nat.factorial 9 ∧
    (Finset.univ.filter (fun p : Equiv.Perm B =>
      displacementSpan p = ⊥)).card = 9 ∧
    (∀ L : AddSubgroup B, isSpecifiedNonzeroLine L →
      (Finset.univ.filter (fun p : Equiv.Perm B =>
        displacementSpan p = L)).card = 639) ∧
    (Finset.univ.filter (fun p : Equiv.Perm B =>
      displacementSpan p = ⊤)).card = 360315

/-- Claim 28649: the all-proper reflection witness has full joint displacement
span, both cross-derivative families equal to the reflection, and two
nontransitive Gamma orbits of sizes three and six. -/
def claim28649_allProperReflectionCounterexample : Prop :=
  let q := reflection
  let r := reflection
  let L := secondCoordinateLine
  let Γ := translatedCollisionAction B q r L
  displacementSpan q = firstCoordinateLine ∧
    displacementSpan r = firstCoordinateLine ∧
    firstCoordinateLine ≠ (⊤ : AddSubgroup B) ∧
    secondCoordinateLine ≠ (⊤ : AddSubgroup B) ∧
    spanThree q r L ∧
    (∀ t : B,
      crossDerivativeFirstGenerator B q r t = reflection ∧
        crossDerivativeSecondGenerator B q r t = reflection) ∧
    translationsPreserveFirstCoordinate L ∧
    orbitBlocks Γ =
      {firstCoordinateZeroBlock, firstCoordinateNonzeroBlock} ∧
    Set.ncard firstCoordinateZeroBlock = 3 ∧
    Set.ncard firstCoordinateNonzeroBlock = 6 ∧
    ¬ transitiveAction Γ

/-- Claim 28650: the central-inversion witness has full displacement spans,
all cross derivatives equal to negation, Gamma generated by negation, and one
singleton orbit together with the four inverse-pair orbits. -/
def claim28650_mixedCentralInversionCounterexample : Prop :=
  let q := Equiv.neg B
  let r := Equiv.neg B
  let L := (⊥ : AddSubgroup B)
  let negation := Equiv.neg B
  let Γ := translatedCollisionAction B q r L
  (∀ x : B, (3 : ℕ) • x = 0) ∧
    displacementSpan q = (⊤ : AddSubgroup B) ∧
    displacementSpan r = (⊤ : AddSubgroup B) ∧
    (∀ t : B,
      crossDerivativeFirstGenerator B q r t = negation ∧
        crossDerivativeSecondGenerator B q r t = negation) ∧
    Γ = Subgroup.closure ({negation} : Set (Equiv.Perm B)) ∧
    actionOrbit Γ 0 = ({0} : Set B) ∧
    orbitBlocks Γ =
      ({({0} : Set B)} : Set (Set B)) ∪ inversePairBlocks ∧
    Set.ncard ({0} : Set B) = 1 ∧
    (∀ x : B, x ≠ 0 →
      actionOrbit Γ x = {x, -x} ∧
        Set.ncard (actionOrbit Γ x) = 2) ∧
    Set.ncard inversePairBlocks = 4 ∧
    ¬ transitiveAction Γ

/-- Claim 28645: the joint displacement-span implication is false, with both
explicit symbolic counterexamples retained. -/
def claim28645_fullJointDisplacementDoesNotImplyTransitivity : Prop :=
  (¬ ∀ (q r : Equiv.Perm B) (L : AddSubgroup B),
      spanThree q r L →
        transitiveAction (translatedCollisionAction B q r L)) ∧
    claim28649_allProperReflectionCounterexample ∧
    claim28650_mixedCentralInversionCounterexample

end

end MathlibPlus.Open.ResearchFormalization.BatchR1075Claims
