import Mathlib

namespace MathlibPlus
namespace Open
namespace ResearchFormalizationBatch01

/-- The finite-field data and sign condition in the triangular-switch setup. -/
structure TriangularSwitchData (A W : Type*)
    [AddCommGroup A] [AddCommGroup W]
    [Module (ZMod 3) A] [Module (ZMod 3) W]
    [FiniteDimensional (ZMod 3) A]
    [FiniteDimensional (ZMod 3) W] where
  phi : A → W
  map_zero : phi 0 = 0
  map_neg : ∀ a : A, phi (-a) = -phi a

/-- The derivative span `H_a` from the triangular-switch packet. -/
def derivativeSpan {A W : Type*}
    [AddCommGroup A] [AddCommGroup W]
    [Module (ZMod 3) A] [Module (ZMod 3) W]
    [FiniteDimensional (ZMod 3) A]
    [FiniteDimensional (ZMod 3) W]
    (D : TriangularSwitchData A W) (a : A) : Submodule (ZMod 3) W :=
  Submodule.span (ZMod 3)
    (Set.range fun x : A => D.phi (x + a) - D.phi x - D.phi a)

/-- The triangular switch `f(a,w)=(a,w+phi(a))`. -/
def triangularSwitch {A W : Type*}
    [AddCommGroup A] [AddCommGroup W]
    [Module (ZMod 3) A] [Module (ZMod 3) W]
    [FiniteDimensional (ZMod 3) A]
    [FiniteDimensional (ZMod 3) W]
    (D : TriangularSwitchData A W) :
    A × W → A × W :=
  fun p => (p.1, p.2 + D.phi p.1)

/-- The connection-set slice `S_a`. -/
def connectionSlice {A W : Type*}
    [AddCommGroup A] [AddCommGroup W] (S : Set (A × W)) (a : A) : Set W :=
  {w | (a, w) ∈ S}

/-- Projective one-spaces used in the group-algebra formulations. -/
abbrev ProjectiveLine (K B : Type*)
    [DivisionRing K] [AddCommGroup B] [Module K B] :=
  {L : Submodule K B // Module.finrank K L = 1}

/-- The coefficient projection of an additive group algebra. -/
noncomputable def coefficientLinear (K B : Type*)
    [Field K] [AddCommGroup B] :
    AddMonoidAlgebra K B →ₗ[K] (B →₀ K) :=
  { toFun := fun r => r.coeff
    map_add' := by intro r s; rfl
    map_smul' := by intro c r; rfl }

/-- The first moment on the additive group algebra. -/
noncomputable def firstMoment (K B : Type*)
    [Field K] [AddCommGroup B] [Module K B] :
    AddMonoidAlgebra K B →ₗ[K] B :=
  (Finsupp.lsum K (fun b : B => LinearMap.toSpanSingleton K B b)).comp
    (coefficientLinear K B)

/-- The tensor first-moment map `v⊗τ_x ↦ v⊗x`. -/
noncomputable def firstMomentMap (K V B : Type*)
    [Field K] [AddCommGroup B] [AddCommMonoid V]
    [Module K B] [Module K V] :
    TensorProduct K V (AddMonoidAlgebra K B) →ₗ[K] TensorProduct K V B :=
  TensorProduct.map (LinearMap.id) (firstMoment K B)

/-- The augmentation ideal of the additive group algebra. -/
noncomputable def augmentationIdeal (K B : Type*)
    [Field K] [AddCommGroup B] :
    Submodule K (AddMonoidAlgebra K B) :=
  (AddMonoidAlgebra.lift K K B
      ({ toFun := fun _ : Multiplicative B => (1 : K)
         map_one' := rfl
         map_mul' := by intro x y; simp } : Multiplicative B →* K)).toLinearMap.ker

/-- The ideal `(tau_d-1)R` generated by one nonzero line translation. -/
noncomputable def lineTranslationIdeal (K B : Type*)
    [Field K] [AddCommGroup B] (d : B) :
    Submodule K (AddMonoidAlgebra K B) :=
  Submodule.span K (Set.range (fun r : AddMonoidAlgebra K B =>
    (AddMonoidAlgebra.single d (1 : K) - (1 : AddMonoidAlgebra K B)) * r))

/-- The augmentation ideal of a line, extended to the full group algebra. -/
noncomputable def extendedLineAugmentationIdeal (K B : Type*)
    [Field K] [AddCommGroup B] [Module K B]
    (L : ProjectiveLine K B) :
    Submodule K (AddMonoidAlgebra K B) :=
  Submodule.span K
    {t | ∃ l : (L : Submodule K B), ∃ r : AddMonoidAlgebra K B,
      t = (AddMonoidAlgebra.single (l : B) (1 : K) -
        (1 : AddMonoidAlgebra K B)) * r}

/-- The submodule generated by pure tensors from two subspaces. -/
noncomputable def tensorSubmodule (K V B : Type*)
    [Field K] [AddCommGroup B] [AddCommMonoid V]
    [Module K B] [Module K V]
    (U : Submodule K V) (J : Submodule K (AddMonoidAlgebra K B)) :
    Submodule K (TensorProduct K V (AddMonoidAlgebra K B)) :=
  Submodule.span K
    {t | ∃ v r, v ∈ U ∧ r ∈ J ∧ t = TensorProduct.tmul K v r}

/-- The sum of the line-fibre tensor submodules. -/
noncomputable def lineTensorSum (K V B : Type*)
    [Field K] [AddCommGroup B] [AddCommMonoid V]
    [Module K B] [Module K V]
    (U : ProjectiveLine K B → Submodule K V)
    (d : ∀ L : ProjectiveLine K B, ↥(L : Submodule K B)) :
    Submodule K (TensorProduct K V (AddMonoidAlgebra K B)) :=
  ⨆ L, tensorSubmodule K V B (U L)
    (lineTranslationIdeal K B (d L : B))

/-- The sum of the line-fibre tensor submodules using extended line ideals. -/
noncomputable def extendedLineTensorSum (K V B : Type*)
    [Field K] [AddCommGroup B] [AddCommMonoid V]
    [Module K B] [Module K V]
    (U : ProjectiveLine K B → Submodule K V) :
    Submodule K (TensorProduct K V (AddMonoidAlgebra K B)) :=
  ⨆ L, tensorSubmodule K V B (U L)
    (extendedLineAugmentationIdeal K B L)

/-- Right multiplication on the group-algebra tensor factor. -/
noncomputable def tensorRightMultiply (K V B : Type*)
    [Field K] [AddCommGroup B] [AddCommMonoid V]
    [Module K B] [Module K V] (a : AddMonoidAlgebra K B) :
    TensorProduct K V (AddMonoidAlgebra K B) →ₗ[K]
      TensorProduct K V (AddMonoidAlgebra K B) :=
  TensorProduct.map (LinearMap.id)
    ((LinearMap.mul K (AddMonoidAlgebra K B)) a)

/-- The submodule product `I C` for the right group-algebra action. -/
noncomputable def idealTimesTensor (K V B : Type*)
    [Field K] [AddCommGroup B] [AddCommMonoid V]
    [Module K B] [Module K V]
    (I : Submodule K (AddMonoidAlgebra K B))
    (C : Submodule K (TensorProduct K V (AddMonoidAlgebra K B))) :
    Submodule K (TensorProduct K V (AddMonoidAlgebra K B)) :=
  Submodule.span K
    {t | ∃ i c, i ∈ I ∧ c ∈ C ∧
      t = tensorRightMultiply K V B i c}

/-- Two-dimensional fibres have the exact first-moment kernel stated in Claim 54745. -/
def FirstMomentKernelExactness : Prop :=
  ∀ (p : ℕ) (hp : Nat.Prime p) (_hodd : Odd p),
    letI : Fact (Nat.Prime p) := ⟨hp⟩
    ∀ (B V : Type*)
      [AddCommGroup B] [AddCommGroup V]
      [Module (ZMod p) B] [Module (ZMod p) V]
      [FiniteDimensional (ZMod p) B]
      [FiniteDimensional (ZMod p) V]
      (_hVdim : Module.finrank (ZMod p) V ≤ 2),
      ∀ (U : ProjectiveLine (ZMod p) B → Submodule (ZMod p) V),
        let C := extendedLineTensorSum (ZMod p) V B U
        C ⊓ (firstMomentMap (ZMod p) V B).ker =
          idealTimesTensor (ZMod p) V B
            (augmentationIdeal (ZMod p) B) C

/-- Rank-two base spaces have the exact translation-code kernel in Claim 54789. -/
def RankTwoProjectiveTranslationCodeKernelIdentity : Prop :=
  ∀ (p : ℕ) (hp : Nat.Prime p) (_hodd : Odd p),
    letI : Fact (Nat.Prime p) := ⟨hp⟩
    ∀ (B V : Type*)
      [AddCommGroup B] [AddCommGroup V]
      [Module (ZMod p) B] [Module (ZMod p) V]
      [FiniteDimensional (ZMod p) B]
      [FiniteDimensional (ZMod p) V]
      (_hBdim : Module.finrank (ZMod p) B = 2),
      ∀ (U : ProjectiveLine (ZMod p) B → Submodule (ZMod p) V),
        ∀ (d : ∀ L : ProjectiveLine (ZMod p) B, ↥(L : Submodule (ZMod p) B)),
          (∀ L, (d L : B) ≠ 0) →
          let C := lineTensorSum (ZMod p) V B U d
          C ⊓ (firstMomentMap (ZMod p) V B).ker =
            idealTimesTensor (ZMod p) V B
              (augmentationIdeal (ZMod p) B) C

end ResearchFormalizationBatch01
end Open
end MathlibPlus
