import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.CIBinaryTimesC9Claim61114

noncomputable section

/-- Conjugation of a permutation set by a displayed permutation. -/
def conjugateSetGeneric {Ω : Type*} (q : Equiv.Perm Ω)
    (K : Set (Equiv.Perm Ω)) : Set (Equiv.Perm Ω) :=
  Set.image (fun h => q⁻¹ * h * q) K

/-- Membership in the ordered two-closure, expressed by preservation of every
ordered orbital. -/
def orderedTwoClosure {Ω : Type*}
    (K : Set (Equiv.Perm Ω)) : Set (Equiv.Perm Ω) :=
  {q | ∀ x y : Ω,
    ∃ k : Equiv.Perm Ω, k ∈ K ∧ q x = k x ∧ q y = k y}

/-- The unordered two-closure, represented by preservation of every orbit of
unordered two-point sets. -/
def unorderedTwoClosure {Ω : Type*} [DecidableEq Ω]
    (K : Set (Equiv.Perm Ω)) : Set (Equiv.Perm Ω) :=
  {q | ∀ x y : Ω,
    ∃ k : Equiv.Perm Ω, k ∈ K ∧
      ({q x, q y} : Finset Ω) = {k x, k y}}

/-- The regular translation set on an additive space. -/
def regularTranslationSet {Ω : Type*} [AddGroup Ω] :
    Set (Equiv.Perm Ω) :=
  Set.range (Equiv.addRight : Ω → Equiv.Perm Ω)

/-- The regular translation subgroup on an additive finite space. -/
def regularTranslationGroup {Ω : Type*} [AddGroup Ω] :
    Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure (regularTranslationSet (Ω := Ω))

/-- The actual conjugacy conclusion for the regular translation group and the
conjugate subgroup generated by the displayed affine permutation. -/
def affineConjugacyInTwoClosures
    {V B : Type*} [AddCommGroup V] [AddCommGroup B]
    [Module (ZMod 2) V]
    [Fintype V] [Fintype B] [DecidableEq V] [DecidableEq B]
    (q : Equiv.Perm (V × B)) : Prop :=
  let R : Subgroup (Equiv.Perm (V × B)) :=
    regularTranslationGroup (Ω := V × B)
  let T : Set (Equiv.Perm (V × B)) :=
    conjugateSetGeneric q (R : Set (Equiv.Perm (V × B)))
  let Y : Subgroup (Equiv.Perm (V × B)) :=
    Subgroup.closure ((R : Set (Equiv.Perm (V × B))) ∪ T)
  ∃ c : Equiv.Perm (V × B),
    c ∈ orderedTwoClosure (Y : Set (Equiv.Perm (V × B))) ∧
      c ∈ unorderedTwoClosure (Y : Set (Equiv.Perm (V × B))) ∧
        conjugateSetGeneric c (R : Set (Equiv.Perm (V × B))) = T

/-- The block-dependent affine presentation in the claim. -/
def affineBlockForm
    {V B : Type*} [AddCommGroup V] [AddCommGroup B]
    [Module (ZMod 2) V]
    (A : B → (V ≃ₗ[ZMod 2] V)) (F : B → V)
    (q : Equiv.Perm (V × B)) : Prop :=
  ∀ v : V, ∀ b : B,
    q (v, b) = ((A b) v + F b, b)

/-- Membership in the pointwise image of the linear displacement map. -/
def displacementImageCondition
    {V B : Type*} [AddCommGroup V] [AddCommGroup B]
    [Module (ZMod 2) V]
    (A : B → (V ≃ₗ[ZMod 2] V)) (F L : B → V) (b : B) : Prop :=
  ∃ a : V, (A b) a - a = F b - L b

/-- Claim 61114: a carry congruent to a group homomorphism modulo each
block's linear displacement image yields conjugacy of the actual regular and
conjugate translation groups inside both two-closures, with the homomorphic
carry specialization in every dimension and for every finite abelian block
set. -/
def claim61114 : Prop :=
  ∀ (V B : Type*) [AddCommGroup V] [AddCommGroup B]
    [Module (ZMod 2) V]
    [FiniteDimensional (ZMod 2) V]
    [Fintype V] [Fintype B] [DecidableEq V] [DecidableEq B],
    ∀ (A : B → (V ≃ₗ[ZMod 2] V)),
      A 0 = LinearEquiv.refl (ZMod 2) V →
      ∀ (F : B → V) (q : Equiv.Perm (V × B)),
        affineBlockForm A F q →
          F 0 = 0 →
            ((∃ L : B →+ V,
                ∀ b : B, displacementImageCondition A F L b) →
                affineConjugacyInTwoClosures q) ∧
              ((∃ L : B →+ V, ∀ b : B, F b = L b) →
                affineConjugacyInTwoClosures q)

end
end MathlibPlus.Open.ResearchFormalization.CIBinaryTimesC9Claim61114
