import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.Claim61156

abbrev F2 := ZMod 2
abbrev V := Fin 2 → F2
abbrev E := Fin 2 → F2
abbrev Ω := V × E
abbrev FibreLinearPart := V ≃ₗ[F2] V

/-- The regular translation subgroup of the additive carrier `Ω`. -/
def translationGroup : Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure (Set.range (fun x : Ω => Equiv.addRight x))

/-- Conjugation of a subgroup with the convention `q⁻¹ R q`. -/
def conjugatedSubgroup (R : Subgroup (Equiv.Perm Ω))
    (q : Equiv.Perm Ω) : Subgroup (Equiv.Perm Ω) :=
  Subgroup.map (MulAut.conj q⁻¹).toMonoidHom R

/-- The subgroup generated by two permutation subgroups. -/
def generatedPair (R T : Subgroup (Equiv.Perm Ω)) :
    Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure ((R : Set (Equiv.Perm Ω)) ∪ (T : Set (Equiv.Perm Ω)))

/-- Membership in the ordered binary two-closure. -/
def orderedTwoClosure (H : Subgroup (Equiv.Perm Ω)) :
    Set (Equiv.Perm Ω) :=
  {c | ∀ x y : Ω, ∃ h : Equiv.Perm Ω,
    h ∈ H ∧ h x = c x ∧ h y = c y}

/-- Membership in the unordered binary two-closure. -/
def unorderedTwoClosure (H : Subgroup (Equiv.Perm Ω)) :
    Set (Equiv.Perm Ω) :=
  {c | ∀ x y : Ω, ∃ h : Equiv.Perm Ω,
    h ∈ H ∧ ((h x = c x ∧ h y = c y) ∨
      (h x = c y ∧ h y = c x))}

/-- The subgroup equality `T = c⁻¹ R c`, written without choosing a subgroup
image representation. -/
def conjugatesBy (c : Equiv.Perm Ω)
    (R T : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ t : Equiv.Perm Ω, t ∈ T ↔
    ∃ r : Equiv.Perm Ω, r ∈ R ∧ t = c⁻¹ * r * c

/-- Conjugacy of two permutation subgroups by an element of a set of
permutations. -/
def conjugateInSet (C : Set (Equiv.Perm Ω))
    (R T : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∃ c : Equiv.Perm Ω, c ∈ C ∧ conjugatesBy c R T

/-- The exact pointed block-fixing affine hypothesis on `q`. -/
def IsPointedBlockFixingAffine
    (q : Equiv.Perm Ω) (A : E → FibreLinearPart) (F : E → V) : Prop :=
  q (0, 0) = (0, 0) ∧ F 0 = 0 ∧
    ∀ v : V, ∀ b : E, q (v, b) = (A b v + F b, b)

/-- Claim 61156: every pointed block-fixing affine permutation on
`F₂² × F₂²`, with independently varying invertible fibre linear parts and
carries, conjugates the translation copy to the conjugate translation copy
inside the ordered and unordered two-closures of the generated pair. -/
def claim61156 : Prop :=
  ∀ (A : E → FibreLinearPart) (F : E → V) (q : Equiv.Perm Ω),
    IsPointedBlockFixingAffine q A F →
      let R := translationGroup
      let T := conjugatedSubgroup R q
      let Y := generatedPair R T
      conjugateInSet (orderedTwoClosure Y) R T ∧
        conjugateInSet (unorderedTwoClosure Y) R T

end MathlibPlus.Open.ResearchFormalization.Claim61156
