import MathlibPlus.Open.ResearchFormalization.R0634Claim23501

namespace MathlibPlus.Open.ResearchFormalization.Claim23507

open MathlibPlus.Open.ResearchFormalization

noncomputable section

/-- The scalar algebra carrier `A` from the conductor presentation. -/
abbrev ScalarA := scalarRootedFactorAlgebra

/-- The ideal type using the commutative-ring structure of `A`, so that its
cotangent module has the standard `Ideal.Cotangent` carrier. -/
abbrev ScalarAIdeal :=
  @Ideal ScalarA scalarRootedFactorAlgebra.toCommRing.toSemiring

/-- The conductor ideal `K` inside the scalar algebra. -/
def conductorIdealInScalarA : ScalarAIdeal :=
  Ideal.comap scalarRootedFactorAlgebra.val conductorIdeal

/-- The rational conductor point `m_c = K + (s-c)A`, as an ideal of `A`.
The set-level description of `s-c` avoids introducing a second model of the
scalar algebra while retaining its verified ambient representative. -/
def rationalConductorPoint (c : ℚ) : ScalarAIdeal :=
  Ideal.span ((conductorIdealInScalarA : Set ScalarA) ∪
    {x : ScalarA |
      (x : RootRing) = scalarS - algebraMap ℚ RootRing c})

/-- The cotangent space `m_c/m_c^2`. -/
abbrev rationalConductorCotangent (c : ℚ) :=
  Ideal.Cotangent (rationalConductorPoint c)

/-- The index set for the displayed direct sum: one index for `s-c`, followed
by one index for each `(k,a)` with `k ≥ 2` and `a ≥ 0`. -/
abbrev rationalConductorBasisIndex :=
  Option (triangularIndex × ℕ)

/-- Claim 23507: at every rational conductor point, the cotangent space is the
rational line generated by `s-c` together with the direct sum of the
`z^a ē_k` directions.  The representatives and their basis coordinates are
part of the statement, so this is not merely an equivalence of bare types. -/
def claim_23507 : Prop :=
  ∀ c : ℚ,
    ∃ basis : Module.Basis rationalConductorBasisIndex ℚ
        (rationalConductorCotangent c),
      (∃ x : rationalConductorPoint c,
        ((x : ScalarA) : RootRing) = scalarS - algebraMap ℚ RootRing c ∧
          basis none = Ideal.toCotangent (rationalConductorPoint c) x) ∧
      (∀ k : triangularIndex, ∀ a : ℕ,
        ∃ x : rationalConductorPoint c,
          ((x : ScalarA) : RootRing) =
            rootZ ^ a * triangularDifference k.1 ∧
            basis (some (k, a)) =
              Ideal.toCotangent (rationalConductorPoint c) x)

end
end MathlibPlus.Open.ResearchFormalization.Claim23507
