import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.Claim28869

abbrev Ternary := ZMod 3
abbrev Plane := Fin 2 → Ternary

def e₁ : Plane := fun i => if i = 0 then 1 else 0

def e₂ : Plane := fun i => if i = 1 then 1 else 0

def normalizedMap {V : Type*} [AddCommGroup V] [Module Ternary V]
    (g : Plane → V) : Prop :=
  (∀ x, g (-x) = -g x) ∧
    (∀ t : Ternary, g (t • e₁) = 0 ∧ g (t • e₂) = 0)

def normalizedDerivative {V : Type*} [AddCommGroup V] [Module Ternary V]
    (g : Plane → V) (a c x : Plane) : V :=
  (g (x + c + a) - g (x + c)) - (g (c + a) - g c)

def derivativeSpan {V : Type*} [AddCommGroup V] [Module Ternary V]
    (g : Plane → V) (x : Plane) : Submodule Ternary V :=
  Submodule.span Ternary
    (Set.range (fun p : Plane × Plane =>
      normalizedDerivative g p.1 p.2 x))

/-- Claim 28869: every nonzero base point of a normalized odd ternary map has
    the span generated by its two off-axis values, uniformly for every
    finite-dimensional ternary specialization. -/
def uniformDerivativeSpan_claim28869 : Prop :=
  ∀ (V : Type*) [AddCommGroup V] [Module Ternary V]
    [FiniteDimensional Ternary V],
    (∀ g : Plane → V, normalizedMap g →
      let A := g (e₁ + e₂)
      let B := g (e₁ - e₂)
      ∀ x : Plane, x ≠ 0 →
        derivativeSpan g x =
          Submodule.span Ternary ({A, B} : Set V)) ∧
    (∀ A B : V, ∃ g : Plane → V,
      normalizedMap g ∧
        g (e₁ + e₂) = A ∧
        g (e₁ - e₂) = B ∧
        ∀ x : Plane, x ≠ 0 →
          derivativeSpan g x =
            Submodule.span Ternary ({A, B} : Set V))

end MathlibPlus.Open.ResearchFormalization.Claim28869
