import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.Claim29203

/-- Automorphisms of a graph or digraph presented by its adjacency relation. -/
def automorphismSet {X : Type*} (Γ : X → X → Prop) : Set (Equiv.Perm X) :=
  {a | ∀ x y, Γ (a x) (a y) ↔ Γ x y}

/-- A permutation subgroup is regular when it contains exactly one transporter
between every ordered pair of points. -/
def regularSubgroup {X : Type*} (R : Subgroup (Equiv.Perm X)) : Prop :=
  ∀ x y : X, ∃! r : Equiv.Perm X, r ∈ R ∧ r x = y

abbrev binaryCayleyGroup (d : ℕ) (B : Type*) [AddCommGroup B] :=
  Multiplicative ((Fin d → ZMod 2) × B)

def quotientImage {X Q : Type*} (q : X → Q) (S : Set (Equiv.Perm X)) :
    Set (Equiv.Perm Q) :=
  {aq | ∃ a, a ∈ S ∧ ∀ x, aq (q x) = q (a x)}

/-- The kernel of the actual action on the fibres of the common block
quotient. -/
def quotientActionKernel {X Q : Type*} (q : X → Q)
    (A : Set (Equiv.Perm X)) : Set (Equiv.Perm X) :=
  {k | k ∈ A ∧ ∀ x, q (k x) = q x}

/-- A fixed-point-free permutation in the kernel swaps every two-point block,
with one common swap on all blocks. -/
def globalTwoPointSwap {X Q : Type*} (q : X → Q)
    (A : Set (Equiv.Perm X)) (δ : Equiv.Perm X) : Prop :=
  δ ∈ A ∧ δ * δ = 1 ∧
    (∀ x, q (δ x) = q x) ∧
    (∀ x, δ x ≠ x)

/-- Claim 29203: after quotient alignment, the two regular copies have the
same kernel intersection, and it is the subgroup generated by the common
global swap. -/
def claim29203 : Prop :=
  ∀ (d : ℕ) (B : Type*) [AddCommGroup B] [Fintype B]
    (Γ : binaryCayleyGroup d B → binaryCayleyGroup d B → Prop)
    (Q : Type*) [Fintype Q]
    (q : binaryCayleyGroup d B → Q)
    (R T : Subgroup (Equiv.Perm (binaryCayleyGroup d B))),
    0 < d →
    Odd (Fintype.card B) →
    (∀ g x y, Γ (g * x) (g * y) ↔ Γ x y) →
    Function.Surjective q →
    (∀ b : Q,
      Set.ncard {x : binaryCayleyGroup d B | q x = b} = 2) →
    (∀ a, a ∈ automorphismSet Γ →
      ∃ aq : Equiv.Perm Q, ∀ x, aq (q x) = q (a x)) →
    (∀ r : Equiv.Perm (binaryCayleyGroup d B),
      r ∈ R → r ∈ automorphismSet Γ) →
    (∀ t : Equiv.Perm (binaryCayleyGroup d B),
      t ∈ T → t ∈ automorphismSet Γ) →
    regularSubgroup R →
    regularSubgroup T →
    Nonempty (R ≃* binaryCayleyGroup d B) →
    Nonempty (T ≃* binaryCayleyGroup d B) →
    quotientImage q (R : Set (Equiv.Perm (binaryCayleyGroup d B))) =
      quotientImage q (T : Set (Equiv.Perm (binaryCayleyGroup d B))) →
    ∃ δ : Equiv.Perm (binaryCayleyGroup d B),
      globalTwoPointSwap q (automorphismSet Γ) δ ∧
        let K := quotientActionKernel q (automorphismSet Γ)
        let D := (Subgroup.closure
          ({δ} : Set (Equiv.Perm (binaryCayleyGroup d B))) :
            Set (Equiv.Perm (binaryCayleyGroup d B)))
        (R : Set (Equiv.Perm (binaryCayleyGroup d B))) ∩ K =
            (T : Set (Equiv.Perm (binaryCayleyGroup d B))) ∩ K ∧
          (R : Set (Equiv.Perm (binaryCayleyGroup d B))) ∩ K = D

end MathlibPlus.Open.ResearchFormalization.Claim29203
