import Mathlib
import MathlibPlus.Open.ResearchFormalization.Batch_01a000fa_ef1a_7026_93c8_b04eb9d2c830

namespace MathlibPlus.Open.ResearchFormalization.Claim45772

open MathlibPlus.Open.ResearchFormalization.Batch01

/-- The simple ordinary-undirected Cayley relation used for the regular-pair
reduction. -/
def cayleyAdj (n : ℕ) (S : Set (r3035Q4n n))
    (x y : r3035Q4n n) : Prop :=
  x ≠ y ∧ r3035CayleyRelation n S x y

def graphAutomorphism (n : ℕ) (S : Set (r3035Q4n n))
    (c : Equiv.Perm (r3035Q4n n)) : Prop :=
  ∀ x y, cayleyAdj n S x y ↔ cayleyAdj n S (c x) (c y)

/-- Regularity retains both the actual permutation action and the displayed
`Q₄ₙ` multiplication. -/
def regularQ4nCopy (n : ℕ) (S : Set (r3035Q4n n))
    (R : Subgroup (Equiv.Perm (r3035Q4n n))) : Prop :=
  (∀ r : R, graphAutomorphism n S r.1) ∧
  (∀ x y : r3035Q4n n, ∃! r : R, r.1 x = y) ∧
  ∃ e : r3035Q4n n ≃ R,
    ∀ x y,
      e (r3035QMul n x y) = e x * e y

/-- A conjugate target copy, with the conjugator required to lie in the
actual generated permutation group. -/
def conjugatedInside
    (T T' : Subgroup (Equiv.Perm (r3035Q4n n)))
    (u : Equiv.Perm (r3035Q4n n)) : Prop :=
  ∀ t : Equiv.Perm (r3035Q4n n),
    t ∈ T' ↔ ∃ s, s ∈ T ∧ t = u⁻¹ * s * u

/-- A subgroup of the displayed `Cₙ ⋊ C₄` presentation. -/
def qSubgroup (n : ℕ) (K : Set (r3035Q4n n)) : Prop :=
  r3035QIdentity n ∈ K ∧
  (∀ x, x ∈ K → r3035QInv n x ∈ K) ∧
  ∀ x, x ∈ K → ∀ y, y ∈ K → r3035QMul n x y ∈ K

/-- Automorphisms of the displayed presentation. -/
def q4nAutomorphism (n : ℕ)
    (f : r3035Q4n n → r3035Q4n n) : Prop :=
  Function.Bijective f ∧
    f (r3035QIdentity n) = r3035QIdentity n ∧
    ∀ x y, f (r3035QMul n x y) = r3035QMul n (f x) (f y)

/-- The characteristic odd Hall subgroup `C_d`, retaining its actual
subgroup carrier, order, and invariance under all presentation
automorphisms. -/
def characteristicOddHall (n d : ℕ)
    (K : Set (r3035Q4n n)) : Prop :=
  qSubgroup n K ∧
  0 < d ∧ d ∣ n ∧ d % 2 = 1 ∧
  Nat.card {x : r3035Q4n n // x ∈ K} = d ∧
  ∀ f : r3035Q4n n → r3035Q4n n,
    q4nAutomorphism n f → Set.image f K = K

/-- A characteristic subgroup of the presented group transported into an
actual regular permutation copy. -/
def characteristicHallCopy (n d : ℕ)
    (R : Subgroup (Equiv.Perm (r3035Q4n n)))
    (K : Subgroup (Equiv.Perm (r3035Q4n n))) : Prop :=
  ∃ P : Set (r3035Q4n n),
    characteristicOddHall n d P ∧
    ∃ e : r3035Q4n n ≃ R,
      (∀ x y, e (r3035QMul n x y) = e x * e y) ∧
      ∀ x, x ∈ P ↔ (e x : Equiv.Perm (r3035Q4n n)) ∈ K

/-- The orbit of one point under an actual permutation subgroup. -/
def orbitBlock {Ω : Type*}
    (H : Subgroup (Equiv.Perm Ω)) (x : Ω) : Set Ω :=
  {y | ∃ h : H, h.1 x = y}

/-- The actual orbit partition of a permutation subgroup. -/
def orbitPartition {Ω : Type*}
    (H : Subgroup (Equiv.Perm Ω)) : Set (Set Ω) :=
  {B | ∃ x : Ω, orbitBlock H x = B}

/-- The partition and refinement predicates used for the common flag. -/
def isPartition {Ω : Type*} (P : Set (Set Ω)) : Prop :=
  (∀ B, B ∈ P → B.Nonempty) ∧
  (∀ B, B ∈ P → ∀ C, C ∈ P → B = C ∨ Disjoint B C) ∧
  ⋃₀ P = Set.univ

def refines {Ω : Type*} (P Q : Set (Set Ω)) : Prop :=
  ∀ B, B ∈ P → ∃ C, C ∈ Q ∧ B ⊆ C

def normalPartition {Ω : Type*}
    (X : Subgroup (Equiv.Perm Ω)) (P : Set (Set Ω)) : Prop :=
  ∀ g : X, ∀ B, B ∈ P → g.1 '' B ∈ P

/-- The product of the first `j` descending prime factors. -/
def prefixProduct {r : ℕ} (p : Fin r → ℕ)
    (j : ℕ) (hj : j ≤ r) : ℕ :=
  ∏ i : Fin j, p (Fin.castLE hj i)

/-- The exact descending-prime-factor carrier for the residual parameter. -/
def descendingPrimeFactors (n r : ℕ) (p : Fin r → ℕ) : Prop :=
  (∀ i, Nat.Prime (p i)) ∧
  StrictAnti p ∧
  (∏ i : Fin r, p i) = n ∧
  (∀ q, Nat.Prime q → q ∣ n → ∃ i, p i = q)

/-- A common nested flag of characteristic odd Hall-prefix orbit
partitions, normal under the subgroup generated by the two copies. -/
def commonHallPrefixFlag
    (n r ℓ : ℕ) (p : Fin r → ℕ) (hℓ : ℓ ≤ r)
    (R T : Subgroup (Equiv.Perm (r3035Q4n n)))
    (KR KT : Fin ℓ → Subgroup (Equiv.Perm (r3035Q4n n))) : Prop :=
  (∀ j : Fin ℓ,
    characteristicHallCopy n
      (prefixProduct p (j.1 + 1) (by omega)) R (KR j)) ∧
  (∀ j : Fin ℓ,
    characteristicHallCopy n
      (prefixProduct p (j.1 + 1) (by omega)) T (KT j)) ∧
  (∀ j : Fin ℓ,
    let PR := orbitPartition (KR j)
    let PT := orbitPartition (KT j)
    isPartition PR ∧ isPartition PT ∧ PR = PT) ∧
  (∀ i j : Fin ℓ, i.1 ≤ j.1 →
    refines (orbitPartition (KR i)) (orbitPartition (KR j)) ∧
    refines (orbitPartition (KT i)) (orbitPartition (KT j))) ∧
  (∀ j : Fin ℓ,
    normalPartition
      (Subgroup.closure ((R : Set (Equiv.Perm (r3035Q4n n))) ∪
        (T : Set (Equiv.Perm (r3035Q4n n)))))
      (orbitPartition (KR j)) ∧
    normalPartition
      (Subgroup.closure ((R : Set (Equiv.Perm (r3035Q4n n))) ∪
        (T : Set (Equiv.Perm (r3035Q4n n)))))
      (orbitPartition (KT j)))

/-- The final odd-Hall orbit partition consists of the four `Cₙ` cosets. -/
def fourCNPartition (n : ℕ)
    (P : Set (Set (r3035Q4n n))) : Prop :=
  Nat.card {B : Set (r3035Q4n n) // B ∈ P} = 4 ∧
  ∀ B, B ∈ P → Nat.card B = n

/-- The normal `Q₁₂` terminal: twelve common `C_{n/3}` blocks are
coarsened by a common partition into four triples, recovering the four
`Cₙ` blocks. -/
def normalQ12Recovery (n : ℕ)
    (Pm Pn : Set (Set (r3035Q4n n))) : Prop :=
  3 ∣ n ∧
  isPartition Pm ∧
  Nat.card {B : Set (r3035Q4n n) // B ∈ Pm} = 12 ∧
  (∀ B, B ∈ Pm → Nat.card B = n / 3) ∧
  isPartition Pn ∧ fourCNPartition n Pn ∧
  refines Pm Pn ∧
  (∀ B, B ∈ Pn →
    Nat.card {C : Set (r3035Q4n n) // C ∈ Pm ∧ C ⊆ B} = 3)

/-- The exceptional dicyclic `4,3` terminal schedule.  It reaches block
sizes `n/3`, `4n/3`, and `4n`, and has no block of size `n` in that chain. -/
def exceptionalDicyclicSchedule (n : ℕ)
    (Pm : Set (Set (r3035Q4n n))) : Prop :=
  3 ∣ n ∧
  isPartition Pm ∧
  Nat.card {B : Set (r3035Q4n n) // B ∈ Pm} = 12 ∧
  (∀ B, B ∈ Pm → Nat.card B = n / 3) ∧
  ∃ P4 Ptop : Set (Set (r3035Q4n n)),
    isPartition P4 ∧
    Nat.card {B : Set (r3035Q4n n) // B ∈ P4} = 3 ∧
    (∀ B, B ∈ P4 → Nat.card B = 4 * (n / 3)) ∧
    isPartition Ptop ∧
    Nat.card {B : Set (r3035Q4n n) // B ∈ Ptop} = 1 ∧
    (∀ B, B ∈ Ptop → Nat.card B = 4 * n) ∧
    refines Pm P4 ∧ refines P4 Ptop ∧
    (∀ B, B ∈ Pm → Nat.card B ≠ n) ∧
    (∀ B, B ∈ P4 → Nat.card B ≠ n) ∧
    (∀ B, B ∈ Ptop → Nat.card B ≠ n) ∧
    (∀ B, B ∈ P4 →
      Nat.card {C : Set (r3035Q4n n) // C ∈ Pm ∧ C ⊆ B} = 4) ∧
    (∀ B, B ∈ Ptop →
      Nat.card {C : Set (r3035Q4n n) // C ∈ P4 ∧ C ⊆ B} = 3)

/-- A terminal with no odd tail for the synchronizer is exactly the excluded
shape `n=3p`. -/
def noOddSynchronizerTail (n : ℕ) : Prop :=
  ∃ p : ℕ, Nat.Prime p ∧ n = 3 * p

/-- The complete Hall-prefix reduction, including both the normal `Q₁₂`
recovery and the exceptional order-three terminal. -/
def hallPrefixReduction (n : ℕ)
    (R T : Subgroup (Equiv.Perm (r3035Q4n n))) : Prop :=
  ∃ r : ℕ, ∃ h_r : 2 ≤ r, ∃ p : Fin r → ℕ,
    descendingPrimeFactors n r p ∧
    ¬ noOddSynchronizerTail n ∧
    ((¬ 3 ∣ n ∧
      ∃ KR KT : Fin r → Subgroup (Equiv.Perm (r3035Q4n n)),
        commonHallPrefixFlag n r r p (by omega) R T KR KT ∧
        fourCNPartition n
          (orbitPartition (KR (⟨r - 1, by omega⟩ : Fin r)))) ∨
     (3 ∣ n ∧
      ((∃ KR KT : Fin r → Subgroup (Equiv.Perm (r3035Q4n n)),
          commonHallPrefixFlag n r r p (by omega) R T KR KT ∧
          normalQ12Recovery n
            (orbitPartition (KR (⟨r - 2, by omega⟩ : Fin r)))
            (orbitPartition (KR (⟨r - 1, by omega⟩ : Fin r)))) ∨
       (∃ KR KT : Fin (r - 1) → Subgroup (Equiv.Perm (r3035Q4n n)),
          commonHallPrefixFlag n r (r - 1) p (by omega) R T KR KT ∧
          exceptionalDicyclicSchedule n
            (orbitPartition (KR (⟨r - 2, by omega⟩ : Fin (r - 1))))))))

/-- Claim 45772: after a conjugation inside the generated permutation group,
the two regular copies have the exact common Hall-prefix reduction. -/
def claim45772 : Prop :=
  ∀ n : ℕ,
    r3035ResidualParameter n →
    ∀ S : Set (r3035Q4n n),
      r3035ConnectionSet n S →
      ∀ R T : Subgroup (Equiv.Perm (r3035Q4n n)),
        regularQ4nCopy n S R →
        regularQ4nCopy n S T →
        ∃ X : Subgroup (Equiv.Perm (r3035Q4n n)),
          X = Subgroup.closure
            ((R : Set (Equiv.Perm (r3035Q4n n))) ∪
              (T : Set (Equiv.Perm (r3035Q4n n)))) ∧
          ∃ u : X, ∃ T' : Subgroup (Equiv.Perm (r3035Q4n n)),
            regularQ4nCopy n S T' ∧
            conjugatedInside T T' u.1 ∧
            hallPrefixReduction n R T'

end MathlibPlus.Open.ResearchFormalization.Claim45772
