import MathlibPlus.Algebra.TranslationShearClaim29695

namespace MathlibPlus.Open.ResearchFormalization.Claim29696

noncomputable section

/-- The additive subgroup generated by the defects at a fixed `h`. -/
def defectSubgroup {A H : Type*} [AddCommGroup A] [Group H]
    (h : H) (τ : H → A) : AddSubgroup A :=
  AddSubgroup.closure (Set.range (fun k : H => τ (h * k) - τ k - τ h))

/-- A one-step move supplied by one of the normalized relative derivatives. -/
def normalizedDerivativeStep {A H : Type*} [AddCommGroup A] [Group H]
    (τ : H → A) (p q : A × H) : Prop :=
  ∃ u : A, ∃ k : H,
    q = MathlibPlus.Algebra.Claim29695.normalizedRelativeDerivative τ u k p

/-- The orbit generated by all normalized relative derivatives, using the
symmetric-transitive closure of their one-step moves. -/
def normalizedDerivativeOrbit {A H : Type*} [AddCommGroup A] [Group H]
    (τ : H → A) (a : A) (h : H) : Set (A × H) :=
  {p | Relation.EqvGen (normalizedDerivativeStep τ) (a, h) p}

/-- The fibrewise coset `(a + W_h) × {h}`. -/
def defectCosetFiber {A H : Type*} [AddCommGroup A] [Group H]
    (τ : H → A) (a : A) (h : H) : Set (A × H) :=
  {p | p.2 = h ∧ ∃ w : A, w ∈ defectSubgroup h τ ∧ p.1 = a + w}

/-- Claim 29696: normalized derivative orbits in a fixed fibre are precisely
cosets of the additive subgroup generated by the displayed defects. -/
def claim29696 : Prop :=
  ∀ {A H : Type*} [Fintype A] [AddCommGroup A] [Fintype H] [Group H]
    (τ : H → A),
    τ 1 = 0 →
    ∀ (h : H) (a : A),
      normalizedDerivativeOrbit τ a h = defectCosetFiber τ a h

end

end MathlibPlus.Open.ResearchFormalization.Claim29696
