import Mathlib

open scoped Sym2

namespace MathlibPlus.Open.ResearchFormalization.Claim61020

/-- The inverse atoms `[d] = {d,-d}` in a finite additive abelian group. -/
def InverseAtom (G : Type*) [AddGroup G] :=
  {D : Set G // ∃ d : G, d ≠ 0 ∧ D = ({d, -d} : Set G)}

/-- The unordered translation-edge atom attached to an inverse atom. -/
def translationEdgeAtom {G : Type*} [AddCommGroup G]
    (D : InverseAtom G) : Set (Sym2 G) :=
  {e | ∃ (x d : G), d ≠ 0 ∧
    D.1 = ({d, -d} : Set G) ∧ e = s(x, x + d)}

/-- The set of group elements in a collection of inverse atoms. -/
def atomLabelUnion {G : Type*} [AddGroup G]
    (L : Set (InverseAtom G)) : Set G :=
  {x | ∃ D : InverseAtom G, D ∈ L ∧ x ∈ D.1}

/-- Source-target incidence is intersection after carrying the source edge
atom through the pointed permutation. -/
def atomIncidence {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G) (D D' : InverseAtom G) : Prop :=
  Set.Nonempty (Sym2.map f '' translationEdgeAtom D ∩
    translationEdgeAtom D')

/-- The bipartite incidence step on source and target copies of atoms. -/
def incidenceStep {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G) :
    Sum (InverseAtom G) (InverseAtom G) →
      Sum (InverseAtom G) (InverseAtom G) → Prop
  | Sum.inl D, Sum.inr D' => atomIncidence f D D'
  | Sum.inr D', Sum.inl D => atomIncidence f D D'
  | _, _ => False

/-- Connectedness in the bipartite incidence graph, expressed by the
relation generated by its incidence steps. -/
def incidenceConnected {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G)
    (u v : Sum (InverseAtom G) (InverseAtom G)) : Prop :=
  Relation.EqvGen (incidenceStep f) u v

def incidenceComponent {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G)
    (u : Sum (InverseAtom G) (InverseAtom G)) :
    Set (Sum (InverseAtom G) (InverseAtom G)) :=
  {v | incidenceConnected f u v}

def sourceLabels {G : Type*} [AddCommGroup G]
    (C : Set (Sum (InverseAtom G) (InverseAtom G))) :
    Set (InverseAtom G) :=
  {D | Sum.inl D ∈ C}

def targetLabels {G : Type*} [AddCommGroup G]
    (C : Set (Sum (InverseAtom G) (InverseAtom G))) :
    Set (InverseAtom G) :=
  {D | Sum.inr D ∈ C}

def componentSourceLabels {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G)
    (u : Sum (InverseAtom G) (InverseAtom G)) : Set (InverseAtom G) :=
  sourceLabels (incidenceComponent f u)

def componentTargetLabels {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G)
    (u : Sum (InverseAtom G) (InverseAtom G)) : Set (InverseAtom G) :=
  targetLabels (incidenceComponent f u)

/-- A set of incidence vertices is a union of connected components. -/
def isIncidenceComponentUnion {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G)
    (C : Set (Sum (InverseAtom G) (InverseAtom G))) : Prop :=
  ∀ u v, incidenceConnected f u v → (u ∈ C ↔ v ∈ C)

def unionTranslationEdges {G : Type*} [AddCommGroup G]
    (L : Set (InverseAtom G)) : Set (Sym2 G) :=
  {e | ∃ D : InverseAtom G, D ∈ L ∧ e ∈ translationEdgeAtom D}

def carriedUnionEdges {G : Type*} [AddCommGroup G]
    (f : Equiv.Perm G)
    (C : Set (Sum (InverseAtom G) (InverseAtom G))) : Prop :=
  Sym2.map f '' unionTranslationEdges (sourceLabels C) =
    unionTranslationEdges (targetLabels C)

def fixedUnionEdges {G : Type*} [AddCommGroup G]
    (C : Set (Sum (InverseAtom G) (InverseAtom G))) : Prop :=
  unionTranslationEdges (sourceLabels C) =
    unionTranslationEdges (targetLabels C)

def identityAutomorphismShadows {G : Type*} [AddGroup G]
    (S T : Set G) : Prop :=
  (AddEquiv.refl G) '' S = T

def supportOf {G : Type*} (f : Equiv.Perm G) : Set G :=
  {x | f x ≠ x}

def atomHasOddOrder {G : Type*} [AddCommGroup G]
    (D : InverseAtom G) : Prop :=
  ∃ d : G, d ≠ 0 ∧ D.1 = ({d, -d} : Set G) ∧ Odd (addOrderOf d)

def alternatingOnTranslation {G : Type*} [AddCommGroup G]
    (K : Set G) (d : G) : Prop :=
  ∀ x : G, x ∈ K ↔ x + d ∉ K

def identityFree {G : Type*} [Zero G] (S : Set G) : Prop :=
  S ⊆ ({0} : Set G)ᶜ

def inverseClosed {G : Type*} [Neg G] (S : Set G) : Prop :=
  ∀ ⦃x : G⦄, x ∈ S → -x ∈ S

def cayleyAdj {G : Type*} [AddGroup G]
    (S : Set G) (x y : G) : Prop :=
  x ≠ y ∧ y - x ∈ S

def cayleyGraphIsomorphism {G : Type*} [AddGroup G]
    (S T : Set G) (f : Equiv.Perm G) : Prop :=
  ∀ x y : G, cayleyAdj S x y ↔ cayleyAdj T (f x) (f y)

/-- Claim 61020: half-support boundary rigidity, odd-order diagonal
incidence, the odd-order component consequences, and the covering-radius
statement against every additive group automorphism. -/
def claim61020 : Prop :=
  ∀ (G : Type*) [Fintype G] [AddCommGroup G],
    (∀ f : Equiv.Perm G, f 0 = 0 →
      let K := supportOf f
      Set.ncard K ≤ Fintype.card G / 2 →
        (∀ D : InverseAtom G,
          ¬ atomIncidence f D D →
            ∀ d : G, d ≠ 0 → D.1 = ({d, -d} : Set G) →
              Set.ncard K = Fintype.card G / 2 ∧
              Even (addOrderOf d) ∧
              Set.image (fun x : G => x + d) K = Kᶜ ∧
              alternatingOnTranslation K d) ∧
        (∀ D : InverseAtom G,
          atomHasOddOrder D → atomIncidence f D D) ∧
        (Fintype.card G % 2 = 1 →
          (∀ D : InverseAtom G, atomIncidence f D D) ∧
          (∀ u : Sum (InverseAtom G) (InverseAtom G),
            componentSourceLabels f u = componentTargetLabels f u) ∧
          (∀ C : Set (Sum (InverseAtom G) (InverseAtom G)),
            isIncidenceComponentUnion f C →
              sourceLabels C = targetLabels C ∧
              carriedUnionEdges f C ∧
              fixedUnionEdges C ∧
              identityAutomorphismShadows
                (atomLabelUnion (sourceLabels C))
                (atomLabelUnion (targetLabels C))))) ∧
    (Fintype.card G % 2 = 1 →
      ∀ (S T : Set G),
        identityFree S → identityFree T →
        inverseClosed S → inverseClosed T →
        ∀ f₀ : Equiv.Perm G, f₀ 0 = 0 →
          cayleyGraphIsomorphism S T f₀ →
          (¬ ∃ α : G ≃+ G, α '' S = T) →
          ∀ α : G ≃+ G,
            Set.ncard {x : G | f₀ x ≠ α x} > Fintype.card G / 2)

end MathlibPlus.Open.ResearchFormalization.Claim61020
