import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.Claim61181

noncomputable section

abbrev F3 := ZMod 3
abbrev H := F3 × F3
abbrev F2 := ZMod 2
abbrev A := Fin 4 → F2

/-- The nine displayed elements of the additive ternary plane, in the
    order used for the pointed permutation. -/
def displayedPoint : Fin 9 → H :=
  ![(0, 0), (1, 0), (2, 0), (0, 1), (1, 1),
    (2, 1), (0, 2), (1, 2), (2, 2)]

/-- The table of the pointed permutation in displayed-point coordinates. -/
def displayedTauIndex : Fin 9 → Fin 9 :=
  ![0, 4, 8, 5, 6, 1, 2, 7, 3]

/-- Exact agreement with the displayed pointed permutation table. -/
def displayedTau (τ : Equiv.Perm H) : Prop :=
  ∀ i : Fin 9, τ (displayedPoint i) =
    displayedPoint (displayedTauIndex i)

/-- The projected derivative component used by the countermodel. -/
def projectedComponent : Set H :=
  {displayedPoint 1, displayedPoint 2}

/-- The normalized transition `q_k`, represented as a permutation. -/
def normalizedTransition (τ : Equiv.Perm H) (k : H) : Equiv.Perm H :=
  (Equiv.addRight k).trans τ |>.trans
    (Equiv.addRight (-(τ k))) |>.trans τ.symm

/-- Evaluation of the transition at a base point. -/
def normalizedTransitionValue (τ : Equiv.Perm H) (k h : H) : H :=
  normalizedTransition τ k h

/-- The subgroup generated by all normalized transitions. -/
def transitionGroup (τ : Equiv.Perm H) : Subgroup (Equiv.Perm H) :=
  Subgroup.closure (Set.range (normalizedTransition τ))

/-- The orbit of a base point under the generated transition group. -/
def transitionOrbit (τ : Equiv.Perm H) (h : H) : Set H :=
  {x | ∃ g : transitionGroup τ, g.1 h = x}

/-- A line in the elementary binary fibre. -/
def fibreLine (e : A) : Submodule F2 A :=
  Submodule.span F2 ({e} : Set A)

/-- The two assigned period subspaces on the projected component. -/
def componentPeriod
    (e₁ e₂ : A) (h : {h : H // h ∈ projectedComponent}) :
    Submodule F2 A :=
  if h.1 = displayedPoint 1 then fibreLine e₁ else fibreLine e₂

/-- The support-lattice identities on the displayed component. -/
def supportLatticeLaw (τ : Equiv.Perm H) (e₁ e₂ : A) : Prop :=
  ∀ (h k : H) (hh : h ∈ projectedComponent)
    (hk : k ∈ projectedComponent),
    ∃ hq : normalizedTransitionValue τ k h ∈ projectedComponent,
      componentPeriod e₁ e₂ ⟨h, hh⟩ ⊔
          componentPeriod e₁ e₂ ⟨k, hk⟩ =
        componentPeriod e₁ e₂
            ⟨normalizedTransitionValue τ k h, hq⟩ ⊔
          componentPeriod e₁ e₂ ⟨k, hk⟩

/-- The ordinary-inversion transport appearing in the twisted formula. -/
def twistedInversionIndex (τ : Equiv.Perm H) (h : H) : H :=
  τ.symm (-τ (-h))

/-- The twisted-inversion identities on the displayed component. -/
def twistedInversionLaw (τ : Equiv.Perm H) (e₁ e₂ : A) : Prop :=
  ∀ (h : H) (hh : h ∈ projectedComponent),
    ∃ hκ : twistedInversionIndex τ h ∈ projectedComponent,
      componentPeriod e₁ e₂ ⟨h, hh⟩ =
        componentPeriod e₁ e₂ ⟨twistedInversionIndex τ h, hκ⟩

/-- Equality of all assigned periods on the projected component. -/
def periodsConstantOnComponent (e₁ e₂ : A) : Prop :=
  ∀ h k : {h : H // h ∈ projectedComponent},
    componentPeriod e₁ e₂ h = componentPeriod e₁ e₂ k

/-- The common order of the assigned period subspaces. -/
def equalPeriodOrder (e₁ e₂ : A) : Prop :=
  ∀ h : {h : H // h ∈ projectedComponent},
    Nat.card (componentPeriod e₁ e₂ h) = 2

/-- The ambient fibre is elementary abelian of order sixteen. -/
def elementaryBinaryFibre : Prop :=
  Fintype.card A = 16 ∧ ∀ a : A, 2 • a = 0

/-- The exact finite countermodel to constancy from the two admitted laws. -/
def claim61181 : Prop :=
  Function.Bijective displayedPoint ∧
    elementaryBinaryFibre ∧
      ∃ τ : Equiv.Perm H,
        displayedTau τ ∧
          transitionOrbit τ (displayedPoint 1) = projectedComponent ∧
            ∃ e₁ e₂ : A,
              LinearIndependent F2 ![e₁, e₂] ∧
                fibreLine e₁ ≠ fibreLine e₂ ∧
                ¬ fibreLine e₁ ≤ fibreLine e₂ ∧
                ¬ fibreLine e₂ ≤ fibreLine e₁ ∧
                equalPeriodOrder e₁ e₂ ∧
                supportLatticeLaw τ e₁ e₂ ∧
                twistedInversionLaw τ e₁ e₂ ∧
                ¬ periodsConstantOnComponent e₁ e₂

end

end MathlibPlus.Open.ResearchFormalization.Claim61181
