import MathlibPlus.Open.ResearchFormalization.Batch_01a000fa_ef1a_7026_93c8_b04eb9d2c830

open Classical
open scoped BigOperators
attribute [local instance] Classical.propDecidable

namespace MathlibPlus.Open.ResearchFormalization.Claim45773

noncomputable section

open MathlibPlus.Open.ResearchFormalization.Batch01

/-- A permutation preserves the actual child block B. -/
def preservesBlock {Ω : Type*} (B : Set Ω)
    (g : Equiv.Perm Ω) : Prop :=
  ∀ x, x ∈ B ↔ g x ∈ B

/-- A marked regular p-cycle on the actual child block B. -/
def regularPrimeCycleOn {Ω : Type*} (B : Set Ω)
    (p : ℕ) (ρ : Equiv.Perm Ω) : Prop :=
  preservesBlock B ρ ∧
    ∀ x y : B, ∃! i : Fin p, (ρ ^ i.1) x.1 = y.1

/-- The local group is the subgroup generated by the two actual marked
permutations. -/
def markedLocalGroup {Ω : Type*}
    (ρ σ : Equiv.Perm Ω) : Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure ({ρ, σ} : Set (Equiv.Perm Ω))

/-- The fixed-point mark in the actual permutation action restricted to B. -/
noncomputable def fixedPointMarkOn {Ω : Type*}
    (B : Set Ω) (g : Equiv.Perm Ω) : ℕ :=
  Nat.card {x : B // g x.1 = x.1}

/-- The actual permutation character mark μ_B(i,j). -/
noncomputable def fixedPointMark {Ω : Type*}
    (B : Set Ω) (ρ σ : Equiv.Perm Ω) (i j : ℕ) : ℕ :=
  fixedPointMarkOn B (ρ ^ i * (σ ^ j)⁻¹)

/-- The number of p-by-p fixed-point marks equal to p. -/
noncomputable def markCount {Ω : Type*}
    (B : Set Ω) (p : ℕ) (ρ σ : Equiv.Perm Ω) : ℕ :=
  (Finset.univ.filter
    (fun ij : Fin p × Fin p =>
      fixedPointMark B ρ σ ij.1.1 ij.2.1 = p)).card

/-- A subgroup of the actual ambient permutation group acts regularly on B. -/
def regularSubgroupOnBlock {Ω : Type*}
    (B : Set Ω) (N : Subgroup (Equiv.Perm Ω)) : Prop :=
  (∀ g : N, preservesBlock B g.1) ∧
    ∀ x y : B, ∃! g : N, g.1 x.1 = y.1

/-- The actual action on B is affine after one identification B ≃ ZMod p. -/
def affineOnBlock {Ω : Type*}
    (B : Set Ω) (p : ℕ) (L : Subgroup (Equiv.Perm Ω)) : Prop :=
  (∀ g : L, preservesBlock B g.1) ∧
  ∃ e : B ≃ ZMod p,
    ∀ g : L, ∃ u : (ZMod p)ˣ, ∃ a : ZMod p,
      ∀ x : B, ∃ y : B,
        y.1 = g.1 x.1 ∧ e y = (u : ZMod p) * e x + a

/-- Normality is expressed by actual conjugation in the ambient permutation
carrier. -/
def normalSubgroupIn {Ω : Type*}
    (B : Set Ω) (N L : Subgroup (Equiv.Perm Ω)) : Prop :=
  N ≤ L ∧
    (∀ g : L, preservesBlock B g.1) ∧
    (∀ g : L, ∀ h : N, g.1 * h.1 * (g.1)⁻¹ ∈ N)

/-- The affine branch has a normal regular p-subgroup. -/
def normalRegularAffine {Ω : Type*}
    (B : Set Ω) (p : ℕ) (L : Subgroup (Equiv.Perm Ω)) : Prop :=
  affineOnBlock B p L ∧
    ∃ N : Subgroup (Equiv.Perm Ω),
      normalSubgroupIn B N L ∧ regularSubgroupOnBlock B N

/-- Transitivity and the point-stabilizer suborbits {α} and B \ {α}. -/
def twoTransitiveOnBlock {Ω : Type*}
    (B : Set Ω) (L : Subgroup (Equiv.Perm Ω)) : Prop :=
  (∀ g : L, preservesBlock B g.1) ∧
  (∀ x y : B, ∃ g : L, g.1 x.1 = y.1) ∧
  ∀ α : B, ∀ y z : B, y ≠ α → z ≠ α →
    ∃ g : L, g.1 α.1 = α.1 ∧ g.1 y.1 = z.1

/-- Two different regular p-lines in the actual local group. -/
def hasTwoRegularLines {Ω : Type*}
    (B : Set Ω) (L : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∃ N M : Subgroup (Equiv.Perm Ω),
    N ≤ L ∧ M ≤ L ∧ regularSubgroupOnBlock B N ∧
    regularSubgroupOnBlock B M ∧ N ≠ M

/-- A regular permutation copy of the displayed generalized-quaternion
presentation in the actual ambient action. -/
def regularQ4nPermutationCopy {Ω : Type*}
    (n : ℕ) (R : Subgroup (Equiv.Perm Ω)) : Prop :=
  (∀ x y : Ω, ∃! r : R, r.1 x = y) ∧
  ∃ e : r3035Q4n n ≃ R,
    ∀ x y, e (r3035QMul n x y) = e x * e y

/-- The two alternatives for the actual fixed-point character, with all
marked-cycle and regular-copy hypotheses supplied by the outer statement. -/
def primeMarkConclusion {Ω : Type*}
    (B : Set Ω) (p : ℕ) (ρ σ : Equiv.Perm Ω) : Prop :=
  let L := markedLocalGroup ρ σ
  (Subgroup.closure ({ρ} : Set (Equiv.Perm Ω)) =
      Subgroup.closure ({σ} : Set (Equiv.Perm Ω)) →
    markCount B p ρ σ = p ∧ normalRegularAffine B p L) ∧
  (Subgroup.closure ({ρ} : Set (Equiv.Perm Ω)) ≠
      Subgroup.closure ({σ} : Set (Equiv.Perm Ω)) →
    markCount B p ρ σ = 1 ∧ twoTransitiveOnBlock B L ∧
      (affineOnBlock B p L → ¬ hasTwoRegularLines B L))

/-- On a three-point actual block there is only one regular subgroup. -/
def uniqueRegularThreeSubgroup (B : Type*) : Prop :=
  Nat.card B = 3 →
    ∀ N M : Subgroup (Equiv.Perm B),
      (∀ x y : B, ∃! g : N, g.1 x = y) →
      (∀ x y : B, ∃! g : M, g.1 x = y) → N = M

/-- The finite replay carrier for a regular prime cycle. -/
def replayPrimeCycle (p : ℕ) (ρ : Equiv.Perm (Fin p)) : Prop :=
  ∀ x y : Fin p, ∃! i : Fin p, (ρ ^ i.1) x = y

noncomputable def replayPrimeCycles (p : ℕ) : Finset (Equiv.Perm (Fin p)) :=
  Finset.univ.filter (replayPrimeCycle p)

noncomputable def replaySameLineTargets (p : ℕ)
    (ρ : Equiv.Perm (Fin p)) : Finset (Equiv.Perm (Fin p)) :=
  (replayPrimeCycles p).filter (fun σ =>
    Subgroup.closure ({ρ} : Set (Equiv.Perm (Fin p))) =
      Subgroup.closure ({σ} : Set (Equiv.Perm (Fin p))))

noncomputable def replayDifferentLineTargets (p : ℕ)
    (ρ : Equiv.Perm (Fin p)) : Finset (Equiv.Perm (Fin p)) :=
  (replayPrimeCycles p).filter (fun σ =>
    Subgroup.closure ({ρ} : Set (Equiv.Perm (Fin p))) ≠
      Subgroup.closure ({σ} : Set (Equiv.Perm (Fin p))))

/-- The retained finite replay controls for p=3,5,7. -/
def replayControls : Prop :=
  (replayPrimeCycles 3).card = 2 ∧
  (replayPrimeCycles 5).card = 24 ∧
  (replayPrimeCycles 7).card = 720 ∧
  (∀ ρ : Equiv.Perm (Fin 3), replayPrimeCycle 3 ρ →
    (replaySameLineTargets 3 ρ).card = 2 ∧
    (replayDifferentLineTargets 3 ρ).card = 0) ∧
  (∀ ρ : Equiv.Perm (Fin 5), replayPrimeCycle 5 ρ →
    (replaySameLineTargets 5 ρ).card = 4 ∧
    (replayDifferentLineTargets 5 ρ).card = 20) ∧
  (∀ ρ : Equiv.Perm (Fin 7), replayPrimeCycle 7 ρ →
    (replaySameLineTargets 7 ρ).card = 6 ∧
    (replayDifferentLineTargets 7 ρ).card = 714)

/-- Claim 45773: the actual fixed-point character alternatives at every
prime layer, the three-point uniqueness statement, and replay controls. -/
def claim45773 : Prop :=
  ∀ n : ℕ,
    r3035ResidualParameter n →
    replayControls ∧
    (∀ p : ℕ, Nat.Prime p → p ∣ n →
      ∀ (Ω : Type*) [Fintype Ω] (B : Set Ω)
        (R T : Subgroup (Equiv.Perm Ω))
        (ρ σ : Equiv.Perm Ω),
        Nat.card B = p →
        regularQ4nPermutationCopy n R →
        regularQ4nPermutationCopy n T →
        ρ ∈ R →
        σ ∈ T →
        regularPrimeCycleOn B p ρ →
        regularPrimeCycleOn B p σ →
        primeMarkConclusion B p ρ σ ∧
        (p = 3 → uniqueRegularThreeSubgroup B))

end

end MathlibPlus.Open.ResearchFormalization.Claim45773
