import MathlibPlus.Open.ResearchFormalization.O0091Klein
import MathlibPlus.Open.ResearchFormalization.O0091Claim13480

open scoped BigOperators Matrix

noncomputable section

namespace MathlibPlus.Open.ResearchFormalization.O0091Claim13508

open MathlibPlus.Open.ResearchFormalization.O0091Claim13477
open MathlibPlus.Open.ResearchFormalization.O0091Klein

abbrev Qubit := Fin 2
abbrev QIndex := Qubit × Qubit
abbrev LocalMatrix := Matrix Qubit Qubit ℂ
abbrev QMatrix := Matrix QIndex QIndex ℂ

/-- The standard row-vectorized Bell frame, ordered by `I,X,Z,iY`. -/
def standardBellFrame : QMatrix :=
  fun (i, j) (k, l) =>
    (1 / (Real.sqrt 2 : ℂ)) *
      (if k = 0 ∧ l = 0 then
        if i = j then 1 else 0
      else if k = 0 ∧ l = 1 then
        if i ≠ j then 1 else 0
      else if k = 1 ∧ l = 0 then
        if i = j then if i = 0 then 1 else -1 else 0
      else
        if i = 0 ∧ j = 1 then 1
        else if i = 1 ∧ j = 0 then -1 else 0)

/-- The Bell frame after the exact phase gauge `theta=t log 2`. -/
def phaseBellFrame (t : ℝ) : QMatrix :=
  tensor (phaseP (t * Real.log 2)) pauliI * standardBellFrame

/-- Conjugation by a Bell frame uses `B† A B`. -/
def bellConjugate (t : ℝ) (A : QMatrix) : QMatrix :=
  Matrix.conjTranspose (phaseBellFrame t) * A * phaseBellFrame t

/-- The random-unitary heat generated by the phase-gauged commuting Weyls. -/
def phaseHeat (t lam : ℝ) (A : QMatrix) : QMatrix :=
  let θ : ℝ := t * Real.log 2
  let Rh := rh θ
  let Rc := rc
  let D := kleinD θ
  (((1 + lam) / 4 : ℝ) : ℂ) •
      (A + D * A * D)
    + (((1 - lam) / 4 : ℝ) : ℂ) •
      (Rh * A * Rh + Rc * A * Rc)

/-- The canonical Gram, written in the phase-gauged Klein algebra with the
parameter `rho` rather than introducing a division by `2+x`. -/
def phaseQStar (t x rho : ℝ) : QMatrix :=
  phaseQ (t * Real.log 2) x ((2 + x) * rho) (rho / 2)

/-- In the phase-gauged Bell frame the five Klein generators have the stated
Pauli product coordinates, the canonical Gram has the stated product factor,
and the random-unitary heat has the stated covariance. -/
def claim13508 : Prop :=
  ∀ t : ℝ,
    let θ : ℝ := t * Real.log 2
    let Rh := rh θ
    let Rc := rc
    let D := kleinD θ
    let J := kleinJ
    let N := kleinN θ
    (bellConjugate t Rh = tensor pauliZ pauliX ∧
      bellConjugate t Rc = tensor pauliI pauliX ∧
      bellConjugate t D = tensor pauliZ pauliI ∧
      bellConjugate t J = tensor pauliI pauliY ∧
      bellConjugate t N = tensor pauliZ pauliY) ∧
      (∀ x rho : ℝ,
        bellConjugate t (phaseQStar t x rho) =
          MathlibPlus.Open.ResearchFormalization.O0091Claim13480.canonicalFactor
            x rho) ∧
      (∀ lam : ℝ,
        phaseHeat t lam identity4 = identity4 ∧
          phaseHeat t lam D = D ∧
          phaseHeat t lam J = (lam : ℂ) • J ∧
          phaseHeat t lam N = (lam : ℂ) • N ∧
          (∀ x rho : ℝ,
            phaseHeat t lam (phaseQStar t x rho) =
              phaseQStar t x (lam * rho)))

end MathlibPlus.Open.ResearchFormalization.O0091Claim13508
