import Mathlib

open MeasureTheory Set
open Filter
open scoped BigOperators ENNReal

namespace MathlibPlus.Open.ResearchFormalization.O0321Levy

noncomputable section

def levyCoshWeight (x : ℝ) : ℝ :=
  Real.exp (-x) * (3 + 2 * Real.cos x) + 1 / (2 * Real.sinh x)

def reciprocalYReal (t : ℝ) : ℝ :=
  (1 / 4) * (1 + t ^ 2) ^ 3 * (t ^ 4 + 4) * Real.cosh (Real.pi * t / 2)

noncomputable def reciprocalY (t : ℝ) : ℂ :=
  ((reciprocalYReal t)⁻¹ : ℂ)

def levyDensity (x : ℝ) : ℝ :=
  levyCoshWeight |x| / |x|

noncomputable def levyMeasure : Measure ℝ :=
  Measure.withDensity volume (fun x => ENNReal.ofReal (levyDensity x))

def reflectedSet (A : Set ℝ) : Set ℝ :=
  {x | -x ∈ A}

def symmetricMeasure (μ : Measure ℝ) : Prop :=
  ∀ A : Set ℝ, MeasurableSet A → μ A = μ (reflectedSet A)

def levyIntegrability : Prop :=
  ∫⁻ x : ℝ, ENNReal.ofReal (min (1 : ℝ) (x ^ 2)) ∂levyMeasure < ∞

def rightEquivalent (f g : ℝ → ℝ) : Prop :=
  Tendsto (fun x => f x / g x) (nhdsWithin (0 : ℝ) (Set.Ioi 0)) (nhds (1 : ℝ))

def nearZeroBigO (f : ℝ → ℝ) : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧
    ∀ᶠ x in nhdsWithin (0 : ℝ) (Set.Ioi 0), |f x| ≤ C / x ^ 2

def exponentialTail (f : ℝ → ℝ) : Prop :=
  ∃ C : ℝ, 0 ≤ C ∧
    ∀ᶠ x in atTop, |f x| ≤ C * Real.exp (-x)

def symmetricCharacteristicFunction (φ : ℝ → ℂ) : Prop :=
  ∃ μ : Measure ℝ,
    μ Set.univ = 1 ∧ symmetricMeasure μ ∧
      ∀ t : ℝ,
        φ t = ∫ x : ℝ,
          Complex.exp (Complex.I * (t : ℂ) * (x : ℂ)) ∂μ

def infinitelyDivisibleCharacteristic (φ : ℝ → ℂ) : Prop :=
  ∀ n : ℕ, 0 < n →
    ∃ ψ : ℝ → ℂ,
      symmetricCharacteristicFunction ψ ∧
        ∀ t : ℝ, ψ t ^ n = φ t

def levyExponent (t : ℝ) : ℝ :=
  ∫ x : ℝ, (1 - Real.cos (t * x)) ∂levyMeasure

def quotientCharacteristic (c t : ℝ) : ℂ :=
  ((reciprocalYReal (c * t) / reciprocalYReal t : ℝ) : ℂ)

/-- Claim 15347: the exact odd-product, odd-exponential sum, and its
Lévy integral identity for the hyperbolic cosine. -/
def claim_15347 : Prop :=
  (∀ t : ℝ,
    Real.cosh (Real.pi * t / 2) =
      ∏' n : ℕ,
        (1 + t ^ 2 / (2 * (n : ℝ) + 1) ^ 2)) ∧
  (∀ x : ℝ, 0 < x →
    1 / (2 * Real.sinh x) =
      ∑' n : ℕ, Real.exp (-(2 * (n : ℝ) + 1) * x)) ∧
  (∀ t : ℝ,
    2 * ∫ x : ℝ in Set.Ioi (0 : ℝ),
      (1 - Real.cos (t * x)) / x / (2 * Real.sinh x) =
        Real.log (Real.cosh (Real.pi * t / 2))
  )

/-- Claim 15349: the displayed density is the symmetric Lévy measure with
its exact finite second-truncated moment and the stated endpoint controls. -/
def claim_15349 : Prop :=
  symmetricMeasure levyMeasure ∧
    levyIntegrability ∧
    rightEquivalent levyCoshWeight (fun x : ℝ => 1 / (2 * x)) ∧
    nearZeroBigO levyDensity ∧
    exponentialTail (fun x : ℝ => Real.exp (-x) * (3 + 2 * Real.cos x)) ∧
    exponentialTail (fun x : ℝ => 1 / (2 * Real.sinh x)) ∧
    exponentialTail levyDensity

/-- Claim 15350: the reciprocal of the exact real restriction of Y is the
symmetric infinitely-divisible characteristic function generated by levyMeasure. -/
def claim_15350 : Prop :=
  (∀ t : ℝ,
    reciprocalY t = Complex.exp (-(levyExponent t : ℂ))) ∧
  infinitelyDivisibleCharacteristic reciprocalY

/-- Claim 15352: every scale c in (0,1) gives the exact self-decomposition
quotient, with the monotone Lévy numerator and the characteristic factor. -/
def claim_15352 : Prop :=
  ∀ c : ℝ, 0 < c → c < 1 →
    (∀ x : ℝ, 0 < x →
      0 ≤ levyCoshWeight x - levyCoshWeight (x / c)) ∧
    (∀ t : ℝ,
      quotientCharacteristic c t =
        reciprocalY t / reciprocalY (c * t)) ∧
    infinitelyDivisibleCharacteristic (quotientCharacteristic c) ∧
    (∀ t : ℝ,
      reciprocalY t = reciprocalY (c * t) * quotientCharacteristic c t)

end
end MathlibPlus.Open.ResearchFormalization.O0321Levy
