import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.PrimeFibreOrbitShadowR1198

/-- The elementary-Sylow condition on a finite abelian additive group.  The
Sylow subgroup is viewed multiplicatively only because `Sylow` is defined for
multiplicative groups; exponent `p` is the elementary-abelian condition. -/
def elementarySylowP (p : ℕ) (H : Type*) [AddCommGroup H] [Fintype H]
    [Fact p.Prime] : Prop :=
  ∃ P : Sylow p (Multiplicative H), ∀ x : P, x ^ p = 1

/-- A normalized quotient-identity affine permutation of the prime fibres,
with its fibrewise affine data allowed to vary with the base point. -/
def normalizedQuotientIdentityAffine
    {p : ℕ} {H : Type*} [AddCommGroup H] [Fact p.Prime]
    (f : (H × ZMod p) ≃ (H × ZMod p)) : Prop :=
  f (0, 0) = (0, 0) ∧
    ∀ h : H, ∃ lambda : (ZMod p)ˣ, ∃ s : ZMod p,
      ∀ t : ZMod p,
        f (h, t) = (h, (lambda : ZMod p) * t + s)

/-- The explicit normalized affine profile used by the formula and orbit
claims. -/
def normalizedAffineProfile
    {p : ℕ} {H : Type*} [AddCommGroup H] [Fact p.Prime]
    (f : (H × ZMod p) ≃ (H × ZMod p))
    (lambda : H → (ZMod p)ˣ) (s : H → ZMod p) : Prop :=
  f (0, 0) = (0, 0) ∧
    s 0 = 0 ∧
    ∀ h : H, ∀ t : ZMod p,
      f (h, t) = (h, (lambda h : ZMod p) * t + s h)

/-- Claim 41889: under the normalized quotient-identity affine-fibre
hypothesis, one global multiplier and translation function give the displayed
form, with the normalization at the identity retained. -/
def normalizedAffinePrimeFibrePermutation_41889 : Prop :=
  ∀ (p : ℕ) [Fact p.Prime]
    (H : Type*) [Fintype H] [AddCommGroup H],
    elementarySylowP p H →
      ∀ (f : (H × ZMod p) ≃ (H × ZMod p)),
        normalizedQuotientIdentityAffine f →
          ∃ lambda : H → (ZMod p)ˣ, ∃ s : H → ZMod p,
            normalizedAffineProfile f lambda s

/-- The split condition on an additive automorphism shadow: it is a group
automorphism of the direct-product carrier and is the identity on the quotient
coordinate. -/
def splitGroupAutomorphismShadow
    {p : ℕ} {H : Type*} [AddCommGroup H] [Fact p.Prime]
    (α : (H × ZMod p) ≃+ (H × ZMod p)) : Prop :=
  ∀ h : H, ∀ t : ZMod p, (α (h, t)).1 = h

/-- Claim 41890: a split group-automorphism shadow has constant nonzero
prime-fibre multiplier and an additive character from the base group. -/
def groupAutomorphismShadowFamily_41890 : Prop :=
  ∀ (p : ℕ) [Fact p.Prime]
    (H : Type*) [Fintype H] [AddCommGroup H],
    ∀ (α : (H × ZMod p) ≃+ (H × ZMod p)),
      splitGroupAutomorphismShadow α →
        ∃ e : (ZMod p)ˣ, ∃ χ : H →+ ZMod p,
          ∀ h : H, ∀ t : ZMod p,
            α (h, t) = (h, (e : ZMod p) * t + χ h)

/-- The normalized relative derivative of a permutation of an additive group.
This is the direct additive form of `f⁻¹ (f (x + shift) - f shift)`. -/
def normalizedRelativeDerivative
    {G : Type*} [AddGroup G]
    (f : G ≃ G) (shift : G) : Equiv.Perm G :=
  (((Equiv.addLeft shift).trans f).trans
    (Equiv.addLeft (-(f shift)))).trans f.symm

/-- The subgroup generated by all normalized relative derivatives. -/
def normalizedDerivativeGroup
    {G : Type*} [AddGroup G]
    (f : G ≃ G) : Subgroup (Equiv.Perm G) :=
  Subgroup.closure (Set.range (normalizedRelativeDerivative f))

/-- An orbit of the normalized relative-derivative group. -/
def normalizedRelativeDerivativeOrbit
    {G : Type*} [AddGroup G]
    (f : G ≃ G) (x : G) : Set G :=
  {y | ∃ g : normalizedDerivativeGroup f, g.1 x = y}

/-- Claim 41891: the displayed scalar `q` is the second coordinate of the
actual normalized relative derivative of the normalized affine permutation. -/
def normalizedRelativeDerivativeFormula_41891 : Prop :=
  ∀ (p : ℕ) [Fact p.Prime]
    (H : Type*) [Fintype H] [AddCommGroup H],
    elementarySylowP p H →
      ∀ (f : (H × ZMod p) ≃ (H × ZMod p))
        (lambda : H → (ZMod p)ˣ) (s : H → ZMod p),
        normalizedAffineProfile f lambda s →
          ∀ (h k : H) (m t : ZMod p),
            normalizedRelativeDerivative f (k, m) (h, t) =
              (h,
                (lambda h : ZMod p)⁻¹ * (lambda (h + k) : ZMod p) * t +
                  (lambda h : ZMod p)⁻¹ *
                    ((lambda (h + k) : ZMod p) - (lambda k : ZMod p)) * m +
                  (lambda h : ZMod p)⁻¹ *
                    (s (h + k) - s k - s h))

/-- The multiplier-period set from Record 5. -/
def multiplierPeriod
    {p : ℕ} {H : Type*} [AddCommGroup H] [Fact p.Prime]
    (lambda : H → (ZMod p)ˣ) : Set H :=
  {h | ∀ k : H, lambda (h + k) = lambda k}

/-- The additive locus from Record 6. -/
def additiveLocus
    {p : ℕ} {H : Type*} [AddCommGroup H] [Fact p.Prime]
    (lambda : H → (ZMod p)ˣ) (s : H → ZMod p) : Set H :=
  {h |
    h ∈ multiplierPeriod lambda ∧
      ∀ k : H, k ∈ multiplierPeriod lambda → s (h + k) = s h + s k}

/-- The whole prime fibre over a base point. -/
def primeFibre
    {p : ℕ} {H : Type*} [AddCommGroup H] [Fact p.Prime]
    (h : H) : Set (H × ZMod p) :=
  {x | x.1 = h}

/-- Claim 32126 (equivalently Claim 41897): the affine prime-fibre
orbit-shadow theorem, including the exact multiplier-period/additive-locus
split, the character, pointwise agreement on the additive locus, and the
whole-fibre orbit and preservation conclusion away from it. -/
def affinePrimeFibreOrbitShadow_32126 : Prop :=
  ∀ (p : ℕ) [Fact p.Prime]
    (H : Type*) [Fintype H] [AddCommGroup H],
    elementarySylowP p H →
      ∀ (f : (H × ZMod p) ≃ (H × ZMod p))
        (lambda : H → (ZMod p)ˣ) (s : H → ZMod p),
        normalizedAffineProfile f lambda s →
          ∃ e : (ZMod p)ˣ, ∃ χ : H →+ ZMod p,
            ∃ α : (H × ZMod p) ≃+ (H × ZMod p),
              e = lambda 0 ∧
              (∀ h : H, ∀ t : ZMod p,
                α (h, t) = (h, (e : ZMod p) * t + χ h)) ∧
              (∀ x : H × ZMod p,
                Set.image (fun y => α y)
                    (normalizedRelativeDerivativeOrbit f x) =
                  Set.image f (normalizedRelativeDerivativeOrbit f x)) ∧
              (∀ h : H, h ∈ additiveLocus lambda s →
                ∀ t : ZMod p, α (h, t) = f (h, t)) ∧
              (∀ h : H, h ∉ additiveLocus lambda s →
                normalizedRelativeDerivativeOrbit f (h, 0) = primeFibre h ∧
                Set.image f (primeFibre h) = primeFibre h ∧
                Set.image (fun y => α y) (primeFibre h) = primeFibre h)

end MathlibPlus.Open.ResearchFormalization.PrimeFibreOrbitShadowR1198
