import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R0088Claim17838

noncomputable section

open scoped BigOperators

/-- The normalized scalar derivative used in a Leibniz block. -/
def normalizedScalarJet (q : ℝ → ℝ) (k : ℕ) (a : ℝ) : ℝ :=
  iteratedDeriv k q a / (k.factorial : ℝ)

/-- The normalized vector-valued jet at one anchor. -/
def normalizedVectorJet {d : ℕ} (v : ℝ → (Fin d → ℝ))
    (k : ℕ) (a : ℝ) : Fin d → ℝ :=
  (k.factorial : ℝ)⁻¹ • iteratedDeriv k v a

/-- The first `m` normalized jets, with vectors as rows and jet order as columns. -/
def normalizedJetBlock {d : ℕ} (v : ℝ → (Fin d → ℝ))
    (m : ℕ) (a : ℝ) : Matrix (Fin d) (Fin m) ℝ :=
  fun u k => normalizedVectorJet v k.val a u

/-- The normalized upper-triangular Leibniz block. -/
def leibnizBlock (q : ℝ → ℝ) (m : ℕ) (a : ℝ) :
    Matrix (Fin m) (Fin m) ℝ :=
  fun i j => if i ≤ j then normalizedScalarJet q (j.val - i.val) a else 0

/-- Multiplication of a vector-valued curve by a scalar factor. -/
def scalarMultiplyCurve {d : ℕ} (q : ℝ → ℝ)
    (v : ℝ → (Fin d → ℝ)) : ℝ → (Fin d → ℝ) :=
  fun s => q s • v s

/-- The osculating subspace generated by the first normalized jets. -/
def osculatingSubspace {d : ℕ} (v : ℝ → (Fin d → ℝ))
    (k : ℕ) (a : ℝ) : Submodule ℝ (Fin d → ℝ) :=
  Submodule.span ℝ (Set.range (fun i : Fin k => normalizedVectorJet v i.val a))

/-- The ordered index type of all jets in a confluent determinant. -/
abbrev ConfluentIndex (r : ℕ) (μ : Fin r → ℕ) := Σ i, Fin (μ i)

/-- A full confluent jet matrix with an explicit ordering of its columns. -/
def confluentJetMatrix {d r : ℕ} (v : ℝ → (Fin d → ℝ))
    (anchors : Fin r → ℝ) (μ : Fin r → ℕ)
    (e : ConfluentIndex r μ ≃ Fin d) : Matrix (Fin d) (Fin d) ℝ :=
  fun u j =>
    let z := e.symm j
    normalizedVectorJet v z.2.val (anchors z.1) u

/-- The scalar determinant factor contributed by a scalar at the anchors. -/
def confluentScale {r : ℕ} (q : ℝ → ℝ)
    (anchors : Fin r → ℝ) (μ : Fin r → ℕ) : ℝ :=
  ∏ i : Fin r, q (anchors i) ^ μ i

/-- Exact full-orientation preservation for a confluent jet determinant. -/
def preservesConfluentOrientation {d r : ℕ} (q : ℝ → ℝ)
    (v : ℝ → (Fin d → ℝ)) (anchors : Fin r → ℝ) (μ : Fin r → ℕ)
    (e : ConfluentIndex r μ ≃ Fin d) : Prop :=
  (∀ i : Fin r, 0 < q (anchors i)) ∧
    Matrix.det (confluentJetMatrix (scalarMultiplyCurve q v) anchors μ e) =
      confluentScale q anchors μ * Matrix.det (confluentJetMatrix v anchors μ e) ∧
    (0 < Matrix.det (confluentJetMatrix (scalarMultiplyCurve q v) anchors μ e) ↔
      0 < Matrix.det (confluentJetMatrix v anchors μ e)) ∧
    (Matrix.det (confluentJetMatrix (scalarMultiplyCurve q v) anchors μ e) < 0 ↔
      Matrix.det (confluentJetMatrix v anchors μ e) < 0)

/-- The positive gamma completion factor fixed by the gamma--Green factor. -/
def gammaCompletionFactor (s : ℝ) : ℝ :=
  Real.pi ^ (-s / 2) * Real.Gamma (1 + s / 2)

/-- The Green factor in the spectral variable. -/
def greenFactor (s : ℝ) : ℝ :=
  s * (1 - s)

/-- The product of the gamma completion and Green factors. -/
def gammaGreenFactor (s : ℝ) : ℝ :=
  gammaCompletionFactor s * greenFactor s

/-- Claim 17838: the exact gamma and gamma--Green multipliers act by positive-
upper-triangular normalized Leibniz blocks, preserving every osculating flag
and every full confluent determinant orientation. -/
def claim17838 : Prop :=
  ∀ (d m : ℕ) (v : ℝ → (Fin d → ℝ)),
    ContDiff ℝ (⊤ : WithTop ℕ∞) v →
      ∀ a : ℝ, 0 < a → a < 1 →
        0 < gammaCompletionFactor a ∧
          0 < gammaGreenFactor a ∧
          normalizedJetBlock (scalarMultiplyCurve gammaCompletionFactor v) m a =
            normalizedJetBlock v m a * leibnizBlock gammaCompletionFactor m a ∧
          normalizedJetBlock (scalarMultiplyCurve gammaGreenFactor v) m a =
            normalizedJetBlock v m a * leibnizBlock gammaGreenFactor m a ∧
          (∀ i j : Fin m, j < i →
            leibnizBlock gammaCompletionFactor m a i j = 0) ∧
          (∀ i j : Fin m, j < i →
            leibnizBlock gammaGreenFactor m a i j = 0) ∧
          (∀ i : Fin m, 0 < leibnizBlock gammaCompletionFactor m a i i) ∧
          (∀ i : Fin m, 0 < leibnizBlock gammaGreenFactor m a i i) ∧
          Matrix.det (leibnizBlock gammaCompletionFactor m a) =
            gammaCompletionFactor a ^ m ∧
          Matrix.det (leibnizBlock gammaGreenFactor m a) =
            gammaGreenFactor a ^ m ∧
          (∀ k : ℕ, k ≤ m →
            osculatingSubspace (scalarMultiplyCurve gammaCompletionFactor v) k a =
              osculatingSubspace v k a ∧
            osculatingSubspace (scalarMultiplyCurve gammaGreenFactor v) k a =
              osculatingSubspace v k a) ∧
          (∀ (r : ℕ) (anchors : Fin r → ℝ) (μ : Fin r → ℕ)
              (e : ConfluentIndex r μ ≃ Fin d),
            (∀ i : Fin r, 0 < μ i) →
              (∀ i : Fin r, 0 < anchors i ∧ anchors i < 1) →
                preservesConfluentOrientation gammaCompletionFactor v anchors μ e ∧
                preservesConfluentOrientation gammaGreenFactor v anchors μ e)

end
end MathlibPlus.Open.ResearchFormalization.R0088Claim17838
