import MathlibPlus.Open.ResearchFormalization.R0322Claim19813

namespace MathlibPlus.Open.ResearchFormalization.R0322Claim19819

open scoped BigOperators Classical
open MathlibPlus.Open.ResearchFormalization.R0322Claim19813

noncomputable section

/-- The degree-k span in the power-sum partition coordinates. -/
def degreePart (k : ℕ) : Submodule ℚ Sym :=
  Submodule.span ℚ (degreeKSpan k)

/-- The degree-k part of the kernel of the specialization map. -/
def kernelPart (k : ℕ) : Submodule ℚ Sym :=
  letI : Module ℚ RationalFunction3 := Algebra.toModule
  LinearMap.ker γ.toLinearMap ⊓ degreePart k

/-- The degree-nine first kernel vector. -/
def degreeNineKernelVector : Sym :=
  p 5 * p 2 * p 2 + p 4 * p 4 * p 1 + p 3 * p 3 * p 3 -
    p 5 * p 3 * p 1 - 2 * (p 4 * p 3 * p 2)

/-- The second displayed degree-ten kernel vector. -/
def degreeTenKernelVector : Sym :=
  p 6 * p 2 * p 2 + p 5 * p 4 * p 1 + p 4 * p 3 * p 3 -
    p 6 * p 3 * p 1 - p 5 * p 3 * p 2 - p 4 * p 4 * p 2

/-- Claim 19819: the first homogeneous kernel occurs in degree nine, with
one generator there, two independent generators in degree ten, and the
kernel ideal is not generated by the degree-nine vector alone. -/
def firstKernelVectors_claim19819 : Prop :=
  (∀ k : ℕ, k < 9 → kernelPart k = ⊥) ∧
  kernelPart 9 = Submodule.span ℚ ({degreeNineKernelVector} : Set Sym) ∧
  Module.finrank ℚ (kernelPart 10) = 2 ∧
  kernelPart 10 =
    Submodule.span ℚ
      ({p 1 * degreeNineKernelVector, degreeTenKernelVector} : Set Sym) ∧
  RingHom.ker γ.toRingHom ≠
    Ideal.span ({degreeNineKernelVector} : Set Sym)

end

end MathlibPlus.Open.ResearchFormalization.R0322Claim19819
