import Mathlib

namespace MathlibPlus.Open.ResearchFormalization

section FiniteUnionClosedFamilies

variable {α : Type*} [DecidableEq α]

/-- The deficit of the principal filter generated by `M` in a finite family. -/
def principalFilterDeficit (F : Finset (Finset α)) (M : Finset α)
    (_hM : M ∈ F) : ℤ :=
  (F.card : ℤ) - 2 * ((F.filter (fun A => M ⊆ A)).card : ℤ)

/-- A finite family of finite sets is union-closed. -/
def unionClosed (F : Finset (Finset α)) : Prop :=
  ∀ ⦃A B : Finset α⦄, A ∈ F → B ∈ F → A ∪ B ∈ F

/-- The trace fiber indexed by an outside support `S`. -/
def outsideSupportTraceFiber (F : Finset (Finset α)) (M S : Finset α) : Set (Finset α) :=
  {T | ∃ A : Finset α, A ∈ F ∧ A \ M = S ∧ T = A ∩ M}

/-- Pairwise union of two trace families. -/
def pairwiseTraceUnion (H K : Set (Finset α)) : Set (Finset α) :=
  {U | ∃ X ∈ H, ∃ Y ∈ K, U = X ∪ Y}

/--
The fiber containment assertions in the outside-support trace claim, with the
finite union-closed-family context made explicit.
-/
def outsideSupportTraceFibersAndProductClosure
    (F : Finset (Finset α)) (M : Finset α) : Prop :=
  M ∈ F ∧ unionClosed F →
    (∀ S : Finset α,
      (outsideSupportTraceFiber F M S).Nonempty →
        M ∈ outsideSupportTraceFiber F M S) ∧
    (∀ S X Y : Finset α,
      X ∈ outsideSupportTraceFiber F M S →
      Y ∈ outsideSupportTraceFiber F M S →
      X ∪ Y ∈ outsideSupportTraceFiber F M S) ∧
    (∀ S T : Finset α,
      pairwiseTraceUnion (outsideSupportTraceFiber F M S)
        (outsideSupportTraceFiber F M T) ⊆
        outsideSupportTraceFiber F M (S ∪ T))

/-- The grounded zero-support condition. -/
def groundedZeroSupportCondition
    (F : Finset (Finset α)) (M : Finset α) : Prop :=
  {A : Finset α | A ∈ F ∧ A ⊆ M} = ({M} : Set (Finset α))

/-- The zero outside-support trace fiber. -/
def zeroOutsideSupportTraceFiber
    (F : Finset (Finset α)) (M : Finset α) : Set (Finset α) :=
  outsideSupportTraceFiber F M ∅

/-- Groundedness is equivalent to the zero outside-support fiber being top-only. -/
def groundedZeroSupportEquivalence
    (F : Finset (Finset α)) (M : Finset α) : Prop :=
  groundedZeroSupportCondition F M ↔
    zeroOutsideSupportTraceFiber F M = ({M} : Set (Finset α))

/-- The neutral trace type is exactly `{∅, M}`. -/
def neutralTraceType (M : Finset α) (H : Set (Finset α)) : Prop :=
  H = ({∅, M} : Set (Finset α))

/-- A nonempty trace type other than the neutral one is essential. -/
def essentialTraceType (M : Finset α) (H : Set (Finset α)) : Prop :=
  H.Nonempty ∧ H ≠ ({∅, M} : Set (Finset α))

/--
The grounded, neutral, and essential trace-type conventions from the admitted
claim, stated together without adding a classification of any further fibers.
-/
def groundedNeutralAndEssentialTraceTypes
    (F : Finset (Finset α)) (M : Finset α) : Prop :=
  groundedZeroSupportEquivalence F M ∧
  (∀ H : Set (Finset α),
    neutralTraceType M H ↔ H = ({∅, M} : Set (Finset α))) ∧
  (∀ H : Set (Finset α),
    essentialTraceType M H ↔
      (H.Nonempty ∧ H ≠ ({∅, M} : Set (Finset α))))

/-- The ground coordinates of a finite set family. -/
def coordinateGround (F : Finset (Finset α)) : Finset α :=
  F.biUnion (fun A => A)

/-- The frequency of a coordinate in a finite set family. -/
def coordinateFrequency (F : Finset (Finset α)) (x : α) : ℕ :=
  (F.filter (fun A => x ∈ A)).card

/-- Frankl's frequency conclusion for a finite family. -/
def satisfiesFrankl (F : Finset (Finset α)) : Prop :=
  ∃ x ∈ coordinateGround F, 2 * coordinateFrequency F x ≥ F.card

/-- Nonabundance of every ground coordinate. -/
def noAbundantCoordinate (F : Finset (Finset α)) : Prop :=
  ∀ x ∈ coordinateGround F, 2 * coordinateFrequency F x < F.card

/-- A finite union-closed family with no abundant coordinate. -/
def franklCounterexample (F : Finset (Finset α)) : Prop :=
  F.Nonempty ∧ unionClosed F ∧ noAbundantCoordinate F

/-- Minimum cardinality among counterexamples on the fixed coordinate universe. -/
def minimumCardinalityFranklCounterexample (F : Finset (Finset α)) : Prop :=
  franklCounterexample F ∧
    ∀ G : Finset (Finset α), franklCounterexample G → F.card ≤ G.card

/-- Removing `M` preserves union-closure. -/
def removableMember
    (F : Finset (Finset α)) (M : Finset α) : Prop :=
  M ∈ F ∧ unionClosed (F.erase M)

/-- Tightness at odd cardinality. -/
def tightCoordinate (F : Finset (Finset α)) (x : α) : Prop :=
  2 * coordinateFrequency F x = F.card - 1

/--
Removing a removable member that contains exactly the currently tight
coordinates forces the Frankl witness for the remainder to be an outside tight
coordinate of the original family.
-/
def removingMemberContainingAllTightCoordinates :
    Finset (Finset α) → Finset α → Prop
  | F, M =>
      minimumCardinalityFranklCounterexample F →
      F.card % 2 = 1 →
      removableMember F M →
      (∀ x, x ∈ M → tightCoordinate F x) →
      (∀ x, x ∈ coordinateGround F → tightCoordinate F x → x ∈ M) →
      ∃ x ∈ coordinateGround (F.erase M),
        2 * coordinateFrequency (F.erase M) x ≥ F.card - 1 ∧
        x ∉ M ∧ tightCoordinate F x

end FiniteUnionClosedFamilies

end MathlibPlus.Open.ResearchFormalization
