import MathlibPlus.Open.ResearchFormalization.BatchHigherTwists

namespace MathlibPlus.Open.ResearchFormalization.R0970Claim27739

open MathlibPlus.Open.ResearchFormalization

abbrev QuadraticScalar := HigherScalar
abbrev QuadraticCoefficient := Fin 5 → QuadraticScalar
abbrev QuadraticClass := Fin 3 → QuadraticScalar

/-- The five-term quadratic plane polynomial in the coordinates `(i,j)`. -/
def quadraticPlaneFunction (c : QuadraticCoefficient) : HigherFunction :=
  fun i j =>
    c 0 * i + c 1 * j + c 2 * i ^ 2 + c 3 * i * j + c 4 * j ^ 2

/-- The displayed six-coordinate transporter
`(z,h) ↦ (z + φ(i,j), g(h))`. -/
def quadraticQ (c : QuadraticCoefficient) : HigherRankSix ≃ HigherRankSix :=
  higherTwist (quadraticPlaneFunction c)

/-- The competing group generated by the translation group and its displayed
conjugate. -/
noncomputable def quadraticGeneratedGroup (c : QuadraticCoefficient) :
    Subgroup (Equiv.Perm HigherRankSix) :=
  higherGeneratedGroup (quadraticPlaneFunction c)

/-- The three coefficients that index the distinct quadratic competing groups. -/
def quadraticClass (c : QuadraticCoefficient) : QuadraticClass :=
  ![c 2, c 3, c 4]

def canonicalQuadraticCoefficients (w : QuadraticClass) : QuadraticCoefficient :=
  ![0, 0, w 0, w 1, w 2]

noncomputable def quadraticGroupMap (c : QuadraticCoefficient) :
    Subgroup (Equiv.Perm HigherRankSix) :=
  quadraticGeneratedGroup c

noncomputable def quadraticConjugateTranslationGroup (c : QuadraticCoefficient) :
    Subgroup (Equiv.Perm HigherRankSix) :=
  higherConjugateSubgroup higherTranslationGroup (quadraticQ c)

def isRegularPermutationSubgroup
    (H : Subgroup (Equiv.Perm HigherRankSix)) : Prop :=
  ∀ x y : HigherRankSix, ∃! h : H,
    (h : Equiv.Perm HigherRankSix) x = y

/-- Claim 27739: the 243 quadratic plane polynomials produce precisely the
    27 distinct competing generated groups indexed by `(γ,δ,ε)`, while the
    two regular groups in every competing pair retain their literal carriers.
-/
def claim27739_quadraticPlaneFiberTwists : Prop :=
  Fintype.card QuadraticCoefficient = 3 ^ 5 ∧
    Fintype.card QuadraticCoefficient = 243 ∧
    Fintype.card QuadraticClass = 3 ^ 3 ∧
    Fintype.card QuadraticClass = 27 ∧
    (∀ c : QuadraticCoefficient,
      quadraticGeneratedGroup c =
        quadraticGeneratedGroup (canonicalQuadraticCoefficients
          (quadraticClass c))) ∧
    Function.Injective
      (fun w : QuadraticClass =>
        quadraticGeneratedGroup (canonicalQuadraticCoefficients w)) ∧
    Set.ncard (Set.range quadraticGroupMap) = 3 ^ 3 ∧
    Set.ncard (Set.range quadraticGroupMap) = 27 ∧
    isRegularPermutationSubgroup higherTranslationGroup ∧
    (∀ c : QuadraticCoefficient,
      isRegularPermutationSubgroup
        (quadraticConjugateTranslationGroup c))

end MathlibPlus.Open.ResearchFormalization.R0970Claim27739
