import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R0982Claim27877

noncomputable section

abbrev Plane (p : ℕ) := ZMod p × ZMod p
abbrev Fiber (p : ℕ) := ZMod p × ZMod p × ZMod p
abbrev H (p : ℕ) := Plane p × Fiber p

/-- The lower-coordinate shear with a plane-dependent fibre increment. -/
def lowerShear (p : ℕ) (f : Plane p → Fiber p) :
    Equiv.Perm (H p) :=
  let e := Equiv.sigmaEquivProd (Plane p) (Fiber p)
  (e.symm.trans
      (Equiv.sigmaCongrRight (fun u => Equiv.addRight (f u)))).trans e

/-- The displayed `x` action on `(i,j,a,b,c)`. -/
def xGenerator (p : ℕ) : Equiv.Perm (H p) :=
  lowerShear p (fun u => (u.1, u.2, 0))

/-- The displayed `y` action on `(i,j,a,b,c)`. -/
def yGenerator (p : ℕ) : Equiv.Perm (H p) :=
  lowerShear p (fun u => (0, u.1, u.2))

/-- The regular translation subgroup `H_R`. -/
def translationSubgroup (p : ℕ) :
    Subgroup (Equiv.Perm (H p)) :=
  Subgroup.closure
    (Set.range (fun h : H p => Equiv.addRight h))

/-- The translation subgroup in the lower coordinates `(a,b,c)`. -/
def lowerTranslationSubgroup (p : ℕ) :
    Subgroup (Equiv.Perm (H p)) :=
  Subgroup.closure
    (Set.range (fun v : Fiber p =>
      Equiv.addRight ((0, v) : H p)))

/-- `X=H_R ⋊ ⟨x,y⟩`, represented by the subgroup generated by the exact
    regular translations and the two displayed shears. -/
def rankFiveGroup (p : ℕ) :
    Subgroup (Equiv.Perm (H p)) :=
  Subgroup.closure
    ((translationSubgroup p : Set (Equiv.Perm (H p))) ∪
      {xGenerator p, yGenerator p})

/-- The centre of `X`, viewed as a subgroup of the ambient permutation group. -/
def ambientCenter (X : Subgroup (Equiv.Perm (H p))) :
    Subgroup (Equiv.Perm (H p)) :=
  Subgroup.map X.subtype (Subgroup.center X)

/-- The subgroup generated by all group commutators in `X`. -/
def ambientCommutator (X : Subgroup (Equiv.Perm (H p))) :
    Subgroup (Equiv.Perm (H p)) :=
  Subgroup.closure
    {g : Equiv.Perm (H p) | ∃ x y : X,
      g = (x : Equiv.Perm (H p))⁻¹ *
          (y : Equiv.Perm (H p))⁻¹ *
          (x : Equiv.Perm (H p)) *
          (y : Equiv.Perm (H p))}

/-- The translation subgroup in the lower three coordinates is the centre and
    derived subgroup of the displayed odd-prime rank-five group. -/
def claim27877 : Prop :=
  ∀ (p : ℕ), Nat.Prime p → Odd p →
    let X := rankFiveGroup p
    let U := lowerTranslationSubgroup p
    U = ambientCenter X ∧
      U = ambientCommutator X ∧
      Nonempty (U ≃* Multiplicative (ZMod p × ZMod p × ZMod p))

end

end MathlibPlus.Open.ResearchFormalization.R0982Claim27877
