import MathlibPlus.Open.ResearchFormalization.R0982Claim27877

namespace MathlibPlus.Open.ResearchFormalization.R0982Claim27874

noncomputable section

open MathlibPlus.Open.ResearchFormalization.R0982Claim27877

/-- The displayed quadratic permutation formula on the exact rank-five
carrier `H p = (𝔽_p × 𝔽_p) × (𝔽_p × 𝔽_p × 𝔽_p)`. -/
def quadraticQuotientFormula (p : ℕ) (h : H p) : H p :=
  ((h.1.1, h.1.2),
    (h.2.1 + h.1.1 * (h.1.1 - 1),
      h.2.2.1 + (2 * h.1.1 - 1) * h.1.2,
      h.2.2.2 + h.1.2 ^ 2))

/-- A model carrying the three displayed permutations.  The quotient group is
not rebuilt with a guessed law: its exact subgroup carrier is the reviewed
`rankFiveGroup p`, generated by the regular translations and the displayed
`xGenerator` and `yGenerator`. -/
structure RankFiveQuadraticQuotientModel (p : ℕ) where
  X : Subgroup (Equiv.Perm (H p))
  x : Equiv.Perm (H p)
  y : Equiv.Perm (H p)
  g : Equiv.Perm (H p)
  X_spec : X = rankFiveGroup p
  x_spec : x = xGenerator p
  y_spec : y = yGenerator p
  g_spec : ∀ h, g h = quadraticQuotientFormula p h

/-- Claim 27874: for every odd prime, the exact rank-five quotient carrier has
its displayed `x`, `y`, and quadratic `g` permutations, with
`X = H_R ⋊ ⟨x,y⟩` represented by the reviewed generated subgroup. -/
def oddPrimeRankFiveQuadraticQuotient_claim27874 : Prop :=
  ∀ (p : ℕ), Nat.Prime p → Odd p →
    Nonempty (RankFiveQuadraticQuotientModel p)

end

end MathlibPlus.Open.ResearchFormalization.R0982Claim27874
