import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R0982Claim27869

noncomputable section

abbrev TernaryField := ZMod 3
abbrev TernaryPlane := TernaryField × TernaryField
abbrev TernaryFiber := Fin 3 → TernaryField
abbrev TernaryH := TernaryPlane × TernaryFiber
abbrev TernaryE := TernaryField × TernaryH

/-- The fixed quadratic part of the ternary transporter. -/
def quadraticF (u : TernaryPlane) : TernaryFiber :=
  ![u.1 * (u.1 - 1), (2 * u.1 - 1) * u.2, u.2 ^ 2]

/-- The displayed action of `q_phi` on the exact six-coordinate carrier. -/
def qPhiSpec (φ : TernaryPlane → TernaryField)
    (q : Equiv.Perm TernaryE) : Prop :=
  ∀ z u w,
    q (z, (u, w)) = (z + φ u, (u, w + quadraticF u))

/-- The regular translation subgroup `T=E_R`. -/
def translationSubgroup : Subgroup (Equiv.Perm TernaryE) :=
  Subgroup.closure
    (Set.range (fun v : TernaryE => (Equiv.addRight v : Equiv.Perm TernaryE)))

/-- The conjugate translation set `T^q`. -/
def conjugatedTranslations (q : Equiv.Perm TernaryE) :
    Set (Equiv.Perm TernaryE) :=
  {u | ∃ t : translationSubgroup,
    u = q⁻¹ * (t : Equiv.Perm TernaryE) * q}

/-- `G_phi` is generated by the translations and their displayed conjugate. -/
def generatedGroup (q : Equiv.Perm TernaryE) :
    Subgroup (Equiv.Perm TernaryE) :=
  Subgroup.closure
    ((translationSubgroup : Set (Equiv.Perm TernaryE)) ∪
      conjugatedTranslations q)

/-- Exact ordered-orbital two-closure membership. -/
def twoClosure (G : Subgroup (Equiv.Perm TernaryE)) :
    Set (Equiv.Perm TernaryE) :=
  {c | ∀ x y : TernaryE, ∃ g : G,
    c x = (g : Equiv.Perm TernaryE) x ∧
      c y = (g : Equiv.Perm TernaryE) y}

/-- Claim 27869: every normalized ternary plane transporter conjugates the
translation subgroup to its displayed conjugate using a conjugator in the
exact two-closure of the group generated by that pair. -/
def claim27869 : Prop :=
  ∀ (φ : TernaryPlane → TernaryField), φ 0 = 0 →
    ∃ q : Equiv.Perm TernaryE,
      qPhiSpec φ q ∧
        ∃ c : Equiv.Perm TernaryE,
          c ∈ twoClosure (generatedGroup q) ∧
            Set.image (fun t : Equiv.Perm TernaryE => c⁻¹ * t * c)
                (translationSubgroup : Set (Equiv.Perm TernaryE)) =
              Set.image (fun t : Equiv.Perm TernaryE => q⁻¹ * t * q)
                (translationSubgroup : Set (Equiv.Perm TernaryE))

end

end MathlibPlus.Open.ResearchFormalization.R0982Claim27869
