import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R0983Claim27896

noncomputable section

/-- The displacement subgroup generated by the exact displacements
`t - p(t) + p(0)`. -/
def displacementSubgroup27896
    (B : Type*) [AddCommGroup B] (p : Equiv.Perm B) : AddSubgroup B :=
  AddSubgroup.closure (Set.range (fun t : B => t - p t + p 0))

/-- The additive coset of `W` represented by `x`. -/
def coset27896 {B : Type*} [AddGroup B]
    (W : AddSubgroup B) (x : B) : Set B :=
  {y | y - x ∈ W}

/-- Claim 27896: a permutation is translation by `p(0)` modulo its exact
 displacement subgroup, and therefore bijects every such coset onto the
 coset represented by the image of its representative. -/
def claim27896 : Prop :=
  ∀ (B : Type*) [Fintype B] [AddCommGroup B],
    Odd (Fintype.card B) →
      ∀ p : Equiv.Perm B,
        let c := p 0
        let W := displacementSubgroup27896 B p
        (∀ x : B,
          QuotientAddGroup.mk' W (p x) =
            QuotientAddGroup.mk' W x + QuotientAddGroup.mk' W c) ∧
          (∀ x : B,
            Set.BijOn (p : B → B) (coset27896 W x) (coset27896 W (p x)) ∧
              Set.image (p : B → B) (coset27896 W x) =
                coset27896 W (p x))

end

end MathlibPlus.Open.ResearchFormalization.R0983Claim27896
