import Mathlib
import MathlibPlus.Open.Research.FormalizationBatch019ffee2

namespace MathlibPlus.Open.ResearchFormalization.R1060Claim32945

open MathlibPlus.Open.Research.FormalizationBatch

noncomputable section

/-- The exponent equality forced by a characteristic-layer scalar period. -/
def resonantScalarPeriodEquation (p q : ℕ) (ζ : (ZMod p)ˣ)
    (r : Fin 4 → ZMod q) : Prop :=
  ∀ (s y : ZMod q) (i : Fin 4),
    ζ ^ (r i * (s + y)).val = ζ ^ (r i * y).val

/-- The characteristic cyclic subgroup of the displayed quaternion chart. -/
def characteristicScalarLayer (q : ℕ) : Set (Q4qCarrier q) :=
  {h | h.2 = 0}

/-- The trivial scalar stabilizer. -/
def trivialScalarStabilizer (q : ℕ) : Set (Q4qCarrier q) :=
  {(0, 0)}

/-- The central involution together with the identity. -/
def centralScalarStabilizer (q : ℕ) : Set (Q4qCarrier q) :=
  {(0, 0), (0, 2)}

/-- The order-four axis generated by `(a,1)` in the quaternion chart. -/
def c4AxisScalarStabilizer (q : ℕ) (a : ZMod q) : Set (Q4qCarrier q) :=
  {h | h = (0, 0) ∨ h = (a, 1) ∨ h = (0, 2) ∨ h = (a, 3)}

/-- Claim 32945.  The scalar period is the actual left stabilizer from the
triangular chart.  Its characteristic-layer case gives the displayed zeta
residue equation and forces a zero exponent profile; for a nonzero profile,
only the trivial, central, and order-four-axis stabilizers remain. -/
def resonantScalarStabilizerClaim32945 : Prop :=
  ∀ (p q : ℕ),
    Nat.Prime p → Nat.Prime q → p ≠ q → 2 < p → 2 < q → q ∣ p - 1 →
    ∀ (ζ : (ZMod p)ˣ) (r u t : Fin 4 → ZMod q)
      (π : Fin 4 → Fin 4),
      orderOf ζ = q →
      Function.Bijective π → (∀ i, u i ≠ 0) → t 0 = 0 → π 0 = 0 →
      let K := scalarPeriod40102 p q ζ r u t π
      (q4qSubgroup40102 q K ∧
        ((∀ s : ZMod q, (s, 0) ∈ K) →
          resonantScalarPeriodEquation p q ζ r ∧ ∀ i, r i = 0) ∧
        ((∃ i, r i ≠ 0) →
          ¬(∀ s : ZMod q, (s, 0) ∈ K)) ∧
        ((∃ i, r i ≠ 0) →
          K = trivialScalarStabilizer q ∨
            K = centralScalarStabilizer q ∨
              ∃ a : ZMod q, K = c4AxisScalarStabilizer q a))

end

end MathlibPlus.Open.ResearchFormalization.R1060Claim32945
