import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1067

noncomputable section

open scoped BigOperators

abbrev F3Square := ZMod 3 × ZMod 3

def horizontal : AddSubgroup F3Square :=
  (⊤ : AddSubgroup (ZMod 3)).prod (⊥ : AddSubgroup (ZMod 3))

def vertical : AddSubgroup F3Square :=
  (⊥ : AddSubgroup (ZMod 3)).prod (⊤ : AddSubgroup (ZMod 3))

/-- The subgroup of permutations given by translations from an additive
subgroup. -/
def translationSubgroup {B : Type*} [AddCommGroup B]
    (L : AddSubgroup B) : Subgroup (Equiv.Perm B) :=
  Subgroup.closure (Set.range (fun h : L => Equiv.addRight (h : B)))

/-- Conjugation by the inverse permutation, matching p⁻¹ T p. -/
def conjugateSubgroup {B : Type*}
    (p : Equiv.Perm B) (H : Subgroup (Equiv.Perm B)) :
    Subgroup (Equiv.Perm B) :=
  H.map (MulAut.conj p⁻¹)

/-- Membership in a permutation subgroup's orbit relation. -/
def orbitRelated {B : Type*}
    (H : Subgroup (Equiv.Perm B)) (x y : B) : Prop :=
  ∃ g : H, (g : Equiv.Perm B) x = y

/-- One of the two cross-derivative permutation families. -/
def crossDerivative {B : Type*} [AddCommGroup B]
    (q r : Equiv.Perm B) (t : B) : Equiv.Perm B :=
  Equiv.addRight (-(q t)) * r * Equiv.addRight t

/-- The local collision group generated by both cross-derivative families and
an opposite-fiber translation subgroup. -/
def localCollisionGroup {B : Type*} [AddCommGroup B]
    (q r : Equiv.Perm B) (L : AddSubgroup B) :
    Subgroup (Equiv.Perm B) :=
  Subgroup.closure (
    Set.range (crossDerivative q r) ∪
      Set.range (crossDerivative r q) ∪
      (translationSubgroup L : Set (Equiv.Perm B)))

/-- The displacement subgroup W(q) from the admitted counterexamples. -/
def displacementSubgroup {B : Type*} [AddCommGroup B]
    (q : Equiv.Perm B) : AddSubgroup B :=
  AddSubgroup.closure (Set.range (fun t : B => t - q t + q 0))

def swapCoordinates : Equiv.Perm F3Square :=
  Equiv.prodComm (ZMod 3) (ZMod 3)

def reflectFirstCoordinate : Equiv.Perm F3Square :=
  Equiv.prodCongr (Equiv.neg (ZMod 3)) (Equiv.refl (ZMod 3))

/-- In F₃², conjugating horizontal translations by the coordinate swap gives
vertical translations, and the resulting group has three three-point orbits. -/
def jointSpanWithoutAlignmentCounterexample : Prop :=
  let H := horizontal
  let K := vertical
  let p := swapCoordinates
  let TH := translationSubgroup H
  let TK := translationSubgroup K
  let conjugate := conjugateSubgroup p TH
  let generated :=
    Subgroup.closure ((conjugate : Set (Equiv.Perm F3Square)) ∪
      (TK : Set (Equiv.Perm F3Square)))
  H ⊔ K = ⊤ ∧
    conjugate = TK ∧
    generated = TK ∧
    (∀ x y : F3Square, orbitRelated TK x y ↔ x.1 = y.1) ∧
    ¬(∀ x y : F3Square, orbitRelated TK x y)

/-- The reflection/vertical-translation counterfeit: the displacement spans
jointly, but the local collision action has exactly two orbits. -/
def properDisplacementJointSpanCounterexample : Prop :=
  let q := reflectFirstCoordinate
  let L := vertical
  let C := localCollisionGroup q q L
  displacementSubgroup q = horizontal ∧
    horizontal ⊔ L = ⊤ ∧
    (∀ x y : F3Square,
      orbitRelated C x y ↔
        ((x.1 = 0 ∧ y.1 = 0) ∨ (x.1 ≠ 0 ∧ y.1 ≠ 0))) ∧
    ¬(∀ x y : F3Square, orbitRelated C x y)

/-- For q=r=-id and zero opposite displacement, the local orbits are the
central-inversion pairs. -/
def mixedFullFullZeroCounterexample : Prop :=
  let q := Equiv.neg F3Square
  let L := (⊥ : AddSubgroup F3Square)
  let C := localCollisionGroup q q L
  displacementSubgroup q = ⊤ ∧
    (∀ t : F3Square, crossDerivative q q t = q) ∧
    (∀ x y : F3Square,
      orbitRelated C x y ↔ y = x ∨ y = -x) ∧
    ¬(∀ x y : F3Square, orbitRelated C x y)

end

end MathlibPlus.Open.ResearchFormalization.R1067
