import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1068Claim28557

noncomputable section

private abbrev HGroup (r : ℕ) :=
  Multiplicative ((Fin r → ZMod 2) × ZMod 9)

private def inverseClosed {G : Type*} [Group G] (S : Set G) : Prop :=
  ∀ ⦃x : G⦄, x ∈ S → x⁻¹ ∈ S

private def identityFree {G : Type*} [Group G] (S : Set G) : Prop :=
  (1 : G) ∉ S

private def preservesGraph {V : Type*}
    (Γ : SimpleGraph V) (R : Subgroup (Equiv.Perm V)) : Prop :=
  ∀ e ∈ R, ∀ x y, Γ.Adj (e x) (e y) ↔ Γ.Adj x y

private def regularGraphSubgroup {V : Type*}
    (R : Subgroup (Equiv.Perm V)) : Prop :=
  ∀ x y : V, ∃! r : R, (r : Equiv.Perm V) x = y

private def copyOfH (r : ℕ) {V : Type*}
    (R : Subgroup (Equiv.Perm V)) : Prop :=
  Nonempty (R ≃* HGroup r)

private def generatedCopies {V : Type*}
    (R T : Subgroup (Equiv.Perm V)) : Subgroup (Equiv.Perm V) :=
  Subgroup.closure ((R : Set (Equiv.Perm V)) ∪ (T : Set (Equiv.Perm V)))

private def primitiveAction {V : Type*}
    (K : Subgroup (Equiv.Perm V)) : Prop :=
  ∀ E : Setoid V,
    (∀ g : K, ∀ x y : V,
      E.r x y ↔
        E.r ((g : Equiv.Perm V) x) ((g : Equiv.Perm V) y)) →
    ((∀ x y : V, E.r x y) ∨
      (∀ x y : V, E.r x y ↔ x = y))

private def emptyGraph {V : Type*} (Γ : SimpleGraph V) : Prop :=
  ∀ x y, ¬ Γ.Adj x y

private def completeGraph {V : Type*} (Γ : SimpleGraph V) : Prop :=
  ∀ x y, x ≠ y → Γ.Adj x y

private def symmetricGraphAut {V : Type*} (Γ : SimpleGraph V) : Prop :=
  ∀ e : Equiv.Perm V, ∀ x y, Γ.Adj (e x) (e y) ↔ Γ.Adj x y

private def conjugateCopies {V : Type*} (Γ : SimpleGraph V)
    (R T : Subgroup (Equiv.Perm V)) : Prop :=
  ∃ a : Equiv.Perm V,
    (∀ x y, Γ.Adj (a x) (a y) ↔ Γ.Adj x y) ∧
      Set.image (fun x : Equiv.Perm V => a * x * a⁻¹)
        (R : Set (Equiv.Perm V)) = (T : Set (Equiv.Perm V))

private def CayleyWitnessData (r : ℕ) (G : Type*) [Group G] [Fintype G]
    (S : Set G) : Prop :=
  (r = 3 ∨ r = 4 ∨ r = 5) ∧
    inverseClosed S ∧ identityFree S

/-- Claim 28557: for the exact Cayley graph and graph-automorphism carriers,
    a primitive group generated by two regular H_r copies forces the empty or
    complete graph and conjugacy in its full symmetric automorphism group. -/
def primitiveGeneratedCayleyPairs_claim28557 : Prop :=
  ∀ (r : ℕ) (G : Type*) [Group G] [Fintype G] (S : Set G),
    CayleyWitnessData r G S →
    let Γ := SimpleGraph.mulCayley S
    ∀ R T : Subgroup (Equiv.Perm G),
      regularGraphSubgroup R → copyOfH r R → preservesGraph Γ R →
      regularGraphSubgroup T → copyOfH r T → preservesGraph Γ T →
      primitiveAction (generatedCopies R T) →
      (emptyGraph Γ ∨ completeGraph Γ) ∧
        symmetricGraphAut Γ ∧ conjugateCopies Γ R T


end

end MathlibPlus.Open.ResearchFormalization.R1068Claim28557
