import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1077Claim28667

abbrev K3 := ZMod 3
abbrev X3 := K3 × K3
abbrev V3 (m : ℕ) := Fin m → K3

def e₁ : X3 :=
  (1, 0)

def e₂ : X3 :=
  (0, 1)

def d : X3 :=
  e₁ + e₂

def h : X3 :=
  e₁ - e₂

def oddMap {m : ℕ} (f : X3 → V3 m) : Prop :=
  ∀ x : X3, f (-x) = -f x

def normalizedSecondDerivative {m : ℕ} (f : X3 → V3 m)
    (a c x : X3) : V3 m :=
  (f (x + c + a) - f (x + c)) - (f (c + a) - f c)

def correctedMap {m : ℕ} (f : X3 → V3 m)
    (ℓ : X3 →ₗ[K3] V3 m) : X3 → V3 m :=
  fun x => f x + ℓ x

def derivativeSpan {m : ℕ} (f : X3 → V3 m) (x : X3) :
    Submodule K3 (V3 m) :=
  Submodule.span K3
    (Set.range (fun ac : X3 × X3 =>
      normalizedSecondDerivative f ac.1 ac.2 x))

def defectSpan {m : ℕ} (A B : V3 m) : Submodule K3 (V3 m) :=
  Submodule.span K3 ({A, B} : Set (V3 m))

/-- Claim 28667: after the same correction as in Claim 28666, every nonzero
point has exactly the span generated by the two diagonal defects, and every
value of the corrected map lies in its corresponding derivative span. -/
def claim28667 : Prop :=
  ∀ (m : ℕ) (f : X3 → V3 m)
    (ℓ : X3 →ₗ[K3] V3 m),
    oddMap f →
    ℓ e₁ = -f e₁ →
    ℓ e₂ = -f e₂ →
    let g := correctedMap f ℓ
    let A := g d
    let B := g h
    (∀ x : X3, x ≠ 0 →
      derivativeSpan f x = defectSpan A B ∧
      derivativeSpan g x = defectSpan A B) ∧
    (∀ x : X3, g x ∈ derivativeSpan f x)

end MathlibPlus.Open.ResearchFormalization.R1077Claim28667
