import MathlibPlus.Open.NewResearch2.R1151NormalizedCollisionDataClaim31590

namespace MathlibPlus.Open.ResearchFormalization.R1151

open MathlibPlus.Open.NewResearch2.R1151NormalizedCollisionData

noncomputable section

abbrev Base := Base41353
abbrev Fiber := Fiber41353
abbrev Carrier := G41353

def activeSupport : Finset Base :=
  {baseMasks41353 1, baseMasks41353 2, baseMasks41353 3}

def normalizedFiberMap
    (q : Base → Equiv.Perm Fiber) : Carrier → Carrier :=
  fun x => (rho041353 x.1, q x.1 x.2)

def displacementGenerators
    (q : Base → Equiv.Perm Fiber) (u : Base) : Set Fiber :=
  {w | ∃ t : Fiber, w = t - q u t + q u 0}

def displacementSubgroup
    (q : Base → Equiv.Perm Fiber) (u : Base) : AddSubgroup Fiber :=
  AddSubgroup.closure (displacementGenerators q u)

def fullRow
    (q : Base → Equiv.Perm Fiber) (u : Base) : Prop :=
  displacementSubgroup q u = ⊤

def properRow
    (q : Base → Equiv.Perm Fiber) (u : Base) : Prop :=
  displacementSubgroup q u ≠ ⊤

/-- Claim 41354: on the exact `C₂³ × C₃²` normalized collision carrier with
rho-zero `(0,1,2,3,4,5,7,6)` and active support `{1,2,3}`, each active row's
subgroup is generated by `t-q_u(t)+q_u(0)`, and full/proper are the exact
complementary row predicates. -/
def claim41354 : Prop :=
  ∀ (q : Base → Equiv.Perm Fiber),
    (∀ a : Base,
      q a ≠ 1 ↔ a ∈ activeSupport) →
      (∃ f : Equiv.Perm Carrier,
        ∀ a : Base, ∀ b : Fiber,
          f (a, b) = (rho041353 a, q a b)) ∧
        ∀ u : Base, u ∈ activeSupport →
          let W := displacementSubgroup q u
          W ≤ (⊤ : AddSubgroup Fiber) ∧
            (fullRow q u ↔ W = ⊤) ∧
              (properRow q u ↔ W ≠ ⊤) ∧
                (fullRow q u ∨ properRow q u) ∧
                  ¬ (fullRow q u ∧ properRow q u)

end
end MathlibPlus.Open.ResearchFormalization.R1151
