import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1155C41415

noncomputable section

abbrev Boolean := ZMod 2
abbrev TwistedCarrier (H : Type*) := H × Boolean

/-- The twisted central-extension multiplication. -/
def twistedMul {H : Type*} [Add H]
    (κ : H → H → Boolean) (x y : TwistedCarrier H) :
    TwistedCarrier H :=
  (x.1 + y.1, x.2 + y.2 + κ x.1 y.1)

/-- The group-law obligations for the twisted central extension. -/
def twistedExtensionLaw {H : Type*} [AddCommGroup H]
    (κ : H → H → Boolean) : Prop :=
  (∀ x y z,
    twistedMul κ (twistedMul κ x y) z =
      twistedMul κ x (twistedMul κ y z)) ∧
    (∀ x,
      twistedMul κ (0, 0) x = x ∧ twistedMul κ x (0, 0) = x) ∧
    (∀ x, ∃ y,
      twistedMul κ x y = (0, 0) ∧ twistedMul κ y x = (0, 0))

/-- A bijective homomorphism of the displayed twisted carrier. -/
def preservesTwistedLaw {H : Type*} [Add H]
    (κ : H → H → Boolean)
    (f : TwistedCarrier H → TwistedCarrier H) : Prop :=
  Function.Bijective f ∧
    ∀ x y, f (twistedMul κ x y) = twistedMul κ (f x) (f y)

/-- The normalized Boolean switching map `f_b`. -/
def booleanSwitch {H : Type*} (b : H → Boolean) :
    TwistedCarrier H → TwistedCarrier H :=
  fun x => (x.1, x.2 + b x.1)

/-- The central shear associated with an extending character. -/
def characterShear {H : Type*} [AddMonoid H]
    (χ : H →+ Boolean) : TwistedCarrier H → TwistedCarrier H :=
  fun x => (x.1, x.2 + χ x.1)

/-- The exact linearity condition and its set carrier. -/
def linearityCondition {H : Type*} [AddCommGroup H]
    (b : H → Boolean) (h : H) : Prop :=
  ∀ u : H, b (h + u) = b h + b u

def linearitySet {H : Type*} [AddCommGroup H]
    (b : H → Boolean) : Set H :=
  {h | linearityCondition b h}

/-- The cocycle-cancelled normalized relative-derivative step. -/
def relativeDerivativeStep {H : Type*} [AddCommGroup H]
    (b : H → Boolean) (x y : TwistedCarrier H) : Prop :=
  ∃ u : H,
    y = (x.1, x.2 + b (x.1 + u) + b x.1 + b u)

/-- The orbit generated by all normalized relative-derivative steps. -/
def relativeDerivativeOrbit {H : Type*} [AddCommGroup H]
    (b : H → Boolean) (x : TwistedCarrier H) : Set (TwistedCarrier H) :=
  {y | Relation.ReflTransGen (relativeDerivativeStep b) x y}

def singletonFiberOrbit {H : Type*} (h : H) (e : Boolean) :
    Set (TwistedCarrier H) :=
  {(h, e)}

def fullFiberOrbit {H : Type*} (h : H) : Set (TwistedCarrier H) :=
  {(h, 0), (h, 1)}

/-- Claim 41415: on the odd-factor times `C₂²` carrier, an already extending
character is an automorphism shadow of the twisted extension; the exact
singleton/full-fibre orbit dichotomy and image equality are retained. -/
def claim41415_characterShearDerivativeOrbitShadow : Prop :=
  ∀ (A : Type*) [AddCommGroup A] [Fintype A],
    Odd (Fintype.card A) →
    let H := A × (Boolean × Boolean)
    ∀ (κ : H → H → Boolean) (b : H → Boolean)
      (L : AddSubgroup H) (χ : H →+ Boolean),
      twistedExtensionLaw κ → b (0 : H) = 0 →
      (∀ h : H, h ∈ L ↔ h ∈ linearitySet b) →
      (∀ x y : L, b (x.1 + y.1) = b x.1 + b y.1) →
      (∀ h : L, χ h.1 = b h.1) →
      preservesTwistedLaw κ (characterShear χ) ∧
        (∀ h : H, ∀ e : Boolean,
          (h ∈ L →
            relativeDerivativeOrbit b (h, e) = singletonFiberOrbit h e) ∧
          (h ∉ L →
            relativeDerivativeOrbit b (h, e) = fullFiberOrbit h)) ∧
        (∀ x : TwistedCarrier H,
          Set.image (characterShear χ) (relativeDerivativeOrbit b x) =
            Set.image (booleanSwitch b) (relativeDerivativeOrbit b x))

end

end MathlibPlus.Open.ResearchFormalization.R1155C41415
