import MathlibPlus.Open.Research.IdentityBasePrimeFiber
import MathlibPlus.Open.ResearchFormalization.ProfileClaims
import MathlibPlus.Open.ResearchFormalization.R1022

namespace MathlibPlus.Open.ResearchFormalization.R1212

abbrev A4 := alternatingGroup (Fin 4)
abbrev CyclicPrime (p : ℕ) := Multiplicative (ZMod p)
abbrev ProductGroup (p : ℕ) := CyclicPrime p × A4

/-- The common-coordinate map on the cyclic-prime and `A₄` factors. -/
def normalizedCommonCoordinateMap {p : ℕ}
    (q : Equiv.Perm A4) (σ : A4 → Equiv.Perm (ZMod p))
    (f : Equiv.Perm (ProductGroup p)) : Prop :=
  q 1 = 1 ∧
    σ 1 = Equiv.refl (ZMod p) ∧
    ∀ (x : ZMod p) (h : A4),
      f (Multiplicative.ofAdd x, h) =
        (Multiplicative.ofAdd ((σ h) x), q h)

/-- Being the unique nonidentity nontranslation chart. -/
def singletonNonlinearChart {p : ℕ}
    (σ : A4 → Equiv.Perm (ZMod p)) (a : A4) : Prop :=
  a ≠ 1 ∧
    ¬ MathlibPlus.Open.Research.isTranslation p (σ a) ∧
    ∀ h : A4, h ≠ a → MathlibPlus.Open.Research.isTranslation p (σ h)

/-- Claim 32296: the normalized profile with exactly one nonlinear chart and
    no restriction on the remaining translation charts. -/
def oneNonlinearCommonCoordinateProfile_claim32296 {p : ℕ}
    (q : Equiv.Perm A4) (σ : A4 → Equiv.Perm (ZMod p))
    (f : Equiv.Perm (ProductGroup p)) : Prop :=
  Nat.Prime p ∧
    5 ≤ p ∧
    normalizedCommonCoordinateMap q σ f ∧
    ∃ a : A4, singletonNonlinearChart σ a

/-- The base of the target fibre of the relative derivative with vertex base
    `a` and source base `h`. -/
def targetBase
    (q : Equiv.Perm A4) (a h : A4) : A4 :=
  q.symm (q (h * a) * (q a)⁻¹)

/-- The first coordinate of the full relative derivative on the source fibre.
    The derivative itself is the independently specified group derivative from
    the Cayley transport criterion. -/
def targetFiberDerivativeValue {p : ℕ}
    (f : Equiv.Perm (ProductGroup p)) (a h : A4)
    (y x : ZMod p) : ZMod p :=
  Multiplicative.toAdd
    ((MathlibPlus.Open.ResearchFormalization.R1022.relativeDerivative f
        (Multiplicative.ofAdd y, a))
      (Multiplicative.ofAdd x, h)).1

/-- Claim 32298: after the source-product chart is written as the translation
    by `t`, the relative derivative has the displayed target-fibre formula. -/
def relativeDerivativeTargetFiberFormula_claim32298 : Prop :=
  ∀ (p : ℕ), Nat.Prime p → 5 ≤ p →
    ∀ (q : Equiv.Perm A4) (σ : A4 → Equiv.Perm (ZMod p))
      (f : Equiv.Perm (ProductGroup p)) (a h : A4) (t : ZMod p),
      normalizedCommonCoordinateMap q σ f →
      singletonNonlinearChart σ a →
      h ≠ 1 →
      σ (h * a) = MathlibPlus.Open.Research.translation p t →
      ∀ (x y : ZMod p),
        targetFiberDerivativeValue f a h y x =
          (σ (targetBase q a h)).symm
            (x + y + t - (σ a) y)

/-- Claim 32300: the quotient of two derivatives is the conjugate of a
    nonzero prime translation, together with the two cycle assertions. -/
def derivativeQuotientConjugateTranslation_claim32300 : Prop :=
  ∀ (p : ℕ), Nat.Prime p → 5 ≤ p →
    ∀ (q : Equiv.Perm A4) (σ : A4 → Equiv.Perm (ZMod p))
      (f : Equiv.Perm (ProductGroup p)) (a h : A4) (t : ZMod p),
      normalizedCommonCoordinateMap q σ f →
      singletonNonlinearChart σ a →
      h ≠ 1 →
      σ (h * a) = MathlibPlus.Open.Research.translation p t →
      ∃ (y z c : ZMod p),
        c ≠ 0 ∧
        (y - (σ a) y) - (z - (σ a) z) = c ∧
        let r := targetBase q a h
        MathlibPlus.Open.ResearchFormalization.ProfileClaims.profileFiberDerivative
              σ a y r *
            (MathlibPlus.Open.ResearchFormalization.ProfileClaims.profileFiberDerivative
              σ a z r)⁻¹ =
          (σ r)⁻¹ * Equiv.addRight c * σ r ∧
        MathlibPlus.Open.Research.isFullCycle p (Equiv.addRight c) ∧
        MathlibPlus.Open.Research.isFullCycle p
          ((σ r)⁻¹ * Equiv.addRight c * σ r)

/-- The relative-derivative subgroup generated by the full normalized
    derivatives of the common-coordinate map. -/
def relativeDerivativeGroup (p : ℕ)
    (f : Equiv.Perm (ProductGroup p)) :
    Subgroup (Equiv.Perm (ProductGroup p)) :=
  Subgroup.closure
    (Set.range
      (MathlibPlus.Open.ResearchFormalization.R1022.relativeDerivative f))

/-- The orbit of a point under the full relative-derivative action. -/
def relativeDerivativeOrbit (p : ℕ)
    (f : Equiv.Perm (ProductGroup p)) (x : ProductGroup p) : Set (ProductGroup p) :=
  {y | ∃ g : relativeDerivativeGroup p f,
    (g : Equiv.Perm (ProductGroup p)) x = y}

/-- The projected compatibility atom carried by a relative-derivative orbit. -/
def projectedCompatibilityAtom (p : ℕ)
    (f : Equiv.Perm (ProductGroup p)) (x : ProductGroup p) : Set A4 :=
  {h | ∃ y : ProductGroup p,
    y ∈ relativeDerivativeOrbit p f x ∧ y.2 = h}

/-- The complete prime fibre over a projected base set. -/
def completePrimeFiber (p : ℕ) (O : Set A4) : Set (ProductGroup p) :=
  {x | x.2 ∈ O}

/-- Claim 32301: every nonidentity projected compatibility atom is saturated
    by one relative-derivative orbit in the complete prime fibre. -/
def projectedAtomPrimeFiberSaturation_claim32301 : Prop :=
  ∀ (p : ℕ), Nat.Prime p → 5 ≤ p →
    ∀ (q : Equiv.Perm A4) (σ : A4 → Equiv.Perm (ZMod p))
      (f : Equiv.Perm (ProductGroup p)),
      oneNonlinearCommonCoordinateProfile_claim32296 q σ f →
      ∀ x : ProductGroup p, x.2 ≠ 1 →
        relativeDerivativeOrbit p f x =
          completePrimeFiber p (projectedCompatibilityAtom p f x)

end MathlibPlus.Open.ResearchFormalization.R1212
