import MathlibPlus.Open.ResearchFormalization.R1288
import MathlibPlus.Open.Research.R1184Claim41746

namespace MathlibPlus.Open.ResearchFormalization.R1288Claim40021

open MathlibPlus.Open.ResearchFormalization.R1288
open MathlibPlus.Open.Research.R1184Formalization_41746

noncomputable section

/-- The exact independent coordinate translation on `Ω = (ℤ/mℤ) × X`. -/
def coordinateTranslation40021
    {m : ℕ} {X : Type*} [Fintype X]
    (v : Profile m X) : Equiv.Perm (Omega m X) :=
  ((Equiv.prodComm (ZMod m) X).trans
    (Equiv.prodCongrRight (fun x => Equiv.addRight (v x)))).trans
      (Equiv.prodComm X (ZMod m))

/-- The full product of the independent coordinate translations. -/
def independentTranslationProduct40021
    (m : ℕ) (X : Type*) [Fintype X] :
    Subgroup (Equiv.Perm (Omega m X)) :=
  Subgroup.closure
    (Set.range (fun v : Profile m X => coordinateTranslation40021 v))

/-- Regularity of a permutation subgroup together with its isomorphism to
 the canonical `C_m ⋊ C_8` source copy. -/
def regularECopy40021
    (m : ℕ) (X : Type*) [Fintype X]
    (R : Subgroup (Equiv.Perm (Omega m X))) : Prop :=
  (∀ x y : Omega m X, ∃! r : R,
    (r : Equiv.Perm (Omega m X)) x = y) ∧
    Nonempty (R ≃* eStandardCopy m)

/-- The Hall subgroup is the cyclic subgroup generated by one coordinate
translation and has the source order `m`. -/
def hallGenerator40021
    (m : ℕ) (X : Type*) [Fintype X]
    (N : Subgroup (Equiv.Perm (Omega m X)))
    (v : Profile m X) : Prop :=
  N = Subgroup.closure
      ({coordinateTranslation40021 v} : Set (Equiv.Perm (Omega m X))) ∧
    Nat.card N = m

/-- Semiregularity of a permutation subgroup on the full `8m`-point carrier. -/
def semiregular40021
    {m : ℕ} {X : Type*} [Fintype X]
    (N : Subgroup (Equiv.Perm (Omega m X))) : Prop :=
  ∀ g : N, ∀ x : Omega m X,
    (g : Equiv.Perm (Omega m X)) x = x → g = 1

/-- Claim 40021: in the exact regular `E(C_m,8)` setup, the cyclic Hall
translation subgroup is semiregular and every coordinate of its profile has
additive order exactly `m`. -/
def claim40021 : Prop :=
  ∀ (m : ℕ), Odd m →
    ∀ (X : Type*) [Fintype X], Fintype.card X = 8 →
      ∀ (R N : Subgroup (Equiv.Perm (Omega m X)))
        (v : Profile m X),
        regularECopy40021 m X R →
        N ≤ R →
        N ≤ independentTranslationProduct40021 m X →
        hallGenerator40021 m X N v →
        semiregular40021 N ∧
          (∀ x : X, addOrderOf (v x) = m)

end

end MathlibPlus.Open.ResearchFormalization.R1288Claim40021
