import MathlibPlus.Open.ResearchFormalization.R1336SmallGroupAudit

namespace MathlibPlus.Open.ResearchFormalization.R1336Claim30959

noncomputable section

abbrev Q12 := MathlibPlus.Open.ResearchFormalization.R1336.Q12
abbrev NormalizedProfile := {h : ZMod 7 → Q12 // h 0 = 1}

/-- The cyclic chart difference `d_i=h_i⁻¹ h_{i+1}`. -/
def chartDifference (h : NormalizedProfile) (i : ZMod 7) : Q12 :=
  (h.1 i)⁻¹ * h.1 (i + 1)

/-- The subgroup generated by the two chart differences at offset `r`. -/
def pairProjectionSubgroup (h : NormalizedProfile) (r : ZMod 7) :
    Subgroup (Q12 × Q12) :=
  Subgroup.closure (Set.range (fun k : ZMod 7 =>
    (chartDifference h k, chartDifference h (k + r))))

/-- The exact chart-surjectivity condition for a normalized profile. -/
def chartSurjectivityCondition (h : NormalizedProfile) : Prop :=
  ∀ i r : ZMod 7,
    (h.1 i, h.1 (i + r)) ∈
      (pairProjectionSubgroup h r : Set (Q12 × Q12))

end

end MathlibPlus.Open.ResearchFormalization.R1336Claim30959
