import MathlibPlus.Open.Research.Q12CIBatch

namespace MathlibPlus.Open.ResearchFormalization.R1336Subdirect

noncomputable section

open MathlibPlus.Open.Research.Q12

def chartDifference {G : Type*} [Group G]
    (h : ZMod 7 → G) (i : ZMod 7) : G :=
  (h i)⁻¹ * h (i + 1)

def chartGeneratedSubgroup {G : Type*} [Group G]
    (h : ZMod 7 → G) : Subgroup G :=
  Subgroup.closure (Set.range (chartDifference h))

def chartPairSubgroup {G : Type*} [Group G]
    (h : ZMod 7 → G) (r : ZMod 7) : Subgroup (G × G) :=
  Subgroup.closure (Set.range (fun k : ZMod 7 =>
    (chartDifference h k, chartDifference h (k + r))))

def subdirectIn {G : Type*} [Group G]
    (L : Subgroup G) (H : Subgroup (G × G)) : Prop :=
  (∀ p : H, p.1.1 ∈ L ∧ p.1.2 ∈ L) ∧
    (∀ x : L, ∃ y : G, ((x : G), y) ∈ H) ∧
    (∀ y : L, ∃ x : G, (x, (y : G)) ∈ H)

/-- Claim 30962: every nonzero offset pair subgroup generated by the cyclic
chart differences is a subdirect subgroup of `L × L`. -/
def claim30962_nonzeroPairProjectionsSubdirect : Prop :=
  ∀ (G : Type*) [Group G] [Fintype G] (a b : G),
    isQ12Presentation a b →
      ∀ h : ZMod 7 → G, h 0 = 1 →
        let L := chartGeneratedSubgroup h
        ∀ r : ZMod 7, r ≠ 0 →
          subdirectIn L (chartPairSubgroup h r)

end

end MathlibPlus.Open.ResearchFormalization.R1336Subdirect
