import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1336Claims30966_30967

noncomputable section

/-- The concrete twelve-element dicyclic group used by the `R-1336` chart. -/
abbrev Q12 := QuaternionGroup 3

/-- The indexed cyclic differences of a chart profile. -/
def chartDifference (h : ZMod 7 → Q12) (i : ZMod 7) : Q12 :=
  (h i)⁻¹ * h (i + 1)

/-- The subgroup generated by all cyclic differences. -/
def chartGeneratedSubgroup (h : ZMod 7 → Q12) : Subgroup Q12 :=
  Subgroup.closure (Set.range (chartDifference h))

/-- The subgroup generated by the paired differences at offset `r`. -/
def chartPairSubgroup (h : ZMod 7 → Q12) (r : ZMod 7) :
    Subgroup (Q12 × Q12) :=
  Subgroup.closure (Set.range (fun k : ZMod 7 =>
    (chartDifference h k, chartDifference h (k + r))))

/-- The Goursat relation is the graph of the still-variable quotient
isomorphism, rather than equality of quotient values. -/
def chartGoursatGraph (L : Subgroup Q12) (N : Subgroup L) [N.Normal]
    (φ : (L ⧸ N) ≃* (L ⧸ N)) : Set (Q12 × Q12) :=
  {p | ∃ hp : p.1 ∈ L, ∃ hq : p.2 ∈ L,
    φ (QuotientGroup.mk' (N := N) (⟨p.1, hp⟩ : L)) =
      QuotientGroup.mk' (N := N) (⟨p.2, hq⟩ : L)}

/-- The exact seven-cycle Goursat data, including the lifted indexed
 differences and the chart-surjectivity relation. -/
def chartGoursatData (h : ZMod 7 → Q12) (r : ZMod 7)
    (L : Subgroup Q12) (N : Subgroup L) [N.Normal]
    (φ : (L ⧸ N) ≃* (L ⧸ N)) (d : ZMod 7 → L) : Prop :=
  r ≠ 0 ∧
    L = chartGeneratedSubgroup h ∧
    (∀ i, (d i : Q12) = chartDifference h i) ∧
    (∀ i, (h i, h (i + r)) ∈
      (chartPairSubgroup h r : Set (Q12 × Q12))) ∧
    (chartPairSubgroup h r : Set (Q12 × Q12)) =
      chartGoursatGraph L N φ ∧
    (∀ i,
      φ (QuotientGroup.mk' (N := N) (d i)) =
        QuotientGroup.mk' (N := N) (d (i + r)))

/-- The exact section-order restriction supplied by the `Q₁₂` subgroup audit. -/
def q12SectionOrderRestriction (L : Subgroup Q12) (N : Subgroup L)
    [N.Normal] : Prop :=
  ∀ ψ : (L ⧸ N) ≃* (L ⧸ N),
    orderOf ψ ∈ ({1, 2, 3, 6} : Set ℕ)

/-- The ordered product in the cyclic telescoping calculation. -/
def orderedSevenProduct {L : Type*} [Group L]
    (d : ZMod 7 → L) : L :=
  d 0 * d 1 * d 2 * d 3 * d 4 * d 5 * d 6

/-- Ambient membership in a normal subgroup of the generated subgroup. -/
def ambientNormalMembership (L : Subgroup Q12) (N : Subgroup L)
    (x : Q12) : Prop :=
  ∃ hx : x ∈ L, (⟨x, hx⟩ : L) ∈ N

/-- Claim 30966: the variable Goursat automorphism is forced to have
seventh power one on the quotient and is then trivial by the exact section
restriction. -/
def claim30966 : Prop :=
  ∀ (h : ZMod 7 → Q12), h 0 = 1 →
    ∀ (r : ZMod 7), r ≠ 0 →
      ∀ (L : Subgroup Q12) (N : Subgroup L) [N.Normal]
        (φ : (L ⧸ N) ≃* (L ⧸ N)) (d : ZMod 7 → L),
        chartGoursatData h r L N φ d →
          q12SectionOrderRestriction L N →
            (∀ i : ZMod 7,
              (φ ^ 7) (QuotientGroup.mk' (N := N) (d i)) =
                QuotientGroup.mk' (N := N) (d i)) ∧
              φ ^ 7 = 1 ∧ φ = 1

/-- Claim 30967: the profile/shift interface itself yields the common
quotient value, the telescoping seventh-power calculation, and membership of
all indexed differences and normalized chart values in the common kernel. -/
def claim30967 : Prop :=
  ∀ (h : ZMod 7 → Q12), h 0 = 1 →
    ∀ (r : ZMod 7), r ≠ 0 →
      ∀ (L : Subgroup Q12) (N : Subgroup L) [N.Normal]
        (φ : (L ⧸ N) ≃* (L ⧸ N)) (d : ZMod 7 → L),
        chartGoursatData h r L N φ d →
          q12SectionOrderRestriction L N →
            φ ^ 7 = 1 ∧
              φ = 1 ∧
              Nat.card (L ⧸ N) ∣ 12 ∧
              ∃ a : L ⧸ N,
                (∀ i : ZMod 7,
                  QuotientGroup.mk' (N := N) (d i) = a) ∧
                  orderedSevenProduct d = 1 ∧
                  a ^ 7 = 1 ∧
                  a = 1 ∧
                  (∀ i : ZMod 7, d i ∈ N) ∧
                  (∀ i : ZMod 7, ambientNormalMembership L N (h i))

end

end MathlibPlus.Open.ResearchFormalization.R1336Claims30966_30967
