import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1339Omega28ProfileCopies

noncomputable section

/-- Claim 41091: the exact `Z/4Z × F₇` standard and voltage-profile
permutation copies are generated by the displayed permutations. -/
def omega28ProfileCopies_claim41091 : Prop :=
  let Ω := ZMod 4 × ZMod 7
  ∃ p s : Equiv.Perm Ω,
    (∀ i : ZMod 4, ∀ x : ZMod 7,
      p (i, x) = (i, x + 1)) ∧
    (∀ i : ZMod 4, ∀ x : ZMod 7,
      s (i, x) = (i + 1, x)) ∧
    ∀ v : ZMod 4 → (ZMod 7)ˣ,
      ∃ q t : Equiv.Perm Ω,
        (∀ i : ZMod 4, ∀ x : ZMod 7,
          q (i, x) = (i, x + (v i : ZMod 7))) ∧
        (∀ i : ZMod 4, ∀ x : ZMod 7,
          t (i, x) =
            (i + 1, ((v (i + 1) / v i : (ZMod 7)ˣ) : ZMod 7) * x)) ∧
        ∃ standard profile : Subgroup (Equiv.Perm Ω),
          standard = Subgroup.closure ({p * s} : Set (Equiv.Perm Ω)) ∧
          profile = Subgroup.closure ({q * t} : Set (Equiv.Perm Ω))

end

end MathlibPlus.Open.ResearchFormalization.R1339Omega28ProfileCopies
