import MathlibPlus.Open.ResearchFormalizationBatch_01a0014d

namespace MathlibPlus.Open.ResearchFormalization.R1437Claim38869

open MathlibPlus.Open.ResearchFormalizationBatch_01a0014d

noncomputable section

abbrev H := C6Squared
abbrev OuterPoints := H × Bool
abbrev OuterPermutation := Equiv.Perm OuterPoints

/-- The permutation obtained by translating the two outer blocks separately. -/
def blockwiseTranslation (a b : H) : OuterPermutation :=
  blockwisePermutation (c6Translation a) (c6Translation b)

/-- The common regular translation copy on the two outer blocks. -/
def hTranslation (a : H) : OuterPermutation :=
  blockAction a

/-- The unshifted outer involution. -/
def outerR : OuterPermutation :=
  unshiftedBlockSwap

/-- The complement involution with shift `a`. -/
def outerT (a : H) : OuterPermutation :=
  complementShift a

/-- The block-fixing product `s = r t`. -/
def outerS (a : H) : OuterPermutation :=
  outerR * outerT a

/-- The anti-diagonal block translation in the aligned cross-strip chart. -/
def antiDiagonalTranslation (a : H) : OuterPermutation :=
  blockwiseTranslation a (-a)

/-- Membership in the common regular copy `H`. -/
def liesInH (f : OuterPermutation) : Prop :=
  ∃ a : H, f = hTranslation a

/-- The permutation acting on one of the two coordinate factors. -/
def coordinatePermutation (g : Equiv.Perm (ZMod 6)) (coordinate : Bool) :
    Equiv.Perm H :=
  if coordinate then
    Equiv.prodCongr (Equiv.refl (ZMod 6)) g
  else
    Equiv.prodCongr g (Equiv.refl (ZMod 6))

/-- A natural diagonal-strip element on both outer blocks. -/
def diagonalStripElement (g : Equiv.Perm (ZMod 6)) (coordinate : Bool) :
    OuterPermutation :=
  blockwisePermutation
    (coordinatePermutation g coordinate)
    (coordinatePermutation g coordinate)

/-- The degree-six S5 product-action factor, generated on the projective
line chart by a five-cycle and the inversion involution. -/
def fiveCycle : Equiv.Perm (ZMod 6) :=
  Equiv.swap 0 1 * Equiv.swap 1 2 * Equiv.swap 2 3 * Equiv.swap 3 4

def fiveInversion : Equiv.Perm (ZMod 6) :=
  Equiv.swap 0 5 * Equiv.swap 1 4 * Equiv.swap 2 3

def localFive : Subgroup (Equiv.Perm (ZMod 6)) :=
  Subgroup.closure ({fiveCycle, fiveInversion} : Set (Equiv.Perm (ZMod 6)))

/-- The natural degree-six S6 factor. -/
def localSix : Subgroup (Equiv.Perm (ZMod 6)) :=
  Subgroup.closure {g : Equiv.Perm (ZMod 6) | Equiv.Perm.sign g = 1}

/-- The two allowed untwisted local derived factors, A5 and A6. -/
def localDerived (m : Bool) : Subgroup (Equiv.Perm (ZMod 6)) :=
  if m then localSix else localFive

/-- The cross-strip kernel in either allowed local chart. -/
def crossStripKernel (m : Bool) : Subgroup OuterPermutation :=
  Subgroup.closure
    {f | ∃ g : Equiv.Perm (ZMod 6),
      g ∈ localDerived m ∧
        (f = diagonalStripElement g false ∨
          f = diagonalStripElement g true)}

/-- Normalization of the displayed diagonal strips. -/
def normalizesCrossStrips (m : Bool) (f : OuterPermutation) : Prop :=
  f ∈ Subgroup.normalizer (crossStripKernel m : Set OuterPermutation)

/-- Conjugation by an outer permutation. -/
def conjugateBy (q f : OuterPermutation) : OuterPermutation :=
  q * f * q⁻¹

/-- The four-element 2-torsion carrier of `C₆²`. -/
def twoTorsion (a : H) : Prop :=
  a + a = 0

/-- The subgroup facts for the 2-torsion carrier. -/
def twoTorsionSubgroupFacts : Prop :=
  Nat.card {a : H // twoTorsion a} = 4 ∧
    twoTorsion 0 ∧
    (∀ a b : H, twoTorsion a → twoTorsion b → twoTorsion (a + b)) ∧
    (∀ a : H, twoTorsion a → twoTorsion (-a))

/-- The subgroup generated by the common regular copy and one complement. -/
def generatedWith (f : OuterPermutation) : Subgroup (Equiv.Perm OuterPoints) :=
  Subgroup.closure ((Set.range hTranslation) ∪ {f})

/-- Regularity of a generated complement copy on the 72-point carrier. -/
def generatedRegular (f : OuterPermutation) : Prop :=
  ∀ x y : OuterPoints, ∃! g : generatedWith f, (g : OuterPermutation) x = y

/-- Claim 38869: cross-strip complement shifts are exactly the four elements
of `H[2]`, and all four complements generate the same regular subgroup. -/
def claim38869 : Prop :=
  Fintype.card H = 36 ∧
    IsRegularAdditiveRepresentation hTranslation ∧
    IsBlockSwap outerR ∧
    IsInvolution outerR ∧
    CentralizesBlockAction outerR ∧
    twoTorsionSubgroupFacts ∧
    generatedRegular outerR ∧
    (∀ m : Bool, normalizesCrossStrips m outerR) ∧
    (∀ (m : Bool) (a : H),
      IsBlockSwap (outerT a) ∧
        IsInvolution (outerT a) ∧
        CentralizesBlockAction (outerT a) ∧
        outerS a = antiDiagonalTranslation a ∧
        (∀ (h : H) (b : Bool), (outerS a (h, b)).2 = b) ∧
        CentralizesBlockAction (outerS a) ∧
        conjugateBy outerR (outerS a) = (outerS a)⁻¹ ∧
        (normalizesCrossStrips m (outerT a) ↔ twoTorsion a) ∧
        (normalizesCrossStrips m (outerS a) ↔ twoTorsion a) ∧
        (normalizesCrossStrips m (outerS a) → liesInH (outerS a)) ∧
        (liesInH (outerS a) ↔ twoTorsion a)) ∧
    (∀ a : H, twoTorsion a →
      outerT a = outerR * outerS a ∧
        generatedRegular (outerT a) ∧
        generatedWith (outerT a) = generatedWith (outerR) ∧
        generatedWith (outerR * outerS a) = generatedWith (outerR)) ∧
    (∀ a b : H, twoTorsion a → twoTorsion b →
      generatedWith (outerT a) = generatedWith (outerT b) ∧
        generatedWith (outerT a) = generatedWith outerR)

end

end MathlibPlus.Open.ResearchFormalization.R1437Claim38869
