import MathlibPlus.Open.ResearchFormalization.R1441MarkedOffsetTransport

namespace MathlibPlus.Open.ResearchFormalization.R1441FiveForms

open MathlibPlus.Open.ResearchFormalization.R1441MarkedOffsetTransport

noncomputable section

abbrev NormalFunctional := W →ₗ[ZMod 7] ZMod 7
abbrev NormalLine := Submodule (ZMod 7) NormalFunctional

/-- Powers for the exact semidirect multiplication on the matching-scalar
quotient carrier. -/
def hPower (h : H) : ℕ → H
  | 0 => (0, 0)
  | n + 1 => hMul (hPower h n) h

/-- The cyclic class generated by a nonidentity quotient element. -/
def cyclicClass (h : H) : Set H :=
  {k | ∃ n : ℕ, hPower h n = k}

/-- The eight cyclic-subgroup classes on the quotient side. -/
def cyclicClasses : Set (Set H) :=
  {K | ∃ h : H, h ≠ (0, 0) ∧ cyclicClass h = K}

/-- A projective normal line is the span of one nonzero linear functional on
W. -/
def projectiveNormalLines : Set NormalLine :=
  {L | ∃ n : NormalFunctional,
    n ≠ 0 ∧ L = Submodule.span (ZMod 7) ({n} : Set NormalFunctional)}

/-- The derivative subspace attached to a normalized translation profile. -/
def derivativeSubspace (τ : H → W) (h : H) : Submodule (ZMod 7) W :=
  Submodule.span (ZMod 7)
    (Set.range (fun k : H =>
      τ (hMul h k) - τ h - hScalar h (τ k)))

/-- A normal functional annihilates a derivative subspace. -/
def annihilatesDerivative (τ : H → W) (h : H)
    (n : NormalFunctional) : Prop :=
  ∀ w, w ∈ derivativeSubspace τ h → n w = 0

/-- The exact active incidence relation between cyclic classes and projective
normal lines. -/
def activeIncidence (τ : H → W) : Set (Set H × NormalLine) :=
  {e | e.1 ∈ cyclicClasses ∧ e.2 ∈ projectiveNormalLines ∧
    ∃ h : H, h ≠ (0, 0) ∧ cyclicClass h = e.1 ∧
      ∃ n : NormalFunctional,
        n ≠ 0 ∧
          Submodule.span (ZMod 7) ({n} : Set NormalFunctional) = e.2 ∧
            annihilatesDerivative τ h n}

def sideProduct : Set (Set H × NormalLine) :=
  {e | e.1 ∈ cyclicClasses ∧ e.2 ∈ projectiveNormalLines}

def fullRow (K : Set H) : Set (Set H × NormalLine) :=
  {e | e ∈ sideProduct ∧ e.1 = K}

def fullColumn (L : NormalLine) : Set (Set H × NormalLine) :=
  {e | e ∈ sideProduct ∧ e.2 = L}

def completeBipartite : Set (Set H × NormalLine) :=
  sideProduct

def isMatching (R : Set (Set H × NormalLine)) : Prop :=
  (∀ K L₁ L₂, (K, L₁) ∈ R → (K, L₂) ∈ R → L₁ = L₂) ∧
    (∀ K₁ K₂ L, (K₁, L) ∈ R → (K₂, L) ∈ R → K₁ = K₂)

def isOneFullRow (R : Set (Set H × NormalLine)) : Prop :=
  ∃ K : Set H, K ∈ cyclicClasses ∧ R = fullRow K

def isOneFullColumn (R : Set (Set H × NormalLine)) : Prop :=
  ∃ L : NormalLine, L ∈ projectiveNormalLines ∧ R = fullColumn L

def isRowColumnUnion (R : Set (Set H × NormalLine)) : Prop :=
  ∃ (K : Set H) (L : NormalLine),
    K ∈ cyclicClasses ∧ L ∈ projectiveNormalLines ∧
      R = {e | e ∈ fullRow K ∨ e ∈ fullColumn L}

def fiveIncidenceForms (R : Set (Set H × NormalLine)) : Prop :=
  isMatching R ∨
    isOneFullRow R ∨
      isOneFullColumn R ∨
        isRowColumnUnion R ∨ R = completeBipartite

/-- Claim 37226: every normalized active incidence graph on the eight
cyclic classes and eight projective normal lines has one of the five stated
forms. -/
def claim37226 : Prop :=
  Set.ncard cyclicClasses = 8 ∧
    Set.ncard projectiveNormalLines = 8 ∧
      ∀ τ : H → W, τ (0, 0) = 0 →
        fiveIncidenceForms (activeIncidence τ)

end

end MathlibPlus.Open.ResearchFormalization.R1441FiveForms
