import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1444

noncomputable section

abbrev quinaryPoint := ZMod 5
abbrev quinaryPermutation := Equiv.Perm quinaryPoint

def rho5 : quinaryPermutation :=
  Equiv.addRight (1 : quinaryPoint)

def affineChart5 (σ : quinaryPermutation) : Prop :=
  ∃ a b : quinaryPoint, a ≠ 0 ∧ ∀ x : quinaryPoint, σ x = a * x + b

def conjugateBy5 (u p : quinaryPermutation) : quinaryPermutation :=
  (MulAut.conj u) p

def derivative5 (σ : quinaryPermutation) : quinaryPermutation :=
  rho5⁻¹ * (σ⁻¹ * rho5 * σ)

def derivativeTuple5 (σ : quinaryPermutation) (k : Fin 5) : quinaryPermutation :=
  conjugateBy5 (rho5 ^ k.val) (derivative5 σ)

def derivativeClosure5 (σ : quinaryPermutation) :
    Subgroup quinaryPermutation :=
  Subgroup.closure (Set.range (derivativeTuple5 σ))

def even5 (g : quinaryPermutation) : Prop :=
  Equiv.Perm.sign g = (1 : ℤˣ)

def closureIsA5 (H : Subgroup quinaryPermutation) : Prop :=
  ∀ g : quinaryPermutation, g ∈ H ↔ even5 g

/-- Claim 37261: every nonaffine quinary derivative closure is `A₅`. -/
def everyNonaffineQuinaryDerivativeClosureIsA5 : Prop :=
  ∀ σ : quinaryPermutation, ¬ affineChart5 σ →
    closureIsA5 (derivativeClosure5 σ)

def synchronousClosure5 (σ τ : quinaryPermutation) :
    Subgroup (quinaryPermutation × quinaryPermutation) :=
  Subgroup.closure
    (Set.range (fun k : Fin 5 =>
      (derivativeTuple5 σ k, derivativeTuple5 τ k)))

def subdirectA5
    (S : Subgroup (quinaryPermutation × quinaryPermutation)) : Prop :=
  (∀ x, x ∈ S → even5 x.1 ∧ even5 x.2) ∧
  (∀ g, even5 g → ∃ h, (g, h) ∈ S) ∧
  (∀ h, even5 h → ∃ g, (g, h) ∈ S)

/-- Claim 37262: distinct nonaffine charts give a subdirect synchronous
subgroup of `A₅ × A₅`. -/
def synchronousQuinaryDerivativeGroupIsSubdirect : Prop :=
  ∀ σ τ : quinaryPermutation, σ ≠ τ →
    ¬ affineChart5 σ → ¬ affineChart5 τ →
      subdirectA5 (synchronousClosure5 σ τ)

def fullA5Product : Set (quinaryPermutation × quinaryPermutation) :=
  {x | even5 x.1 ∧ even5 x.2}

def isA5Automorphism (φ : quinaryPermutation → quinaryPermutation) : Prop :=
  (∀ g, even5 g → even5 (φ g)) ∧
  (∀ h, even5 h → ∃! g, even5 g ∧ φ g = h) ∧
  (∀ g h, even5 g → even5 h → φ (g * h) = φ g * φ h)

def graphA5 (φ : quinaryPermutation → quinaryPermutation) :
    Set (quinaryPermutation × quinaryPermutation) :=
  {x | even5 x.1 ∧ even5 x.2 ∧ φ x.1 = x.2}

/-- Claim 37263: the exact synchronous subgroup generated by two distinct
nonaffine charts is either the full product or an automorphism graph. -/
def a5GoursatDichotomy : Prop :=
  ∀ σ τ : quinaryPermutation, σ ≠ τ →
    ¬ affineChart5 σ → ¬ affineChart5 τ →
    let S := synchronousClosure5 σ τ
    (S : Set (quinaryPermutation × quinaryPermutation)) = fullA5Product ∨
      ∃ φ : quinaryPermutation → quinaryPermutation,
        isA5Automorphism φ ∧
          (S : Set (quinaryPermutation × quinaryPermutation)) = graphA5 φ

def simultaneouslyConjugateDerivativeTuples
    (σ τ : quinaryPermutation) : Prop :=
  ∃ u : quinaryPermutation, ∀ k : Fin 5,
    derivativeTuple5 σ k = conjugateBy5 u (derivativeTuple5 τ k)

/-- Claim 37265: the graph branch is exactly simultaneous conjugacy of the
ordered derivative tuples by one element of `S₅`. -/
def graphBranchIsSimultaneousTupleConjugacy : Prop :=
  ∀ σ τ : quinaryPermutation, ¬ affineChart5 σ → ¬ affineChart5 τ →
    ((∃ φ : quinaryPermutation → quinaryPermutation,
        isA5Automorphism φ ∧
          (synchronousClosure5 σ τ : Set (quinaryPermutation × quinaryPermutation)) =
            graphA5 φ) ↔
      simultaneouslyConjugateDerivativeTuples σ τ)

end

end MathlibPlus.Open.ResearchFormalization.R1444
