import MathlibPlus.Open.ResearchFormalization.R1516

namespace MathlibPlus.Open.ResearchFormalization.R1516Claim38054

noncomputable section

open MathlibPlus.Open.ResearchFormalization.R1516

/-- The normalized directed relative-derivative generator used for orbit
harmlessness. -/
def normalizedDerivativeGenerator {X : Type*} [Group X]
    (f : X ≃ X) (x : X) : Equiv.Perm X :=
  (((Equiv.mulRight x).trans f).trans
      (Equiv.mulRight ((f x)⁻¹))).trans f.symm

/-- The subgroup generated by all normalized directed derivative generators. -/
def normalizedDerivativeSubgroup {X : Type*} [Group X]
    (f : X ≃ X) : Subgroup (Equiv.Perm X) :=
  Subgroup.closure (Set.range (normalizedDerivativeGenerator f))

/-- One normalized directed derivative orbit. -/
def normalizedDerivativeOrbit {X : Type*} [Group X]
    (f : X ≃ X) (x : X) : Set X :=
  {y : X | ∃ p : normalizedDerivativeSubgroup f, p.1 x = y}

/-- Setwise fixing of every normalized directed derivative orbit. -/
def fixesEveryNormalizedDerivativeOrbit {X : Type*} [Group X]
    (f : X ≃ X) (u : Equiv.Perm X) : Prop :=
  ∀ x : X,
    Set.image u (normalizedDerivativeOrbit f x) =
      normalizedDerivativeOrbit f x

/-- The product automorphism induced by a base automorphism. -/
def baseCentralizerEquiv {A B : Type*} [Group A]
    (α : A ≃* A) : A × B ≃ A × B :=
  Equiv.prodCongr α.toEquiv (Equiv.refl B)

/-- Conjugation of a normalized row map by the base-centralizer product
automorphism. -/
def rowTransport {A B : Type*} [Group A]
    (f : A × B ≃ A × B) (α : A ≃* A) : A × B ≃ A × B :=
  ((baseCentralizerEquiv α).trans f).trans (baseCentralizerEquiv α).symm

/-- The exact skew-row presentation condition. -/
def isSkewRowPresentation {A B : Type*}
    (σ : Equiv.Perm A) (q : A → Equiv.Perm B)
    (f : A × B ≃ A × B) : Prop :=
  ∀ a : A, ∀ b : B,
    f (a, b) = skewRowMap σ q (a, b)

/-- Claim 38054: normalized directed derivative-orbit harmlessness is
preserved by centralizer row transport, with the exact row relabeling formula. -/
def claim38054 : Prop :=
  ∀ {A B : Type*} [Fintype A] [Fintype B] [Group A] [Group B]
    (σ : Equiv.Perm A) (q : A → Equiv.Perm B)
    (α : A ≃* A) (f : A × B ≃ A × B),
    isSkewRowPresentation σ q f →
      permutationCentralizes α σ →
        baseCentralizerAutomorphismProperty (A := A) (B := B) α ∧
          (∀ a : A, ∀ b : B,
            rowTransport f α (a, b) = (σ a, q (α a) b)) ∧
          (∀ u : Equiv.Perm (A × B),
            fixesEveryNormalizedDerivativeOrbit f u ↔
              fixesEveryNormalizedDerivativeOrbit (rowTransport f α)
                (((baseCentralizerEquiv α).trans u).trans
                  (baseCentralizerEquiv α).symm))

end

end MathlibPlus.Open.ResearchFormalization.R1516Claim38054
