import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1579

noncomputable section

abbrev CoordinatePlane := ZMod 3 × ZMod 3
abbrev TranslationOmega (H : Type*) := CoordinatePlane × H

/-- The zero-top triangular chart from the coordinate model. -/
def zeroTopChart {H : Type*} [AddCommGroup H]
    (q : Equiv.Perm (TranslationOmega H)) : Prop :=
  ∃ (m : H → ZMod 3) (g : H ≃ H),
    ∀ z w h, q ((z, w), h) = ((z, w + m h), g h)

/-- The regular translation subgroup on an additive coordinate carrier. -/
def translationGroup (Ω : Type*) [AddCommGroup Ω] :
    Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure (Set.range (fun v : Ω => Equiv.addRight v))

/-- Conjugation of the regular translation subgroup by a chart. -/
def conjugatedTranslationGroup {Ω : Type*}
    [AddCommGroup Ω] (T : Subgroup (Equiv.Perm Ω)) (q : Equiv.Perm Ω) :
    Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure
    (Set.image (fun t : Equiv.Perm Ω => q⁻¹ * t * q) (T : Set (Equiv.Perm Ω)))

/-- Literal translation by one in the displayed `z` coordinate. -/
def tauZ (H : Type*) [AddCommGroup H] :
    Equiv.Perm (TranslationOmega H) :=
  Equiv.addRight (((1 : ZMod 3), 0), 0)

/-- Literal translation by one in the displayed `w` coordinate. -/
def tauW (H : Type*) [AddCommGroup H] :
    Equiv.Perm (TranslationOmega H) :=
  Equiv.addRight (((0 : ZMod 3), 1), 0)

/-- The subgroup generated by the two displayed coordinate translations. -/
def commonCoordinateTranslations (H : Type*) [AddCommGroup H] :
    Subgroup (Equiv.Perm (TranslationOmega H)) :=
  Subgroup.closure
    ({tauZ H, tauW H} : Set (Equiv.Perm (TranslationOmega H)))

/-- Independence of the two order-three coordinate generators. -/
def independentCoordinateTranslations (H : Type*) [AddCommGroup H] : Prop :=
  ∀ (a b : ZMod 3),
    tauZ H ^ a.val * tauW H ^ b.val =
        (1 : Equiv.Perm (TranslationOmega H)) →
      a = 0 ∧ b = 0

/-- Claim 39345: the source and target regular translation copies contain the
literal independent `C₃²` coordinate subgroup, with all stated order and
cardinality conclusions. -/
def claim39345 : Prop :=
  ∀ {H : Type*} [Fintype H] [AddCommGroup H],
    (∀ h : H, 3 • h = 0) →
      ∀ q : Equiv.Perm (TranslationOmega H),
        zeroTopChart q →
          let T := translationGroup (TranslationOmega H)
          let Tq := conjugatedTranslationGroup T q
          commonCoordinateTranslations H ≤ T ⊓ Tq ∧
            orderOf (tauZ H) = 3 ∧
            orderOf (tauW H) = 3 ∧
            independentCoordinateTranslations H ∧
            Nonempty
              (commonCoordinateTranslations H ≃*
                (Multiplicative (ZMod 3) × Multiplicative (ZMod 3))) ∧
            Nat.card (↥(T ⊓ Tq)) ≥ 9

end
end MathlibPlus.Open.ResearchFormalization.R1579
