import Mathlib

namespace MathlibPlus.Open

/-- The abstract group `C₂ × C₃²`, represented as a product of additive cyclic groups. -/
abbrev E18 :=
  Multiplicative (ZMod 2) ×
    (Multiplicative (ZMod 3) × Multiplicative (ZMod 3))

abbrev Perm18 := Equiv.Perm (Fin 18)

/-- A subgroup of a permutation group is regular on its underlying finite set. -/
def IsRegularPermutationSubgroup {Ω : Type*} [Fintype Ω]
    (U : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ a b : Ω, ∃! u : U, u.1 a = b

/-- Two permutation subgroups are conjugate inside `X`. -/
def IsConjugateInside (X U V : Subgroup Perm18) : Prop :=
  ∃ x : Perm18, x ∈ X ∧
    ∀ g : Perm18, g ∈ V ↔ ∃ u : Perm18, u ∈ U ∧ g = x * u * x⁻¹

/-- The orbit relation on ordered pairs induced by a permutation subgroup. -/
def SameOrbital {Ω : Type*} (X : Subgroup (Equiv.Perm Ω))
    (a b c d : Ω) : Prop :=
  ∃ x : X, x.1 a = c ∧ x.1 b = d

/-- Transitivity of a permutation subgroup. -/
def IsTransitivePermutationSubgroup {Ω : Type*}
    (X : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ a b : Ω, ∃ x : X, x.1 a = b

/-- Membership in the ordinary (colored-orbital) two-closure. -/
def IsInTwoClosure {Ω : Type*} (X : Subgroup (Equiv.Perm Ω))
    (σ : Equiv.Perm Ω) : Prop :=
  ∀ a b : Ω, SameOrbital X a b (σ a) (σ b)

/-- A permutation group equals its colored-orbital two-closure. -/
def IsTwoClosed {Ω : Type*} (X : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ σ : Equiv.Perm Ω, IsInTwoClosure X σ ↔ σ ∈ X

/-- A regular copy of `E18` contained in a degree-18 permutation group. -/
def IsRegularE18Copy (X U : Subgroup Perm18) : Prop :=
  U ≤ X ∧ IsRegularPermutationSubgroup U ∧ Nonempty (E18 ≃* U)

/--
Claim 39568.  For every 2-closed transitive permutation group `X` of degree
18, all regular subgroups of `X` isomorphic to `E18` form at most one
`X`-conjugacy class.
-/
def e18RegularClassTheorem : Prop :=
  ∀ X : Subgroup Perm18,
    IsTransitivePermutationSubgroup X →
    IsTwoClosed X →
    ∀ U V : Subgroup Perm18,
      IsRegularE18Copy X U →
      IsRegularE18Copy X V →
      IsConjugateInside X U V

/-- The equivalent `CI^(2)` formulation of Claim 39568. -/
def e18IsCI2 : Prop := e18RegularClassTheorem

abbrev E18BinaryRelation := E18 → E18 → Prop

/-- A directed binary Cayley relation, expressed by left-translation invariance. -/
def IsDirectedE18CayleyRelation (R : E18BinaryRelation) : Prop :=
  ∀ g x y : E18, R (g * x) (g * y) ↔ R x y

/-- Automorphism of every relation in a finite tuple. -/
def PreservesE18Tuple {k : Nat} (R : Fin k → E18BinaryRelation)
    (σ : Equiv.Perm E18) : Prop :=
  ∀ i x y, R i x y ↔ R i (σ x) (σ y)

/-- A regular `E18` copy contained in the automorphism set of a relation tuple. -/
def IsRegularE18CopyInTuple {k : Nat} (R : Fin k → E18BinaryRelation)
    (U : Subgroup (Equiv.Perm E18)) : Prop :=
  IsRegularPermutationSubgroup U ∧ Nonempty (E18 ≃* U) ∧
    ∀ u : Equiv.Perm E18, u ∈ U → PreservesE18Tuple R u

/-- Conjugacy of two tuple-automorphism copies inside the tuple automorphism set. -/
def IsConjugateInE18Tuple {k : Nat} (R : Fin k → E18BinaryRelation)
    (U V : Subgroup (Equiv.Perm E18)) : Prop :=
  ∃ x : Equiv.Perm E18, PreservesE18Tuple R x ∧
    ∀ g : Equiv.Perm E18, g ∈ V ↔ ∃ u : Equiv.Perm E18,
      u ∈ U ∧ g = x * u * x⁻¹

/-- The regular-copy conjugacy property for one finite relation tuple. -/
def E18TupleCI {k : Nat} (R : Fin k → E18BinaryRelation) : Prop :=
  ∀ U V : Subgroup (Equiv.Perm E18),
    IsRegularE18CopyInTuple R U →
    IsRegularE18CopyInTuple R V →
    IsConjugateInE18Tuple R U V

/-- Symmetry of a binary relation. -/
def IsSymmetricE18Relation (R : E18BinaryRelation) : Prop :=
  ∀ x y, R x y ↔ R y x

/--
Claim 39569.  Every finite tuple of directed binary Cayley relations on
`E18`, every directed Cayley graph, and every undirected Cayley graph has the
regular-copy conjugacy property.
-/
def e18TupleDirectedUndirectedCI : Prop :=
  (∀ (k : Nat) (R : Fin k → E18BinaryRelation),
    (∀ i, IsDirectedE18CayleyRelation (R i)) → E18TupleCI R) ∧
  (∀ R : E18BinaryRelation,
    IsDirectedE18CayleyRelation R → E18TupleCI (fun _ : Fin 1 => R)) ∧
  (∀ R : E18BinaryRelation,
    IsDirectedE18CayleyRelation R → IsSymmetricE18Relation R →
      E18TupleCI (fun _ : Fin 1 => R))

/-- The subgroup generated by two permutation subgroups. -/
def GeneratedByTwo {Ω : Type*} (U V : Subgroup (Equiv.Perm Ω)) :
    Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure ((U : Set (Equiv.Perm Ω)) ∪ (V : Set (Equiv.Perm Ω)))

/-- Invariance under `A` is the assertion that a relation is a union of
`A`-orbitals. -/
def IsUnionOfOrbitals {Ω : Type*} (A : Subgroup (Equiv.Perm Ω))
    (R : Ω → Ω → Prop) : Prop :=
  ∀ g : A, ∀ x y : Ω, R (g.1 x) (g.1 y) ↔ R x y

/--
Claim 39570.  For a finite tuple of directed binary Cayley relations and two
regular copies `U,V` in its automorphism set, the subgroup generated by them
preserves every relation, its colored-orbital two-closure is still contained
in the automorphism set, and the two copies are conjugate there.
-/
def e18TwoClosureReduction : Prop :=
  ∀ (k : Nat) (R : Fin k → E18BinaryRelation),
    (∀ i, IsDirectedE18CayleyRelation (R i)) →
    ∀ U V : Subgroup (Equiv.Perm E18),
      IsRegularE18CopyInTuple R U →
      IsRegularE18CopyInTuple R V →
      let A := GeneratedByTwo U V
      (∀ i, IsUnionOfOrbitals A (R i)) ∧
        (∀ σ : Equiv.Perm E18, IsInTwoClosure A σ → PreservesE18Tuple R σ) ∧
        IsConjugateInE18Tuple R U V

/--
Claim 39573.  In the symmetric endpoint, any two regular representations of
one abstract group of order 18 are conjugate in the full symmetric group.
-/
def symmetricEndpointRegularRepresentations : Prop :=
  ∀ (G : Type*) [Group G] [Fintype G],
    Fintype.card G = 18 →
    ∀ U V : Subgroup Perm18,
      IsRegularPermutationSubgroup U →
      IsRegularPermutationSubgroup V →
      Nonempty (G ≃* U) →
      Nonempty (G ≃* V) →
      ∃ x : Perm18, ∀ g : Perm18, g ∈ V ↔
        ∃ u : Perm18, u ∈ U ∧ g = x * u * x⁻¹

end MathlibPlus.Open
