import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1698AffineTransitivity

noncomputable section

/-- Claim 33434: on the exact `ZMod 3` carrier, the subgroup generated by
the two affine maps with multiplier `a=1` or `-1` is transitive exactly when
the offset `c` is nonzero. -/
def pairedAffineMapsOverF3Transitive_claim33434 : Prop :=
  ∀ (a c : ZMod 3),
    (a = 1 ∨ a = -1) →
      let affine : ZMod 3 → ZMod 3 → Equiv.Perm (ZMod 3) :=
        fun m b => if m = 1 then
          Equiv.addRight b
        else
          (Equiv.neg (ZMod 3)).trans (Equiv.addRight b)
      let H : Subgroup (Equiv.Perm (ZMod 3)) :=
        Subgroup.closure
          ({affine a c, affine a (-c)} : Set (Equiv.Perm (ZMod 3)))
      ((∀ x y : ZMod 3, ∃ g : H,
          (g : Equiv.Perm (ZMod 3)) x = y) ↔ c ≠ 0) ∧
        (c = 0 →
          (affine a c) 0 = 0 ∧ (affine a (-c)) 0 = 0)

end

end MathlibPlus.Open.ResearchFormalization.R1698AffineTransitivity
