import Mathlib
import MathlibPlus.Open.ResearchFormalization.R1710Claim33538
import MathlibPlus.Open.ResearchFormalization.R1710Claim33543

namespace MathlibPlus.Open.ResearchFormalization.R1710Claim33533

noncomputable section

abbrev F7 := ZMod 7
abbrev H := MathlibPlus.Open.ResearchFormalization.Batch1484.H
abbrev W := MathlibPlus.Open.ResearchFormalization.Batch1484.W 2
abbrev GLW := W ≃ₗ[F7] W

open MathlibPlus.Open.ResearchFormalization.Batch1484

/-- The linear part of the normalized relative derivative at row `h`. -/
def relativeDerivativeLinearPart (L : H → GLW) (h k : H) : GLW :=
  (L h).symm * L (hMul h k)

def multiplierImage (L : H → GLW) : Subgroup GLW :=
  Subgroup.closure (Set.range L)

def relativeDerivativeLinearImage (L : H → GLW) (h : H) : Subgroup GLW :=
  Subgroup.closure (Set.range (fun k : H =>
    relativeDerivativeLinearPart L h k))

def leftTranslateRecovery (L : H → GLW) : Prop :=
  ∀ h j : H, ∃ k : H,
    hMul h k = j ∧
      L j = L h * relativeDerivativeLinearPart L h k

/-- Claim 33533: every row of the normalized affine profile has the full
multiplier image as the subgroup generated by its relative-derivative linear
parts, and left translation recovers every multiplier. -/
def claim33533 : Prop :=
  ∀ (L : H → GLW) (τ : H → W),
    MathlibPlus.Open.ResearchFormalization.R1710Claim33538.normalizedAffineProfile
      L τ →
      (∀ h : H,
        relativeDerivativeLinearImage L h = multiplierImage L) ∧
      leftTranslateRecovery L

end

end MathlibPlus.Open.ResearchFormalization.R1710Claim33533
