-- UNVERIFIED (downstream): submitted but not kernel-verified, so it is not built and MathlibPlus.lean does not import it. See unverified.txt.
import MathlibPlus.Open.ResearchBatch.Lease_01a001c2.ActualAffine
import MathlibPlus.Algebra.Claim32618
import MathlibPlus.LinearAlgebra.Claim32617

namespace MathlibPlus.Open.ResearchFormalization.R1821

noncomputable section
open scoped BigOperators

abbrev F3 := MathlibPlus.Open.ResearchBatch.ActualAffine.F3
abbrev H3 := MathlibPlus.Open.ResearchBatch.ActualAffine.H3
abbrev Omega3 := MathlibPlus.Open.ResearchBatch.ActualAffine.Omega3
abbrev AffinePermutation := Equiv.Perm Omega3
abbrev SymmetricMatrix3 := {B : Matrix (Fin 5) (Fin 5) F3 // B.IsSymm}

open MathlibPlus.Open.ResearchBatch.ActualAffine

/-- The marked actual-image carrier for the classified rank-six copies. -/
def containedInActualAffineImage (R : Subgroup (Equiv.Perm Omega3)) : Prop :=
  ∀ g : R, (g : Equiv.Perm Omega3) ∈ affineImage

/-- Regular elementary-abelian subgroups of the asserted order `3^6`. -/
def regularElementaryAbelianOrderSix
    (R : Subgroup (Equiv.Perm Omega3)) : Prop :=
  regularAffineSubgroup R ∧
    Nat.card R = 3 ^ 6 ∧
    (∀ g h : R, g * h = h * g) ∧
    ∀ g : R, g ^ 3 = 1

/-- The exact polynomial `f_B` in the admitted quadratic transporter. -/
def quadraticFunction (B : SymmetricMatrix3) (x : H3) : F3 :=
  2 * (∑ i, B.1 i i * x i ^ 2) +
    ∑ j, Finset.sum (Finset.Iio j) (fun i => B.1 i j * x i * x j)

/-- The displayed triangular map `q_B(z,x)=(z+f_B(x),x)`. -/
def quadraticTransporter (B : SymmetricMatrix3) : Omega3 → Omega3 :=
  fun p => (p.1 + quadraticFunction B p.2, p.2)

/-- The displayed inverse triangular map used in the conjugation formula. -/
def quadraticTransporterInverse (B : SymmetricMatrix3) : Omega3 → Omega3 :=
  fun p => (p.1 - quadraticFunction B p.2, p.2)

/-- The displayed triangular maps are the mutually inverse permutation maps. -/
def quadraticTransporterIsPermutation (B : SymmetricMatrix3) : Prop :=
  Function.LeftInverse (quadraticTransporterInverse B) (quadraticTransporter B) ∧
    Function.RightInverse (quadraticTransporterInverse B) (quadraticTransporter B)

/-- Membership in the conjugate of the natural translation copy by `q_B`. -/
def quadraticConjugateMember
    (B : SymmetricMatrix3) (u : Equiv.Perm Omega3) : Prop :=
  quadraticTransporterIsPermutation B ∧
    ∃ v : Equiv.Perm Omega3, v ∈ translationImageGroup ∧
      ∀ p : Omega3,
        u p = quadraticTransporterInverse B (v (quadraticTransporter B p))

/-- The copy `R_B` generated by the exact quadratic conjugates of `T`. -/
def quadraticCopy (B : SymmetricMatrix3) : Subgroup (Equiv.Perm Omega3) :=
  Subgroup.closure {u | quadraticConjugateMember B u}

/-- Conjugacy by an element of the selected actual affine-function image. -/
def conjugateInActualAffineImage
    (R T : Subgroup (Equiv.Perm Omega3)) : Prop :=
  ∃ a : Equiv.Perm Omega3, a ∈ affineImage ∧
    ∀ u : Equiv.Perm Omega3,
      u ∈ R ↔ ∃ v : Equiv.Perm Omega3, v ∈ T ∧ u = a⁻¹ * v * a

/-- The vertical function profile of a permutation, evaluated on the marked
line `z=0`. -/
def verticalProfile (g : Equiv.Perm Omega3) : H3 → F3 :=
  fun x => (g (0, x)).1

/-- The vertical profiles occurring in a subgroup. -/
def verticalProfiles (G : Subgroup (Equiv.Perm Omega3)) : Set (H3 → F3) :=
  {f | ∃ g : G, ∀ x : H3, f x = verticalProfile (g : Equiv.Perm Omega3) x}

/-- The generated vertical function module. -/
def verticalFunctionModule
    (G : Subgroup (Equiv.Perm Omega3)) : Submodule F3 (H3 → F3) :=
  Submodule.span F3 (verticalProfiles G)

/-- The constant line in the vertical function space. -/
def constantLine : Submodule F3 (H3 → F3) :=
  Submodule.span F3 {fun _ : H3 => (1 : F3)}

/-- The row space of a symmetric matrix, represented by its row linear
functionals on `H`. -/
def rowSpace (B : SymmetricMatrix3) : Submodule F3 (H3 → F3) :=
  Submodule.span F3
    (Set.range (fun i : Fin 5 => fun x : H3 =>
      ∑ j, B.1 i j * x j))

/-- The matrix rank used in the order formula is the dimension of this exact
row space. -/
def matrixRank (B : SymmetricMatrix3) : ℕ :=
  Matrix.rank B.1

/-- The group generated by `T` and `R_B`. -/
def generatedGroup (B : SymmetricMatrix3) : Subgroup (Equiv.Perm Omega3) :=
  Subgroup.closure
    ((translationImageGroup : Set (Equiv.Perm Omega3)) ∪
      (quadraticCopy B : Set (Equiv.Perm Omega3)))

/-- Claim 32616: symmetric matrices classify exactly the regular elementary-
abelian order-`3^6` copies in the selected actual image, without duplication. -/
def claim32616_symmetricMatrixClassification : Prop :=
  ∀ R : Subgroup (Equiv.Perm Omega3),
    regularElementaryAbelianOrderSix R →
      containedInActualAffineImage R →
        ∃! B : SymmetricMatrix3, R = quadraticCopy B

/-- Claim 32619: each symmetric matrix gives the exact quadratic conjugate copy,
and all such copies are regular, with the zero and nonzero consequences. -/
def claim32619_quadraticConjugateCopies : Prop :=
  (∀ B : SymmetricMatrix3,
    ∀ u : Equiv.Perm Omega3,
      u ∈ quadraticCopy B ↔ quadraticConjugateMember B u) ∧
  (∀ B : SymmetricMatrix3,
    quadraticTransporterIsPermutation B ∧
      regularElementaryAbelianOrderSix (quadraticCopy B) ∧
      containedInActualAffineImage (quadraticCopy B)) ∧
  (∀ B : SymmetricMatrix3,
    B.1 = 0 → quadraticCopy B = translationImageGroup) ∧
  (∀ B : SymmetricMatrix3,
    B.1 ≠ 0 → quadraticCopy B ≠ translationImageGroup)

/-- Claim 32620: a nonzero quadratic copy is outside the natural copy's
conjugacy class inside the selected actual image. -/
def claim32620_nonconjugateActualImage : Prop :=
  ∀ B : SymmetricMatrix3,
    B.1 ≠ 0 →
      ¬ conjugateInActualAffineImage (quadraticCopy B) translationImageGroup

/-- Claim 32621: the generated vertical module and the exact order formula. -/
def claim32621_generatedVerticalModuleOrder : Prop :=
  ∀ B : SymmetricMatrix3,
    verticalFunctionModule (generatedGroup B) =
        constantLine ⊔ rowSpace B ∧
      Nat.card (generatedGroup B) = 3 ^ (6 + matrixRank B)

end
end MathlibPlus.Open.ResearchFormalization.R1821
