import MathlibPlus.Open.ResearchFormalization.R1821Suborbits
import MathlibPlus.Open.ResearchFormalization.PermutationClaims

namespace MathlibPlus.Open.ResearchFormalization.R1821Claim32626

noncomputable section

open MathlibPlus.Open.ResearchBatch.ActualAffine
open MathlibPlus.Open.ResearchFormalization.R1821Suborbits
open MathlibPlus.Open.ResearchFormalization.PermutationClaims

/-- Claim 32626: the exact quadratic transporter belongs to the two-closure of
The group generated by the natural translation copy and its quadratic copy. -/
def everySymmetricQuadraticTransporterInGeneratedTwoClosure_claim32626 : Prop :=
  ∀ B : Matrix (Fin 5) (Fin 5) F3, B.IsSymm →
    quadraticTransporter B ∈ twoClosure (generatedGroup B)

end

end MathlibPlus.Open.ResearchFormalization.R1821Claim32626
