import MathlibPlus.Algebra.R2111ContextIdeal37141

namespace MathlibPlus.Open.ResearchFormalization.R2111Claim37144

noncomputable section

abbrev ContextCoefficient := MvPolynomial ℕ ℤ
abbrev MarkerPolynomial := Polynomial ContextCoefficient

/-- The complete shifted-trace top-host defect statement over the exact
coefficient and marker rings.  The trace operator is explicit as a linear
map, while the context ideal is generated by its second and third shifted
traces. -/
def completeTopHostDefectInPrimeContextIdeal_37144 : Prop :=
  ∀ (Φ : MarkerPolynomial →ₗ[ContextCoefficient] ContextCoefficient)
    (C : MarkerPolynomial)
    (G Q0 j0 : ContextCoefficient),
    let S2 : ContextCoefficient := Φ (Polynomial.X ^ 2 * C)
    let S3 : ContextCoefficient := Φ (Polynomial.X ^ 3 * C)
    let I := MathlibPlus.Algebra.R2111ContextIdeal37141.contextIdeal S2 S3
    I.IsPrime →
      j0 = G * Q0 →
        j0 ∈ I →
          Q0 ∉ I →
            G ∈ I

end

end MathlibPlus.Open.ResearchFormalization.R2111Claim37144
