import Mathlib
import MathlibPlus.Open.ResearchFormalization.BatchR3074Claims45864_45865_45866_45867

namespace MathlibPlus.Open.ResearchFormalization.R3074ConstructionClaim45863

noncomputable section

open MathlibPlus.Open.ResearchFormalization.BatchR3074

/-- The common linear layer acting on every copy of `V`. -/
def commonLinearSet (d n : ℕ) : Set (Equiv.Perm (Omega d n)) :=
  {f | ∃ L : V d ≃+ V d,
    ∀ x : V d, ∀ i : Fin n,
      f (x, i) = (L x, i)}

/-- The block-permutation layer fixing the `V` coordinate. -/
def blockPermutationSet (d n : ℕ) : Set (Equiv.Perm (Omega d n)) :=
  {f | ∃ σ : Equiv.Perm (Fin n),
    ∀ x : V d, ∀ i : Fin n,
      f (x, i) = (x, σ i)}

/-- The subgroup generated by the translation, common-linear, and block
permutation layers. -/
def generatedDiagonalAffineGroup (d n : ℕ) :
    Subgroup (Equiv.Perm (Omega d n)) :=
  Subgroup.closure
    (diagonalTranslationSet d n ∪
      commonLinearSet d n ∪ blockPermutationSet d n)

/-- Claim 45863: the displayed diagonal translation set is `M`, while the
permutation group `X` is generated by that layer, the common `GL(V)` layer,
and the blockwise `S_n` layer, with the exact common affine normal form. -/
def diagonalAffineConstruction_claim45863 : Prop :=
  ∀ (d n : ℕ),
    (∀ f : Equiv.Perm (Omega d n),
      f ∈ diagonalTranslationGroup d n ↔
        diagonalTranslationForm f) ∧
      diagonalAffineGroup d n = generatedDiagonalAffineGroup d n ∧
        (∀ f : Equiv.Perm (Omega d n),
          f ∈ diagonalAffineGroup d n ↔ diagonalAffineForm f) ∧
          (∀ L : V d ≃+ V d,
            ∃ f : Equiv.Perm (Omega d n),
              f ∈ commonLinearSet d n ∧
                (∀ x : V d, ∀ i : Fin n,
                  f (x, i) = (L x, i))) ∧
            (∀ σ : Equiv.Perm (Fin n),
              ∃ f : Equiv.Perm (Omega d n),
                f ∈ blockPermutationSet d n ∧
                  (∀ x : V d, ∀ i : Fin n,
                    f (x, i) = (x, σ i))) ∧
              (∀ f : diagonalAffineGroup d n,
                ∃ (L : V d ≃+ V d) (t : V d)
                  (σ : Equiv.Perm (Fin n)),
                  ∀ x : V d, ∀ i : Fin n,
                    f.1 (x, i) = (L x + t, σ i))

end

end MathlibPlus.Open.ResearchFormalization.R3074ConstructionClaim45863
