import MathlibPlus.Open.ResearchFormalization.RademacherArea

namespace MathlibPlus.Open.ResearchFormalization.R3630

noncomputable section

open Classical
open scoped BigOperators

/-- Two cube points are Hamming neighbors when exactly one coordinate differs. -/
def cubeAdjacent {n : ℕ} (x y : RademacherCube n) : Prop :=
  ∃ i : Fin n, x i ≠ y i ∧ ∀ j : Fin n, j ≠ i → x j = y j

/-- The maximum edge oscillation, with zero included for the zero-dimensional cube. -/
noncomputable def edgeOscillation {n : ℕ}
    (z : RademacherCube n → ℝ) : ℝ :=
  sSup {a : ℝ |
    a = 0 ∨ ∃ x y : RademacherCube n, cubeAdjacent x y ∧
      a = |z x - z y|}

/-- The half-normalized Hamming Lipschitz constant. -/
def lipPlus {n : ℕ} (z : RademacherCube n → ℝ) : ℝ :=
  edgeOscillation z / 2

/-- The complete branch transcript generated by a cube point. -/
def treePath {n : ℕ} : DecisionTree n → RademacherCube n → List Bool
  | .leaf _, _ => []
  | .query coordinate ifFalse ifTrue, x =>
      if x coordinate then true :: treePath ifTrue x
      else false :: treePath ifFalse x

/-- The coordinates queried along a complete branch transcript. -/
def treeQueryPath {n : ℕ} : DecisionTree n → List Bool → List (Fin n)
  | .leaf _, _ => []
  | .query _ _ _, [] => []
  | .query coordinate ifFalse ifTrue, branch :: path =>
      coordinate ::
        if branch then treeQueryPath ifTrue path
        else treeQueryPath ifFalse path

/-- The stopping time of a tree on a cube point. -/
def treeTau {n : ℕ} (tree : DecisionTree n) (x : RademacherCube n) : ℕ :=
  (treePath tree x).length

/-- The filtration cell after the first `m` branch decisions on the path of `x`. -/
noncomputable def treeFiltrationCell {n : ℕ} (tree : DecisionTree n)
    (x : RademacherCube n) (m : ℕ) : Finset (RademacherCube n) :=
  transcriptCell tree ((treePath tree x).take m)

/-- Conditional mean of an arbitrary real target on a finite transcript cell. -/
noncomputable def realConditionalMean {n : ℕ}
    (g : RademacherCube n → ℝ)
    (cell : Finset (RademacherCube n)) : ℝ :=
  cell.sum g / (cell.card : ℝ)

/-- Conditional variance of an arbitrary real target on a finite transcript cell. -/
noncomputable def realConditionalVariance {n : ℕ}
    (g : RademacherCube n → ℝ)
    (cell : Finset (RademacherCube n)) : ℝ :=
  let μ := realConditionalMean g cell
  cell.sum (fun x => (g x - μ) ^ 2) / (cell.card : ℝ)

/-- The node mean for an arbitrary real target. -/
noncomputable def realNodeMean {n : ℕ} (g : RademacherCube n → ℝ)
    (tree : DecisionTree n) (path : List Bool) : ℝ :=
  realConditionalMean g (transcriptCell tree path)

/-- The node Haar half-difference for an arbitrary real target. -/
noncomputable def realNodeHalfDifference {n : ℕ}
    (g : RademacherCube n → ℝ) (tree : DecisionTree n) (path : List Bool) : ℝ :=
  (realConditionalMean g (transcriptCell tree (path ++ [true])) -
      realConditionalMean g (transcriptCell tree (path ++ [false]))) / 2

/-- The conditional variance attached to a tree node. -/
noncomputable def realNodeVariance {n : ℕ} (g : RademacherCube n → ℝ)
    (tree : DecisionTree n) (path : List Bool) : ℝ :=
  realConditionalVariance g (transcriptCell tree path)

/-- Covariance under the uniform finite Rademacher measure. -/
def cubeCovariance {n : ℕ} (f g : RademacherCube n → ℝ) : ℝ :=
  uniformMean (fun x => f x * g x) - uniformMean f * uniformMean g

/-- Boundedness of a target on the finite cube. -/
def boundedCube {n : ℕ} (g : RademacherCube n → ℝ) : Prop :=
  ∃ B : ℝ, ∀ x, |g x| ≤ B

/-- A real target is terminally computed by a no-repeat tree. -/
def terminalTree {n : ℕ} (g : RademacherCube n → ℝ)
    (tree : DecisionTree n) : Prop :=
  noRepeat tree ∧ ∀ x, tree.evaluate x = g x

/-- The cumulative posterior-variance area of a terminal real-target tree. -/
noncomputable def realTreeArea {n : ℕ} (tree : DecisionTree n)
    (g : RademacherCube n → ℝ) : ℝ :=
  tree.internalPaths.sum (fun path =>
    nodeProbability tree path * realNodeVariance g tree path)

/-- The optimal cumulative area for a real target. -/
noncomputable def realIntrinsicArea {n : ℕ}
    (g : RademacherCube n → ℝ) : ℝ :=
  sInf {a : ℝ | ∃ tree : DecisionTree n,
    terminalTree g tree ∧ a = realTreeArea tree g}

/-- Expected number of queries in a determining no-repeat tree. -/
noncomputable def expectedTreeCost {n : ℕ} (tree : DecisionTree n) : ℝ :=
  (∑ x : RademacherCube n, (treeTau tree x : ℝ)) / (2 : ℝ) ^ n

/-- The minimum expected deterministic query cost of a Boolean target. -/
noncomputable def queryCost {n : ℕ} (h : BooleanFunction n) : ℝ :=
  sInf {c : ℝ | ∃ tree : DecisionTree n,
    validDeterminingTree h tree ∧ c = expectedTreeCost tree}

/-- The path-Haar profile appearing in the absolute relaxation. -/
noncomputable def pathHaarProfile {n : ℕ} (h : BooleanFunction n)
    (tree : DecisionTree n) (r : List Bool → ℝ) : ℝ :=
  tree.internalPaths.sum (fun path =>
    nodeProbability tree path * |nodeHalfDifference h tree path| * r path)

/-- The suggested absolute depth profile `d(v)+1`. -/
def naturalDepthProfile (path : List Bool) : ℝ :=
  (path.length + 1 : ℝ)

/-- The minimum absolute Haar load over determining trees for this profile. -/
noncomputable def depthProfileMinimum {n : ℕ} (h : BooleanFunction n) : ℝ :=
  sInf {c : ℝ | ∃ tree : DecisionTree n,
    validDeterminingTree h tree ∧
      c = pathHaarProfile h tree naturalDepthProfile}

/-- One node Haar packet, written without choosing a default coordinate at leaves. -/
noncomputable def treeHaarPacket {n : ℕ}
    (tree : DecisionTree n) (g : RademacherCube n → ℝ)
    (path : List Bool) (x : RademacherCube n) : ℝ :=
  match tree.queryAt path with
  | none => 0
  | some coordinate =>
      realNodeHalfDifference g tree path *
        (if x ∈ transcriptCell tree path then rademacherValue (x coordinate) else 0)

/-- The residual-sum test along a terminal tree. -/
noncomputable def residualSum {n : ℕ} (tree : DecisionTree n)
    (g : RademacherCube n → ℝ) (x : RademacherCube n) : ℝ :=
  Finset.sum (Finset.range (treeTau tree x)) (fun m =>
    g x - realConditionalMean g (treeFiltrationCell tree x m))

/-- The expected sum of conditional variances along the stopped filtration. -/
noncomputable def filtrationVarianceSum {n : ℕ} (tree : DecisionTree n)
    (g : RademacherCube n → ℝ) : ℝ :=
  uniformMean (fun x =>
    Finset.sum (Finset.range (treeTau tree x)) (fun m =>
      realConditionalVariance g (treeFiltrationCell tree x m)))

/-- A finite Boolean law whose barycentre is the given real target. -/
def representsTarget {n : ℕ} (g : RademacherCube n → ℝ)
    (law : BooleanLaw n) : Prop :=
  isProbabilityLaw law ∧ ∀ x, lawBarycenter law x = g x

/-- Expected covariance with a fixed test under a finite Boolean law. -/
def lawExpectedCovariance {n : ℕ} (law : BooleanLaw n)
    (z : RademacherCube n → ℝ) : ℝ :=
  (law.map (fun entry => entry.2 * cubeCovariance entry.1.1 z)).sum

/-- Expected minimum query cost under a finite Boolean law. -/
def lawExpectedQueryCost {n : ℕ} (law : BooleanLaw n) : ℝ :=
  (law.map (fun entry => entry.2 * queryCost entry.1)).sum

/-- Area optimality for a terminal real target. -/
def areaOptimal {n : ℕ} (tree : DecisionTree n)
    (g : RademacherCube n → ℝ) : Prop :=
  terminalTree g tree ∧ realTreeArea tree g = realIntrinsicArea g

/-- Claim 51060: the normalized edge-Lipschitz covariance bound, its local
child-mean inequalities, and the factor-one-half convention correction. -/
def claim51060_hammingLipschitzCovarianceBound : Prop :=
  ∀ (n : ℕ) (h : BooleanFunction n) (tree : DecisionTree n)
    (z : RademacherCube n → ℝ),
    validDeterminingTree h tree →
      lipPlus z ≤ 1 →
      (∀ path ∈ tree.internalPaths,
        |realNodeHalfDifference z tree path| ≤ 1) ∧
      (∀ path ∈ tree.internalPaths,
        nodeMean h tree (path ++ [true]) =
            nodeMean h tree path + nodeHalfDifference h tree path ∧
          nodeMean h tree (path ++ [false]) =
            nodeMean h tree path - nodeHalfDifference h tree path ∧
          |nodeMean h tree path + nodeHalfDifference h tree path| ≤ 1 ∧
          |nodeMean h tree path - nodeHalfDifference h tree path| ≤ 1 ∧
          |nodeHalfDifference h tree path| ≤
            1 - |nodeMean h tree path| ∧
          1 - |nodeMean h tree path| ≤
            1 - (nodeMean h tree path) ^ 2) ∧
      |cubeCovariance h.1 z| ≤ decisionTreeArea h tree ∧
      |cubeCovariance h.1 z| ≤ intrinsicArea h ∧
      (edgeOscillation z ≤ 1 →
        |cubeCovariance h.1 z| ≤ intrinsicArea h / 2)

/-- Claim 51064: the absolute profile relaxation and the failure of the natural
absolute depth profile to be controlled by minimum expected query cost. -/
def claim51064_absolutePathHaarProfile : Prop :=
  (∀ (n : ℕ) (h : BooleanFunction n) (tree : DecisionTree n)
    (z : RademacherCube n → ℝ) (r : List Bool → ℝ),
    validDeterminingTree h tree →
      (∀ path ∈ tree.internalPaths, 0 ≤ r path) →
      (∀ path ∈ tree.internalPaths,
        |realNodeHalfDifference z tree path| ≤ r path) →
      |cubeCovariance h.1 z| ≤ pathHaarProfile h tree r) ∧
  (∃ (n : ℕ) (h : BooleanFunction n),
    queryCost h < depthProfileMinimum h)

/-- Claim 51062: the stopped residual sum, its filtration variance identity,
its depth-sensitive Haar expansion, and the coefficient-sensitive dual. -/
def claim51062_residualSumCoefficientSensitiveDual : Prop :=
  ∀ (n : ℕ) (g : RademacherCube n → ℝ) (tree : DecisionTree n),
    boundedCube g → terminalTree g tree →
      cubeCovariance g (residualSum tree g) = filtrationVarianceSum tree g ∧
      filtrationVarianceSum tree g = realTreeArea tree g ∧
      (∀ x : RademacherCube n,
        residualSum tree g x =
          ∑ path ∈ tree.internalPaths,
            ((path.length + 1 : ℝ) * treeHaarPacket tree g path x)) ∧
      (∀ path ∈ tree.internalPaths,
        realNodeHalfDifference (residualSum tree g) tree path =
          (path.length + 1 : ℝ) * realNodeHalfDifference g tree path) ∧
      (∀ law : BooleanLaw n,
        representsTarget g law →
          areaOptimal tree g →
            realIntrinsicArea g =
              lawExpectedCovariance law (residualSum tree g)) ∧
      (areaOptimal tree g →
        (∀ h : BooleanFunction n,
          cubeCovariance h.1 (residualSum tree g) ≤ queryCost h) →
        ∀ law : BooleanLaw n,
          representsTarget g law →
            realIntrinsicArea g ≤ lawExpectedQueryCost law)

/-- A Boolean target is the parity character of the finite Rademacher cube. -/
def parityTarget {n : ℕ} (h : BooleanFunction n) : Prop :=
  ∀ x : RademacherCube n,
    h.1 x = ∏ j : Fin n, rademacherValue (x j)

/-- Claim 51065: the exact parity test for query cost, area, absolute depth
profile, and the residual-sum certificate. -/
def claim51065_parityExactTest : Prop :=
  ∀ (k : ℕ) (h : BooleanFunction k),
    parityTarget h →
      queryCost h = (k : ℝ) ∧
      intrinsicArea h = (k : ℝ) ∧
      depthProfileMinimum h = (k : ℝ) ∧
      (∀ tree : DecisionTree k,
        validDeterminingTree h tree →
          (∀ x : RademacherCube k,
            (treePath tree x).length = k ∧
              (treeQueryPath tree (treePath tree x)).toFinset = Finset.univ) ∧
          (∀ path ∈ tree.internalPaths,
            path.length < k ∧
              (path.length + 1 < k →
                nodeHalfDifference h tree path = 0) ∧
              (path.length + 1 = k →
                |nodeHalfDifference h tree path| = 1)) ∧
          (∀ x : RademacherCube k,
            residualSum tree h.1 x = (k : ℝ) * h.1 x) ∧
          cubeCovariance h.1 (residualSum tree h.1) =
            realTreeArea tree h.1 ∧
          realTreeArea tree h.1 = decisionTreeArea h tree ∧
          decisionTreeArea h tree = (k : ℝ))

end

end MathlibPlus.Open.ResearchFormalization.R3630
