import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R4734

noncomputable section

abbrev V (B Z : Type*) := B × Z

/-- Translation by an element of the additive group `B × Z`. -/
def translation {B Z : Type*} [AddGroup B] [AddGroup Z]
    (v : V B Z) : Equiv.Perm (V B Z) :=
  { toFun := fun x => x + v
    invFun := fun x => x - v
    left_inv := by intro x; exact add_sub_cancel_right x v
    right_inv := by intro x; exact sub_add_cancel x v }

/-- The pointed triangular shear and its inverse. -/
def triangularShear {B Z : Type*} [AddGroup B] [AddGroup Z]
    (f : B → Z) : Equiv.Perm (V B Z) :=
  { toFun := fun x => (x.1, x.2 + f x.1)
    invFun := fun x => (x.1, x.2 - f x.1)
    left_inv := by intro x; simp
    right_inv := by intro x; simp }

def translationGroup {B Z : Type*} [AddGroup B] [AddGroup Z] :
    Subgroup (Equiv.Perm (V B Z)) :=
  Subgroup.closure (Set.range (translation (B := B) (Z := Z)))

def transportedTranslationGroup {B Z : Type*} [AddGroup B] [AddGroup Z]
    (f : B → Z) : Subgroup (Equiv.Perm (V B Z)) :=
  (translationGroup (B := B) (Z := Z)).map
    (MulAut.conj (triangularShear f)).toMonoidHom

def generatedTwoCopyGroup {B Z : Type*} [AddGroup B] [AddGroup Z]
    (f : B → Z) : Subgroup (Equiv.Perm (V B Z)) :=
  Subgroup.closure
    ((translationGroup (B := B) (Z := Z) : Set (Equiv.Perm (V B Z))) ∪
      (transportedTranslationGroup (B := B) (Z := Z) f :
        Set (Equiv.Perm (V B Z))))

def pointStabilizer {B Z : Type*} [AddGroup B] [AddGroup Z]
    (X : Subgroup (Equiv.Perm (V B Z))) :
    Subgroup (Equiv.Perm (V B Z)) :=
  { carrier := {g | g ∈ X ∧ g (0, 0) = (0, 0)}
    one_mem' := by simp
    mul_mem' := by
      intro a b ha hb
      constructor
      · exact X.mul_mem ha.1 hb.1
      · simp [ha.2, hb.2]
    inv_mem' := by
      intro a ha
      constructor
      · exact X.inv_mem ha.1
      · simpa using (congrArg (fun y => a⁻¹ y) ha.2).symm }

def verticalMap {B Z : Type*} [AddGroup B] [AddGroup Z]
    (h : B → Z) : Equiv.Perm (V B Z) :=
  { toFun := fun x => (x.1, x.2 + h x.1)
    invFun := fun x => (x.1, x.2 - h x.1)
    left_inv := by intro x; simp
    right_inv := by intro x; simp }

def verticalPart {B Z : Type*} [AddGroup B] [AddGroup Z] :
    Subgroup (Equiv.Perm (V B Z)) :=
  { carrier := {g | ∀ b z, (g (b, z)).1 = b}
    one_mem' := by intro b z; rfl
    mul_mem' := by
      intro a b ha hb b₀ z
      change (a (b (b₀, z))).1 = b₀
      calc
        (a (b (b₀, z))).1 = (b (b₀, z)).1 := ha _ _
        _ = b₀ := hb _ _
    inv_mem' := by
      intro a ha b z
      have h := ha ((a⁻¹ (b, z)).1) ((a⁻¹ (b, z)).2)
      simpa using h.symm }

def secondDifference {B Z : Type*} [AddGroup B] [AddGroup Z]
    (f : B → Z) (u t b : B) : Z :=
  f (b + t + u) - f (b + t) - f (t + u) + f t

/-- R-4734.1: the normalized second differences give vertical elements of the
point stabilizer; equivalently, the subgroup generated by all displayed
vertical maps lies in the vertical part of `X₀`. -/
def claim58517 : Prop :=
  ∀ {B Z : Type*} [AddGroup B] [AddGroup Z]
    (f : B → Z), f 0 = 0 →
    Subgroup.closure
        (Set.range (fun ut : B × B =>
          verticalMap (secondDifference f ut.1 ut.2))) ≤
      pointStabilizer (generatedTwoCopyGroup f) ⊓ verticalPart

end

end MathlibPlus.Open.ResearchFormalization.R4734
