import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R4923LiteralCarrier

noncomputable section

/-- The exact first-cell dimensions in R-4923. -/
def literalK : ℕ := 690988

def literalP : ℕ := 8192

def literalR : ℕ := 5660573696

/-- The interval on which the literal carrier is considered. -/
def literalInterval : Set ℝ :=
  Set.Icc (6000000185827 : ℝ) (6000012174869.163 : ℝ)

abbrev literalIntervalPoint := {x : ℝ // x ∈ literalInterval}

/-- The real logarithmic frequency attached to the one-based carrier index. -/
def literalCarrierFrequency (r : Fin literalR) : ℝ :=
  Real.log (((r.1 + 1 : ℕ) : ℝ)) / 2

/-- The complex exponential exponent corresponding to the logarithmic frequency. -/
def literalCarrierExponent (r : Fin literalR) : ℂ :=
  -Complex.I * (literalCarrierFrequency r : ℂ)

/-- The individual literal-carrier exponential on the stated interval. -/
def literalCarrierBasis (r : Fin literalR) : literalIntervalPoint → ℂ :=
  fun x => Complex.exp ((x.1 : ℂ) * literalCarrierExponent r)

/-- The exponential polynomial with coefficient vector `c` on the stated interval. -/
def literalCarrierFunction (c : Fin literalR → ℂ) : literalIntervalPoint → ℂ :=
  fun x => ∑ r : Fin literalR, c r * literalCarrierBasis r x

/-- The vector-space carrier generated by the displayed literal exponentials. -/
noncomputable def literalCarrierSubmodule :
    Submodule ℂ (literalIntervalPoint → ℂ) :=
  Submodule.span ℂ (Set.range literalCarrierBasis)

/-- R-4923.1: the literal carrier is exactly the displayed `R`-term
exponential-polynomial family, with the stated dimensions and interval. -/
def literalCarrierSpace_claim55457 : Prop :=
  literalK * literalP = literalR ∧
    ∀ f : literalIntervalPoint → ℂ,
      f ∈ literalCarrierSubmodule ↔
        ∃ c : Fin literalR → ℂ, f = literalCarrierFunction c

/-- R-4923.4: the logarithmic frequencies are pairwise distinct, and every
nonzero coefficient vector gives a nonzero carrier function at a point of the
stated interval. -/
def distinctLogarithmicCarrier_claim55460 : Prop :=
  (∀ r s : Fin literalR, r ≠ s →
      literalCarrierFrequency r ≠ literalCarrierFrequency s) ∧
    ∀ c : Fin literalR → ℂ, c ≠ 0 →
      ∃ x : literalIntervalPoint, literalCarrierFunction c x ≠ 0

end

end MathlibPlus.Open.ResearchFormalization.R4923LiteralCarrier
