import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R5272Claim57497

noncomputable section

/-- The mixed second difference in the exact finite-dimensional vector-space
carrier. -/
def mixedDifference {B D : Type*}
    [AddCommGroup B] [AddCommGroup D]
    (Φ : B → D) (b x u : B) : D :=
  Φ (x + b + u) - Φ (x + b) - Φ (x + u) + Φ x

/-- The subspace generated by all mixed differences at direction `b`. -/
def mixedDifferenceSpace (p : ℕ) {B D : Type*}
    [AddCommGroup B] [AddCommGroup D] [Field (ZMod p)]
    [Module (ZMod p) D]
    (Φ : B → D) (b : B) : Submodule (ZMod p) D :=
  Submodule.span (ZMod p)
    (Set.range (fun xu : B × B => mixedDifference Φ b xu.1 xu.2))

/-- Claim 57497: reversing the base direction leaves the entire mixed-
difference subspace unchanged, not merely its dimension. -/
def claim57497 : Prop :=
  ∀ p : ℕ, Nat.Prime p → p % 2 = 1 →
    ∀ [Fact p.Prime],
    ∀ (B : Type*) [AddCommGroup B] [Module (ZMod p) B]
      [FiniteDimensional (ZMod p) B]
      (Φ : B → (ZMod p × ZMod p)),
      Φ 0 = 0 →
        ∀ b : B,
          mixedDifferenceSpace p Φ (-b) = mixedDifferenceSpace p Φ b

end

end MathlibPlus.Open.ResearchFormalization.R5272Claim57497
