import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R5537CompleteComponentShadow

noncomputable section

abbrev R5 := ZMod 5
abbrev W := Fin 3 → R5

/-- The first triangular shear in the displayed quinary permutation. -/
def shearA (v : W) : W :=
  ![v 0, v 1 + 3 * (v 0) ^ 2 * (v 2) ^ 3, v 2]

/-- The second triangular shear in the displayed quinary permutation. -/
def shearB (v : W) : W :=
  ![v 0, v 1 + 2 * (v 0) ^ 3 * (v 2) ^ 2, v 2]

/-- The two linear matrices in the displayed permutation. -/
def L1 : Matrix (Fin 3) (Fin 3) R5 :=
  !![2, 4, 0; 3, 3, 2; 4, 2, 1]

def L2 : Matrix (Fin 3) (Fin 3) R5 :=
  !![3, 4, 4; 4, 0, 4; 2, 1, 0]

/-- Matrix action on the quinary three-coordinate space. -/
def matrixAction (M : Matrix (Fin 3) (Fin 3) R5) (v : W) : W :=
  fun i => ∑ j : Fin 3, M i j * v j

/-- The pointed odd permutation from the R-5537 packet. -/
def q : W → W :=
  fun v =>
    matrixAction L2
      (matrixAction L1
        (shearB (shearA (shearA (shearA v)))))

/-- The explicit matrix claimed to shadow `q` on every transport block. -/
def A : W → W :=
  matrixAction !![0, 2, 0; 1, 4, 0; 0, 1, 1]

/-- The inverse used in the relative-transport difference. -/
def qInv (v : W) : W := Function.invFun q v

def qTau (x s : W) : W := qInv (q (x + s) - q x)

/-- One generator of the relative-transport equivalence relation. -/
def qTransportStep (s t : W) : Prop :=
  ∃ x : W, t = qTau x s ∨ t = -qTau x s

/-- The coarsest block containing a displacement under relative transport and
negation. -/
def qTransportBlock (s : W) : Set W :=
  {t | Relation.EqvGen qTransportStep s t}

/-- The partition generated by all relative transports and their negatives. -/
def qTransportPartition : Set (Set W) :=
  {B | ∃ s : W, B = qTransportBlock s}

def qLexLess (u v : W) : Prop :=
  ∃ i : Fin 3,
    (∀ j : Fin 3, j.val < i.val → u j = v j) ∧
      (u i).val < (v i).val

def qIsLeast (B : Set W) (m : W) : Prop :=
  m ∈ B ∧ ∀ w : W, w ∈ B → ¬ qLexLess w m

def qBlockBefore (B C : Set W) : Prop :=
  Set.ncard B < Set.ncard C ∨
    (Set.ncard B = Set.ncard C ∧
      ∃ b c : W, qIsLeast B b ∧ qIsLeast C c ∧ qLexLess b c)

/-- An ordered enumeration of the fifteen blocks, including the exact sizes
and the ordering rule used in the packet. -/
def qOrderedBlockFamily (B : Fin 15 → Set W) : Prop :=
  (∀ i : Fin 15, B i ∈ qTransportPartition) ∧
    (∀ C : Set W, C ∈ qTransportPartition → ∃ i : Fin 15, B i = C) ∧
    (∀ i j : Fin 15, i ≠ j → Disjoint (B i) (B j)) ∧
    (⋃ i : Fin 15, B i) = Set.univ ∧
    Set.ncard (B 0) = 1 ∧
    Set.ncard (B 1) = 2 ∧
    Set.ncard (B 2) = 2 ∧
    (∀ i : Fin 15, 3 ≤ i.val → Set.ncard (B i) = 10) ∧
    (∀ i j : Fin 15, i.val < j.val → qBlockBefore (B i) (B j))

/-- A set of displacements is a union of the transport blocks. -/
def qIsUnionOfBlocks (C : Set W) : Prop :=
  ∀ w : W, w ∈ C ↔
    ∃ B : Set W, B ∈ qTransportPartition ∧ w ∈ B ∧ B ⊆ C

def qLift {U : Type*} (z : W × U) : W × U := (q z.1, z.2)

def ALift {U : Type*} (z : W × U) : W × U := (A z.1, z.2)

def qPassiveSet {U : Type*} (C : U → Set W) : Set (W × U) :=
  {z | z.1 ∈ C z.2}

def qIdentityFree {G : Type*} [Zero G] (S : Set G) : Prop :=
  (0 : G) ∉ S

def qInverseClosed {G : Type*} [Neg G] (S : Set G) : Prop :=
  ∀ ⦃x : G⦄, x ∈ S → -x ∈ S

def qCayleyGraphIsomorphism {G : Type*} [AddGroup G]
    (S T : Set G) (f : G → G) : Prop :=
  Function.Bijective f ∧
    ∀ x y : G,
      (x ≠ y ∧ y - x ∈ S) ↔
        (f x ≠ f y ∧ f y - f x ∈ T)

def qLinearShadow (B : Set W) : Prop :=
  Set.image A B = Set.image q B

/-- The six passive directions in the exact rank-six R-5537 source. -/
def rankSixDirections : Fin 6 → W
  | 0 => ![1, 0, 0]
  | 1 => ![0, 1, 0]
  | 2 => ![1, 1, 0]
  | 3 => ![0, 0, 1]
  | 4 => ![1, 0, 1]
  | 5 => ![0, 1, 1]

def rankSixBlockIndices : Fin 6 → Fin 15
  | 0 => 1
  | 1 => 10
  | 2 => 14
  | 3 => 4
  | 4 => 14
  | 5 => 14

def rankSixSource (B : Fin 15 → Set W) : Set (W × W) :=
  {z | ∃ j : Fin 6, ∃ ε : R5,
    (ε = 1 ∨ ε = -1) ∧
      z.2 = ε • rankSixDirections j ∧
        z.1 ∈ B (rankSixBlockIndices j)}

def rankSixTarget (B : Fin 15 → Set W) : Set (W × W) :=
  Set.image qLift (rankSixSource B)

def rankSixShadow : (W × W) → (W × W) :=
  fun z => (A z.1, z.2)

def rankSixAmbientMatrix : Matrix (Fin 6) (Fin 6) R5 :=
  !![0, 2, 0, 0, 0, 0;
     1, 4, 0, 0, 0, 0;
     0, 1, 1, 0, 0, 0;
     0, 0, 0, 1, 0, 0;
     0, 0, 0, 0, 1, 0;
     0, 0, 0, 0, 0, 1]

def rankSixActiveMatrix : Matrix (Fin 3) (Fin 3) R5 :=
  !![0, 2, 0; 1, 4, 0; 0, 1, 1]

def rankSixMatrixAction (z : W × W) : W × W :=
  (matrixAction rankSixActiveMatrix z.1, z.2)

/-- Exact rank-six source size and its common linear shadow. -/
def rankSixShadowStatement (B : Fin 15 → Set W) : Prop :=
  Set.ncard (rankSixSource B) = 104 ∧
    qIdentityFree (rankSixSource B) ∧
    qInverseClosed (rankSixSource B) ∧
    qIdentityFree (rankSixTarget B) ∧
    qInverseClosed (rankSixTarget B) ∧
    qCayleyGraphIsomorphism
      (rankSixSource B) (rankSixTarget B) qLift ∧
    AddSubgroup.closure (rankSixSource B) = ⊤ ∧
    AddSubgroup.closure (rankSixTarget B) = ⊤ ∧
    Function.Bijective rankSixShadow ∧
    (∃ e : (W × W) ≃ₗ[R5] (W × W),
      ∀ z, e z = rankSixShadow z) ∧
    Set.image rankSixShadow (rankSixSource B) = rankSixTarget B ∧
    Set.image rankSixMatrixAction (rankSixSource B) = rankSixTarget B

/-- Claim 61177: the exact quinary component partition, its common linear
shadow, all component-labelled passive lifts, and the displayed rank-six
specialization. -/
def claim61177 : Prop :=
  Function.Bijective q ∧
    q 0 = 0 ∧
    (∀ x : W, q (-x) = -q x) ∧
    (∃ B : Fin 15 → Set W,
      qOrderedBlockFamily B ∧
        Function.Bijective A ∧
        (∃ e : W ≃ₗ[R5] W, ∀ x, e x = A x) ∧
        (∀ C : Set W, C ∈ qTransportPartition → qLinearShadow C) ∧
        (∀ (U : Type*) [AddCommGroup U] [Module R5 U]
          [Module.Finite R5 U],
          ∀ C : U → Set W,
            (∀ d : U, qIsUnionOfBlocks (C d)) →
              let S := qPassiveSet C
              qIdentityFree S →
                qInverseClosed S →
                  qCayleyGraphIsomorphism S (Set.image qLift S) qLift ∧
                    Set.image ALift S = Set.image qLift S) ∧
        rankSixShadowStatement B)

end
end MathlibPlus.Open.ResearchFormalization.R5537CompleteComponentShadow
