import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.Claim23508

noncomputable section

private abbrev ConductorRing := MvPolynomial (Fin 2 ⊕ ℕ) ℚ

private def conductorS : ConductorRing :=
  MvPolynomial.X (Sum.inl (0 : Fin 2))

private def conductorZ : ConductorRing :=
  MvPolynomial.X (Sum.inl (1 : Fin 2))

private def conductorE (k : ℕ) : ConductorRing :=
  MvPolynomial.X (Sum.inr k)

private def conductorKIdeal : Ideal ConductorRing :=
  Ideal.span (Set.range conductorE)

private def polynomialAtS (p : Polynomial ℚ) : ConductorRing :=
  Polynomial.eval₂ (algebraMap ℚ ConductorRing) conductorS p

private def conductorA : Set ConductorRing :=
  {x | ∃ p : Polynomial ℚ, ∃ k : ConductorRing,
    k ∈ conductorKIdeal ∧ x = polynomialAtS p + k}

private def conductorPoint (c : ℚ) : Submodule ℚ ConductorRing :=
  conductorKIdeal.restrictScalars ℚ ⊔
    Submodule.span ℚ {x : ConductorRing |
      ∃ a ∈ conductorA,
        (conductorS - algebraMap ℚ ConductorRing c) * a = x}

private def conductorSquare (c : ℚ) : Submodule ℚ ConductorRing :=
  Submodule.span ℚ {x : ConductorRing |
    ∃ a ∈ conductorPoint c, ∃ b ∈ conductorPoint c, a * b = x}

private abbrev conductorCotangent (c : ℚ) :=
  (conductorPoint c : Type) ⧸
    Submodule.comap (conductorPoint c).subtype (conductorSquare c)

/-- Claim 23508: at every rational conductor parameter, the cotangent
quotient of the exact point ideal by its square has countably infinite
vector-space dimension.  The polynomial carrier is
`ℚ[s,z,e₂,e₃,…]`, `K` is generated by the independent `e_k`, and the point
ideal is `K + (s-c)A` with its polynomial `ℚ[s]` part displayed explicitly. -/
def claim_23508 : Prop :=
  ∀ c : ℚ,
    Module.rank ℚ (conductorCotangent c) = Cardinal.aleph0

end
end MathlibPlus.Open.ResearchFormalization.Claim23508
