import Mathlib

open scoped BigOperators

namespace MathlibPlus.Open.ResearchFormalization.R0613

noncomputable section

abbrev PositiveIndex := ℕ+
abbrev CoefficientRing := MvPolynomial PositiveIndex ℚ
abbrev RootRing := Polynomial CoefficientRing
abbrev ToricRing := MvPolynomial (Fin 2) ℚ

private def positiveOne : PositiveIndex := 1

private def rootZ : RootRing := Polynomial.X

private def rootX (k : PositiveIndex) : RootRing :=
  Polynomial.C (MvPolynomial.X k)

private def rootClosure (P : RootRing) : RootRing :=
  rootZ * P +
    P.support.sum (fun k =>
      Polynomial.C (MvPolynomial.X (Nat.succPNat k) * P.coeff k))

private def rootStable (S : Subalgebra ℚ RootRing) : Prop :=
  ∀ P : RootRing, P ∈ S → rootClosure P ∈ S

private def scalarAlgebra : Subalgebra ℚ RootRing :=
  sInf {S : Subalgebra ℚ RootRing | rootStable S}

private def toricU : ToricRing := MvPolynomial.X 0

private def toricV : ToricRing := MvPolynomial.X 1

private def toricCoefficientMap : CoefficientRing →+* ToricRing :=
  MvPolynomial.eval₂Hom (algebraMap ℚ ToricRing)
    (fun k => toricU * toricV ^ (k : ℕ))

private def toricSpecialization : RootRing →ₐ[ℚ] ToricRing :=
  RingHom.toRatAlgHom (Polynomial.eval₂RingHom toricCoefficientMap toricV)

private def scalarS : RootRing := rootZ + rootX positiveOne

private def scalarW : ToricRing := toricV * (1 + toricU)

private def scalarLine : Subalgebra ℚ ToricRing :=
  Algebra.adjoin ℚ ({scalarW} : Set ToricRing)

private def scalarPreimage : Subalgebra ℚ RootRing :=
  Subalgebra.comap toricSpecialization scalarLine

private def scalarFiberProduct : Subalgebra ℚ (RootRing × scalarLine) :=
  AlgHom.pullback toricSpecialization scalarLine.val

private def scalarLineInRoot : Subalgebra ℚ RootRing :=
  Algebra.adjoin ℚ ({scalarS} : Set RootRing)

private def phiKernel : Submodule ℚ RootRing :=
  LinearMap.ker toricSpecialization.toLinearMap

private def vectorSpaceDirectSum
    (U V W : Submodule ℚ RootRing) : Prop :=
  U ⊔ V = W ∧ Disjoint U V

private def coefficientWeight (m : PositiveIndex →₀ ℕ) : ℕ :=
  m.sum (fun k a => (k : ℕ) * a)

private def rootMonomialWeight (zDegree : ℕ)
    (m : PositiveIndex →₀ ℕ) : ℕ :=
  zDegree + coefficientWeight m

private def weightedHomogeneous (P : RootRing) (n : ℕ) : Prop :=
  ∀ a ∈ P.support, ∀ m ∈ (P.coeff a).support,
    rootMonomialWeight a m = n

private def weightPiece (n : ℕ) : Submodule ℚ RootRing :=
  Submodule.span ℚ {P : RootRing | weightedHomogeneous P n}

private def scalarPiece (n : ℕ) : Submodule ℚ RootRing :=
  scalarAlgebra.toSubmodule ⊓ weightPiece n

private def closedPolynomialSubmodule : Submodule ℚ RootRing :=
  Submodule.span ℚ {P : RootRing | P.support ⊆ ({0} : Finset ℕ)}

private def closedOnlyPiece (n : ℕ) : Submodule ℚ RootRing :=
  scalarPiece n ⊓ closedPolynomialSubmodule

private def fullScalarDimension (n : ℕ) : ℕ :=
  Module.finrank ℚ (scalarPiece n)

private def positiveScalarDimension (n : ℕ) : ℕ :=
  fullScalarDimension n - Module.finrank ℚ (closedOnlyPiece n)

private def closedOnlyPositiveDimension (n : ℕ) : ℕ :=
  Module.finrank ℚ (closedOnlyPiece n)

private abbrev TriangularIndex := {k : PositiveIndex // 2 ≤ (k : ℕ)}

private def scalarE (k : TriangularIndex) : RootRing :=
  rootX k.1 - rootZ ^ ((k : ℕ) - 1) * rootX positiveOne

private def eWeight (m : TriangularIndex →₀ ℕ) : ℕ :=
  m.sum (fun k a => (k : ℕ) * a)

private def eProduct (m : TriangularIndex →₀ ℕ) : RootRing :=
  m.prod (fun k a => scalarE k ^ a)

private structure KernelMonomialIndex (n : ℕ) where
  zExponent : ℕ
  xExponent : ℕ
  eExponents : TriangularIndex →₀ ℕ
  weight_eq : zExponent + xExponent + eWeight eExponents = n
  has_e_factor : eExponents.support.Nonempty

private abbrev ScalarBasisIndex (n : ℕ) := Option (KernelMonomialIndex n)

private def scalarBasisVector {n : ℕ} : ScalarBasisIndex n → RootRing
  | none => scalarS ^ n
  | some q =>
      rootZ ^ q.zExponent * rootX positiveOne ^ q.xExponent *
        eProduct q.eExponents

/-- Claim 23326: the complete scalar rooted-factor algebra is the exact
preimage of the polynomial line generated by w, equivalently the displayed
algebraic pullback over the toric specialization. -/
def claim23326 : Prop :=
  scalarAlgebra = scalarPreimage ∧
    ∃ e : (scalarAlgebra : Type) ≃ₐ[ℚ] (scalarFiberProduct : Type),
      ∀ P : scalarAlgebra,
        (e P).1.1 = P.1 ∧
          (e P).1.2.1 = toricSpecialization P.1

/-- Claim 23327: the scalar algebra is the direct vector-space sum of the
polynomial line generated by s and the specialization kernel. -/
def claim23327 : Prop :=
  vectorSpaceDirectSum scalarLineInRoot.toSubmodule phiKernel
    scalarAlgebra.toSubmodule

/-- Claim 23328: the displayed s-power and e-monomials form the homogeneous
basis in every weight. -/
def claim23328 : Prop :=
  ∀ n : ℕ,
    ∃ basis : Module.Basis (ScalarBasisIndex n) ℚ (scalarPiece n),
      ∀ i : ScalarBasisIndex n,
        ((basis i : scalarPiece n) : RootRing) = scalarBasisVector i

/-- Claim 23331: the exact closed-only, full, and positive dimension data. -/
def claim23331 : Prop :=
  closedOnlyPositiveDimension 1 = 0 ∧
  closedOnlyPositiveDimension 2 = 0 ∧
  closedOnlyPositiveDimension 3 = 0 ∧
  closedOnlyPositiveDimension 4 = 1 ∧
  closedOnlyPositiveDimension 5 = 2 ∧
  closedOnlyPositiveDimension 6 = 5 ∧
  closedOnlyPositiveDimension 7 = 8 ∧
  closedOnlyPositiveDimension 8 = 14 ∧
  closedOnlyPositiveDimension 9 = 21 ∧
  closedOnlyPositiveDimension 10 = 32 ∧
  closedOnlyPositiveDimension 11 = 45 ∧
  closedOnlyPositiveDimension 12 = 65 ∧
  fullScalarDimension 1 = 1 ∧
  fullScalarDimension 2 = 2 ∧
  fullScalarDimension 3 = 4 ∧
  fullScalarDimension 4 = 8 ∧
  fullScalarDimension 5 = 14 ∧
  fullScalarDimension 6 = 24 ∧
  fullScalarDimension 7 = 38 ∧
  fullScalarDimension 8 = 59 ∧
  fullScalarDimension 9 = 88 ∧
  positiveScalarDimension 9 = 67 ∧
  fullScalarDimension 10 = 129 ∧
  positiveScalarDimension 10 = 97 ∧
  fullScalarDimension 11 = 184 ∧
  positiveScalarDimension 11 = 139 ∧
  fullScalarDimension 12 = 260 ∧
  positiveScalarDimension 12 = 195

end
end MathlibPlus.Open.ResearchFormalization.R0613
