import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1250.Claim30593

abbrev C9 := ZMod 9

/-- The normalized additive relative derivative on `C₉`. -/
def normalizedRelativeDerivative
    (σ : Equiv.Perm C9) (t : C9) : Equiv.Perm C9 :=
  (((Equiv.addRight t).trans σ).trans
      (Equiv.addRight (-(σ t)))).trans σ.symm

/-- The subgroup generated by all normalized relative derivatives. -/
def derivativeGroup (σ : Equiv.Perm C9) : Subgroup (Equiv.Perm C9) :=
  Subgroup.closure (Set.range (normalizedRelativeDerivative σ))

/-- Source inversion on the additive cyclic group. -/
def sourceInversion : Equiv.Perm C9 :=
  Equiv.neg C9

/-- Inversion transported through the normalized permutation. -/
def transportedInversion (σ : Equiv.Perm C9) : Equiv.Perm C9 :=
  (σ.trans (Equiv.neg C9)).trans σ.symm

/-- The subgroup generated by the derivative and both inversion maps. -/
def gammaGroup (σ : Equiv.Perm C9) : Subgroup (Equiv.Perm C9) :=
  Subgroup.closure
    ((derivativeGroup σ : Set (Equiv.Perm C9)) ∪
      ({sourceInversion, transportedInversion σ} : Set (Equiv.Perm C9)))

/-- The `Γ_σ`-orbit through a point of `C₉`. -/
def gammaOrbit (σ : Equiv.Perm C9) (x : C9) : Set C9 :=
  {y | ∃ g : Equiv.Perm C9, g ∈ gammaGroup σ ∧ g x = y}

/-- The multiplier `m_u(x)=ux` attached to a unit of `ZMod 9`. -/
def multiplier (u : C9ˣ) : C9 → C9 :=
  fun x => (u : C9) * x

/-- Claim 30593: every normalized permutation of the additive `C₉` has a
single unit multiplier shadow on every `Γ_σ` orbit, with the exact `8!`
normalization count. -/
def claim30593 : Prop :=
  Nat.factorial 8 = 40_320 ∧
    Nat.card {σ : Equiv.Perm C9 // σ 0 = 0} = Nat.factorial 8 ∧
      ∀ σ : Equiv.Perm C9, σ 0 = 0 →
        ∃ u : C9ˣ, ∀ x : C9,
          Set.image (multiplier u) (gammaOrbit σ x) =
            Set.image (fun y => σ y) (gammaOrbit σ x)

end MathlibPlus.Open.ResearchFormalization.R1250.Claim30593
