import MathlibPlus.Open.ResearchFormalization.R1250.Claim30597

namespace MathlibPlus.Open.ResearchFormalization.R1250.Claim30596

open MathlibPlus.Open.ResearchFormalization.R1250.Claim30597

noncomputable section

abbrev C9_30596 := ZMod 9

/-- The C₉ permutation δ_t(c)=σ⁻¹(σ(c+t)-σ(t)). -/
private def deltaPermutation30596
    (σ : Equiv.Perm C9_30596) (t : C9_30596) : Equiv.Perm C9_30596 :=
  (((Equiv.addRight t).trans σ).trans (Equiv.addRight (-σ t))).trans σ.symm

/-- Source inversion and the inversion transported through σ. -/
private def sourceInversion30596 : Equiv.Perm C9_30596 :=
  Equiv.neg C9_30596

private def targetInversion30596
    (σ : Equiv.Perm C9_30596) : Equiv.Perm C9_30596 :=
  (σ.trans (Equiv.neg C9_30596)).trans σ.symm

/-- The exact Γσ generated by all relative derivatives and the two inversion
permutations. -/
private def gammaGenerators30596 (σ : Equiv.Perm C9_30596) :
    Set (Equiv.Perm C9_30596) :=
  Set.range (deltaPermutation30596 σ) ∪
    {sourceInversion30596, targetInversion30596 σ}

private def gammaGroup30596 (σ : Equiv.Perm C9_30596) :
    Subgroup (Equiv.Perm C9_30596) :=
  Subgroup.closure (gammaGenerators30596 σ)

private def gammaOrbit30596
    (σ : Equiv.Perm C9_30596) (c : C9_30596) : Set C9_30596 :=
  {d | ∃ g : gammaGroup30596 σ, g.1 c = d}

/-- The product-space lifts of the Γσ generators, which preserve the V
coordinate. -/
private def productDerivativeEquiv30596
    {V : Type*} (σ : Equiv.Perm C9_30596) (t : C9_30596) :
    Equiv.Perm (V × C9_30596) :=
  Equiv.prodCongr (Equiv.refl V) (deltaPermutation30596 σ t)

private def productGenerators30596
    {V : Type*} (σ : Equiv.Perm C9_30596) :
    Set (Equiv.Perm (V × C9_30596)) :=
  Set.range (productDerivativeEquiv30596 σ) ∪
    {Equiv.prodCongr (Equiv.refl V) sourceInversion30596,
      Equiv.prodCongr (Equiv.refl V) (targetInversion30596 σ)}

private def productGroup30596
    {V : Type*} (σ : Equiv.Perm C9_30596) :
    Subgroup (Equiv.Perm (V × C9_30596)) :=
  Subgroup.closure (productGenerators30596 σ)

private def productOrbit30596
    {V : Type*} (σ : Equiv.Perm C9_30596) (x : V × C9_30596) :
    Set (V × C9_30596) :=
  {y | ∃ g : productGroup30596 σ, g.1 x = y}

private def transportedTargetInversionProduct30596
    {V : Type*} [AddGroup V] (σ : Equiv.Perm C9_30596) (x : V × C9_30596) :
    V × C9_30596 :=
  (-x.1, σ.symm (-σ x.2))

/-- Claim 30596: direct substitution gives the product relative derivative,
source and transported target inversion preserve the elementary-2 coordinate,
and the compatibility atoms are exactly the cylinders over Γσ-orbits in C₉. -/
def claim30596 : Prop :=
  ∀ (V : Type*) [Fintype V] [AddCommGroup V]
    (hV : ∀ v : V, v + v = 0)
    (σ : Equiv.Perm C9_30596),
    σ 0 = 0 →
      (∀ (v w : V) (c t : C9_30596),
        pureBaseMap σ (v, c) = (v, σ c) ∧
          productRelativeDerivative σ (w, t) (v, c) =
            (v, σ.symm (σ (c + t) - σ t)) ∧
          ((-v, -c) = (v, -c)) ∧
          transportedTargetInversionProduct30596 σ (v, c) =
            (v, σ.symm (-σ c))) ∧
      (∀ (v : V) (c : C9_30596),
        productOrbit30596 σ (v, c) =
          {x | x.1 = v ∧ x.2 ∈ gammaOrbit30596 σ c})

end

end MathlibPlus.Open.ResearchFormalization.R1250.Claim30596
