import Mathlib

namespace MathlibPlus.Open.ResearchBatch.UnorderedOrbitals

abbrev Perm (Ω : Type*) := Equiv.Perm Ω

/-- Sharp transitivity of a permutation subgroup on a finite point set. -/
def RegularOn {Ω : Type*} (H : Subgroup (Perm Ω)) : Prop :=
  ∀ x y : Ω, ∃! h : H, (h : Perm Ω) x = y

/-- A point-stabilizer suborbit of `G` at `ω`. -/
def pointStabilizerSuborbit {Ω : Type*}
    (G : Subgroup (Perm Ω)) (ω x : Ω) : Set Ω :=
  {y | ∃ g : G, (g : Perm Ω) ω = ω ∧ (g : Perm Ω) x = y}

/-- The paired color associated with an element of a regular subgroup. -/
def pairedColor {Ω : Type*}
    (G H : Subgroup (Perm Ω)) (ω : Ω) (h : H) : Set Ω :=
  pointStabilizerSuborbit G ω ((h : Perm Ω) ω) ∪
    pointStabilizerSuborbit G ω (((h⁻¹ : H) : Perm Ω) ω)

/-- The symmetric relation generated by the orbit of an ordered pair. -/
def unorderedOrbital {Ω : Type*}
    (G : Subgroup (Perm Ω)) (x y : Ω) : Set (Ω × Ω) :=
  {p | ∃ g : G,
    p = ((g : Perm Ω) x, (g : Perm Ω) y) ∨
    p = ((g : Perm Ω) y, (g : Perm Ω) x)}

/-- The color of an unordered orbital at a chosen basepoint. -/
def basepointColor {Ω : Type*}
    (G : Subgroup (Perm Ω)) (ω x y : Ω) : Set Ω :=
  {v | (ω, v) ∈ unorderedOrbital G x y}

/-- The explicit meaning of `H^u ≤ G` used below. -/
def conjugateContained {Ω : Type*}
    (H G : Subgroup (Perm Ω)) (u : Perm Ω) : Prop :=
  ∀ h : H, u⁻¹ * (h : Perm Ω) * u ∈ G

/-- A permutation fixes a subset pointwise as a color. -/
def fixesColor {Ω : Type*} (u : Perm Ω) (C : Set Ω) : Prop :=
  ∀ x : Ω, x ∈ C ↔ u x ∈ C

def applyPair {Ω : Type*} (u : Perm Ω) (p : Ω × Ω) : Ω × Ω :=
  (u p.1, u p.2)

/-- Fixing every unordered orbital, expressed as preservation of its pair relation. -/
def fixesUnorderedOrbitals {Ω : Type*}
    (G : Subgroup (Perm Ω)) (u : Perm Ω) : Prop :=
  ∀ x y : Ω, ∀ p : Ω × Ω,
    p ∈ unorderedOrbital G x y ↔
      applyPair u p ∈ unorderedOrbital G x y

/-- An ordinary simple undirected graph relation. -/
def OrdinaryGraph {Ω : Type*} (E : Set (Ω × Ω)) : Prop :=
  (∀ x : Ω, (x, x) ∉ E) ∧
  (∀ p : Ω × Ω, p ∈ E ↔ (p.2, p.1) ∈ E)

/-- Invariance of a graph relation under a permutation subgroup. -/
def GraphInvariant {Ω : Type*}
    (G : Subgroup (Perm Ω)) (E : Set (Ω × Ω)) : Prop :=
  ∀ g : G, ∀ p : Ω × Ω,
    p ∈ E ↔ applyPair (g : Perm Ω) p ∈ E

/-- Being an automorphism of an ordinary graph relation. -/
def GraphAutomorphism {Ω : Type*}
    (u : Perm Ω) (E : Set (Ω × Ω)) : Prop :=
  ∀ p : Ω × Ω, p ∈ E ↔ applyPair u p ∈ E

/-- Inverse-paired suborbit colors are exactly the basepoint colors of unordered
    orbitals, and fixing those colors fixes every ordinary invariant graph. -/
def claim38957 {Ω : Type*} [Fintype Ω] [DecidableEq Ω] : Prop :=
  ∀ (G H : Subgroup (Perm Ω)) (ω : Ω),
    H ≤ G →
    RegularOn H →
    ({C : Set Ω | ∃ x y : Ω, C = basepointColor G ω x y} =
      {C : Set Ω | ∃ h : H, C = pairedColor G H ω h}) ∧
    (∀ u : Perm Ω,
      u ω = ω →
      conjugateContained H G u →
      (∀ h : H, fixesColor u (pairedColor G H ω h)) →
      fixesUnorderedOrbitals G u ∧
      (∀ E : Set (Ω × Ω), OrdinaryGraph E → GraphInvariant G E →
        GraphAutomorphism u E))

end MathlibPlus.Open.ResearchBatch.UnorderedOrbitals
