import Mathlib.GroupTheory.Sylow
import Mathlib.Data.Set.Card

namespace MathlibPlus.Open.GroupTheory

/-- Claim 41783: for regular copies of a group of order `m * p`, with `p` a
prime larger than its cofactor, the Sylow-`p` orbit partitions can be aligned
by conjugation inside the subgroup generated by the two copies. -/
def generatedSylowOrbitBlocks_claim41783 : Prop :=
  ∀ (Ω G : Type*) [Fintype Ω] [DecidableEq Ω] [Group G] [Finite G],
    ∀ (p m : ℕ),
      Nat.Prime p → m < p → ¬ p ∣ m →
      Nat.card G = m * p → Fintype.card Ω = m * p →
      ∀ (R T : Subgroup (Equiv.Perm Ω)),
        (∀ x y : Ω, ∃ h : R, h.1 x = y) ∧
          (∀ h : R, ∀ x : Ω, h.1 x = x → h.1 = 1) →
        (∀ x y : Ω, ∃ h : T, h.1 x = y) ∧
          (∀ h : T, ∀ x : Ω, h.1 x = x → h.1 = 1) →
        Nonempty (R ≃* G) → Nonempty (T ≃* G) →
        ∀ (P : Sylow p R) (Q : Sylow p T),
          let orbitP : Ω → Set Ω := fun ω =>
            {v | ∃ h : P, h.1.1 ω = v}
          let orbitQx : Equiv.Perm Ω → Ω → Set Ω := fun x ω =>
            {v | ∃ h : Q, x (h.1.1 (x⁻¹ ω)) = v}
          let partsP : Set (Set Ω) := {S | ∃ ω, orbitP ω = S}
          let partsQx : Equiv.Perm Ω → Set (Set Ω) :=
            fun x => {S | ∃ ω, orbitQx x ω = S}
          ∃ x : Subgroup.closure
              ((Set.range (fun h : R => (h : Equiv.Perm Ω))) ∪
                Set.range (fun h : T => (h : Equiv.Perm Ω))),
            partsP = partsQx x.1 ∧
              (∀ S ∈ partsP, Set.ncard S = p) ∧ Set.ncard partsP = m

end MathlibPlus.Open.GroupTheory
