import MathlibPlus.Basic

namespace MathlibPlus.Open.NumberTheory

/--
The arithmetic antichain recorded in claim 43497.  For the existentially
selected prime `p`, `qs` is the infinite family of prime second coordinates
congruent to `1` modulo `3 * p`; the displayed divisibility condition is the packet's pair-core
criterion.  The final clause defines the residual upward closure generated by
these products and forbids any finite subfamily from having the same closure.
-/
def infiniteArithmeticAntichain_claim43497 : Prop :=
  ∃ p : ℕ, Nat.Prime p ∧
    ∃ qs : Set ℕ,
      qs.Infinite ∧
      (∀ q ∈ qs,
        Nat.Prime q ∧ q % (3 * p) = 1 ∧ p ∣ q - 1) ∧
      (∀ ⦃q r : ℕ⦄,
        q ∈ qs → r ∈ qs → q ≠ r →
          ¬ (p * q ∣ p * r) ∧ ¬ (p * r ∣ p * q)) ∧
      let residual : Set ℕ := {n | ∃ q ∈ qs, p * q ∣ n}
      ¬ ∃ F : Finset ℕ,
        (∀ r ∈ F, ∃ q ∈ qs, r = p * q) ∧
        (∀ n : ℕ, n ∈ residual ↔ ∃ r ∈ F, r ∣ n)

end MathlibPlus.Open.NumberTheory
