import MathlibPlus.Open.Research.BatchDerivative
import MathlibPlus.GroupTheory.DirectProductDerivativeClaim28503

namespace MathlibPlus.Open.Research.BatchDerivative

noncomputable section

open scoped Pointwise
open MathlibPlus.GroupTheory.Claim28503

/-- The product derivative leaves the finite factor fixed and applies the local
`C₃²` derivative to the second coordinate. -/
def productDerivative {K : Type*} [Group K]
    (σ : Equiv.Perm H3) (_u : K) (t : H3) : Equiv.Perm (K × H3) :=
  Equiv.prodCongr (Equiv.refl K) (derivative σ t)

/-- The subgroup generated by all product derivatives. -/
def productDerivativeGroup {K : Type*} [Group K]
    (σ : Equiv.Perm H3) : Subgroup (Equiv.Perm (K × H3)) :=
  Subgroup.closure (Set.range (fun p : K × H3 =>
    productDerivative σ p.1 p.2))

/-- A product derivative orbit. -/
def productDerivativeOrbit {K : Type*} [Group K]
    (σ : Equiv.Perm H3) (p : K × H3) : Set (K × H3) :=
  MulAction.orbit (productDerivativeGroup (K := K) σ) p

/-- The section of a subset of `K × H3` over a fixed element of `K`. -/
def productSection {K : Type*}
    (S : Set (K × H3)) (k : K) : Set H3 :=
  {h | (k, h) ∈ S}

/-- A subset of `H3` is a union of the local derivative orbits. -/
def unionOfLocalDerivativeOrbits
    (σ : Equiv.Perm H3) (U : Set H3) : Prop :=
  ∃ 𝒪 : Set (Set H3), 𝒪 ⊆ orbitFamily σ ∧ U = ⋃₀ 𝒪

/-- Invariance under the subgroup generated by the product derivatives. -/
def productDerivativeInvariant {K : Type*} [Group K]
    (σ : Equiv.Perm H3) (S : Set (K × H3)) : Prop :=
  ∀ p : productDerivativeGroup (K := K) σ, p.1 '' S = S

/-- The identity on `K` together with a linear map on the `C₃²` factor. -/
def productLinearShadowMap {K : Type*}
    (L : H3 ≃ₗ[ZMod 3] H3) : K × H3 → K × H3 :=
  fun p => (p.1, L p.2)

/-- Claim 28504: product derivative orbits are the same local orbit system on
all `K`-sections, and every invariant section is a union of those orbits. -/
def claim28504 : Prop :=
  ∀ (K : Type*) [Finite K] [Group K]
    (σ : Equiv.Perm H3), normalized σ →
    (∀ (k : K) (h : H3),
      productDerivativeOrbit σ (k, h) =
        {p : K × H3 | p.1 = k ∧ p.2 ∈ derivativeOrbit σ h}) ∧
    ∀ S : Set (K × H3), productDerivativeInvariant σ S →
      ∀ k : K, unionOfLocalDerivativeOrbits σ (productSection S k)

/-- Claim 28505: one global linear shadow is chosen once for a normalized
`σ`, and that same map transports every derivative-invariant subset. -/
def claim28505 : Prop :=
  ∀ (K : Type*) [Finite K] [Group K]
    (σ : Equiv.Perm H3), normalized σ →
    ∃ L : H3 ≃ₗ[ZMod 3] H3,
      linearShadow σ L ∧
        ∀ S : Set (K × H3), productDerivativeInvariant σ S →
          directProductMap σ '' S = productLinearShadowMap L '' S

/-- The coordinate vectors for the standard basis of `C₃²`. -/
def coordinateVector : Fin 2 → H3 :=
  fun i => if i = 0 then (1, 0) else (0, 1)

/-- The two coordinates of a vector in the standard `C₃²` model. -/
def coordinateValue (i : Fin 2) (x : H3) : ZMod 3 :=
  if i = 0 then x.1 else x.2

/-- The matrix of a linear equivalence in these coordinates. -/
def linearMapMatrix (L : H3 ≃ₗ[ZMod 3] H3) :
    Matrix (Fin 2) (Fin 2) (ZMod 3) :=
  fun i j => coordinateValue i (L (coordinateVector j))

/-- A two-by-two matrix with exactly one nonzero entry in each row and column. -/
def isMonomialMatrix
    (M : Matrix (Fin 2) (Fin 2) (ZMod 3)) : Prop :=
  (∀ i : Fin 2, ∃! j : Fin 2, M i j ≠ 0) ∧
    (∀ j : Fin 2, ∃! i : Fin 2, M i j ≠ 0)

/-- The eight monomial linear maps in the standard `C₃²` coordinates. -/
def monomialLinearMaps : Set (H3 ≃ₗ[ZMod 3] H3) :=
  {L | isMonomialMatrix (linearMapMatrix L)}

/-- The subgroup generated by the monomial linear maps. -/
def monomialLinearSubgroup : Subgroup (H3 ≃ₗ[ZMod 3] H3) :=
  Subgroup.closure monomialLinearMaps

/-- The displayed nonmonomial linear permutation, written as the tuple
`(0,1,2,4,5,3,8,6,7)` in row-major coordinates on `ZMod 3 × ZMod 3`. -/
def sigma28510 : Equiv.Perm H3 :=
  ((Equiv.swap ((1 : ZMod 3), (0 : ZMod 3)) ((1 : ZMod 3), (1 : ZMod 3))).trans
      (Equiv.swap ((1 : ZMod 3), (0 : ZMod 3)) ((1 : ZMod 3), (2 : ZMod 3)))).trans
    ((Equiv.swap ((2 : ZMod 3), (0 : ZMod 3)) ((2 : ZMod 3), (2 : ZMod 3))).trans
      (Equiv.swap ((2 : ZMod 3), (0 : ZMod 3)) ((2 : ZMod 3), (1 : ZMod 3))))

/-- Claim 28510: the full linear group is needed; the eight monomial maps are
proper, while the displayed normalized permutation has singleton derivative
orbits and no monomial simultaneous shadow. -/
def claim28510 : Prop :=
  normalized sigma28510 ∧
  (Set.ncard monomialLinearMaps = 8) ∧
  (monomialLinearSubgroup : Set (H3 ≃ₗ[ZMod 3] H3)) = monomialLinearMaps ∧
  monomialLinearSubgroup ≠ ⊤ ∧
  (∃ L : H3 ≃ₗ[ZMod 3] H3,
    (L : H3 → H3) = sigma28510 ∧ L ∉ monomialLinearMaps) ∧
  (∀ x : H3, derivativeOrbit sigma28510 x = {x}) ∧
  (∀ L : H3 ≃ₗ[ZMod 3] H3, linearShadow sigma28510 L →
    ∀ x : H3, L x = sigma28510 x) ∧
  ¬ ∃ L : H3 ≃ₗ[ZMod 3] H3,
    L ∈ monomialLinearMaps ∧ linearShadow sigma28510 L

end

end MathlibPlus.Open.Research.BatchDerivative
