import Mathlib

namespace MathlibPlus.Open.Research.BatchDerivative

noncomputable section

abbrev H3 := ZMod 3 × ZMod 3

/-- The derivative permutation associated to a permutation of `C₃²`. -/
def derivative (σ : Equiv.Perm H3) (t : H3) : Equiv.Perm H3 :=
  ((Equiv.addRight t).trans σ).trans (Equiv.subRight (σ t)) |>.trans σ.symm

/-- The subgroup generated by all derivatives. -/
def derivativeGroup (σ : Equiv.Perm H3) : Subgroup (Equiv.Perm H3) :=
  Subgroup.closure (Set.range (derivative σ))

/-- An orbit of the derivative group. -/
def derivativeOrbit (σ : Equiv.Perm H3) (x : H3) : Set H3 :=
  MulAction.orbit (derivativeGroup σ) x

/-- A normalized permutation fixes the additive identity. -/
def normalized (σ : Equiv.Perm H3) : Prop :=
  σ 0 = 0

/-- A linear shadow transports every derivative orbit to its `σ`-image. -/
def linearShadow (σ : Equiv.Perm H3) (L : H3 ≃ₗ[ZMod 3] H3) : Prop :=
  ∀ x : H3, L '' derivativeOrbit σ x = σ '' derivativeOrbit σ x

def hasLinearShadow (σ : Equiv.Perm H3) : Prop :=
  ∃ L : H3 ≃ₗ[ZMod 3] H3, linearShadow σ L

/-- The first admitted claim records the derivative group definition exactly. -/
def claim28501 : Prop :=
  ∀ σ : Equiv.Perm H3, normalized σ →
    derivativeGroup σ = Subgroup.closure (Set.range (derivative σ))

/-- Every normalized permutation has one linear shadow, in the orbit-image sense. -/
def claim28502 : Prop :=
  ∀ σ : Equiv.Perm H3, normalized σ → hasLinearShadow σ

def orbitFamily (σ : Equiv.Perm H3) : Set (Set H3) :=
  Set.range (derivativeOrbit σ)

def orbitSizeCount (σ : Equiv.Perm H3) (n : ℕ) : ℕ :=
  Set.ncard {O : Set H3 | O ∈ orbitFamily σ ∧ O.ncard = n}

def shadowCount (σ : Equiv.Perm H3) : ℕ :=
  Set.ncard {L : H3 ≃ₗ[ZMod 3] H3 | linearShadow σ L}

def normalizedPermutations : Set (Equiv.Perm H3) :=
  {σ | normalized σ}

def orbitShape_1_9 (σ : Equiv.Perm H3) : Prop :=
  orbitSizeCount σ 1 = 9 ∧ ∀ n, n ≠ 1 → orbitSizeCount σ n = 0

def orbitShape_1_3_3_2 (σ : Equiv.Perm H3) : Prop :=
  orbitSizeCount σ 1 = 3 ∧ orbitSizeCount σ 3 = 2 ∧
    ∀ n, n ≠ 1 → n ≠ 3 → orbitSizeCount σ n = 0

def orbitShape_1_2_3_2 (σ : Equiv.Perm H3) : Prop :=
  orbitSizeCount σ 1 = 1 ∧ orbitSizeCount σ 2 = 1 ∧ orbitSizeCount σ 3 = 2 ∧
    ∀ n, n ≠ 1 → n ≠ 2 → n ≠ 3 → orbitSizeCount σ n = 0

def orbitShape_1_8 (σ : Equiv.Perm H3) : Prop :=
  orbitSizeCount σ 1 = 1 ∧ orbitSizeCount σ 8 = 1 ∧
    ∀ n, n ≠ 1 → n ≠ 8 → orbitSizeCount σ n = 0

/-- The complete multiplicity, orbit-shape, and shadow-count census. -/
def claim28507 : Prop :=
  Set.ncard normalizedPermutations = 40320 ∧
  (∀ σ ∈ normalizedPermutations, hasLinearShadow σ) ∧
  Set.ncard {σ : Equiv.Perm H3 |
    σ ∈ normalizedPermutations ∧ orbitShape_1_9 σ ∧ shadowCount σ = 1} = 48 ∧
  Set.ncard {σ : Equiv.Perm H3 |
    σ ∈ normalizedPermutations ∧ orbitShape_1_3_3_2 σ ∧ shadowCount σ = 3} = 384 ∧
  Set.ncard {σ : Equiv.Perm H3 |
    σ ∈ normalizedPermutations ∧ orbitShape_1_2_3_2 σ ∧ shadowCount σ = 6} = 1728 ∧
  Set.ncard {σ : Equiv.Perm H3 |
    σ ∈ normalizedPermutations ∧ orbitShape_1_8 σ ∧ shadowCount σ = 48} = 38160

def linearDoubleCosetRel (σ τ : Equiv.Perm H3) : Prop :=
  ∃ L₁ L₂ : H3 ≃ₗ[ZMod 3] H3,
    (L₁ : H3 → H3) ∘ σ ∘ (L₂ : H3 → H3) = τ

def linearDoubleCosetFamily : Set (Set (Equiv.Perm H3)) :=
  Set.range (fun σ : {σ : Equiv.Perm H3 // normalized σ} =>
    {τ : Equiv.Perm H3 | normalized τ ∧ linearDoubleCosetRel σ τ})

def doubleCosetSizeCount (n : ℕ) : ℕ :=
  Set.ncard {C : Set (Equiv.Perm H3) |
    C ∈ linearDoubleCosetFamily ∧ C.ncard = n}

def sameDerivativeSignature (σ τ : Equiv.Perm H3) : Prop :=
  (∀ n : ℕ, orbitSizeCount σ n = orbitSizeCount τ n) ∧
    shadowCount σ = shadowCount τ

/-- The admitted double-coset census and its signature invariance. -/
def claim28508 : Prop :=
  linearDoubleCosetFamily.ncard = 26 ∧
  doubleCosetSizeCount 48 = 1 ∧
  doubleCosetSizeCount 144 = 1 ∧
  doubleCosetSizeCount 192 = 1 ∧
  doubleCosetSizeCount 384 = 2 ∧
  doubleCosetSizeCount 1152 = 8 ∧
  doubleCosetSizeCount 2304 = 13 ∧
  (∀ n, n ≠ 48 → n ≠ 144 → n ≠ 192 → n ≠ 384 →
    n ≠ 1152 → n ≠ 2304 → doubleCosetSizeCount n = 0) ∧
  (∀ σ τ : Equiv.Perm H3, normalized σ → normalized τ →
    linearDoubleCosetRel σ τ → sameDerivativeSignature σ τ)

end
end MathlibPlus.Open.Research.BatchDerivative
