import Mathlib

namespace MathlibPlus.Open.Research

/-- The quotient differences with exactly one lift in a two-point connection
set. -/
def quotientUnequalDifferences {H : Type*} [AddCommGroup H]
    (S : Set (H × ZMod 2)) : Set H :=
  {h | ((h, 0) ∈ S) ≠ ((h, 1) ∈ S)}

/-- The vertex permutation that swaps the two points above `x` according to
`c x`. -/
def twoPointBlockSwitch {H : Type*} [AddCommGroup H]
    (c : H → ZMod 2) (x : H × ZMod 2) : H × ZMod 2 :=
  (x.1, x.2 + c x.1)

/-- The full kernel of block switches preserving the Cayley relation with
connection set `S`. -/
def twoPointCayleySwitchKernel {H : Type*} [AddCommGroup H]
    (S : Set (H × ZMod 2)) : Set (H → ZMod 2) :=
  {c | ∀ x y : H × ZMod 2,
    ((y.1 - x.1, y.2 - x.2) ∈ S ↔
      ((twoPointBlockSwitch c y).1 - (twoPointBlockSwitch c x).1,
        (twoPointBlockSwitch c y).2 - (twoPointBlockSwitch c x).2) ∈ S)}

/-- Component-constant functions for the Cayley graph generated by a set of
quotient differences. -/
def componentConstantFunctions {H : Type*} [AddCommGroup H]
    (U : Set H) : Set (H → ZMod 2) :=
  {c | ∀ x y : H, y - x ∈ AddSubgroup.closure U → c y = c x}

/-- The component-constant functions form the binary permutation module. -/
def componentConstantSubmodule {H : Type*} [AddCommGroup H]
    (U : Set H) : Submodule (ZMod 2) (H → ZMod 2) where
  carrier := componentConstantFunctions U
  zero_mem' := by
    intro x y _
    rfl
  add_mem' := by
    intro f g hf hg x y hxy
    rw [Pi.add_apply, Pi.add_apply, hf x y hxy, hg x y hxy]
  smul_mem' := by
    intro a f hf x y hxy
    rw [Pi.smul_apply, Pi.smul_apply, hf x y hxy]

/-- Claim 29815: the exact two-point block kernel is the component-constant
kernel, and its binary module is the function module on the quotient. -/
def exactTwoPointCayleyBlockKernel : Prop :=
  ∀ (H : Type*) [Fintype H] [AddCommGroup H]
    (S : Set (H × ZMod 2)),
    twoPointCayleySwitchKernel S =
      componentConstantFunctions (quotientUnequalDifferences S) ∧
    let L : AddSubgroup H := AddSubgroup.closure (quotientUnequalDifferences S)
    Nonempty
      ({c : H → ZMod 2 // c ∈ componentConstantSubmodule
          (quotientUnequalDifferences S)}
        ≃ₗ[ZMod 2] ((H ⧸ L) → ZMod 2))

/-- The unordered orbital of a pair under a permutation subgroup. -/
def unorderedOrbital {Ω : Type*}
    (K : Subgroup (Equiv.Perm Ω)) (u : Sym2 Ω) : Set (Sym2 Ω) :=
  Set.range (fun k : K => Sym2.map (k : Equiv.Perm Ω) u)

/-- A permutation fixes every unordered orbital of `K`. -/
def fixesUnorderedOrbitals {Ω : Type*}
    (K : Subgroup (Equiv.Perm Ω)) (p : Equiv.Perm Ω) : Prop :=
  ∀ u v : Sym2 Ω,
    v ∈ unorderedOrbital K u ↔
      Sym2.map p v ∈ unorderedOrbital K u

/-- A permutation subgroup acts regularly when each ordered pair has a
unique transporter. -/
def regularlyActsOn {Ω : Type*}
    (E : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ x y : Ω, ∃! e : E, (e : Equiv.Perm Ω) x = y

/-- Claim 29838: unordered symmetric closure is monotone under ambient
enlargement, and therefore an orbital-fixing conjugator for the core
`E ⊔ F` generated by a regular pair remains available after enlarging the
ambient group. -/
def symmetricClosureMonotoneUnderEnlargement : Prop :=
  (∀ (Ω : Type*) (K L : Subgroup (Equiv.Perm Ω)), K ≤ L →
    ∀ u v : Sym2 Ω,
      v ∈ unorderedOrbital K u → v ∈ unorderedOrbital L u) ∧
  (∀ (Ω : Type*) (E F L : Subgroup (Equiv.Perm Ω)),
    regularlyActsOn E → regularlyActsOn F → E ≤ L → F ≤ L →
    ∀ p : Equiv.Perm Ω,
      fixesUnorderedOrbitals (E ⊔ F) p → fixesUnorderedOrbitals L p)

end MathlibPlus.Open.Research
