import Mathlib

namespace MathlibPlus.Open.Research

open scoped BigOperators

/-! The sign coordinates and the globally labelled depth-two trees in Claim 49597. -/

abbrev DepthTwoCoordinate (n : ℕ) :=
  Sum Unit (Sum (Fin n) (Sum (Fin n) (Sum Unit (Fin n))))

abbrev DepthTwoAssignment (n : ℕ) := DepthTwoCoordinate n → Bool

def coordA (n : ℕ) : DepthTwoCoordinate n :=
  Sum.inl ()

def coordZ {n : ℕ} (j : Fin n) : DepthTwoCoordinate n :=
  Sum.inr (Sum.inl j)

def coordC {n : ℕ} (j : Fin n) : DepthTwoCoordinate n :=
  Sum.inr (Sum.inr (Sum.inl j))

def coordB (n : ℕ) : DepthTwoCoordinate n :=
  Sum.inr (Sum.inr (Sum.inr (Sum.inl ())))

def coordW {n : ℕ} (j : Fin n) : DepthTwoCoordinate n :=
  Sum.inr (Sum.inr (Sum.inr (Sum.inr j)))

def signValue : Bool → ℚ
  | false => -1
  | true => 1

def coordinateValue (ω : DepthTwoAssignment n) (c : DepthTwoCoordinate n) : ℚ :=
  signValue (ω c)

inductive DepthTwoTree (n : ℕ) where
  | leaf (value : Bool)
  | query (level : ℕ) (coordinate : DepthTwoCoordinate n)
      (negative positive : DepthTwoTree n)

def DepthTwoTree.eval : DepthTwoTree n → DepthTwoAssignment n → Bool
  | .leaf value, _ => value
  | .query _ coordinate negative positive, ω =>
      if ω coordinate then positive.eval ω else negative.eval ω

def signQuery (level : ℕ) (coordinate : DepthTwoCoordinate n) : DepthTwoTree n :=
  .query level coordinate (.leaf false) (.leaf true)

def mainPlusTree (n : ℕ) : DepthTwoTree n :=
  .query 1 (coordA n) (.leaf true) (signQuery 2 (coordB n))

def mainMinusTree (n : ℕ) : DepthTwoTree n :=
  .query 1 (coordA n) (.leaf false) (signQuery 2 (coordB n))

def dictatorTree (j : Fin n) : DepthTwoTree n :=
  signQuery 1 (coordZ j)

def parityTree (j : Fin n) : DepthTwoTree n :=
  .query 1 (coordC j)
    (.query 2 (coordW j) (.leaf true) (.leaf false))
    (signQuery 2 (coordW j))

def treeValue (tree : DepthTwoTree n) (ω : DepthTwoAssignment n) : ℚ :=
  signValue (tree.eval ω)

def mainTreeWeight : ℚ := 1 / 4

def componentWeight (n : ℕ) : ℚ := 1 / (4 * (n : ℚ))

def totalWeight (n : ℕ) : ℚ :=
  mainTreeWeight + mainTreeWeight
    + (∑ _ : Fin n, componentWeight n)
    + (∑ _ : Fin n, componentWeight n)

def depthTwoMixture (n : ℕ) (ω : DepthTwoAssignment n) : ℚ :=
  mainTreeWeight * treeValue (mainPlusTree n) ω
    + mainTreeWeight * treeValue (mainMinusTree n) ω
    + (∑ j : Fin n, componentWeight n * treeValue (dictatorTree j) ω)
    + (∑ j : Fin n, componentWeight n * treeValue (parityTree j) ω)

def depthTwoTarget (n : ℕ) (ω : DepthTwoAssignment n) : ℚ :=
  (((1 : ℚ) + coordinateValue ω (coordA n)) * coordinateValue ω (coordB n)) / 4
    + (1 / (4 * (n : ℚ))) *
        ∑ j : Fin n,
          (coordinateValue ω (coordZ j)
            + coordinateValue ω (coordC j) * coordinateValue ω (coordW j))

def assignmentMass (n : ℕ) (_ω : DepthTwoAssignment n) : ℚ :=
  1 / (Fintype.card (DepthTwoAssignment n) : ℚ)

def eventMass (n : ℕ) (S : Finset (DepthTwoCoordinate n))
    (a : DepthTwoAssignment n) : ℚ :=
  ∑ ω : DepthTwoAssignment n,
    if (∀ c ∈ S, ω c = a c) then assignmentMass n ω else 0

def independentUniformSigns (n : ℕ) : Prop :=
  ∀ (S : Finset (DepthTwoCoordinate n)) (a : DepthTwoAssignment n),
    eventMass n S a = ∏ c ∈ S, (1 / 2 : ℚ)

/-- Claim 49597: the depth-two family, its independent signs, weights, and target. -/
def scalableDepthTwoFamily : Prop :=
  ∀ n : ℕ, 1 ≤ n →
    totalWeight n = 1 ∧
      independentUniformSigns n ∧
        ∀ ω : DepthTwoAssignment n,
          depthTwoMixture n ω = depthTwoTarget n ω

/-! The coefficient-space presentation of multiaffine polynomials in Claim 49644. -/

abbrev MultiaffineCoefficients (n : ℕ) (R : Type*) [Zero R] :=
  Finset (Fin n) →₀ R

noncomputable def qMonomial {n : ℕ} {R : Type*} [Semiring R]
    (I : Finset (Fin n)) : MultiaffineCoefficients n R :=
  Finsupp.single (M := R) I (1 : R)

def rankSum {n : ℕ} {R : Type*} [Semiring R]
    (F : MultiaffineCoefficients n R) (k : ℕ) : R :=
  ∑ I ∈ F.support.filter (fun I => I.card = k), F I

noncomputable def diagonal {n : ℕ} {R : Type*} [Semiring R]
    (F : MultiaffineCoefficients n R) : Polynomial R :=
  ∑ I ∈ F.support, Polynomial.C (F I) * Polynomial.X ^ I.card

def sameRankDifferences {n : ℕ} {R : Type*} [Ring R] :
    Set (MultiaffineCoefficients n R) :=
  {d | ∃ I J : Finset (Fin n), I.card = J.card ∧
      d = qMonomial (n := n) (R := R) I - qMonomial (n := n) (R := R) J}

def diagonalKernel {n : ℕ} {R : Type*} [Semiring R] :
    Set (MultiaffineCoefficients n R) :=
  {F | diagonal (n := n) F = (0 : Polynomial R)}

/-- Claim 49644: diagonalization keeps rank sums and its kernel is generated by
same-cardinality basis differences. -/
def diagonalKernelRankSum {R : Type*} [CommRing R] (n : ℕ) : Prop :=
  (∀ (F : MultiaffineCoefficients n R) (k : ℕ),
    (diagonal F).coeff k = rankSum F k) ∧
    (∀ (F : MultiaffineCoefficients n R),
      diagonal F = 0 ↔ ∀ k : ℕ, rankSum F k = 0) ∧
    (diagonalKernel (n := n) =
      (Submodule.span R (sameRankDifferences (n := n) (R := R))
        : Submodule R (MultiaffineCoefficients n R)).carrier)

/-! The ambient-group formulation of Claim 59634. -/

/-- Claim 59634: equivariance and transitivity reduce the orbital condition to
point-stabilizer transporters. -/
def orbitalStabilizerTransporterCriterion
    {A R Ω : Type*} [Group A] [Group R] [MulAction A Ω]
    (rho sigma : R →* A) (b : Ω) (U : Ω ≃ Ω)
    (hOrbit : ∀ x : Ω, ∃ r : R, rho r • b = x)
    (hBase : U b = b)
    (hEquivariant : ∀ (r : R) (x : Ω),
      U (rho r • x) = sigma r • U x) : Prop :=
  (∀ (x y : Ω), ∃ a : A, a • x = U x ∧ a • y = U y) ↔
    (∀ y : Ω, ∃ a : A, a • b = b ∧ a • y = U y)

end MathlibPlus.Open.Research
