import Mathlib

namespace MathlibPlus.Open.Research.FormalizationBatch_019ffedf

/-- An unordered edge is a two-element finite subset of a vertex type. -/
def UnorderedEdge (Ω : Type*) := {e : Finset Ω // e.card = 2}

/-- The action of a permutation on an unordered edge. -/
def edgeMap {Ω : Type*} (h : Equiv.Perm Ω) (e : UnorderedEdge Ω) : UnorderedEdge Ω :=
  ⟨e.1.map h.toEmbedding, by simpa [e.2] using (Finset.card_map h.toEmbedding)⟩

/-- The unordered orbital of an edge under a permutation subgroup. -/
def unorderedOrbital {Ω : Type*} (K : Subgroup (Equiv.Perm Ω))
    (e : UnorderedEdge Ω) : Set (UnorderedEdge Ω) :=
  {f | ∃ k : K, edgeMap k.1 e = f}

/-- Two edges lie in the same unordered orbital. -/
def sameUnorderedOrbital {Ω : Type*} (K : Subgroup (Equiv.Perm Ω))
    (e f : UnorderedEdge Ω) : Prop :=
  f ∈ unorderedOrbital K e

/-- One step on source orbital labels: stay in an `R`-orbital or apply one extra generator. -/
def sourceOrbitalStep {Ω : Type*} (R : Subgroup (Equiv.Perm Ω))
    (S : Set (Equiv.Perm Ω)) (e f : UnorderedEdge Ω) : Prop :=
  sameUnorderedOrbital R e f ∨
    ∃ s ∈ S, sameUnorderedOrbital R (edgeMap s e) f

/-- The quotient component generated by the source-orbital steps. -/
def sourceOrbitalComponent {Ω : Type*} (R : Subgroup (Equiv.Perm Ω))
    (S : Set (Equiv.Perm Ω)) (e f : UnorderedEdge Ω) : Prop :=
  Relation.EqvGen (sourceOrbitalStep R S) e f

/-- The subgroup generated by `R` and the additional permutations `S`. -/
def generatedPermutationGroup {Ω : Type*} (R : Subgroup (Equiv.Perm Ω))
    (S : Set (Equiv.Perm Ω)) : Subgroup (Equiv.Perm Ω) :=
  Subgroup.closure ((R : Set (Equiv.Perm Ω)) ∪ S)

/--
The generated unordered-orbital quotient statement: the transitive quotient of the
`R`-source labels joined by the extra generators is exactly the unordered orbital
partition of the generated group, and its pointwise fixed-orbital criterion is the
same source-component criterion.  No regularity assumption occurs.
-/
def claim_27760 : Prop :=
  ∀ (Ω : Type*) [Fintype Ω]
    (R : Subgroup (Equiv.Perm Ω)) (S : Set (Equiv.Perm Ω)),
    let L := generatedPermutationGroup R S
    (∀ e f : UnorderedEdge Ω,
        sourceOrbitalComponent R S e f ↔ sameUnorderedOrbital L e f) ∧
      (∀ h : Equiv.Perm Ω,
        (∀ e : UnorderedEdge Ω, sameUnorderedOrbital L e (edgeMap h e)) ↔
          (∀ e : UnorderedEdge Ω,
            sourceOrbitalComponent R S e (edgeMap h e)))

/-- The nonidentity elements used as labels for regular unordered source orbitals. -/
def Nonidentity (G : Type*) [One G] := {d : G // d ≠ 1}

/-- The edge at the identity labelled by a nonidentity group element. -/
noncomputable def identityEdge {G : Type*} [Group G] (d : Nonidentity G) :
    UnorderedEdge G := by
  classical
  refine ⟨{1, d.1}, ?_⟩
  have h : (1 : G) ≠ d.1 := Ne.symm d.2
  simp [h]

/-- The left-regular unordered orbital of a source label. -/
def leftRegularOrbital {G : Type*} [Group G] (d : Nonidentity G) :
    Set (UnorderedEdge G) :=
  {e | ∃ g : G, edgeMap (Equiv.mulLeft g) (identityEdge d) = e}

/-- Equality of inverse source labels. -/
def inverseLabelRelation {G : Type*} [Group G] (a b : Nonidentity G) : Prop :=
  a.1 = b.1 ∨ a.1 = b.1⁻¹

/-- The inverse-class quotient on nonidentity group elements. -/
def inverseLabelSetoid {G : Type*} [Group G] : Setoid (Nonidentity G) where
  r := inverseLabelRelation
  iseqv := by
    refine ⟨?_, ?_, ?_⟩
    · intro a
      exact Or.inl rfl
    · intro a b h
      rcases h with h | h
      · exact Or.inl h.symm
      · exact Or.inr (by simpa using (congrArg Inv.inv h).symm)
    · intro a b c hab hbc
      rcases hab with hab | hab <;> rcases hbc with hbc | hbc
      · exact Or.inl (hab.trans hbc)
      · exact Or.inr (hab.trans hbc)
      · exact Or.inr (hab.trans (by simpa [hbc]))
      · exact Or.inl (hab.trans (by simpa [hbc]))

/-- The number of nonidentity involution labels. -/
noncomputable def nonidentityInvolutionCount {G : Type*} [Group G] [Fintype G] : ℕ := by
  classical
  exact Fintype.card {d : G // d ≠ 1 ∧ d = d⁻¹}

/--
For a finite regular group, source labels are inverse classes, their number is the
stated `(n - 1 + t) / 2`, and the left-regular unordered orbital sizes distinguish
noninvolution and involution classes as `n` and `n / 2`.
-/
def claim_27761 : Prop := by
  classical
  exact ∀ (G : Type*) [Group G] [Fintype G],
    (∀ d e : Nonidentity G,
        leftRegularOrbital d = leftRegularOrbital e ↔
          Quotient.mk (inverseLabelSetoid (G := G)) d =
            Quotient.mk (inverseLabelSetoid (G := G)) e) ∧
      Nat.card (Quotient (inverseLabelSetoid (G := G))) =
        (Fintype.card G - 1 + nonidentityInvolutionCount (G := G)) / 2 ∧
      (∀ d : Nonidentity G,
        Set.ncard (leftRegularOrbital d) =
          if d.1 = d.1⁻¹ then Fintype.card G / 2 else Fintype.card G)

end MathlibPlus.Open.Research.FormalizationBatch_019ffedf
