import MathlibPlus.Open.Research.GeneratedGroupExact

namespace MathlibPlus.Open.Research.GeneratedGroupExact

noncomputable section

/-- The block-kernel sign image is exactly the cyclic code generated by the
cyclic shifts of the mask derivative. -/
def claim38251 : Prop :=
  ∀ q : ℕ, ∀ hq : Nat.Prime q, 2 < q →
    letI : NeZero q := ⟨hq.ne_zero⟩
    ∀ μ : Mask,
      {ν : Mask |
          ∃ h : Perm q,
            h ∈ generatedGroup q μ ∧
              (∀ p : Omega q, (h p).1 = p.1) ∧
                normalizerSignVector h ν} =
        (generatedSignCode μ : Set Mask)

end
end MathlibPlus.Open.Research.GeneratedGroupExact
