import Mathlib

namespace MathlibPlus.Open.Research.PacketShadowWitnesses

/-- The multiplicative residue represented by `p` modulo `q`, for a verified
coprimality witness. -/
def packetGenerator (p q : ℕ) (h : Nat.Coprime p q) : (ZMod q)ˣ :=
  ZMod.unitOfCoprime p h

/-- The subgroup generated by the residue of `p` in `𝔽_qˣ`. -/
def packetShadowSubgroup (p q : ℕ) (h : Nat.Coprime p q) : Subgroup ((ZMod q)ˣ) :=
  Subgroup.closure ({packetGenerator p q h} : Set ((ZMod q)ˣ))

/-- The quotient `𝔽_qˣ / ⟨p⟩` appearing as a finite packet shadow. -/
def packetShadowQuotient (p q : ℕ) (h : Nat.Coprime p q) :=
  (ZMod q)ˣ ⧸ packetShadowSubgroup p q h

/-- The cardinality of the packet shadow quotient. -/
noncomputable def packetShadowCard (p q : ℕ) (h : Nat.Coprime p q) : ℕ :=
  Nat.card (packetShadowQuotient p q h)

/-- The tuple recorded in the admitted packet-shadow witness claim. -/
noncomputable def packetShadowTuple (p q : ℕ) (h : Nat.Coprime p q) :
    ℕ × ℕ × ℕ × ℕ :=
  (p, q, orderOf (packetGenerator p q h), packetShadowCard p q h)

/-- A displayed prime pair realizes a specified packet-shadow tuple. -/
def packetShadowWitness (p q ord card : ℕ) : Prop :=
  Nat.Prime p ∧ Nat.Prime q ∧ p ≠ q ∧
    ∃ h : Nat.Coprime p q, packetShadowTuple p q h = (p, q, ord, card)

/-- A finite packet shadow has more than one quotient orbit. -/
def packetShadowHasMultipleOrbits (p q : ℕ) (h : Nat.Coprime p q) : Prop :=
  packetShadowCard p q h > 1

/-- Explicit nontrivial packet-shadow witnesses, including the consequence that
one of the displayed finite quotients has more than one orbit. -/
def explicitNontrivialPacketShadowWitnesses : Prop :=
  packetShadowWitness 2 7 3 2 ∧
    packetShadowWitness 2 17 8 2 ∧
    packetShadowWitness 2 31 5 6 ∧
    packetShadowWitness 3 13 3 4 ∧
    ∃ h : Nat.Coprime 2 7, packetShadowHasMultipleOrbits 2 7 h

end MathlibPlus.Open.Research.PacketShadowWitnesses
