import Mathlib

namespace MathlibPlus.Open.Research.QuadraticBatch

abbrev F3 := ZMod 3
abbrev Plane := Fin 2 → F3
abbrev Fiber := Fin 3 → F3
abbrev Omega := F3 × Plane × Fiber

/-- The fixed quadratic shift from the admitted statements. -/
def fixedShift (x : Plane) : Fiber :=
  fun k => if k = 0 then x 0 * (x 0 - 1)
    else if k = 1 then (2 * x 0 - 1) * x 1
    else x 1 ^ 2

/-- A symmetric bilinear polarization witnessing a homogeneous quadratic form. -/
def IsHomogeneousQuadratic (m : Fiber → F3) : Prop :=
  ∃ b : Fiber → Fiber → F3,
    (∀ u v, b u v = b v u) ∧
    (∀ u₁ u₂ v, b (u₁ + u₂) v = b u₁ v + b u₂ v) ∧
    (∀ u v₁ v₂, b u (v₁ + v₂) = b u v₁ + b u v₂) ∧
    (∀ u, m u = b u u)

/-- The pure one-direction fiber twist. -/
def twistFunction (H : Plane → F3) (m : Fiber → F3) (p : Omega) : Omega :=
  (p.1 + H p.2.1 * m p.2.2, p.2.1, p.2.2 + fixedShift p.2.1)

noncomputable def twist (H : Plane → F3) (m : Fiber → F3) : Omega ≃ Omega :=
  Equiv.ofBijective (twistFunction H m) (by
    constructor
    · intro p q h
      have hx' := congrArg (fun r : Omega => r.2.1) h
      have hx : p.2.1 = q.2.1 := by
        simpa [twistFunction] using hx'
      have hu : p.2.2 = q.2.2 := by
        have hq := congrArg (fun r : Omega => r.2.2) h
        simp [twistFunction, hx] at hq
        exact hq
      have hz : p.1 = q.1 := by
        have hq := congrArg (fun r : Omega => r.1) h
        simp [twistFunction, hx, hu] at hq
        exact hq
      exact Prod.ext hz (Prod.ext hx hu)
    · intro y
      refine ⟨(y.1 - H y.2.1 * m (y.2.2 - fixedShift y.2.1),
        y.2.1, y.2.2 - fixedShift y.2.1), ?_⟩
      simp [twistFunction, sub_eq_add_neg, add_left_comm, add_comm])

/-- Translation by a point of the additive ambient space. -/
noncomputable def translation (a : Omega) : Omega ≃ Omega :=
  Equiv.ofBijective (fun p => p + a) (by
    constructor
    · intro p q h
      exact add_right_cancel h
    · intro p
      refine ⟨p - a, ?_⟩
      simp [sub_eq_add_neg, add_assoc])

/-- The regular translation subgroup. -/
def translationGroup : Subgroup (Equiv.Perm Omega) :=
  Subgroup.closure (Set.range translation)

def conjugateElement (q g : Equiv.Perm Omega) : Equiv.Perm Omega :=
  q.symm.trans (g.trans q)

def conjugateSet (K : Subgroup (Equiv.Perm Omega)) (q : Equiv.Perm Omega) : Set (Equiv.Perm Omega) :=
  {p | ∃ g : Equiv.Perm Omega, g ∈ K ∧ p = conjugateElement q g}

/-- The group generated by the translation group and its displayed conjugate. -/
def generatedPair (H : Plane → F3) (m : Fiber → F3) : Subgroup (Equiv.Perm Omega) :=
  Subgroup.closure (translationGroup.carrier ∪ conjugateSet translationGroup (twist H m))

/-- Membership in the exact 2-closure, expressed by preservation of every ordered orbital. -/
def InExactTwoClosure (G : Subgroup (Equiv.Perm Omega)) (q : Equiv.Perm Omega) : Prop :=
  ∀ a b : Omega, ∃ g : Equiv.Perm Omega, g ∈ G ∧ q a = g a ∧ q b = g b

/-- The correction term used in the point-stabilizer formulas. -/
def bilinearCorrection (s x : Plane) : Fiber :=
  fixedShift (x + s) - fixedShift x - fixedShift s

def polarForm (m : Fiber → F3) (v w : Fiber) : F3 :=
  m (v + w) - m v - m w

def alignedFormA (u : Fiber) : F3 := u 0 ^ 2
def alignedFormAB (u : Fiber) : F3 := u 0 * u 1
def alignedFormA2B2 (u : Fiber) : F3 := u 0 ^ 2 + u 1 ^ 2
def alignedFormA2B2C2 (u : Fiber) : F3 := u 0 ^ 2 + u 1 ^ 2 + u 2 ^ 2

def alignedDirection (i : Fin 4) : Fiber → F3 :=
  if i = 0 then alignedFormA
  else if i = 1 then alignedFormAB
  else if i = 2 then alignedFormA2B2
  else alignedFormA2B2C2

/-- Claim 31869: the fixed shift and pure one-direction twist construction. -/
def claim_31869 : Prop :=
  ∀ (H : Plane → F3) (m : Fiber → F3), IsHomogeneousQuadratic m →
    (∀ z x u, twist H m (z, x, u) =
      (z + H x * m u, x, u + fixedShift x)) ∧
    generatedPair H m =
      Subgroup.closure
        (translationGroup.carrier ∪ conjugateSet translationGroup (twist H m))

/-- Claim 41634: the same construction, independently retained. -/
def claim_41634 : Prop :=
  ∀ (H : Plane → F3) (m : Fiber → F3), IsHomogeneousQuadratic m →
    (∀ z x u, twist H m (z, x, u) =
      (z + H x * m u, x, u + fixedShift x)) ∧
    generatedPair H m =
      Subgroup.closure
        (translationGroup.carrier ∪ conjugateSet translationGroup (twist H m))

/-- Claim 31871: the displayed regular subgroups are conjugate inside the exact 2-closure. -/
def claim_31871 : Prop :=
  ∀ (H : Plane → F3) (m : Fiber → F3), IsHomogeneousQuadratic m →
    InExactTwoClosure (generatedPair H m) (twist H m) ∧
    (∀ g : Equiv.Perm Omega, g ∈ translationGroup →
      conjugateElement (twist H m) g ∈ generatedPair H m) ∧
    (∀ g : Equiv.Perm Omega, g ∈ translationGroup →
      InExactTwoClosure (generatedPair H m) (conjugateElement (twist H m) g))

/-- Claim 41636: the same conjugacy assertion, independently retained. -/
def claim_41636 : Prop :=
  ∀ (H : Plane → F3) (m : Fiber → F3), IsHomogeneousQuadratic m →
    InExactTwoClosure (generatedPair H m) (twist H m) ∧
    (∀ g : Equiv.Perm Omega, g ∈ translationGroup →
      conjugateElement (twist H m) g ∈ generatedPair H m) ∧
    (∀ g : Equiv.Perm Omega, g ∈ translationGroup →
      InExactTwoClosure (generatedPair H m) (conjugateElement (twist H m) g))

/-- Claim 31874: the two admitted correction formulas. -/
def claim_31874 : Prop :=
  (∀ s x : Plane,
    bilinearCorrection s x = fixedShift (x + s) - fixedShift x - fixedShift s) ∧
  (∀ (m : Fiber → F3), IsHomogeneousQuadratic m → ∀ v w,
    polarForm m v w = m (v + w) - m v - m w)

/-- Claim 41639: the same correction formulas, independently retained. -/
def claim_41639 : Prop :=
  (∀ s x : Plane,
    bilinearCorrection s x = fixedShift (x + s) - fixedShift x - fixedShift s) ∧
  (∀ (m : Fiber → F3), IsHomogeneousQuadratic m → ∀ v w,
    polarForm m v w = m (v + w) - m v - m w)

/-- Claims 31880 and 41645: the four aligned directions in fixed fiber coordinates. -/
def claim_31880 : Prop :=
  Set.range alignedDirection =
    {alignedFormA, alignedFormAB, alignedFormA2B2, alignedFormA2B2C2}

def claim_41645 : Prop :=
  Set.range alignedDirection =
    {alignedFormA, alignedFormAB, alignedFormA2B2, alignedFormA2B2C2}

/-- Claims 41635, 34285, and 41646: pure one-direction quadratic closure. -/
def claim_41635 : Prop :=
  ∀ (m : Fiber → F3), IsHomogeneousQuadratic m →
    ∀ H : Plane → F3,
      InExactTwoClosure (generatedPair H m) (twist H m)

def claim_34285 : Prop :=
  ∀ H : Plane → F3, ∀ m : Fiber → F3,
    (m = alignedFormA ∨ m = alignedFormAB ∨
      m = alignedFormA2B2 ∨ m = alignedFormA2B2C2) →
    InExactTwoClosure (generatedPair H m) (twist H m)

def claim_41646 : Prop :=
  ∀ H : Plane → F3, ∀ m : Fiber → F3,
    (m = alignedFormA ∨ m = alignedFormAB ∨
      m = alignedFormA2B2 ∨ m = alignedFormA2B2C2) →
    InExactTwoClosure (generatedPair H m) (twist H m)

end MathlibPlus.Open.Research.QuadraticBatch
