import Mathlib

namespace MathlibPlus.Open.Research.R1007

/-- The group `C₂³ × C₃²`, written with its two elementary-abelian factors. -/
abbrev C2Base := Fin 3 → ZMod 2
abbrev C3Base := Fin 2 → ZMod 3
abbrev G := C2Base × C3Base

/-- Nonzero inverse-closed connection sets of valency eleven on `G`. -/
abbrev Valency11ConnectionSet :=
  {S : Finset G // 0 ∉ S ∧ S.card = 11 ∧ ∀ x ∈ S, -x ∈ S}

noncomputable instance valency11ConnectionSetFintype :
    Fintype Valency11ConnectionSet := Fintype.ofFinite _

/-- The image of a connection set under a group automorphism. -/
def automorphismImage (α : G ≃+ G) (S : Finset G) : Finset G :=
  S.map α.toEquiv.toEmbedding

/-- One-step equivalence of Cayley presentations under a group automorphism. -/
def sameAutomorphismOrbit (S T : Valency11ConnectionSet) : Prop :=
  ∃ α : G ≃+ G, automorphismImage α S.1 = T.1

/-- The orbit relation generated by the full automorphism action. -/
def automorphismOrbitSetoid : Setoid Valency11ConnectionSet where
  r := Relation.EqvGen sameAutomorphismOrbit
  iseqv := ⟨
    fun S => Relation.EqvGen.refl S,
    fun {S T} h => Relation.EqvGen.symm S T h,
    fun {S T U} h₁ h₂ => Relation.EqvGen.trans S T U h₁ h₂⟩

noncomputable instance automorphismOrbitQuotientFintype :
    Fintype (Quotient automorphismOrbitSetoid) := Fintype.ofFinite _

/-- Adjacency in the undirected Cayley graph presented by `S`. -/
def cayleyAdjacency (S : Valency11ConnectionSet) (x y : G) : Prop :=
  x ≠ y ∧ x - y ∈ S.1

/-- An ordinary graph isomorphism between two Cayley presentations. -/
def graphIsomorphic (S T : Valency11ConnectionSet) : Prop :=
  ∃ e : G ≃ G, ∀ x y : G,
    cayleyAdjacency S x y ↔ cayleyAdjacency T (e x) (e y)

/-- The ordinary graph-isomorphism classes of valency-eleven presentations. -/
def graphOrbitSetoid : Setoid Valency11ConnectionSet where
  r := Relation.EqvGen graphIsomorphic
  iseqv := ⟨
    fun S => Relation.EqvGen.refl S,
    fun {S T} h => Relation.EqvGen.symm S T h,
    fun {S T U} h₁ h₂ => Relation.EqvGen.trans S T U h₁ h₂⟩

noncomputable instance graphOrbitQuotientFintype :
    Fintype (Quotient graphOrbitSetoid) := Fintype.ofFinite _

/-- Connectivity of the undirected Cayley graph presented by `S`. -/
def cayleyConnected (S : Valency11ConnectionSet) : Prop :=
  ∀ x y : G, Relation.ReflTransGen (cayleyAdjacency S) x y

abbrev ConnectedValency11ConnectionSet :=
  {S : Valency11ConnectionSet // cayleyConnected S}

def connectedGraphOrbitSetoid : Setoid ConnectedValency11ConnectionSet where
  r := Relation.EqvGen (fun S T : ConnectedValency11ConnectionSet =>
    graphIsomorphic S.1 T.1)
  iseqv := ⟨
    fun S => Relation.EqvGen.refl S,
    fun {S T} h => Relation.EqvGen.symm S T h,
    fun {S T U} h₁ h₂ => Relation.EqvGen.trans S T U h₁ h₂⟩

noncomputable instance connectedGraphOrbitQuotientFintype :
    Fintype (Quotient connectedGraphOrbitSetoid) := Fintype.ofFinite _

/-- Claim 29735: the exact valency-eleven presentation-orbit census. -/
def exactValency11PresentationOrbitCensus : Prop :=
  Fintype.card Valency11ConnectionSet = 2772888 ∧
    Fintype.card (Quotient automorphismOrbitSetoid) = 1564

/-- Claim 29736: presentation orbits are exactly ordinary graph types, with the
    stated connected subcensus. -/
def presentationOrbitsEqualOrdinaryGraphTypes : Prop :=
  Fintype.card (Quotient graphOrbitSetoid) = 1564 ∧
    (∀ S T : Valency11ConnectionSet,
      graphIsomorphic S T ↔ Relation.EqvGen sameAutomorphismOrbit S T) ∧
    Fintype.card (Quotient connectedGraphOrbitSetoid) = 1319

/-- Claim 29737: every inverse-closed valency-eleven Cayley graph on `G` is CI. -/
def everyValency11CayleyGraphIsCI : Prop :=
  ∀ S T : Valency11ConnectionSet,
    graphIsomorphic S T →
      ∃ α : G ≃+ G, automorphismImage α S.1 = T.1

end MathlibPlus.Open.Research.R1007
