import Mathlib

namespace MathlibPlus.Open.Research.R1291

abbrev H := Fin 5 → ZMod 3

/-- The three coordinate maps in Claim 40054, written on `𝔽₃⁵`. -/
def xFun (h : H) : H :=
  ![h 0, h 1, h 2 + h 0, h 3 + h 1, h 4]

def xInvFun (h : H) : H :=
  ![h 0, h 1, h 2 - h 0, h 3 - h 1, h 4]

def x : H ≃ H where
  toFun := xFun
  invFun := xInvFun
  left_inv := by
    intro h
    funext k
    fin_cases k <;> simp [xFun, xInvFun]
  right_inv := by
    intro h
    funext k
    fin_cases k <;> simp [xFun, xInvFun]

def yFun (h : H) : H :=
  ![h 0, h 1, h 2, h 3 + h 0, h 4 + h 1]

def yInvFun (h : H) : H :=
  ![h 0, h 1, h 2, h 3 - h 0, h 4 - h 1]

def y : H ≃ H where
  toFun := yFun
  invFun := yInvFun
  left_inv := by
    intro h
    funext k
    fin_cases k <;> simp [yFun, yInvFun]
  right_inv := by
    intro h
    funext k
    fin_cases k <;> simp [yFun, yInvFun]

def gFun (h : H) : H :=
  ![h 0, h 1, h 2 + h 0 * (h 0 - 1),
    h 3 + (2 * h 0 - 1) * h 1, h 4 + h 1 ^ 2]

def gInvFun (h : H) : H :=
  ![h 0, h 1, h 2 - h 0 * (h 0 - 1),
    h 3 - (2 * h 0 - 1) * h 1, h 4 - h 1 ^ 2]

def g : H ≃ H where
  toFun := gFun
  invFun := gInvFun
  left_inv := by
    intro h
    funext k
    fin_cases k <;> simp [gFun, gInvFun]
  right_inv := by
    intro h
    funext k
    fin_cases k <;> simp [gFun, gInvFun]

def rightTranslation (h : H) : Equiv.Perm H := Equiv.addRight h

def H_R : Subgroup (Equiv.Perm H) :=
  Subgroup.closure (Set.range rightTranslation)

def conjugationHom (p : Equiv.Perm H) : Equiv.Perm H →* Equiv.Perm H where
  toFun q := p * q * p⁻¹
  map_one' := by simp
  map_mul' := by
    intro a b
    simp [mul_assoc]

def conjugateSubgroup (p : Equiv.Perm H) (K : Subgroup (Equiv.Perm H)) :
    Subgroup (Equiv.Perm H) :=
  K.map (conjugationHom p)

/-- The subgroup generated by the right regular copy and the two displayed maps. -/
def X : Subgroup (Equiv.Perm H) :=
  Subgroup.closure ((H_R : Set (Equiv.Perm H)) ∪ {x, y})

def isRegular (K : Subgroup (Equiv.Perm H)) : Prop :=
  ∀ a b : H, ∃! p : Equiv.Perm H, p ∈ K ∧ p a = b

/-- Claim 40054: the two displayed regular copies have the stated position in `X`. -/
def claim40054 : Prop :=
  isRegular H_R ∧
  isRegular (conjugateSubgroup g H_R) ∧
  H_R ≤ X ∧
  conjugateSubgroup g H_R ≤ X ∧
  (∀ p : Equiv.Perm H, p ∈ X →
    ∀ q : Equiv.Perm H, q ∈ H_R → p * q * p⁻¹ ∈ H_R) ∧
  H_R ≠ conjugateSubgroup g H_R ∧
  ¬ ∃ p : Equiv.Perm H, p ∈ X ∧
    conjugateSubgroup p H_R = conjugateSubgroup g H_R

end MathlibPlus.Open.Research.R1291
