import MathlibPlus.Combinatorics.Claim40144

open scoped Classical
noncomputable section

namespace MathlibPlus.Open.Research.R1298Charts

abbrev V := Fin 3 → ZMod 2

/-- The exact canonical chart alphabet: identity and transpositions of two
nonzero vectors. -/
def canonicalChart (c : Equiv.Perm V) : Prop :=
  c = 1 ∨
    ∃ a b : V,
      a ≠ 0 ∧ b ≠ 0 ∧ a ≠ b ∧ c = Equiv.swap a b

def chartAlphabet : Set (Equiv.Perm V) :=
  {c | canonicalChart c}

def profileMap {B : Type*}
    (c : B → Equiv.Perm V) : V × B → V × B :=
  fun x => (c x.2 x.1, x.2)

def sectionSet {B : Type*} (b : B) : Set (V × B) :=
  Set.univ ×ˢ ({b} : Set B)

def normalizedProfile {B : Type*} [Group B]
    (c : B → Equiv.Perm V) : Prop :=
  (∀ b : B, canonicalChart (c b)) ∧ c 1 = 1

/-- The normalized relative derivative in the direct-product coordinates. -/
def normalizedDerivative {B : Type*} [Group B]
    (c : B → Equiv.Perm V)
    (v : V) (b : B) (a : V) (s : B) : V × B :=
  let sourcePoint := profileMap c (a, s)
  let shiftedPoint := profileMap c (v + a, b * s)
  ((c b)⁻¹ (sourcePoint.1 + shiftedPoint.1), b)

def localDerivativeGenerator
    (i j k : Equiv.Perm V) (a : V) : Equiv.Perm V :=
  i⁻¹ * (Equiv.addRight (j a)) * k * (Equiv.addRight a)⁻¹

def localDerivativeGroup
    (i j k : Equiv.Perm V) : Subgroup (Equiv.Perm V) :=
  Subgroup.closure {g | ∃ a : V, g = localDerivativeGenerator i j k a}

def orbitOf (D : Subgroup (Equiv.Perm V)) (v : V) : Set V :=
  {w | ∃ d : D, (d : Equiv.Perm V) v = w}

/-- Claim 40145: canonical profiles preserve every direct-factor section and
are normalized at the identity section. -/
def claim40145 : Prop :=
  ∀ (B : Type*) [Finite B] [Group B]
    (c : B → Equiv.Perm V),
    normalizedProfile c →
      (∀ b : B,
        profileMap c '' sectionSet b = sectionSet b) ∧
        profileMap c (0, (1 : B)) = (0, (1 : B))

/-- Claim 40146: the normalized derivative fixes the B-coordinate and has the
specified chart expression on every V-fiber. -/
def claim40146 : Prop :=
  ∀ (B : Type*) [Group B]
    (c : B → Equiv.Perm V),
    normalizedProfile c →
      ∀ (v a : V) (b s : B),
        normalizedDerivative c v b a s =
          ((c b)⁻¹ (c s a + c (b * s) (v + a)), b)

/-- Claim 40148: every canonical section chart preserves every orbit of the
exact local derivative group generated by the three charts. -/
def claim40148 : Prop :=
  ∀ (i j k : Equiv.Perm V),
    canonicalChart i → canonicalChart j → canonicalChart k →
      ∀ v : V,
        Set.image i (orbitOf (localDerivativeGroup i j k) v) =
          orbitOf (localDerivativeGroup i j k) v

end MathlibPlus.Open.Research.R1298Charts
