import Mathlib

namespace MathlibPlus.Open.Research.R1378

abbrev CyclicPrime (p : ℕ) := Multiplicative (ZMod p)
abbrev A4 := (alternatingGroup (Fin 4))

/-- Adjacency for the right-difference Cayley graph. -/
def cayleyAdj {G : Type*} [Group G] (S : Set G) (x y : G) : Prop :=
  x ≠ y ∧ x * y⁻¹ ∈ S

/-- The full permutation automorphism group of that Cayley relation. -/
def cayleyAutomorphisms {G : Type*} [Group G] (S : Set G) :
    Subgroup (Equiv.Perm G) where
  carrier := {p | ∀ x y, cayleyAdj S (p x) (p y) ↔ cayleyAdj S x y}
  one_mem' := by
    intro x y
    simp
  mul_mem' := by
    intro p q hp hq x y
    exact (hp (q x) (q y)).trans (hq x y)
  inv_mem' := by
    intro p hp x y
    simpa using (hp (p⁻¹ x) (p⁻¹ y)).symm

/-- The subgroup generated by all right translations. -/
def rightRegular {G : Type*} [Group G] : Subgroup (Equiv.Perm G) :=
  Subgroup.closure (Set.range (fun g : G => Equiv.mulRight g))

/-- A subgroup is a regular copy of `G` on the underlying point set. -/
def IsRegularCopy (G : Type*) {Ω : Type*} [Group G]
    (R : Subgroup (Equiv.Perm Ω)) : Prop :=
  Nonempty (R ≃* G) ∧ ∀ x y : Ω, ∃! r : R, r.1 x = y

/-- Conjugation of permutation subgroups by a permutation. -/
def conjugateTo {Ω : Type*} (α : Equiv.Perm Ω)
    (R T : Subgroup (Equiv.Perm Ω)) : Prop :=
  ∀ p, p ∈ R ↔ α * p * α⁻¹ ∈ T

/-- Ordinary undirected CI for a finite group, expressed using its Cayley relation. -/
def IsUndirectedCIGroup (G : Type*) [Fintype G] [Group G] : Prop :=
  ∀ S : Set G,
    (∀ s, s ∈ S → s⁻¹ ∈ S) → 1 ∉ S →
      ∀ R : Subgroup (Equiv.Perm G),
        R ≤ cayleyAutomorphisms S → IsRegularCopy G R →
          ∃ α : cayleyAutomorphisms S,
            conjugateTo (α : Equiv.Perm G) R (rightRegular : Subgroup (Equiv.Perm G))

/-- Claim 38387. -/
def claim38387 : Prop :=
  IsUndirectedCIGroup (CyclicPrime 7 × A4) ∧
    IsUndirectedCIGroup (CyclicPrime 11 × A4)

/-- Claim 38388. -/
def claim38388 : Prop :=
  ∀ p : ℕ, ∀ hp : Nat.Prime p, 5 ≤ p →
    letI : Fact (Nat.Prime p) := ⟨hp⟩
    IsUndirectedCIGroup (CyclicPrime p × A4)

end MathlibPlus.Open.Research.R1378
