import Mathlib

namespace MathlibPlus.Open.GraphTheory.Claim4438

universe u

/-- An unordered pair of distinct vertices, represented by its two-element set. -/
def SimpleEdge (V : Type u) := {e : Set V // e.Finite ∧ e.ncard = 2}

/-- The action of a vertex permutation on a simple edge. -/
def permuteSimpleEdge {V : Type u} (σ : Equiv.Perm V) (e : SimpleEdge V) : SimpleEdge V :=
  ⟨σ '' e.1, Set.Finite.image σ e.2.1, by
    rw [Set.ncard_image_of_injective e.1 σ.injective]
    exact e.2.2⟩

/-- The induced equivalence of simple edges. -/
def permuteSimpleEdgeEquiv {V : Type u} (σ : Equiv.Perm V) : SimpleEdge V ≃ SimpleEdge V :=
  { toFun := permuteSimpleEdge σ
    invFun := permuteSimpleEdge σ.symm
    left_inv := by
      intro e
      apply Subtype.ext
      simp [permuteSimpleEdge, Set.image_image]
    right_inv := by
      intro e
      apply Subtype.ext
      simp [permuteSimpleEdge, Set.image_image] }

/-- A fixed-point family of vertex permutations, as in a card cocycle. -/
def CardCocycle (V : Type u) := {π : V → Equiv.Perm V // ∀ i : V, π i i = i}

/-- The two copies of the simple-edge carrier in the constraint multigraph. -/
def ConstraintVertex (V : Type u) := SimpleEdge V ⊕ SimpleEdge V

/-- The undirected constraint step generated by every avoided vertex. -/
def constraintStep {V : Type u} (π : CardCocycle V) :
    ConstraintVertex V → ConstraintVertex V → Prop
  | Sum.inl e, Sum.inr f => ∃ i : V, i ∉ e.1 ∧ f = permuteSimpleEdge (π.1 i) e
  | Sum.inr f, Sum.inl e => ∃ i : V, i ∉ e.1 ∧ f = permuteSimpleEdge (π.1 i) e
  | _, _ => False

/-- Path-connectedness of the constraint graph, before identifying it with `EqvGen`. -/
def constraintConnectedness {V : Type u} (π : CardCocycle V) :
    ConstraintVertex V → ConstraintVertex V → Prop :=
  Relation.ReflTransGen (constraintStep π)

/--
The admitted symmetry and component claim for the bipartite equality-constraint step:
`constraintStep` is symmetric, and its connectedness relation is `EqvGen constraintStep`.
-/
def symmetryAndComponentRelation_claim4438 (π : CardCocycle V) : Prop :=
  Std.Symm (constraintStep π) ∧
    constraintConnectedness π = Relation.EqvGen (constraintStep π)

end MathlibPlus.Open.GraphTheory.Claim4438
