import MathlibPlus.Open.ResearchBatch.Formalization_01a00175.Sylow

namespace MathlibPlus.Open.GraphTheory.R1405PrimitiveRegularPair

open MathlibPlus.Open.ResearchBatch.Formalization_01a00175.Sylow

noncomputable section

abbrev A4 := alternatingGroup (Fin 4)
abbrev C5SquaredTimesA4 := ZMod 5 × ZMod 5 × A4
abbrev Degree300 := C5SquaredTimesA4

/-- A regular copy of `C₅² × A₄` on its degree-300 regular-action carrier. -/
def regularCopyOfC5SquaredTimesA4
    (R : PermSubgroup Degree300) : Prop :=
  Nonempty (C5SquaredTimesA4 ≃* R) ∧
    isRegularPermutationSubgroup R

/-- Preservation of a simple graph by one permutation. -/
def preservesGraph
    (Γ : SimpleGraph Degree300) (g : Equiv.Perm Degree300) : Prop :=
  ∀ x y : Degree300,
    Γ.Adj (g x) (g y) ↔ Γ.Adj x y

/-- The literal finite simple undirected Cayley-graph carrier. -/
def isUndirectedCayleyGraph
    (Γ : SimpleGraph Degree300) : Prop :=
  ∃ S : Set Degree300,
    (1 : Degree300) ∉ S ∧
    (∀ s, s ∈ S → s⁻¹ ∈ S) ∧
    ∀ x y : Degree300,
      Γ.Adj x y ↔ x ≠ y ∧ x⁻¹ * y ∈ S

/-- The subgroup generated by the two regular copies. -/
def generatedRegularPair
    (R T : PermSubgroup Degree300) :
    PermSubgroup Degree300 :=
  Subgroup.closure ((R : Set (Equiv.Perm Degree300)) ∪
    (T : Set (Equiv.Perm Degree300)))

/-- Conjugacy of the two copies by a full graph automorphism. -/
def graphConjugates
    (Γ : SimpleGraph Degree300)
    (R T : PermSubgroup Degree300) : Prop :=
  ∃ q : Equiv.Perm Degree300,
    preservesGraph Γ q ∧
      ∀ u : Equiv.Perm Degree300,
        u ∈ T ↔
          ∃ r : Equiv.Perm Degree300,
            r ∈ R ∧ u = q⁻¹ * r * q

/-- Transitivity of a permutation subgroup. -/
def transitiveAction
    (X : PermSubgroup Degree300) : Prop :=
  ∀ x y : Degree300, ∃ g : X, g.1 x = y

/-- The block relation for this permutation action. -/
def isBlock
    (X : PermSubgroup Degree300) (B : Set Degree300) : Prop :=
  B.Nonempty ∧
    ∀ g : X,
      Set.image g.1 B = B ∨
        Disjoint (Set.image g.1 B) B

/-- A primitive action permits exactly the singleton and whole-set blocks. -/
def primitiveOn
    (X : PermSubgroup Degree300) : Prop :=
  transitiveAction X ∧
    ∀ B : Set Degree300,
      isBlock X B → B.Subsingleton ∨ B = Set.univ

/-- A genuine imprimitive action is transitive and has a nontrivial block;
its cardinal bounds exclude both singleton blocks and the whole carrier. -/
def imprimitiveOn
    (X : PermSubgroup Degree300) : Prop :=
  transitiveAction X ∧
    ∃ B : Set Degree300,
      isBlock X B ∧
        1 < B.ncard ∧ B.ncard < Nat.card Degree300

/-- The two graph alternatives in the primitive conclusion. -/
def emptySimpleGraph (Γ : SimpleGraph Degree300) : Prop :=
  ∀ x y : Degree300, ¬ Γ.Adj x y

def completeSimpleGraph (Γ : SimpleGraph Degree300) : Prop :=
  ∀ x y : Degree300, x ≠ y → Γ.Adj x y

/-- Claim 38692: the primitive regular-pair classification for
`C₅² × A₄`. -/
def primitiveRegularPairTheorem_claim38692 : Prop :=
  ∀ (Γ : SimpleGraph Degree300)
    (R T : PermSubgroup Degree300),
    isUndirectedCayleyGraph Γ →
    regularCopyOfC5SquaredTimesA4 R →
    regularCopyOfC5SquaredTimesA4 T →
    (∀ r : R, preservesGraph Γ r.1) →
    (∀ t : T, preservesGraph Γ t.1) →
    primitiveOn (generatedRegularPair R T) →
      (generatedRegularPair R T = alternatingGroup Degree300 ∨
        generatedRegularPair R T = ⊤) ∧
      (emptySimpleGraph Γ ∨ completeSimpleGraph Γ) ∧
      graphConjugates Γ R T

/-- Claim 38693: every ordinary undirected CI defect pair on
`C₅² × A₄` generates an imprimitive permutation group. -/
def everyOrdinaryCIDefectIsImprimitive_claim38693 : Prop :=
  ∀ (Γ : SimpleGraph Degree300)
    (R T : PermSubgroup Degree300),
    isUndirectedCayleyGraph Γ →
    regularCopyOfC5SquaredTimesA4 R →
    regularCopyOfC5SquaredTimesA4 T →
    (∀ r : R, preservesGraph Γ r.1) →
    (∀ t : T, preservesGraph Γ t.1) →
    ¬ graphConjugates Γ R T →
    imprimitiveOn (generatedRegularPair R T)

end

end MathlibPlus.Open.GraphTheory.R1405PrimitiveRegularPair
