import MathlibPlus.Open.Research.FormalizationBatch.R1529

namespace MathlibPlus.Open.ResearchFormalization.R1529.Claim38296

open MathlibPlus.Open.Research.FormalizationBatch.R1529

abbrev F7 := ZMod 7
abbrev Z8 := ZMod 8
abbrev OrderedBlockPairRow :=
  NormalizedAffineProfileSeven × (Z8 × Z8)

/-- The second row coordinate records separation first and starting block
second; it therefore determines the ordered pair `(k,k+d)`. -/
def rowSeparation (r : OrderedBlockPairRow) : Z8 :=
  r.2.1

def rowStartingBlock (r : OrderedBlockPairRow) : Z8 :=
  r.2.2

def orderedBlockPair (r : OrderedBlockPairRow) : Z8 × Z8 :=
  (rowStartingBlock r, rowStartingBlock r + rowSeparation r)

/-- The blockwise affine chart carried by an affine profile. -/
def blockwiseChart (p : AffineProfileSeven) :
    F7 × Z8 → F7 × Z8 :=
  fun z => (((p.a z.2 : F7) * z.1 + p.t z.2), z.2)

/-- An affine line map is recorded by its nonzero slope and intercept. -/
structure AffineLineMapSeven where
  slope : F7ˣ
  intercept : F7

/-- Evaluation of an affine line map. -/
def affineApply (f : AffineLineMapSeven) (x : F7) : F7 :=
  (f.slope : F7) * x + f.intercept

/-- Composition and inverse in the displayed affine-map coordinates. -/
def affineCompose (g f : AffineLineMapSeven) : AffineLineMapSeven :=
  ⟨g.slope * f.slope,
    (g.slope : F7) * f.intercept + g.intercept⟩

def affineInverse (f : AffineLineMapSeven) : AffineLineMapSeven :=
  ⟨f.slope⁻¹, -(f.slope⁻¹ : F7) * f.intercept⟩

def affineIdentity : AffineLineMapSeven :=
  ⟨1, 0⟩

/-- The slope periodicity at an ordered block separation. -/
def profileSlopePeriodic (p : NormalizedAffineProfileSeven)
    (d : Z8) : Prop :=
  ∀ k : Z8, p.1.a (k + d) = p.1.a k

/-- The shifted difference and its alternating correction. -/
def profileDelta (p : NormalizedAffineProfileSeven)
    (d k : Z8) : F7 :=
  p.1.t (k + d) - p.1.t k

def profileGamma (p : NormalizedAffineProfileSeven)
    (d k : Z8) : F7 :=
  (-1 : F7) ^ k.val * profileDelta p d k

/-- The required affine map at block `k`. -/
def profilePhi (p : NormalizedAffineProfileSeven)
    (d k : Z8) : AffineLineMapSeven :=
  ⟨p.1.a k, profileGamma p d k⟩

/-- The shifted derivative `D_k=φ_(k+1) φ_k⁻¹`. -/
def profileDerivative (p : NormalizedAffineProfileSeven)
    (d k : Z8) : AffineLineMapSeven :=
  affineCompose (profilePhi p d (k + 1))
    (affineInverse (profilePhi p d k))

/-- A word in the shifted derivatives and their inverses. -/
def affineWord (p : NormalizedAffineProfileSeven) (d : Z8) :
    List (Z8 × Bool) → AffineLineMapSeven
  | [] => affineIdentity
  | (k, forward) :: w =>
      affineCompose (affineWord p d w)
        (if forward then profileDerivative p d k
         else affineInverse (profileDerivative p d k))

/-- Membership in the affine subgroup generated by the shifted derivatives. -/
def inDerivativeGeneratedSet (p : NormalizedAffineProfileSeven)
    (d : Z8) (f : AffineLineMapSeven) : Prop :=
  ∃ w : List (Z8 × Bool), affineWord p d w = f

/-- The generated derivative group contains a nonzero translation. -/
def hasNonzeroDerivativeTranslation
    (p : NormalizedAffineProfileSeven) (d : Z8) : Prop :=
  ∃ w : List (Z8 × Bool),
    let f := affineWord p d w
    f.slope = 1 ∧ f.intercept ≠ 0

/-- A common fixed point of all shifted derivatives. -/
def hasCommonFixedPointAt
    (p : NormalizedAffineProfileSeven) (d : Z8) (z : F7) : Prop :=
  ∀ k : Z8, affineApply (profileDerivative p d k) z = z

/-- The fixed-point telescope `Γ_k=z₀-u a_k`. -/
def hasFixedPointTelescopeAt
    (p : NormalizedAffineProfileSeven) (d : Z8)
    (z₀ u : F7) : Prop :=
  ∀ k : Z8,
    profileGamma p d k = z₀ - u * (p.1.a k : F7)

/-- The map selected by the starting block of an ordered row fixes the common
fixed point, which is exactly the available difference-map condition. -/
def selectedFixedPointMap
    (p : NormalizedAffineProfileSeven) (d k : Z8) (z₀ : F7) : Prop :=
  affineApply (profilePhi p d k) z₀ = z₀

/-- The nonperiodic full-translation category of an ordered row. -/
def nonperiodFullTranslation (r : OrderedBlockPairRow) : Prop :=
  rowSeparation r ≠ 0 ∧
    ¬ profileSlopePeriodic r.1 (rowSeparation r)

/-- The periodic category in which the derivative group contains all
translations. -/
def periodTranslationSubgroup (r : OrderedBlockPairRow) : Prop :=
  rowSeparation r ≠ 0 ∧ profileSlopePeriodic r.1 (rowSeparation r) ∧
    hasNonzeroDerivativeTranslation r.1 (rowSeparation r)

/-- The periodic common-fixed-point category, retaining the selected starting
block in its transporter test. -/
def periodFixedPointTelescope (r : OrderedBlockPairRow) : Prop :=
  rowSeparation r = 0 ∨
    (rowSeparation r ≠ 0 ∧
      profileSlopePeriodic r.1 (rowSeparation r) ∧
      ∃ z₀ u : F7,
        hasCommonFixedPointAt r.1 (rowSeparation r) z₀ ∧
          hasFixedPointTelescopeAt r.1 (rowSeparation r) z₀ u ∧
            selectedFixedPointMap r.1 (rowSeparation r)
              (rowStartingBlock r) z₀)

/-- A missing difference map is a periodic common-fixed-point row whose
selected starting-block map is absent. -/
def missingDifferenceMap (r : OrderedBlockPairRow) : Prop :=
  rowSeparation r ≠ 0 ∧
    profileSlopePeriodic r.1 (rowSeparation r) ∧
    ∃ z₀ u : F7,
      hasCommonFixedPointAt r.1 (rowSeparation r) z₀ ∧
        hasFixedPointTelescopeAt r.1 (rowSeparation r) z₀ u ∧
          ¬ selectedFixedPointMap r.1 (rowSeparation r)
              (rowStartingBlock r) z₀

/-- The six equal-copy alternating translation profiles. -/
def equalCopyProfile (p : NormalizedAffineProfileSeven) : Prop :=
  ∃ ε : F7, ε ≠ 0 ∧
    p.1.a = (fun _ : Z8 => (1 : F7ˣ)) ∧
      ∀ j : Z8,
        p.1.t j = if j.val % 2 = 0 then 0 else ε

/-- A profile is bad precisely when one of its missing rows is not one of the
admitted alternating equal-copy profiles. -/
def badProfile (p : NormalizedAffineProfileSeven) : Prop :=
  ∃ d k : Z8,
    missingDifferenceMap (p, (d, k)) ∧ ¬ equalCopyProfile p

/-- The ordered-row category split is disjoint and exhaustive. -/
def orderedRowCategorySplit : Prop :=
  (∀ r : OrderedBlockPairRow,
    nonperiodFullTranslation r ∨
      periodTranslationSubgroup r ∨
        periodFixedPointTelescope r ∨ missingDifferenceMap r) ∧
    (∀ r : OrderedBlockPairRow,
      nonperiodFullTranslation r →
        ¬ periodTranslationSubgroup r ∧
          ¬ periodFixedPointTelescope r ∧ ¬ missingDifferenceMap r) ∧
    (∀ r : OrderedBlockPairRow,
      periodTranslationSubgroup r →
        ¬ periodFixedPointTelescope r ∧ ¬ missingDifferenceMap r) ∧
    (∀ r : OrderedBlockPairRow,
      periodFixedPointTelescope r → ¬ missingDifferenceMap r)

/-- Claim 38296: the exact q=7 ordered block-pair census, with the starting
block retained in every row predicate and no bad profile. -/
def claim38296 : Prop :=
  Nat.card OrderedBlockPairRow = 14_754_517_327_872 ∧
    Nat.card {r : OrderedBlockPairRow // nonperiodFullTranslation r} =
      12_908_674_166_080 ∧
    Nat.card {r : OrderedBlockPairRow // periodTranslationSubgroup r} =
      1_527_902_208 ∧
    Nat.card {r : OrderedBlockPairRow // periodFixedPointTelescope r} =
      1_844_315_259_392 ∧
    Nat.card {r : OrderedBlockPairRow // missingDifferenceMap r} = 192 ∧
    orderedRowCategorySplit ∧
    ∀ p : NormalizedAffineProfileSeven, ¬ badProfile p

end MathlibPlus.Open.ResearchFormalization.R1529.Claim38296
