import MathlibPlus.Open.ResearchBatch.AdvancedGroups

namespace MathlibPlus.ResearchFormalization.R1686

noncomputable section

abbrev W (p : ℕ) [NeZero p] := Fin 2 → ZMod p
abbrev R1686GL (p : ℕ) [NeZero p] := W p ≃ₗ[ZMod p] W p

noncomputable instance r1686GLFintype (p : ℕ) [NeZero p] : Fintype (R1686GL p) :=
  Fintype.ofInjective (fun L : R1686GL p => (L : W p → W p)) (by
    intro L M h
    exact DFunLike.ext L M (fun x => congrFun h x))

/-- A coordinate-diagonal linear map in the displayed basis. -/
def diagonalMonomial (p : ℕ) [NeZero p] (L : R1686GL p) : Prop :=
  ∃ a b : ZMod p, ∀ x : W p, ∀ i : Fin 2,
    L x i = if i = 0 then a * x 0 else b * x 1

/-- A coordinate-antidiagonal linear map in the displayed basis. -/
def antidiagonalMonomial (p : ℕ) [NeZero p] (L : R1686GL p) : Prop :=
  ∃ a b : ZMod p, ∀ x : W p, ∀ i : Fin 2,
    L x i = if i = 0 then a * x 1 else b * x 0

/-- The diagonal torus, as the subgroup generated by all displayed diagonal
linear maps that are already invertible. -/
def diagonalTorus (p : ℕ) [NeZero p] : Subgroup (R1686GL p) :=
  Subgroup.closure {L | diagonalMonomial p L}

/-- The exact source normalizer of the displayed diagonal torus. -/
def monomialNormalizer (p : ℕ) [NeZero p] : Subgroup (R1686GL p) :=
  Subgroup.normalizer (diagonalTorus p : Set (R1686GL p))

/-- The matrix used by the antidiagonal containment claim. -/
def antidiagonalMatrix {K : Type*} [Semiring K] (a d : K) :
    Matrix (Fin 2) (Fin 2) K :=
  !![0, a; d, 0]

/-- A one-dimensional submodule is the exact line carrier used below. -/
def isLine {K V : Type*} [Field K] [AddCommGroup V] [Module K V]
    (L : Submodule K V) : Prop :=
  ∃ v : V, v ≠ 0 ∧ L = Submodule.span K ({v} : Set V)

end

end MathlibPlus.ResearchFormalization.R1686

namespace MathlibPlus.Open.ResearchFormalization.R1686

noncomputable section

open MathlibPlus.ResearchFormalization.R1686
open MathlibPlus.Open.ResearchBatch.AdvancedGroups

/-- Claim 33290: the odd-prime two-dimensional diagonal-torus normalizer
has exactly its diagonal and antidiagonal monomial elements, order
`2 * (p - 1)^2`, and order coprime to `p`. -/
def monomialNormalizerOrder_claim33290 : Prop :=
  ∀ (p : ℕ) [Fact (Nat.Prime p)] [NeZero p] (hodd : Odd p),
    let N := monomialNormalizer p
    letI : Fintype N := Fintype.ofFinite N
    Fintype.card N = 2 * (p - 1) ^ 2 ∧
      (∀ L : R1686GL p,
        L ∈ N ↔ diagonalMonomial p L ∨ antidiagonalMonomial p L) ∧
      Nat.Coprime (Fintype.card N) p

/-- Claim 33291: for the exact affine subgroup carrier inside the displayed
monomial normalizer, the common setwise orbit-translation stabilizer equals
the identity-linear translation core. -/
def commonOrbitTranslationStabilizerEqualsCore_claim33291 : Prop :=
  ∀ (p : ℕ) [Fact (Nat.Prime p)] [NeZero p] (hodd : Odd p)
    (Γ : Subgroup (Equiv.Perm (W p))),
    affineContainedIn (monomialNormalizer p) Γ →
      commonTranslationStabilizer (K := ZMod p) Γ =
        affineTranslationCore (K := ZMod p) Γ

/-- Claim 33305: for the literal antidiagonal `2 × 2` matrix, containment
of the image of `M - I` in a line gives the stated rank, determinant, and
product conclusions. -/
def antidiagonalContainmentForcesDeterminantOne_claim33305 : Prop :=
  ∀ (K : Type*) [Field K] (a d : K)
    (V : Submodule K (Fin 2 → K)),
    isLine V →
      LinearMap.range
          (Matrix.toLin' (antidiagonalMatrix a d -
            (1 : Matrix (Fin 2) (Fin 2) K))) ≤ V →
        Module.finrank K
            (LinearMap.range
              (Matrix.toLin' (antidiagonalMatrix a d -
                (1 : Matrix (Fin 2) (Fin 2) K)))) ≤ 1 ∧
          Matrix.det (antidiagonalMatrix a d -
            (1 : Matrix (Fin 2) (Fin 2) K)) = 1 - a * d ∧
          Matrix.det (antidiagonalMatrix a d -
            (1 : Matrix (Fin 2) (Fin 2) K)) = 0 ∧
          a * d = 1

end

end MathlibPlus.Open.ResearchFormalization.R1686
