import Mathlib

namespace MathlibPlus.Open.ResearchFormalization.R1357

noncomputable section

/-- The fixed elementary-abelian base carrier C₂³. -/
abbrev Base := Fin 3 → ZMod 2

/-- The displacement subgroup attached to an active base point. -/
def displacementSubgroup {B : Type*} [AddCommGroup B]
    (q : Base → Equiv.Perm B) (u : Base) : AddSubgroup B :=
  AddSubgroup.closure
    (Set.range (fun t : B => t - q u t + q u 0))

/-- The joint subgroup generated by the active-fiber displacements. -/
def jointDisplacementSubgroup {B : Type*} [AddCommGroup B]
    (q : Base → Equiv.Perm B) (K : Finset Base) : AddSubgroup B :=
  AddSubgroup.closure
    (⋃ u ∈ (K : Set Base), (displacementSubgroup q u : Set B))

/-- Claim 38192: for a finite abelian odd-order fiber and an exactly
four-point nonzero active support, the full joint displacement condition is
the equality of the explicit generated subgroup with the whole fiber. -/
def claim38192_displacementSubgroup
    {B : Type*} [AddCommGroup B] [Fintype B] [DecidableEq B]
    (q : Base → Equiv.Perm B) (K : Finset Base) : Prop :=
  Odd (Fintype.card B) ∧
    K.card = 4 ∧
      (∀ u : Base, u ∈ K → u ≠ 0) ∧
        jointDisplacementSubgroup q K = ⊤

end

end MathlibPlus.Open.ResearchFormalization.R1357
