import Mathlib

namespace MathlibPlus.Algebra.Claim6162

/-!
The source treats `x₁` as one polynomial variable over the ring generated by
all other variables.  This univariate formulation records the same
x₁-independent residue as a constant polynomial over an explicit
characteristic-zero, additively torsion-free coefficient ring.
-/

/-- Equality of formal derivatives leaves exactly a constant residue. -/
theorem split_antiderivative_residue
    {R : Type*} [CommRing R] [CharZero R] [IsAddTorsionFree R]
    (P Q : Polynomial R) (h : P.derivative = Q.derivative) :
    P - Q = Polynomial.C ((P - Q).coeff 0) := by
  have hder : (P - Q).derivative = 0 := by
    rw [Polynomial.derivative_sub, h, sub_self]
  exact Polynomial.eq_C_of_derivative_eq_zero hder

end MathlibPlus.Algebra.Claim6162
