import Mathlib

namespace MathlibPlus.Algebra.Claim27497

/-- The predecessor displacement subspace generated by `u + ψ u + ψ 0`. -/
def predecessorDisplacementSpan_claim27497
    (V : Type*) [AddCommGroup V] [Module (ZMod 2) V] [Finite V]
    (ψ : Equiv.Perm V) : Submodule (ZMod 2) V :=
  Submodule.span (ZMod 2) (Set.range (fun u : V => u + ψ u + ψ 0))

end MathlibPlus.Algebra.Claim27497
