import Mathlib.RingTheory.Ideal.Operations

namespace MathlibPlus.Algebra.Claim52072

/-- The displayed signed difference belongs to the ideal generated by the two
physical columns. -/
theorem signedDifferenceInGeneratedIdeal
    {R : Type*} [CommRing R] (x_a x_s x_t : R) :
    x_s - x_t ∈ Ideal.span ({x_a - x_s, x_a - x_t} : Set R) := by
  have hs : x_a - x_s ∈ Ideal.span ({x_a - x_s, x_a - x_t} : Set R) := by
    exact Ideal.subset_span (by simp)
  have ht : x_a - x_t ∈ Ideal.span ({x_a - x_s, x_a - x_t} : Set R) := by
    exact Ideal.subset_span (by simp)
  rw [show x_s - x_t = (x_a - x_t) - (x_a - x_s) by ring]
  exact Ideal.sub_mem _ ht hs

end MathlibPlus.Algebra.Claim52072
