import MathlibPlus.Algebra.Claim37138

noncomputable section

namespace MathlibPlus.Algebra.R2111ContextIdeal37141

/-- The triangular context ideal generated by the second and third shifted
trace elements. -/
def contextIdeal {R : Type*} [CommRing R]
    (S₂ S₃ : MvPolynomial ℕ R) : Ideal (MvPolynomial ℕ R) :=
  Ideal.span ({S₂, S₃} : Set (MvPolynomial ℕ R))

/-- Claim 37141: the prime-quotient cancellation in the shifted-trace
coefficient relation. -/
def claim37141 : Prop :=
  ∀ {R : Type*} [CommRing R]
    (S₁ S₂ S₃ : MvPolynomial ℕ R)
    (j₀ j₁ j₂ : MvPolynomial ℕ R),
    let I := contextIdeal S₂ S₃
    I.IsPrime →
      S₁ ∉ I →
        j₀ * S₁ + j₁ * S₂ + j₂ * S₃ = 0 →
          j₀ ∈ I

end MathlibPlus.Algebra.R2111ContextIdeal37141
