import Mathlib

namespace MathlibPlus.Open

/-- The zero/one/many code used by an outside-event register. -/
inductive OutsideCode (ι : Type*) where
  | zero
  | one (label : ι)
  | many
  deriving DecidableEq

/-- The anchor span generated by the vectors at the anchor labels. -/
def anchorSpan {ι F : Type*} [Field F] {d : ℕ}
    (v : ι → Fin d → F) (A : Finset ι) : Submodule F (Fin d → F) :=
  Submodule.span F (v '' (A : Set ι))

/-- Labels in a finite family whose vectors lie outside the anchor span. -/
noncomputable def outsideLabels {ι F : Type*} [DecidableEq ι] [Field F] {d : ℕ}
    (v : ι → Fin d → F) (E A : Finset ι) : Finset ι := by
  classical
  exact E.filter (fun k => v k ∉ anchorSpan v A)

/-- The zero/one/many commutative outside-register fold. -/
noncomputable def outRegister {ι F : Type*} [DecidableEq ι] [Field F] {d : ℕ}
    (v : ι → Fin d → F) (E A : Finset ι) : OutsideCode ι := by
  classical
  let S := outsideLabels v E A
  by_cases h0 : S = ∅
  · exact .zero
  · by_cases h1 : ∃ k, S = {k}
    · exact .one (Classical.choose h1)
    · exact .many

/-- A vector-labelled element is a coloop when it lies outside the span of its competitors. -/
def vectorColoop {ι F : Type*} [DecidableEq ι] [Field F] {d : ℕ}
    (v : ι → Fin d → F) (E : Finset ι) (e : ι) : Prop :=
  e ∈ E ∧ v e ∉ Submodule.span F (v '' ((E.erase e : Finset ι) : Set ι))

/--
Deletion-stable bounded-anchor recognition: after any deletion, an undeleted
coloop is recognized by an outside register with at most `d - 1` surviving
anchors avoiding the deletion set and the candidate.
-/
def deletionStableBoundedAnchorRecognition
    {ι F : Type*} [DecidableEq ι] [Field F]
    (d : ℕ) (K E : Finset ι) (v : ι → Fin d → F) (hE : E ⊆ K) : Prop :=
  ∀ (X : Finset ι) (e : ι),
    e ∈ E → e ∉ X →
      (vectorColoop v (E \ X) e ↔
        ∃ A : Finset ι,
          A ⊆ K \ (X ∪ {e}) ∧
          A.card ≤ d - 1 ∧
          outRegister v (E \ X) A = OutsideCode.one e)

end MathlibPlus.Open
