import Mathlib

open scoped Pointwise

namespace MathlibPlus.Open.Research.FormalizationBatch
namespace DihedralOrbit

abbrev Vertex := ZMod 4

/-- Rotation and reflection of the 4-cycle. -/
def rotation : Equiv.Perm Vertex := Equiv.addRight 1

def reflection : Equiv.Perm Vertex := Equiv.neg Vertex

/-- The concrete dihedral action generated by rotation and reflection. -/
def D4 : Subgroup (Equiv.Perm Vertex) :=
  Subgroup.closure ({rotation, reflection} : Set (Equiv.Perm Vertex))

def isCycleEdge (e : Finset Vertex) : Prop :=
  ∃ x : Vertex, e = {x, x + 1} ∨ e = {x, x - 1}

def cycleEdges : Set (Finset Vertex) := {e | isCycleEdge e}

def edgeAction (g : Equiv.Perm Vertex) (e : Finset Vertex) : Finset Vertex :=
  e.image g

def edgeOrbit (e : Finset Vertex) : Set (Finset Vertex) :=
  {f | ∃ g : D4, edgeAction g.1 e = f}

/-- Claim 13267: D₄ is transitive on the vertices and edges of the 4-cycle,
and one edge orbit is the complete edge set. -/
def claim13267 : Prop :=
  (∀ x y : Vertex, ∃ g : D4, g.1 x = y) ∧
    (∀ e f : Finset Vertex,
      isCycleEdge e → isCycleEdge f → ∃ g : D4, edgeAction g.1 e = f) ∧
    (∀ e : Finset Vertex, isCycleEdge e → edgeOrbit e = cycleEdges)

end DihedralOrbit
end MathlibPlus.Open.Research.FormalizationBatch
