import Mathlib

namespace MathlibPlus.Open.Research

section DirectedParentGraphs

variable {P C : Type*} [Fintype P] [Fintype C] [DecidableEq P]

/-- One directed parent-cell step. -/
def parentStep (source target : C → P) (a b : P) : Prop :=
  ∃ e, source e = a ∧ target e = b

/-- Directed reachability generated by parent cells. -/
def parentReachable (source target : C → P) (a b : P) : Prop :=
  Relation.ReflTransGen (parentStep source target) a b

/-- One step in the underlying undirected parent graph. -/
def parentWeakStep (source target : C → P) (a b : P) : Prop :=
  ∃ e, (source e = a ∧ target e = b) ∨ (source e = b ∧ target e = a)

/-- Weak connectivity generated by the underlying parent graph. -/
def parentWeaklyConnected (source target : C → P) (a b : P) : Prop :=
  Relation.ReflTransGen (parentWeakStep source target) a b

/-- The incidence boundary of a chain of parent cells over the integers. -/
def parentBoundaryInt (source target : C → P) (r : C → ℤ) : P → ℤ :=
  fun p => ∑ e : C, ((if source e = p then r e else 0) - (if target e = p then r e else 0))

/-- The incidence boundary of a chain of parent cells over the reals. -/
def parentBoundaryReal (source target : C → P) (r : C → ℝ) : P → ℝ :=
  fun p => ∑ e : C, ((if source e = p then r e else 0) - (if target e = p then r e else 0))

/-- The source vector `[a] - [b]`. -/
def parentSourceInt (a b : P) : P → ℤ :=
  fun p => if p = a then 1 else if p = b then -1 else 0

/-- The source vector `[a] - [b]` over the reals. -/
def parentSourceReal (a b : P) : P → ℝ :=
  fun p => if p = a then 1 else if p = b then -1 else 0

/-- The indicator of the vertices reachable from `a`. -/
noncomputable def reachableIndicatorInt (source target : C → P) (a : P) : P → ℤ := by
  classical
  exact fun p => if parentReachable source target a p then 1 else 0

/--
The reachable-set cut certificate for a finite directed parent graph (R-5081.4).
The displayed indicator is the canonical source-value-one certificate, and the
last two conjuncts record the resulting integral and real infeasibility.
-/
def claim57200 (source target : C → P) (a b : P) : Prop :=
  ¬ parentReachable source target a b →
      let χ := reachableIndicatorInt source target a
      (∀ e : C,
          χ (source e) - χ (target e) = 0 ∨
            χ (source e) - χ (target e) = -1) ∧
        (∀ e : C, χ (source e) - χ (target e) ≤ 0) ∧
        χ a - χ b = 1 ∧
        (∀ r : C → ℤ,
          (∀ e : C, 0 ≤ r e) →
            parentBoundaryInt source target r ≠ parentSourceInt a b) ∧
        (∀ r : C → ℝ,
          (∀ e : C, 0 ≤ r e) →
            parentBoundaryReal source target r ≠ parentSourceReal a b)

/-- The literal orientation double of a chosen parent-cell set. -/
abbrev OrientedParentCell (C₀ : Type*) := C₀ × Bool

/-- Literal reversal in the orientation double. -/
def orientedParentReverse {C₀ : Type*} (e : OrientedParentCell C₀) : OrientedParentCell C₀ :=
  (e.1, !e.2)

/-- Source endpoint of an oriented parent cell. `true` is the chosen orientation. -/
def orientedParentSource (source target : C₀ → P) : OrientedParentCell C₀ → P
  | (e, true) => source e
  | (e, false) => target e

/-- Target endpoint of an oriented parent cell. -/
def orientedParentTarget (source target : C₀ → P) : OrientedParentCell C₀ → P
  | (e, true) => target e
  | (e, false) => source e

/--
Weak connectivity, signed integral generation, nonnegative integral flow,
nonnegative real flow, and directed reachability agree after literal
orientation completion (R-5082.2).
-/
def claim57204 {C₀ : Type*} [Fintype C₀]
    (source target : C₀ → P) (a b : P) : Prop :=
  a ≠ b →
    (parentWeaklyConnected source target a b ↔
      (∃ m : C₀ → ℤ,
        parentBoundaryInt source target m = parentSourceInt a b) ∧
        (∃ m : OrientedParentCell C₀ → ℕ,
          parentBoundaryInt
              (orientedParentSource source target)
              (orientedParentTarget source target)
              (fun e => (m e : ℤ)) = parentSourceInt a b) ∧
        (∃ r : OrientedParentCell C₀ → ℝ,
          (∀ e, 0 ≤ r e) ∧
            parentBoundaryReal
              (orientedParentSource source target)
              (orientedParentTarget source target) r = parentSourceReal a b) ∧
        parentReachable
          (orientedParentSource source target)
          (orientedParentTarget source target) a b)

end DirectedParentGraphs

end MathlibPlus.Open.Research
