import MathlibPlus.Open.ResearchFormalization.BatchR1258
import MathlibPlus.Open.ResearchFormalization.Claim60990

namespace MathlibPlus.Open.Research.FormalizationBatch.R1258Claims30698_30700

open MathlibPlus.Open.ResearchFormalization
open MathlibPlus.Open.ResearchFormalization.BatchR1258

abbrev R1258Group (A B : Type*) := A × B × D10

/-- The right-difference adjacency relation of the displayed Cayley graph. -/
def cayleyAdjacency (A B : Type*) [Group A] [Group B]
    (x y : R1258Group A B) : Prop :=
  x ≠ y ∧ x⁻¹ * y ∈ connectionSet A B

/-- Permutations preserving a binary graph relation. -/
def graphAutomorphismSet {X : Type*} (adj : X → X → Prop) :
    Set (Equiv.Perm X) :=
  {p | ∀ x y, adj x y ↔ adj (p x) (p y)}

/-- A permutation of a Cartesian carrier that acts independently on its two
coordinates. -/
def r1258CoordinateForm {X Y : Type*}
    (p : Equiv.Perm (X × Y)) (u : Equiv.Perm X) (v : Equiv.Perm Y) : Prop :=
  ∀ x y, p (x, y) = (u x, v y)

/-- The target-coordinate carrier after the five-cycle and independent fibres
have been exposed. -/
abbrev R1258TargetVertex (m n : ℕ) :=
  Fin (2 * m) × (Fin n × ZMod 5)

/-- The relation on the target-coordinate carrier corresponding to the
Cartesian clique-cycle model. -/
def r1258TargetAdj (m n : ℕ)
    (x y : R1258TargetVertex m n) : Prop :=
  x ≠ y ∧
    ((x.1 ≠ y.1 ∧ x.2 = y.2) ∨
      (x.1 = y.1 ∧
        (y.2.2 - x.2.2 = (1 : ZMod 5) ∨
          y.2.2 - x.2.2 = (-1 : ZMod 5))))

/-- The characteristic `A` and `B` factor carriers in `A × B × D₁₀`. -/
def r1258AFactorSet (A B : Type*) [Group A] [Group B] :
    Set (R1258Group A B) :=
  Set.range (fun a : A => (a, 1, 1))

def r1258BFactorSet (A B : Type*) [Group A] [Group B] :
    Set (R1258Group A B) :=
  Set.range (fun b : B => (1, b, 1))

/-- First-coordinate projections of a factor under an aligned target action. -/
def r1258FirstProjectionSet
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (F : Set (R1258Group A B)) : Set (Equiv.Perm (Fin (2 * m))) :=
  {u | ∃ g, g ∈ F ∧
    ∃ v : Equiv.Perm (Fin n × ZMod 5),
      r1258CoordinateForm (e.symm g).1 u v}

/-- Second-coordinate projections of a factor under an aligned target action. -/
def r1258SecondProjectionSet
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (F : Set (R1258Group A B)) : Set (Equiv.Perm (Fin n × ZMod 5)) :=
  {v | ∃ g, g ∈ F ∧
    ∃ u : Equiv.Perm (Fin (2 * m)),
      r1258CoordinateForm (e.symm g).1 u v}

/-- The action induced on the selected `n`-point quotient fibre. -/
def r1258FiberProjectionSet
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (F : Set (R1258Group A B)) : Set (Equiv.Perm (Fin n)) :=
  {u | ∃ v : Equiv.Perm (Fin n × ZMod 5),
    v ∈ r1258SecondProjectionSet A B m n T e F ∧
      ∀ a : Fin n, v (a, 0) = (u a, 0)}

/-- The first-coordinate image of the distinguished reflection. -/
def r1258ReflectionProjection
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (τ : Equiv.Perm (Fin (2 * m))) : Prop :=
  ∃ v : Equiv.Perm (Fin n × ZMod 5),
    r1258CoordinateForm
      (e.symm (1, 1, reflection)).1 τ v

/-- The aligned `C₂ wr S_m` first-coordinate action. -/
def r1258FirstWreathMember (B : Type*) (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (u : Equiv.Perm (Fin (2 * m))) : Prop :=
  ∃ σ : Equiv.Perm B,
    ∃ κ : B → Equiv.Perm (Fin 2),
      ∀ b i, η (u (η.symm (b, i))) = (σ b, κ b i)

/-- The regular `B × C₂` action in the aligned first coordinate. -/
def r1258AlignedHallAction (B : Type*) [Group B] (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (H : Subgroup (Equiv.Perm (Fin (2 * m))))
    (e : B ≃* H) : Prop :=
  ∀ b g i, η ((e b).1 (η.symm (g, i))) = (b * g, i)

/-- The aligned reflection swaps the two regular Hall orbits. -/
def r1258AlignedReflection (B : Type*) [Group B] (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (τ : Equiv.Perm (Fin (2 * m))) : Prop :=
  ∀ g i, η (τ (η.symm (g, i))) =
    (g, (Equiv.swap (0 : Fin 2) 1) i)

/-- Permutations in the first-coordinate wreath action that commute with the
Hall action and its aligned reflection. -/
def r1258ReflectionPreservingCentralizer {B : Type*} [Group B]
    (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (H : Subgroup (Equiv.Perm (Fin (2 * m))))
    (τ : Equiv.Perm (Fin (2 * m)))
    (u : Equiv.Perm (Fin (2 * m))) : Prop :=
  r1258FirstWreathMember B m η u ∧
    (∀ h : H, Commute u h.1) ∧ Commute u τ

/-- The subgroup generated by a first-coordinate Hall action and its
reflection. -/
def r1258HallReflectionGroup {X : Type*}
    (H : Subgroup (Equiv.Perm X)) (τ : Equiv.Perm X) :
    Subgroup (Equiv.Perm X) :=
  Subgroup.closure ((H : Set (Equiv.Perm X)) ∪ {τ})

/-- The natural left-regular permutation copy of a finite group. -/
def naturalRegularCopy (G : Type*) [Group G] :
    Subgroup (Equiv.Perm G) :=
  MonoidHom.range (MulAction.toPermHom G G)

/-- Conjugacy of permutation subgroups in the ambient symmetric group. -/
def conjugateSubgroups {X : Type*}
    (R T : Subgroup (Equiv.Perm X)) : Prop :=
  ∃ p : Equiv.Perm X,
    ∀ q : Equiv.Perm X,
      q ∈ T ↔ ∃ r : Equiv.Perm X, r ∈ R ∧ q = p⁻¹ * r * p

/-- The four factor projections supplied by an aligned regular target. -/
def r1258ProjectionAlignment
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (P₁ H₁ : Subgroup (Equiv.Perm (Fin (2 * m))))
    (P₂ H₂ : Subgroup (Equiv.Perm (Fin n))) : Prop :=
  (P₁ : Set (Equiv.Perm (Fin (2 * m)))) =
      r1258FirstProjectionSet A B m n T e (r1258AFactorSet A B) ∧
    (H₁ : Set (Equiv.Perm (Fin (2 * m)))) =
      r1258FirstProjectionSet A B m n T e (r1258BFactorSet A B) ∧
    (P₂ : Set (Equiv.Perm (Fin n))) =
      r1258FiberProjectionSet A B m n T e (r1258AFactorSet A B) ∧
    (H₂ : Set (Equiv.Perm (Fin n))) =
      r1258FiberProjectionSet A B m n T e (r1258BFactorSet A B)

/-- Every regular graph-automorphism subgroup of the construction with the
prescribed abstract group is conjugate to the natural left-regular copy. -/
def r1258RegularClass (A B : Type*) [Group A] [Group B] : Prop :=
  ∀ H : Subgroup (Equiv.Perm (R1258Group A B)),
    (∀ h : H,
      h.1 ∈ graphAutomorphismSet (cayleyAdjacency A B)) →
    permutationSubgroupRegular H →
    Nonempty (H ≃* R1258Group A B) →
    conjugateSubgroups (naturalRegularCopy (R1258Group A B)) H

/-- Claim 30698: every regular copy of `A × B × D₁₀` in the graph
automorphism group is conjugate to the natural regular copy. -/
def claim_30698 : Prop :=
  ∀ (A B : Type*) [Group A] [Fintype A] [Group B] [Fintype B]
    (n m : ℕ),
    Nontrivial A →
    Fintype.card A = n → Odd n →
    Fintype.card B = m → Odd m →
    Nat.Coprime n m → Nat.Coprime (n * m) 10 →
    r1258RegularClass A B

/-- Claim 30699: the displayed inverse-closed Cayley graph is CI in the
ordinary undirected sense. -/
def claim_30699 : Prop :=
  ∀ (A B : Type*) [Group A] [Fintype A] [Group B] [Fintype B]
    (n m : ℕ),
    Nontrivial A →
    Fintype.card A = n → Odd n →
    Fintype.card B = m → Odd m →
    Nat.Coprime n m → Nat.Coprime (n * m) 10 →
    claim60990OrdinaryUndirectedCI (connectionSet A B)

/-- The canonical vertex carrier for `K_(2m) □ C₅[overline(K_n)]`.
The first coordinate labels the complete-factor vertices, the second coordinate
labels a five-cycle quotient vertex and an independent `n`-point fibre. -/
abbrev R1258BlowupVertex (m n : ℕ) :=
  Fin (2 * m) × (ZMod 5 × Fin n)

/-- The adjacency relation of `K_(2m) □ C₅[overline(K_n)]`. -/
def r1258BlowupAdj (m n : ℕ)
    (x y : R1258BlowupVertex m n) : Prop :=
  x ≠ y ∧
    ((x.1 ≠ y.1 ∧ x.2 = y.2) ∨
      (x.1 = y.1 ∧
        (y.2.1 - x.2.1 = (1 : ZMod 5) ∨
          y.2.1 - x.2.1 = (-1 : ZMod 5))))

/-- An isomorphism between two explicitly given binary graph relations. -/
def relationIsomorphism {X Y : Type*}
    (r : X → X → Prop) (s : Y → Y → Prop) : Prop :=
  ∃ e : X ≃ Y, ∀ x y, r x y ↔ s (e x) (e y)

/-- The natural action of `D₁₀` on the five quotient fibres. -/
def r1258DihedralAction : D10 → Equiv.Perm (ZMod 5)
  | DihedralGroup.r k => Equiv.addRight k
  | DihedralGroup.sr k =>
      (Equiv.neg (ZMod 5)).trans (Equiv.addRight k)

/-- The concrete `S_n^5 ⋊ D₁₀` action on the five independent fibres. -/
def r1258WreathMember (m n : ℕ)
    (p : Equiv.Perm (R1258BlowupVertex m n)) : Prop :=
  ∃ σ : Equiv.Perm (Fin (2 * m)),
    ∃ z : D10,
      ∃ f : ZMod 5 → Equiv.Perm (Fin n),
        ∀ i c a,
          p (i, (c, a)) =
            (σ i, (r1258DihedralAction z c, f c a))

/-- No permutation of the canonical graph mixes the complete-factor and
five-cycle/fibre coordinates beyond the stated wreath action. -/
def r1258NoCrossCoordinateShear (m n : ℕ) : Prop :=
  ∀ p : Equiv.Perm (R1258BlowupVertex m n),
    p ∈ graphAutomorphismSet (r1258BlowupAdj m n) →
      r1258WreathMember m n p

/-- The canonical graph has exactly the stated product-wreath automorphism
action. -/
def r1258WreathAutomorphismCharacterization (m n : ℕ) : Prop :=
  ∀ p : Equiv.Perm (R1258BlowupVertex m n),
    p ∈ graphAutomorphismSet (r1258BlowupAdj m n) ↔
      r1258WreathMember m n p

abbrev r1258ElementaryA (p d : ℕ) :=
  Multiplicative (Fin d → ZMod p)

abbrev r1258PrimeB (q : ℕ) := Multiplicative (ZMod q)

/-- The rank-specialized no-twist package: the graph model, its full
automorphism action, the single regular subgroup class, and CI. -/
def r1258RankNoTwist (p q d : ℕ)
    (hp : Nat.Prime p) (hq : Nat.Prime q) : Prop :=
  let A := r1258ElementaryA p d
  let B := r1258PrimeB q
  relationIsomorphism
      (cayleyAdjacency A B)
      (r1258BlowupAdj q (p ^ d)) ∧
    r1258WreathAutomorphismCharacterization q (p ^ d) ∧
    r1258RegularClass A B ∧
    claim60990OrdinaryUndirectedCI (connectionSet A B) ∧
    r1258NoCrossCoordinateShear q (p ^ d)

/-- Claim 30700: the elementary-abelian rank family has the displayed graph,
automorphism group, one regular subgroup class, and CI, with no reflection
twist or cross-coordinate shear at any rank. -/
def claim_30700 : Prop :=
  ∀ (d p q : ℕ),
    1 ≤ d →
    ∀ (hp : Nat.Prime p) (hq : Nat.Prime q),
      Odd p → Odd q →
      p ≠ q → p ≠ 5 → q ≠ 5 →
      r1258RankNoTwist p q d hp hq

end MathlibPlus.Open.Research.FormalizationBatch.R1258Claims30698_30700
