import MathlibPlus.Open.ResearchFormalization.BatchR1258
import MathlibPlus.Open.ResearchFormalization.Claim60990

namespace MathlibPlus.Open.Research.FormalizationBatch.R1258Claim30697

open MathlibPlus.Open.ResearchFormalization
open MathlibPlus.Open.ResearchFormalization.BatchR1258

abbrev R1258Group (A B : Type*) := A × B × D10

/-- The right-difference adjacency relation of the displayed Cayley graph. -/
def cayleyAdjacency (A B : Type*) [Group A] [Group B]
    (x y : R1258Group A B) : Prop :=
  x ≠ y ∧ x⁻¹ * y ∈ connectionSet A B

/-- Permutations preserving a binary graph relation. -/
def graphAutomorphismSet {X : Type*} (adj : X → X → Prop) :
    Set (Equiv.Perm X) :=
  {p | ∀ x y, adj x y ↔ adj (p x) (p y)}

/-- A permutation of a Cartesian carrier that acts independently on its two
coordinates. -/
def r1258CoordinateForm {X Y : Type*}
    (p : Equiv.Perm (X × Y)) (u : Equiv.Perm X) (v : Equiv.Perm Y) : Prop :=
  ∀ x y, p (x, y) = (u x, v y)

/-- The target-coordinate carrier after the five-cycle and independent fibres
have been exposed. -/
abbrev R1258TargetVertex (m n : ℕ) :=
  Fin (2 * m) × (Fin n × ZMod 5)

/-- The relation on the target-coordinate carrier corresponding to the
Cartesian clique-cycle model. -/
def r1258TargetAdj (m n : ℕ)
    (x y : R1258TargetVertex m n) : Prop :=
  x ≠ y ∧
    ((x.1 ≠ y.1 ∧ x.2 = y.2) ∨
      (x.1 = y.1 ∧
        (y.2.2 - x.2.2 = (1 : ZMod 5) ∨
          y.2.2 - x.2.2 = (-1 : ZMod 5))))

/-- The characteristic `A` and `B` factor carriers in `A × B × D₁₀`. -/
def r1258AFactorSet (A B : Type*) [Group A] [Group B] :
    Set (R1258Group A B) :=
  Set.range (fun a : A => (a, 1, 1))

def r1258BFactorSet (A B : Type*) [Group A] [Group B] :
    Set (R1258Group A B) :=
  Set.range (fun b : B => (1, b, 1))

/-- First-coordinate projections of a factor under an aligned target action. -/
def r1258FirstProjectionSet
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (F : Set (R1258Group A B)) : Set (Equiv.Perm (Fin (2 * m))) :=
  {u | ∃ g, g ∈ F ∧
    ∃ v : Equiv.Perm (Fin n × ZMod 5),
      r1258CoordinateForm (e.symm g).1 u v}

/-- Second-coordinate projections of a factor under an aligned target action. -/
def r1258SecondProjectionSet
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (F : Set (R1258Group A B)) : Set (Equiv.Perm (Fin n × ZMod 5)) :=
  {v | ∃ g, g ∈ F ∧
    ∃ u : Equiv.Perm (Fin (2 * m)),
      r1258CoordinateForm (e.symm g).1 u v}

/-- The action induced on the selected `n`-point quotient fibre. -/
def r1258FiberProjectionSet
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (F : Set (R1258Group A B)) : Set (Equiv.Perm (Fin n)) :=
  {u | ∃ v : Equiv.Perm (Fin n × ZMod 5),
    v ∈ r1258SecondProjectionSet A B m n T e F ∧
      ∀ a : Fin n, v (a, 0) = (u a, 0)}

/-- The first-coordinate image of the distinguished reflection. -/
def r1258ReflectionProjection
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (τ : Equiv.Perm (Fin (2 * m))) : Prop :=
  ∃ v : Equiv.Perm (Fin n × ZMod 5),
    r1258CoordinateForm
      (e.symm (1, 1, reflection)).1 τ v

/-- The aligned `C₂ wr S_m` first-coordinate action. -/
def r1258FirstWreathMember (B : Type*) (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (u : Equiv.Perm (Fin (2 * m))) : Prop :=
  ∃ σ : Equiv.Perm B,
    ∃ κ : B → Equiv.Perm (Fin 2),
      ∀ b i, η (u (η.symm (b, i))) = (σ b, κ b i)

/-- The regular `B × C₂` action in the aligned first coordinate. -/
def r1258AlignedHallAction (B : Type*) [Group B] (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (H : Subgroup (Equiv.Perm (Fin (2 * m))))
    (e : B ≃* H) : Prop :=
  ∀ b g i, η ((e b).1 (η.symm (g, i))) = (b * g, i)

/-- The aligned reflection swaps the two regular Hall orbits. -/
def r1258AlignedReflection (B : Type*) [Group B] (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (τ : Equiv.Perm (Fin (2 * m))) : Prop :=
  ∀ g i, η (τ (η.symm (g, i))) =
    (g, (Equiv.swap (0 : Fin 2) 1) i)

/-- Permutations in the first-coordinate wreath action that commute with the
Hall action and its aligned reflection. -/
def r1258ReflectionPreservingCentralizer {B : Type*} [Group B]
    (m : ℕ)
    (η : Fin (2 * m) ≃ B × Fin 2)
    (H : Subgroup (Equiv.Perm (Fin (2 * m))))
    (τ : Equiv.Perm (Fin (2 * m)))
    (u : Equiv.Perm (Fin (2 * m))) : Prop :=
  r1258FirstWreathMember B m η u ∧
    (∀ h : H, Commute u h.1) ∧ Commute u τ

/-- The subgroup generated by a first-coordinate Hall action and its
reflection. -/
def r1258HallReflectionGroup {X : Type*}
    (H : Subgroup (Equiv.Perm X)) (τ : Equiv.Perm X) :
    Subgroup (Equiv.Perm X) :=
  Subgroup.closure ((H : Set (Equiv.Perm X)) ∪ {τ})

/-- The natural left-regular permutation copy of a finite group. -/
def naturalRegularCopy (G : Type*) [Group G] :
    Subgroup (Equiv.Perm G) :=
  MonoidHom.range (MulAction.toPermHom G G)

/-- Conjugacy of permutation subgroups in the ambient symmetric group. -/
def conjugateSubgroups {X : Type*}
    (R T : Subgroup (Equiv.Perm X)) : Prop :=
  ∃ p : Equiv.Perm X,
    ∀ q : Equiv.Perm X,
      q ∈ T ↔ ∃ r : Equiv.Perm X, r ∈ R ∧ q = p⁻¹ * r * p

/-- The four factor projections supplied by an aligned regular target. -/
def r1258ProjectionAlignment
    (A B : Type*) [Group A] [Group B]
    (m n : ℕ)
    (T : Subgroup (Equiv.Perm (R1258TargetVertex m n)))
    (e : T ≃* R1258Group A B)
    (P₁ H₁ : Subgroup (Equiv.Perm (Fin (2 * m))))
    (P₂ H₂ : Subgroup (Equiv.Perm (Fin n))) : Prop :=
  (P₁ : Set (Equiv.Perm (Fin (2 * m)))) =
      r1258FirstProjectionSet A B m n T e (r1258AFactorSet A B) ∧
    (H₁ : Set (Equiv.Perm (Fin (2 * m)))) =
      r1258FirstProjectionSet A B m n T e (r1258BFactorSet A B) ∧
    (P₂ : Set (Equiv.Perm (Fin n))) =
      r1258FiberProjectionSet A B m n T e (r1258AFactorSet A B) ∧
    (H₂ : Set (Equiv.Perm (Fin n))) =
      r1258FiberProjectionSet A B m n T e (r1258BFactorSet A B)


/-- In a regular target, the aligned Hall projections and reflection data
are forced by the graph-automorphism and regular-target hypotheses; their
centralizer orders and divisibility then force the two odd Hall factors into
opposite Cartesian coordinates. -/
def claim_30697 : Prop :=
  ∀ (A B : Type*) [Group A] [Fintype A] [Group B] [Fintype B]
    (n m : ℕ),
    Nontrivial A →
    Fintype.card A = n → Odd n →
    Fintype.card B = m → Odd m →
    Nat.Coprime n m → Nat.Coprime (n * m) 10 →
    ∀ T : Subgroup (Equiv.Perm (R1258TargetVertex m n)),
      ∀ e : T ≃* R1258Group A B,
        permutationSubgroupRegular T →
        (∀ t : T,
          t.1 ∈ graphAutomorphismSet (r1258TargetAdj m n)) →
        ∃ (P₁ H₁ : Subgroup (Equiv.Perm (Fin (2 * m))))
          (P₂ H₂ : Subgroup (Equiv.Perm (Fin n))),
          ∃ τ : Equiv.Perm (Fin (2 * m)),
            ∃ η : Fin (2 * m) ≃ B × Fin 2,
              ∃ eB : B ≃* H₁,
                r1258ProjectionAlignment A B m n T e P₁ H₁ P₂ H₂ ∧
                permutationSubgroupRegular P₂ ∧
                Nonempty (P₂ ≃* A) ∧
                r1258AlignedHallAction B m η H₁ eB ∧
                r1258AlignedReflection B m η τ ∧
                r1258ReflectionProjection A B m n T e τ ∧
                τ ≠ 1 ∧
                τ ^ (2 : ℕ) = 1 ∧
                (∀ h : H₁, Commute h.1 τ) ∧
                let K := r1258HallReflectionGroup H₁ τ
                permutationSubgroupRegular K ∧
                Nonempty (K ≃* B × Equiv.Perm (Fin 2)) ∧
                uniqueInvolution K τ ∧
                (∀ h : H₂, ∀ p : P₂, Commute h.1 p.1) ∧
                (∀ p : P₁,
                  r1258ReflectionPreservingCentralizer m η H₁ τ p.1) ∧
                Nat.card {u : Equiv.Perm (Fin (2 * m)) //
                    r1258ReflectionPreservingCentralizer m η H₁ τ u} = 2 * m ∧
                Nat.card H₂ ∣ m ∧ Nat.card H₂ ∣ n ∧ H₂ = ⊥ ∧
                Nat.card P₁ ∣ n ∧ Nat.card P₁ ∣ 2 * m ∧ P₁ = ⊥

end MathlibPlus.Open.Research.FormalizationBatch.R1258Claim30697
