import Mathlib

namespace MathlibPlus.Combinatorics.Claim16268

/-- The rational Venn-cell kernel for three sets is generated by the
alternating cell vector.  Coordinates are ordered as empty, singletons,
pairs, and the triple. -/
theorem threeSetVennKernel
    (x₀ x₁ x₂ x₃ x₁₂ x₁₃ x₂₃ x₁₂₃ : ℚ) :
    (x₀ + x₁ + x₂ + x₃ + x₁₂ + x₁₃ + x₂₃ + x₁₂₃ = 0 ∧
      x₁ + x₁₂ + x₁₃ + x₁₂₃ = 0 ∧
      x₂ + x₁₂ + x₂₃ + x₁₂₃ = 0 ∧
      x₃ + x₁₃ + x₂₃ + x₁₂₃ = 0 ∧
      x₁₂ + x₁₂₃ = 0 ∧
      x₁₃ + x₁₂₃ = 0 ∧
      x₂₃ + x₁₂₃ = 0) ↔
      ∃ t : ℚ,
        x₀ = -t ∧ x₁ = t ∧ x₂ = t ∧ x₃ = t ∧
          x₁₂ = -t ∧ x₁₃ = -t ∧ x₂₃ = -t ∧ x₁₂₃ = t := by
  constructor
  · rintro ⟨h₀, h₁, h₂, h₃, h₁₂, h₁₃, h₂₃⟩
    refine ⟨x₁₂₃, ?_⟩
    constructor
    · linarith
    constructor
    · linarith
    constructor
    · linarith
    constructor
    · linarith
    constructor
    · linarith
    constructor
    · linarith
    constructor
    · linarith
    · linarith
  · rintro ⟨t, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩
    norm_num

end MathlibPlus.Combinatorics.Claim16268
